### ISSUE TITLE
DAX Studio cannot connect to Power BI

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#1]
I was able to repro this issue on a notebook with SSAS Tabular 2016 SP1 installed (maybe it’s the same on other versions):
1.	The SSAS instance has no databases
2.	Open DAX Studio and connect to SSAS instance
3.	You see no databases – click on DMV tab
4.	You see no DMVs, which is strange but possible for other reasons..
5.	Now open Power BI without closing DAX Studio
6.	Connect DAX Studio to Power BI – you get an error and you are not able to connect anymore
 
The workaround is simple: close DAX Studio and restart.

**Comment by mattflorian2** [comment]
I am using DaxStudio 2.7.4 and PBI 2.56.5023.1021 64-bit (March, 2018) release. My ability to connect  to the PBI file only works for an empty file. Any PBIX file that has a connection to my SSAS 2016 instance is not visible 95% (my own metric) of the time. I am attempting to run traces on these PBIX to optimize their performance and you tool is what I am hoping to use.

Thanks

**Comment by marcosqlbi** [comment]
If you connect Power BI to SSAS Tabular with a live connection, you should connect DAX Studio to SSAS Tabular. Only when you work with imported data you can connect DAX Studio to Power BI Desktop directly.

**Comment by luuminhvuong93** [comment]
Dear Marcos,
I opened Power BI, connected to a live dataset in my company,
Then I tried to connect to this PBI in Dax Studio but this is the error (in the picture)
![image](https://user-images.githubusercontent.com/32800049/53141125-94a03b80-35c1-11e9-842b-8499ad7672b7.png)

How can I connect to a live connection in Dax Studio?

Thanks a lot for any help,

**Comment by dgosbell** [comment]
As the error says, if your PBIX file is using a Live Connection to SSAS you need to connect DAX Studio to your SSAS model. When Power BI Desktop is using Live Connection there is no data in the PBIX file, DAX Studio needs to connect to the data source that has the data.

**Comment by luuminhvuong93** [comment]
@dgosbell  Thank you for replying,
My problem is I do not know how to connect to this dataset as I am not the owner of the dataset, 
I tried to find a way but cannot see how to connect to this dataset using Dax studio

**Comment by dgosbell** [comment]
@luuminhvuong93 in Power BI Desktop, when you have your report open click on the following option:
![image](https://user-images.githubusercontent.com/8241830/53145377-0beec300-35f4-11e9-9cea-3082fe52e413.png)
This will open a dialog box with the server and database name.

Then open DAX Studio and put the server name into the "Tabular Server" option in the connection box
![image](https://user-images.githubusercontent.com/8241830/53145427-46586000-35f4-11e9-92c5-1f8e4925e907.png)
and make sure that you are connected to the same database by selecting it from the Database dropdown in DAX Studio.

> Note that some options may not be enabled in DAX Studio if you do not have admin rights on this server. Tracing features such as All Queries, Query Plans and Server Timings require admin rights on the data source, so you would need to speak to one of your server admins to try to get access to do this (or to get them to run traces for you)
