### ISSUE TITLE
DAX Studio 2.7 beta test

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#10]
We are looking for a few beta testers of DAX Studio 2.7.
If you are interested, please contact us in this thread.

**Comment by daniilmaslyuk** [comment]
Would love to be a beta tester of DAX Studio 2.7!

**Comment by OwenAuger** [comment]
Yes please, would like to be a beta tester!

**Comment by slunyakin** [comment]
Count me as well )

**Comment by Hugoberry** [comment]
Count me in

**Comment by hohlick** [comment]
For sure, I am in!

**Comment by sergeinca** [comment]
I would like it

**Comment by SQLBent** [comment]
Count me in

**Comment by jarrettmoore** [comment]
Would love to be a beta tester!

**Comment by luisquedas** [comment]
Hi Marco,
Fantastic work, count me in.
Cheers, Luis

**Comment by craigbersiks** [comment]
Hi Marco,

Very interested!

Bests,

Craig.

**Comment by scharly3** [comment]
Interested!

**Comment by kesneyf** [comment]
Interested

**Comment by awbarbeau** [comment]
I would be interested!

**Comment by gregoryjkramer** [comment]
Me please

**Comment by dgosbell** [comment]
An installer for the 2.7 beta is now available in the following OneDrive folder [https://1drv.ms/f/s!AnSKp2UbblSYgZlNWkrpq3eInReMNg](https://1drv.ms/f/s!AnSKp2UbblSYgZlNWkrpq3eInReMNg) which also contains a PDF with release notes. The major change that we want feedback on and help testing is around the way the trace windows work and the new trace option.

**Comment by paullevchuk** [comment]
I have already tested it.
-- New tooltips are really useful. 
-- Export to CSV of datetime is now working like a sharm. 
Thanks guys!

**Comment by paullevchuk** [comment]
One thing that is still inconvenient for me is how DaxStudio copies value from Output window. 
For example, I put cursor on some cell in "tutor_id" column and copy cell value. 
DaxStudio saves data in clipboard in such format "tutor_id\nvalue\n".
I can't use this value in any other tool until I clean column name and remove 2 CR symbols. 
Please, consider this case in next releases.
Thanks!

**Comment by dgosbell** [comment]
I think I can add an option to turn off the headers, but the trailing CR still comes through. We are using the standard copy mechanism for the DataGrid control so we might need to look at overriding this somehow.

**Comment by slunyakin** [comment]
Hi guys,
I like a new All queries feature. It is very helpful, especially that I can see even queries are running currently in SSAS engine.

Unfortunately, filter in All queries doesn't work for me or maybe I don't know how it should work.
![allqueries_filter](https://user-images.githubusercontent.com/11273261/29211011-bc3ddb18-7e96-11e7-8512-1ea0e2e5a0a5.png)

**Comment by dgosbell** [comment]
@paullevchuk - we can add an option to exclude the headers when copying from the results grid, but getting rid of the final trailing newline looks trickier.

**Comment by dgosbell** [comment]
@slunyakin - the release notes mentioned that the database and user columns currently use "starts with" style searches, we will probably move all the text columns over to "contains" searches for the final release

**Comment by paullevchuk** [comment]
@dgosbell, it would be great!

**Comment by pugliathomas** [comment]
I am as well!
