### ISSUE TITLE
ServerTimings window layout gets reformatted strangely after opening a saved file

### ISSUE THREAD

**Issue by MarkWojciechowicz** [DaxStudio/DaxStudio#100]
The server timings window layout goes crazy when reopening a saved file that used server timings.
To reproduce:
1) Create a new file
2) enable server timings
3) save the file
4) close the file
5) reopen the file and view the server timings window.  Screenshot is attached.  Note the warnings pane on the top is oversized and cutoff.  the lower panes are unuseable.
![servertimingsformat](https://user-images.githubusercontent.com/11320108/45847517-4f699c00-bcf9-11e8-9109-c465b12cbb0c.png)

Workaround:
Delete the server timings file and then open the saved file.  Renable server timings

**Comment by dgosbell** [comment]
Thanks for reporting this, We have already noticed this issue and there is a fix in the code base that will be part of the next release (v2.8)

**Comment by dgosbell** [comment]
This should now be fixed in the 2.8.0 release
