### ISSUE TITLE
F-Secure Deepguard antivirus claims this has a Trojan!

### ISSUE THREAD

**Issue by TimoRiikonen** [DaxStudio/DaxStudio#1013]
**Describe the bug**
And according to it this has the following Trojan:
https://www.f-secure.com/v-descs/trojan_w32_injector.shtml

**To Reproduce**
1. Download network installer.
2. Select install
3. If you have F-Secure installed, see the error message

**Expected behavior**
If this is not a Trojan, can you ask F-Secure to whitelist your app.

**Screenshots**
![image](https://user-images.githubusercontent.com/10447579/210073723-b6c5d3b3-aefe-4ea5-b9a4-9d79d0fa4f3f.png)

**Comment by dgosbell** [comment]
I don't have F-Secure so I don't see this issue, but we occassionally get false positives from various different anti-virus vendors.

I've run the setup through the Virus Total website and 90 other AV products reported no issue see
https://www.virustotal.com/gui/url/51d371bfd7cd0ef0b5b9f05ca9828fbfaab713ff5825a4e907af94a16896b02c?nocache=1 

I've tried a couple of times to upload a sample to F-Secure, but the upload page keeps reporting an error. You can try yourself if you like https://www.f-secure.com/en/home/support/submit-a-sample?m=submit-file-sample-error 

I do the production builds using AppVeyor build servers, so a clean Virtual Machine is created, it pulls the source code from Github and then builds the program and the installer, so the chances of the installer getting infected with malware as low as I can possibly make them.
