### ISSUE TITLE
Bug or just how Tabular works - format changes based on TABLE expression

### ISSUE THREAD

**Issue by edhans** [DaxStudio/DaxStudio#1018]
I ran this query and it worked great.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/45298358/210858051-19d92f34-bf19-4a2d-b74f-ee66081c9ebb.png">

Then I decided to move the query to a Table definition to do other stuff with it. Now the formats for dates and IDs are different.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/45298358/210858307-2cca16f4-d8b5-416c-bd44-529f8fd44ed5.png">
I am not sure what that date is. Dates are 5 digits with decimals for times, correct? These have no times. They are just dates at 12:00:00am.

Assigning it to a VAR works fine as well, but that isn't the same as a TABLE of course.

**Comment by edhans** [comment]
Check your inbox

**Comment by dgosbell** [comment]
I'm the same as Marco, I cannot repo this against Adventure Works. I would expect that the column formatting would be lost since DAX Studio would look for a physical tblExceptions[Date] column to try and find the format string so you would probably see the date using a default Short Date format for your locale.

**Comment by edhans** [comment]
I would have been ok with that, but it was that 7 digit integer that was returned. Don't see how that could be coming from any of my locale settings.

**Comment by dgosbell** [comment]
Actually that 7 Digit number looks like the data from the ConsultantID column, but I still have no idea what is causing this

**Comment by marcosqlbi** [comment]
I created a repro and submitted it to Microsoft for review.
It seems to be an engine bug triggered by different data types in other columns.
The bug appears when the first table has a column CURRENCY (which is fixed decimal number in PBI) and the same column is DOUBLE in the second table (which is decimal number in PBI).
Repro attached and sample repro query below.

[tablebug.zip](https://github.com/DaxStudio/DaxStudio/files/10359178/tablebug.zip)

```
-- T1 and T2 tables are defined this way:
-- T1 = DATATABLE ( "Date", DATETIME, "Number", CURRENCY, { { dt"2022-12-19", 7 }, { dt"2022-12-20", 6 } } )
-- T2 = DATATABLE ( "Date", DATETIME, "Number", DOUBLE, { { dt"2022-12-20", 6 } } )

DEFINE
    TABLE tblExceptions =
        EXCEPT ( T1, T2 )

EVALUATE
tblExceptions -- Result is wrong, Date is a number

EVALUATE
EXCEPT ( T1, T2 ) -- Result is correct
```
