### ISSUE TITLE
Dax Studio Excel Add-In Installed but not working

### ISSUE THREAD

**Issue by pgmclean** [DaxStudio/DaxStudio#102]
**Appears to be problem with recent upgrade of Office 365 on Windows 10**

**Assemblies needed for VAX Studio add-in are not registered or not available:**

C:\>Windows 10 systeminfo

Host Name:                 PMCLEANLT-W10P
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          HP
Registered Organization:   HP
Product ID:                00330-80000-00000-AA519
Original Install Date:     18/05/2018, 10:21:42 AM
System Boot Time:          2/10/2018, 2:09:59 PM
System Manufacturer:       HP
System Model:              HP Pavilion Power Laptop 15-cb0xx
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~2808 Mhz
BIOS Version:              Insyde F.16, 22/06/2018
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+10:00) Canberra, Melbourne, Sydney
Total Physical Memory:     16,269 MB
Available Physical Memory: 10,588 MB
Virtual Memory: Max Size:  18,701 MB
Virtual Memory: Available: 11,667 MB
Virtual Memory: In Use:    7,034 MB
Page File Location(s):     C:\pagefile.sys

**Output from DaxStudio.Checker.exe:**
    Version =  v2.7.4.102

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSVersion       = 10.0.17134
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.89
    FreeMemoryGB    = 10.89

    Culture Name              = en-AU
    Culture DisplayName       = English (Australia)
    Culture EnglishName       = English (Australia)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = d/MM/yyyy

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.03056
    v4\Client\1033 -> 4.7.03056
    v4\Full -> 4.7.03056
    v4\Full\1033 -> 4.7.03056
    v4.0\Client -> 4.0.0.0

Checking AMO
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 9
    AMO : 14.0.0.0
    ADOMD : 14.0.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - c:\program files (x86)\mindjet\mindmanager 8\mm8excellinker.dll
    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.4.102, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4R
        VSTORFeature_UNM 1
        VSTORFeature_CLR35 1
        VSTORFeature_CLR40 1
        Version 10.0.50903
        Revision 00
        ProductCode {9495AEB4-AB97-39DE-8C42-806EEF75ECA7}

**Excel VAX Studio Add-in not listed**
![exceldaxstudionotlisted](https://user-images.githubusercontent.com/43798053/46381825-38f51480-c6eb-11e8-8097-a53252de65fb.JPG)

**Zip file for fusion logs:**
[Fusion.zip](https://github.com/DaxStudio/DaxStudio/files/2440032/Fusion.zip)

**Excel Office 365 Details**
![exceloffice365versiondetails1](https://user-images.githubusercontent.com/43798053/46382181-2ed41580-c6ed-11e8-913f-d26ffc68b7f4.JPG)

![exceloffice365versiondetails2](https://user-images.githubusercontent.com/43798053/46382186-3693ba00-c6ed-11e8-9445-e85c045c96f4.JPG)

**Comment by dgosbell** [comment]
I can't see any problem with the required assemblies. The config bindings have been set to use the 14.0 version of the assemblies and both of those appear to be installed OK.

In DaxStudio.Checker there is an option under the File menu to Enable VSTO Alerts. Can you close all copies of Excel, switch that on and then see if any error messages get display when you start Excel? (after doing this you can go back into DaxStudio.Checker and the file menu should show an option to disable the VSTO Alerts)

**Comment by pgmclean** [comment]
Hi dgosbell.  Thank you for your contribution, I apologise for not having replied earlier. I've upgraded Office 365 to the latest version and I am now able to use the add-in and launch DAX Studio from the PP Utilities Menu. The add-in now appears in the Excel->Options->Add-ins->COM Add-ins->Go List and it is enabled. However DAX studio Checker is still reporting assembly load failures and warnings on assembly Microsoft.AnalysisServices,AdomdClient.  I think this is due to the latest version of Windows now having a Microsoft.AnalysisServices,AdomdClient.ni dll that was originally the Microsoft.AnalysisServices,AdomdClient dll. This is not affecting me however as I am not currently using the Ado client, There are also still numerous failure messages in the fusion logs for DAX Studio and Excel when DAX Studio is used, but these have also not affected my current use of DAX Studio and the Excel DAX Studio add-in. I will report any further issues if I think that I can add value to the resolution of related DAX Studio not working issues. Cheers.

**Comment by dgosbell** [comment]
Glad that it's started working for you.

Some warnings in DaxStudio.Checker are normal as are some of the fusion log errors.
