### ISSUE TITLE
Daxformatter Button Not return formatted Dax Code

### ISSUE THREAD

**Issue by fgavery** [DaxStudio/DaxStudio#1023]
DAX Studio v3.0.5.767
Connection: not connected

## Summary of Issue
When pressing Daxformatter the code is deleted and nothing isreturned from the website

## Steps to Reproduce
1.Select Code tp Format

2. Press the Dax Format Button

**Comment by dgosbell** [comment]
Thanks for logging this, it appears to be an issue with the daxformatter.com site. I've asked the admins there to investigate.

**Comment by marcosqlbi** [comment]
The issue was caused by the migration of an internal service that affected URL redirection - the problem is fixed now!

**Comment by fgavery** [comment]
Marco,

Thanks you very much for the response,  I had my team chasing down firewall issues, etc,  I tested on a personal PC and got the same.  That is when i decided it might be best to report it.  Excellent response.

Great tool.  I am still learning, but I have now built some very sophisticated models and used Dax Studio through the entire process. Simply great!!!  I am a huge fan of you and Alberto.  You guys know your stuff!!

Have a great weekend.


Best regards,

Regards,

Frank Avery

________________________________

**Comment by marcosqlbi** [comment]
Thanks for the nice words! We didn't expect the issue for DAX Formatter for a big migration we made for other services, but that's the reason why we plan these activity over the weekend :)
