### ISSUE TITLE
Add detail to the names and tooltips of columns in the VertiPaq Analyzer

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1026]
Under Advanced → View Metrics → VertiPaq Analyzer, many of the column names, and even some of the tooltips that appear when you hover over them, need more detail.

2 particular types of improvements come to mind:
- Expand any abbreviations, acronyms, or other short forms to their full form
- Add unit labelling. For example, the size columns never mention any kind of unit. They could be in bits or bytes for all the user knows. The "Partitions" and "Segments" columns should be called "Partition Count" and "Segment Count", respectively, so that the user does not misinterpret these values as being flags (especially if all of the values are 1) or a numeric code of some sort.

Since these changes will make the column names longer, please also allow the column names to occupy multiple lines if possible. The additional text should not be as much of an issue for the tooltips.

**Comment by dgosbell** [comment]
Thanks for logging this, I can definitely add more information to the tooltips like the units and expansions of the abbreviations. But the reason we used abbreviations and short names is that by default the headers for the datagrid control does not wrap onto multiple lines. I learnt a few more advanced techniques during the visual upgrade for the v3 release, so I might be able to work around this restriction, but this is why we selected the current column headers.

**Comment by Kenneth-Barber** [comment]
I encountered another set of columns and their tooltips that are not clear. In the VertiPaq Analyzer, under "Partitions", it is not clear what is the difference between the "Segments" column and the "Tot. Seg." column.

**Comment by dgosbell** [comment]
> I encountered another set of columns and their tooltips that are not clear. In the VertiPaq Analyzer, under "Partitions", it is not clear what is the difference between the "Segments" column and the "Tot. Seg." column.

This was recently covered in Discussion #1042 and I've updated the tooltips to match the information discussed there. :)

**Comment by dgosbell** [comment]
The updated tooltips are now available in the 3.0.6 release
