### ISSUE TITLE
Split the "Table-Column" column in the VertiPaq Analyzer

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1027]
Under Advanced → View Metrics → VertiPaq Analyzer → Columns, there is a column called "Table-Column", which contains both the table name and the column name together. Please consider splitting this column into a "Table" column and a "Column" column. Reasons:
- Easier to read
- Better alignment of similar types of values
- Be able to sort by column name (currently not possible)
- Be able to more easily visually detect clusters of columns from the same table or columns with the same name from different tables
- Less confusion as to what is the table name or what is the column name if either of them contains "-"

Here is an example of where this would be handy. Suppose that you have a dimension table and multiple fact tables that use a "Start Of Hour" column, which contains datetimes for every hour of every day. By having a separate "Column" column, you could more easily see, for example, that all of the "Start Of Hour" columns are taking up a lot of space, both separately and especially together, which would make it more obvious that a "Start Of Hour" column should not be used anywhere. Without the "Column" column, it would be easy to miss this big-picture issue and you might end up wasting time optimizing 1 table at a time.

**Comment by SharmaAntriksh** [comment]
Yup, just like the Tabular Form + Repeat All Labels option in Pivot Table.
