### ISSUE TITLE
EULA?

### ISSUE THREAD

**Issue by Benouboy** [DaxStudio/DaxStudio#103]
Hi, my IT department is requesting from me the EULA for Dax Studio... any clue where to find it?
Thx!
Ben

**Comment by dgosbell** [comment]
If you run the installer the license is displayed on the first page of the install wizard.

You can also download the license directly from the source for the installer from here: [https://github.com/DaxStudio/DaxStudio/raw/master/installer/eula.rtf](https://github.com/DaxStudio/DaxStudio/raw/master/installer/eula.rtf)

**Comment by Benouboy** [comment]
Perfect, thx  a lot Darren!
