### ISSUE TITLE
missing table reference in measure after loading .dax file

### ISSUE THREAD

**Issue by JarekWuDev** [DaxStudio/DaxStudio#1030]
DAX Studio v3.0.5.767
Connection: PowerBIService - 16.0.59.21

## Summary of Issue
missing table reference in measures after loading .dax file, missing table reference refers to measures created in DAX Studio,
mainly issue refers to execute query after loading .dax file, in additional measure not created in dataset need to add table reference to reuse query

## Steps to Reproduce
1. create additional measure and add table reference
2. save and load .dax file
3. in measure definition there is no table reference anymore

**Comment by dgosbell** [comment]
Thanks for logging this, I've been able to reproduce this and identify the issue. I should be able to include a fix in the next release. But unfortunately, some of the required information was missing when we saved the file. So, I've had to update the file save routines to fix this. I think I have figured out how to auto-repair this in most circumstances, but if not then re-selecting the table in the expression editor then re-saving the file should fix this when the update is released.
