### ISSUE TITLE
saving .csv file with semicolon separator and Unicode encoding

### ISSUE THREAD

**Issue by JarekWuDev** [DaxStudio/DaxStudio#1031]
I've used since always unicode encoding in Excel and semicolon separator for csv files or semicolon for formulas.
Tried all combinations of saving .csv file but missing right one for me,
For me additional one could be enough but maybe should be additional options for encoding in Custom Export Format

**Comment by dgosbell** [comment]
Thanks for logging this. I think I should be able to add an option for the encoding type to the custom export options to support this sort of requirement.
