### ISSUE TITLE
Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by cts14** [DaxStudio/DaxStudio#1032]
DAX Studio v3.0.5.767
Connection: AnalysisServices - 14.0.6.461

## Summary of Issue
When users that belong to a specific  RLS role, try to open DAX Studio they get error: Value cannot be null. Parameter name: key
Metadata fails to load.
![2023-01-19 10 38 13](https://user-images.githubusercontent.com/56339801/213394126-ea888fb1-ee41-4196-b0ad-5d8862748ab1.png)

## Steps to Reproduce
I can re-produce when I use functionality: View as and choose the specific RLS role
1. Connect to Tabular server
2. Metadata does not appear

**Comment by dgosbell** [comment]
I cannot reproduce this issue. Can you provide an example bim or pbix file which reproduces this problem?

**Comment by dgosbell** [comment]
Closing due to lack of response. Feel free to re-open this or to create a new issue if you are able to provide more information
