### ISSUE TITLE
Pivot Table Problem

### ISSUE THREAD

**Issue by BurimBehrami** [DaxStudio/DaxStudio#1034]
**Area Values doesn't work **

When I import data from PBI to Excel with Dax Studio, I can't put any field to area Values.

Here is the message:

![image](https://user-images.githubusercontent.com/123157945/213671139-e7bd4985-bbe3-40a6-b07f-1a5e2959e310.png)

Thanks in advance!

**Comment by dgosbell** [comment]
It looks like you've done something else to the data after you exported it. I can see multiple tables in your PivotTable field list. Have you imported the data into a data model in Excel or something? Whatever manipulation you have done the issue seems to be related to that.

**Comment by SharmaAntriksh** [comment]
@BurimBehrami If you have a Calculation Group in the model then Implicit Measures are discouraged by default so this isn't a problem of DAX Studio by a design choice from PBI Team.

**Comment by dgosbell** [comment]
Closing due to lack of response
