### ISSUE TITLE
Installer issue: Access denied creating c:\users\public\desktop\DAX Studio.lnk

### ISSUE THREAD

**Issue by SergioMurru** [DaxStudio/DaxStudio#1036]
**Describe the bug**
Running DAXStudio_3_0_5_Setup.exe and selecting "just for me" and to create an icon on the desktop, it shows an error messagebox "IPersistFile::Save failed; code 0x80070005. Access is denied". The installer window shows "Creating shortcuts... C:\Users\Public\Desktop\DAX Studio.lnk"

**To Reproduce**
1. Run the installer as a normal user.
2. Select "Just for me"
3. Check "create desktop icon"
4. the installation run and then shows the error messagebox.

**Expected behavior**
the installation should craeate the icon to the user desktop and not to the Public one.

**Screenshots**
![image](https://user-images.githubusercontent.com/38207222/215063111-ba6eac2f-c904-478c-bf68-114d41475723.png)

**Comment by dgosbell** [comment]
Thanks for logging this. Normally the c:\users\public file should be writable by all accounts, which is probably why this has not been reported before. But you are correct that it should be writing to the `c:\users\<current user>` folder. A fix for this will be included in the next release. Until then you could untick the option to create a desktop shortcut and the install should then proceed.
