### ISSUE TITLE
excel 2013 add-in cannot be activated

### ISSUE THREAD

**Issue by lidewbri** [DaxStudio/DaxStudio#104]
Dear all,

In excel 2013, I am unable to activate the DAX studio add-in. Moreover, I cannot connect to powerpivot data sources from within daxstudio application. In the logfile, I see the fatal error:

FATAL ERROR:
Object reference not set to an instance of an object.

(see below). Can you pease help me out? Which setting or condifiguration should I modify?

Best regards, lidewbri

    Version =  v2.7.4.102

Checking Operating System
=======================
    OSCaption       = Microsoft Windows Server 2012 R2 Standard
    OSVersion       = 6.3.9600
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 32.00
    FreeMemoryGB    = 27.31

    Culture Name              = en-GB
    Culture DisplayName       = English (United Kingdom)
    Culture EnglishName       = English (United Kingdom)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = £
    Culture ShortDatePattern  = dd/MM/yyyy

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.02053
    v4\Client\1033 -> 4.7.02053
    v4\Full -> 4.7.02053
    v4\Full\1033 -> 4.7.02053
    v4.0\Client -> 4.0.0.0

Checking AMO
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 9
    AMO : 13.0.0.0
    ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 15 - Excel_2016
    Excel Path: E:\Program Files\Microsoft Office\Office15\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.4.102, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64

FATAL ERROR:
Object reference not set to an instance of an object.
   at DaxStudio.Checker.Checker.CheckVSTO()
   at DaxStudio.Checker.Checker.CheckExcelAddin()
   at DaxStudio.Checker.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by dgosbell** [comment]
> Moreover, I cannot connect to powerpivot data sources from within daxstudio application.

If you have not launched DAX Studio from the Excel addin that is the expected behaviour. The addin is what allows us to connect to a PowerPivot model.

Are you able to run the PowerPivot management interface? (by clicking on the "Manage" button in the PowerPivot ribbon) The error you are getting indicates that the Checker could not find the VSTO framework at all which is strange because I'm pretty sure PowerPivot uses this same framework to integrate with Excel.

If the PowerPivot manage window is working, but DAX Studio is not you could try manually installing the VSTO runtime from here [http://go.microsoft.com/fwlink/?LinkId=158918](http://go.microsoft.com/fwlink/?LinkId=158918)

**Comment by dgosbell** [comment]
Closing due to lack of response. If you have anything new to add feel free to re-open this issue
