### ISSUE TITLE
add new feature - view unused measure - columns

### ISSUE THREAD

**Issue by Charles92100** [DaxStudio/DaxStudio#1040]
Hi there,

It would be nice to add a feature to analyze a report based on the used/unused column or measure of this report.
It can particularly be interesting at the end of a project when you have added a few "test" columns or measures, and you need to do a little cleanup.

**Comment by dgosbell** [comment]
Yes, this ask has come up before and it would be nice, but it is non-trivial and we don't actually have access to all the required information to do this properly from DAX Studio - the following issue summarizes the problems #359 

There are some other external tools which attempt to do this by using unsupported methods of accessing the data in a pbix file.
