### ISSUE TITLE
Tabular connection for Dax Studio

### ISSUE THREAD

**Issue by Weixu01** [DaxStudio/DaxStudio#1047]
**Describe the bug**
It always set the IntegratedSecurity  to be [true] while connecting tabular on windows even the user and password were configured.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/68360609/217505250-c792997d-fe72-47a7-930b-a0e5bf441ef2.png)

**Additional context**

**Comment by dgosbell** [comment]
The code you have highlighted is for the export wizard connection to a SQL Server database. It has nothing to do with the connection to a tabular model.

> It always set the IntegratedSecurity to be [true] while connecting tabular on windows even the user and password were configured.

Integrated Security is the default for tabular models. If you need to test security roles as a different user you could use the "View As" option in the Advanced ribbon. Or you can either use the "Effective User Name" setting in the connection dialog. 

![image](https://user-images.githubusercontent.com/8241830/217667980-1b9dfea7-7dfe-42fe-9f0e-352a65a3be01.png)

Or if you actually need to impersonate another user you could add the UserID and Password properties in the "Additional Options" as per the notes [here](https://learn.microsoft.com/en-us/analysis-services/instances/connection-string-properties-analysis-services?view=asallproducts-allversions#user-idpassword)

Does this solve your issue?

**Comment by Weixu01** [comment]
"Additional Options" is not effective in windows environment as the IntegratedSecurity hardcode to be [true] for win environment.
"Effective User Name" can be only effective for user who has admin permission for tabular.

**Comment by dgosbell** [comment]
If there is any hard coding it's in the Microsoft AdomdClient library, not in DAX Studio so you'll need to talk to them about it. 

Why do you need to run as a different user if you are not an admin who is testing security?

Your other option is to just run DAX Studio as a different user. see https://www.makeuseof.com/windows-11-run-app-different-user/

**Comment by dgosbell** [comment]
closing due to lack of response
