### ISSUE TITLE
[Dax studio] Not show model when get data in excel 2013

### ISSUE THREAD

**Issue by shaming10** [DaxStudio/DaxStudio#105]
Dear Sir,

Pls, help me check agian. when i open dax studio in excel 2013, connect succesful but not show model (data).

issue image: 
![image](https://user-images.githubusercontent.com/24898894/47740966-b50f5780-dcab-11e8-93a6-d3c47f709e7c.png)

**Comment by dgosbell** [comment]
Can you create a pivot table in Excel against this model and show values from one of your measures?
If you open the Manage window first, then start up DAX Studio does it connect?

**Comment by shaming10** [comment]
i can create a pivot table in excel.
![image](https://user-images.githubusercontent.com/24898894/47802183-52c55e00-dd62-11e8-9f20-abe967cfbefe.png)

if i have open dax studio first, it show error: PowerPivot model not detected

![image](https://user-images.githubusercontent.com/24898894/47801997-f3674e00-dd61-11e8-828f-9fdb33f578bb.png)

so i have open manage window first, then start up Dax studio it connect, but not show model (data)
![image](https://user-images.githubusercontent.com/24898894/47802257-7be5ee80-dd62-11e8-9ef5-40d0fb8d6fe0.png)


![image](https://user-images.githubusercontent.com/24898894/47802289-8902dd80-dd62-11e8-8422-0fe06a8a2649.png)

**Comment by dgosbell** [comment]
Does this happen on all workbooks with PowerPivot models or just this one?

Can you completely shutdown all copies of Excel and then start-up enabling the debug logging following the instructions [here ](http://daxstudio.org/documentation/troubleshooting/logging-settings/). Then try and open this file and then close DAX Studio and Excel. This should generate 2 logs, one for the Excel addin and another for the User Interface. If you can post both log files here I can see if they give any hints as to why this is not working.

**Comment by shaming10** [comment]
thanks @dgosbell, i send 2 file log: 

[DaxStudio-20181031.log](https://github.com/DaxStudio/DaxStudio/files/2543467/DaxStudio-20181031.log)
[log2.txt](https://github.com/DaxStudio/DaxStudio/files/2543469/log2.txt)

Pls, help me check again.

**Comment by dgosbell** [comment]
Sorry, the first log is one of the correct files, but the debug logging was not enabled, you need to keep the shift key held down until the Excel UI is fully loaded, then you see a popup like the following when you start DAX Studio confirming that Debug Logging is enabled:
![image](https://user-images.githubusercontent.com/8241830/48168511-995b1f80-e343-11e8-9b3f-ee00759be273.png)
Then DAX Studio will create 2 log files a DaxStudio-yyyymmdd.log file and a DaxStudioExcel-yyyymmdd.log file, where yyyymmdd is the year, month and day for the current date.

**Comment by dgosbell** [comment]
Sorry, but there is nothing in either of those files that points to there being any issues. What I really need is the log file from the Excel Addin (DaxStudioExcel_yyyymmdd.log). Can you either try shutting down all copies of Excel and then holding down the shift key longer while Excel is starting up (the shift key needs to be held down while you see the DAX Studio addin being loaded). Or manually enable the diagnostic logging using the DaxStudio.dll.config file as noted in the section on manually enabling logging [here](http://daxstudio.org/documentation/troubleshooting/logging-settings/) (you will still need to shut down all copies of Excel, then re-start Excel for this logging setting to be activated)

**Comment by shaming10** [comment]
[DaxStudio-20181116.log](https://github.com/DaxStudio/DaxStudio/files/2590016/DaxStudio-20181116.log)
Pls, help me check again.

**Comment by shaming10** [comment]
thanks for support! @dgosbell, but i can find log excel addin (DaxStudioExcel...). 
I closed issue.

Thanks so much!
