### ISSUE TITLE
Support time format type between PowerBi and SQL Server exporting.

### ISSUE THREAD

**Issue by ShockMonster** [DaxStudio/DaxStudio#1051]
I recently installed Dax Studio for our company's Power BI to export data to SQL server. There is a column called "start_time" set in a time format type that needs to be exported to our SQL table in a time format type. 

Dax Studio currently exports the data in a datetime format in place of the time format type. This forces all our times to be exported with "1899-12-30" date attached to them. 

Can Dax Studio be updated to support time format type when exporting from PowerBI to SQL Server, instead of using datetime format?

![Dax Studio](https://user-images.githubusercontent.com/104030051/218558198-9fad238f-28db-4a3e-a297-b02c5b68e7e4.png)
![Screenshot 2023-02-13 144937](https://user-images.githubusercontent.com/104030051/218560229-3f343a3c-ec11-4574-8ae7-af74057104bb.png)

**Comment by dgosbell** [comment]
Thanks for logging this. But to a degree this behaviour is expected as the tabular engine only has a datetime data type and when we do exports we typically don't apply any formatting and export the raw data. 

How are you exporting to SQL Server? Are you using the data export option or are you exporting to a file first and then importing the file? I'm looking at adding a "Formatted File" output option to the next release which would help if you are exporting to a file first, but it won't help if you are using the Data Export option to push entire tables direct to SQL.

**Comment by ShockMonster** [comment]
Currently we are using the Data Export option to migrate the data from multiple PowerBI tables to the Azure SQL server tables in one setting.  Adding a formatted file option sounds like a really good thing to add in general.

**Comment by dgosbell** [comment]
Unfortunately, there does not seem to be an easy fix for this. I'm using the SQL Bulk Insert methods to get the most speed out of this export feature, but that does not give me a chance to alter the column types. There is only one datetime data type in tabular models and the difference between a date and a time column is just the formatting that gets applied after the fact. I'd have to completely re-write the SQL export logic to use some sort of internal buffers where I could alter the data types and this is not something I'm likely to find time to do anytime soon.

One possible workaround is to create a view on top of your target table which does a cast of that column to the "time" data type in SQL. Then any downstream processes could just consume the data from that view.

PS. I've accidentally tagged this issue against the new csv formatting so I'll need to re-open this issue after that change is released as it will auto-close this issue.
