### ISSUE TITLE
Reordering columns in VertiPaq Analyzer changes column header order but not column contents order

### ISSUE THREAD

**Issue by steve-james-hcc** [DaxStudio/DaxStudio#1052]
DAX Studio v3.0.5.767
Connection: PowerBIDesktop - 16.0.48.19

## Summary of Issue
Dragging a column header in the VertiPaq Analyzer output window moves the column headers to a new position, but the column contents don't reorder, so the columns become misaligned with their headers

## Steps to Reproduce
1. Run VertiPaq Analyzer
2. Switch to the Relationships view
3. Click and drag the Missing Keys and Invalid Rows column headers to be between the Table/Relationship column and the Size column

See screenshot
![DAXEditorVPACols](https://user-images.githubusercontent.com/106304920/218721782-910d7b67-3ec9-40bc-95d0-d3272e57cdf1.png)

**Comment by dgosbell** [comment]
Thanks for logging this. Unfortunately it does not appear to be simple to fix and I might just have to disable the re-ordering option to reduce any confusion
