### ISSUE TITLE
Swap delimiter

### ISSUE THREAD

**Issue by bluehenve** [DaxStudio/DaxStudio#1055]
DAX Studio v3.0.5.767
Connection: not connected

Hi
I cant find the 'Swap delimiter' no more - is it just me?
Regards, Henrik

![image](https://user-images.githubusercontent.com/70111241/219370598-416590f6-01a1-424d-8cc3-7deafd18a186.png)

**Comment by dgosbell** [comment]
This was discussed here #1041 . In the next release the setting in question will move the buttons between the Home and Advance tabs rather than completely swapping them.
