### ISSUE TITLE
Enable hotkey support for Shift+Enter

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#1060]
A number of other products in the data space such as python notebooks support Shift+Enter as a way of executing the current query/statement. This currently does not work in DAX Studio and Shift+Enter just adds a new line in the editor. It would be great to allow Shift+Enter to be used as a custom hotkey combination.

**Comment by MikeCarlo** [comment]
When I’m working on jupyter notebooks. I am also using ctrl+enter a lot to run the selected cell command. I’d also like to execute Dax with ctrl + enter:

https://towardsdatascience.com/jypyter-notebook-shortcuts-bf0101a98330

**Comment by dgosbell** [comment]
@MikeCarlo - ctrl+Enter should already work. You can set custom hotkey bindings in the options and ctrl+enter is not captured by the edit control (which is the problem with shift+enter)
![image](https://user-images.githubusercontent.com/8241830/223283292-2b6cdb29-6cc0-4ee5-9ae6-a8628ba4cf9d.png)
