### ISSUE TITLE
DaxStudio.vsto does not install, DaxStudio.ico is missing

### ISSUE THREAD

**Issue by arisaastamoinen** [DaxStudio/DaxStudio#1064]
**Describe the bug**
VSTO does not install, missing .ico file

**To Reproduce**
1. Go to ".\Dax Studio\bin"
2. Click on 'DaxStudio.vsto'
3. Wait for installer magic "Retrieving Office customization information..."
4. Fails with error:
Name: DaxStudio
From: file:///C:/RDSProgramFiles/DAX Studio/bin/DaxStudio.vsto

************** Exception Text **************
System.Deployment.Application.DeploymentDownloadException: Downloading file:///C:/RDSProgramFiles/DAX Studio/bin/DaxStudio.ico did not succeed. ---> System.Net.WebException: Could not find file 'C:\RDSProgramFiles\DAX Studio\bin\DaxStudio.ico'. ---> System.Net.WebException: Could not find file 'C:\RDSProgramFiles\DAX Studio\bin\DaxStudio.ico'. ---> System.IO.FileNotFoundException: **Could not find file** 'C:\RDSProgramFiles\DAX Studio\bin\DaxStudio.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

**Expected behavior**
VSTO should be installable with vstoinstaller.exe or just by double-clicking the .vsto file

**Screenshots**
Added screenshot of error message
![DaxStudioFailure](https://user-images.githubusercontent.com/56233438/223822495-24c1d5b2-aea6-4f04-9df9-a4e892de5214.png)

**Additional context**
My DaxStudio installation is in C:\RDSProgramFiles but this is irrelevant as the .ico file is missing regardless of where DaxStudio is installed

**Comment by dgosbell** [comment]
The .ico file issue is not important. The DAX Studio Excel addin does not support installation via a double click. 

It needs to be registered using the installer to function correctly. This is documented here https://daxstudio.org/docs/installation/index/ 

I might even extend this documentation to explicitly warn against trying to double click the vsto file.

I could fix the missing daxstudio.ico file issue, but it will not fix the root issue - which is that a default double-click install will load the addin, but it will not register it correctly. So you would have the addin visible in Excel, but it will not function correctly. Therefore I'm tempted to leave this so people at least get an error when attempting to double-click the vsto file.
