### ISSUE TITLE
Selecting DESCRIPTION from $SYSTEM.MDSCHEMA_MEASURES

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1065]
If you run **_SELECT DESCRIPTION FROM $SYSTEM.MDSCHEMA_MEASURES_** it throws an error that 'the syntax for DESCRIPTION is incorrect'.

**Comment by dgosbell** [comment]
I believe the DESCRIPTION is a keyword in the Microsoft DMX language (which is what the DMV queries use)

If you enclose it in square brackets it should work `SELECT [DESCRIPTION] FROM $SYSTEM.MDSCHEMA_MEASURES `

**Comment by SharmaAntriksh** [comment]
> I believe the DESCRIPTION is a keyword in the Microsoft DMX language (which is what the DMV queries use)
> 
> If you enclose it in square brackets it should work `SELECT [DESCRIPTION] FROM $SYSTEM.MDSCHEMA_MEASURES `

Thanks!
