### ISSUE TITLE
Wrong Setup hash - for release 3.0.6

### ISSUE THREAD

**Issue by shishini** [DaxStudio/DaxStudio#1077]
get-fileHash -Algorithm SHA256 '.\DaxStudio_3_0_6_setup.exe'

produces this hash: 498FD9D749D25F9C6B2FA3BE77315E40F0A14C97F00D0D186CCAA50F33E5046E
Setup hash file in https://github.com/DaxStudio/DaxStudio/releases/download/v3.0.6/Setup_Hash.txt
has this hash: 17b7b6cf3b6f5032c92d105b23f6d619ce86695cfed349324a46ebbe1ea64631

**Comment by dgosbell** [comment]
Thanks for logging this. I'm actually accidentally calculating the hash of the hash. I've corrected the build script so the next release will generate the same hash as the Get-FileHash cmdlet.
