### ISSUE TITLE
Dax Studio Installation

### ISSUE THREAD

**Issue by Neochiku** [DaxStudio/DaxStudio#1078]
Installed Dax Studio Version 3.0.6

Connect 
PowerBI/SSDT Model is greyed out

Installed with local administrative permission on windows 10 surface

**Comment by dgosbell** [comment]
Did you have Power BI Desktop or SSDT open with a model loaded? This option should enable if you have a running instance of either of these tools.

**Comment by dgosbell** [comment]
closing due to lack of response
