### ISSUE TITLE
Linked excel export dont work if there are single line comment the beginning of the query

### ISSUE THREAD

**Issue by nexus150** [DaxStudio/DaxStudio#1080]
**Describe the bug**
When you try to export to xls linked, if the query was pasted from the performance analyzer of Power BI Desktop or with the "Preview Data" option of the metadata pane, having a single line comment at the beginning, excel shows an error when trying to open the dynamic file, the error: "the database driver does not include the features needed and cannot be used with excel...."(im attaching an image, but in Spanish).

**To Reproduce**
1.- Open a model
2.- Change Resuts to Linked XLS
3.- Go to Metadata Pane
4.- Preview Data on Any Table or Column

**Expected behavior**
Excel opens, with a table linked to the DAX Query.

**Screenshots**
![image](https://user-images.githubusercontent.com/11592309/225980293-a0462e31-3893-4b7f-8c79-503e9e1ec70c.png)

**Additional context**
Single line comments can also cause the same problem not only being at the beginning of the script but in other parter as well, it seems that when passing the query to excel the line break is not taken, then the comment when opened ( // ) affects the next part of the query.

**Comment by dgosbell** [comment]
Thanks for logging this. It looks like the newlines are not being encoded correctly for the xml format of the odc file. A fix for this will be included in the next release. This issue will automatically close when I push out the next release

For the time being the workaround is to either temporarily remove single line comments or replace them with block comments eg `/* comment */`
