### ISSUE TITLE
DAX Studio - 401 Unauthorized.  

### ISSUE THREAD

**Issue by jaylynrepdos27** [DaxStudio/DaxStudio#1087]
Hi everyone. 

I'm an admin of a power Bi workspace which I'm trying to connect to the DAX studio, but Im getting this error message. 

![image](https://user-images.githubusercontent.com/128844931/227622742-a6453dc7-2f6a-45e2-9dcc-a5b767e2c146.png)

Can someone help, please? The datasets are saved on the Sharepoint as it needs to be visible to my colleagues, but the workspace was created by me, and I'm the admin.

**Comment by dgosbell** [comment]
A 401 error is an access denied message from the server you are connecting to. So this issue is on the service side. Is this a premium workspace with the XMLA endpoint enabled? Did you copy the connection string from the workspace settings and does it start with powerbi:// as per https://daxstudio.org/docs/tutorials/getting-connected/#connecting-to-power-bi-premium-xmla-endpoint

**Comment by jaylynrepdos27** [comment]
> A 401 error is an access denied message from the server you are connecting to. So this issue is on the service side. Is this a premium workspace with the XMLA endpoint enabled? Did you copy the connection string from the workspace settings and does it start with powerbi:// as per https://daxstudio.org/docs/tutorials/getting-connected/#connecting-to-power-bi-premium-xmla-endpoint

-- Hi @dgosbell , Thanks for the reply. 
May I know if it requires the workspace to be a premium capacity or if the user is a premium user for it to work so the XMLA endpoint to be enabled? if so, a Power BI pro license is not sufficient unless the workspace is at premium capacity.   Is that correct? Thanks in advance.

**Comment by dgosbell** [comment]
> May I know if it requires the workspace to be a premium capacity or if the user is a premium user for it to work so the XMLA endpoint to be enabled? 

Yes, you either need a premium capacity or premium per user to enable the XMLA endpoint.

> if so, a Power BI pro license is not sufficient unless the workspace is at premium capacity. Is that correct?

This is correct.

**Comment by jaylynrepdos27** [comment]
> > May I know if it requires the workspace to be a premium capacity or if the user is a premium user for it to work so the XMLA endpoint to be enabled?
> 
> Yes, you either need a premium capacity or premium per user to enable the XMLA endpoint.
> 
> > if so, a Power BI pro license is not sufficient unless the workspace is at premium capacity. Is that correct?
> 
> This is correct.

-- Thank you so much @dgosbell . Really appreciate it.
