### ISSUE TITLE
In-editor modification of model measures not effecting dependent model measures in query

### ISSUE THREAD

**Issue by codechrisps** [DaxStudio/DaxStudio#1088]
**Describe the bug**
When modifying a model measure in the editor, dependent model measures are not pointed to the in-session modified version of the measure. Dependent measures are only recalculated against the modified measure if they are also placed in the same editor window, otherwise they will calculate against the original model measure.

**To Reproduce**
1. Connect to a Power BI desktop model.
2. Set up an EVALUATE statement using SUMMARIZECOLUMNS(). Query builder works great to get it set up. Make sure to add at least two measures, where one is dependent on the other.
3. Find the "dependent on/parent"-measure in the in the Metadata-pane, right click and choose "Define Measure".
4. Run the query without any changes.
5. Modify the measure that was added to the query-editor window.
6. Re-run the query and both measures should now return a different result.
7. However, the dependent measure does not change. It does however change if it's definition is also added to the editor.

**Expected behavior**
The expected behaiviour would be for all measures dependent on an in session modified measure to be redirected to the modified definition, without also having to add all their definitions to the editor window before running the query.

**Screenshots**

**Additional context**
I am not 100% sure that this was not the behaviour also in previous versions, but I noticed it after installing 3.0.6, and it seems like an odd behaviour. Especially in my scenario where I have heavily utilized and relied on measure branching in my models.
![DAX Studio Odd](https://user-images.githubusercontent.com/129112852/228059984-acb44bb0-456f-4547-8023-b76f778d8e46.png)

**Comment by marcosqlbi** [comment]
This is by design in the engine, it does not depend on DAX Studio, and it is why you should use the feature "Define dependent measure" starting from the measure you apply to the report when you want to modify the behavior of related measures in your query.

**Comment by codechrisps** [comment]
Thank you for your response @marcosqlbi! I think it would be a good future feature to have DAX Studio perform the "Define dependent measures" implicity/in the background if one so chooses. Any chance this could be added to the ideas-list for the future?

**Comment by marcosqlbi** [comment]
A safe way to do that is to analyze the query measures defined and add to those definitions the measures that depend on them and are referenced (directly or indirectly) in the query. But it's complex to manage that fully automated and without a full parser. You may inject duplicated measures and get hard-to-explain errors as a result. 
A full parser is a huge investment. I don't think it's sustainable for a tool like DAX Studio.
