### ISSUE TITLE
can not able to enter values when Multiple variables used

### ISSUE THREAD

**Issue by farhansoomro** [DaxStudio/DaxStudio#1090]
**Describe the bug**
cannot able to enter values when Multiple variables used, single variable is fine 

**To Reproduce**
Define more than one variables. A popup screen appears but no option to enter a value. 

**Expected behavior**
Able to input value for the variables .

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
I can't reproduce this, using multiple variables works fine for me. Can you provide an example query or some screenshots of this issue?
![image](https://user-images.githubusercontent.com/8241830/229632705-0ec39b3a-a6c3-412e-a9f8-83a573ba458c.png)

**Comment by dgosbell** [comment]
Closing due to lack of response. Feel free to reopen or create a new issue if you can provide more information.
