### ISSUE TITLE
Search/Replace with multiple tabs

### ISSUE THREAD

**Issue by bruce-clawson** [DaxStudio/DaxStudio#1091]
DAX Studio v3.0.6.893
Connection: PowerBIDesktop - 16.0.71.16

## Summary of Issue
When performing a subsequent search/replace action on a separate tab if the replace box is left empty the replacement value from a previous tab is used instead of a blank value.

I was attempting to remove several single quotes from some text by performing a search/replace and leaving the replace box empty. This normally works great but not after using search/replace on another tab.

## Steps to Reproduce
1. on first tab perform a search/replace action to replace some text in the window
2. on a new (second tab) perform another search/replace leaving the replace box empty. The value from the first replace will be used.

**Comment by dgosbell** [comment]
Thanks for logging this. The binding for the replacement text was not refreshing correctly on the second tab. I've checked in a fix for this which will be in the next release.
