### ISSUE TITLE
"dax" spelling mistake in the installer

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1092]
At a certain point when using the DAX Studio installer, there will be a check box that says: "[NOT RECOMMENDED] Blocks all features requiring internet access including version checks, dax formatting and crash reporting. This setting requires a re-install to change."

"dax" should be "DAX". You might also want to consider changing "a re-install" to "reinstallation".

**Comment by dgosbell** [comment]
Thanks for logging this. I've updated the installer and this fix will be included in the next release.
