### ISSUE TITLE
Unable to run queries with Server Timings enabled

### ISSUE THREAD

**Issue by mark-endicott** [DaxStudio/DaxStudio#1097]
Hello, 
This morning I have been unable to run any queries with Server timings enabled - If I switch them off, the queries work. The error message I am receiving is seen below: 

![image](https://user-images.githubusercontent.com/95371077/232458839-130dd099-834a-435a-a2df-fc71305809c8.png)

I have restarted the application several times, but to no effect. I'm on version 3.0.6 and have been since its release. Traces were running fine on 14/04/23. I have been intermittently receiving [this](https://github.com/DaxStudio/DaxStudio/issues/1076) issue also. 

I am running queries against a PBI data model held on the Server. 

Please can someone advise?

Thanks, 
Mark

**Comment by mark-endicott** [comment]
Full screenshot showing working query with no Trace enabled. 

![image](https://user-images.githubusercontent.com/95371077/232461422-7634eeca-9d18-46de-ab78-ecca47c67598.png)

**Comment by mark-endicott** [comment]
[DaxStudio-20230417.log](https://github.com/DaxStudio/DaxStudio/files/11249275/DaxStudio-20230417.log)

**Comment by dgosbell** [comment]
Sorry, but this is a Power BI issue. I'm not sure why this is happening, but it looks like Power BI keeps cancelling the query session. DAX Studio has a retry mechanism built-in but the Server Timings needs to be able to filter on the SessionID of the executing query and it won't be able to do that if the session keeps getting cancelled as the ID will keep changing. 

From what I understand, this type of error should be transient. If you are seeing it consistently you might need to raise a support ticket with Microsoft.

**Comment by mark-endicott** [comment]
Thanks @dgosbell it did clear after a few attempts on Monday, so I will speak with MS if we get any further issues.
