### ISSUE TITLE
工作室有没有计划增加语言选项啊，期待上线中文简体语言

### ISSUE THREAD

**Issue by 50lovelace** [DaxStudio/DaxStudio#1098]
工作室有没有计划增加语言选项啊，期待上线中文简体语言

**Comment by dgosbell** [comment]
Duplicate of #772
Google translate gives me this as the translation for your issue: "Does the studio have any plans to add language options? I look forward to launching Simplified Chinese". 

So I'm going to close this as it's a duplicate of the issue above. I would be open to adding other translations in future, but it's a fair bit of work and there are a number of technical issues I have to figure out.
