### ISSUE TITLE
VertiPaq analyzer rendering glitches

### ISSUE THREAD

**Issue by greggyb** [DaxStudio/DaxStudio#1099]
**Describe the bug**

The column headers displayed in the VertiPaq Analyzer tab can become out of sync with the column data.

**To Reproduce**
1. Open DAX Studio
2. Open VPAX (exported from TE 3.6.0)
3. Observe column alignment in VertiPaq Analyzer in the 'Tables' view
4. Expand first table (it has columns sufficiently long enough to force the column header to re-align)
5. Collapse the first table
6. The later tables' column values no longer align with the column headers

**Expected behavior**

All column values should align with the column headers, even if one or the other is forced to move when re-rendering.

**Screenshots**

In order: first open, expanded, collapsed

![first-open](https://user-images.githubusercontent.com/12113895/235252222-62606990-6f61-49d7-925c-b672fba9163f.png)

![expand-first](https://user-images.githubusercontent.com/12113895/235252242-1af21665-58b8-4e72-a2ba-d939df672ce2.png)

![collapse-first](https://user-images.githubusercontent.com/12113895/235252261-19ff5e95-62ee-41d6-9a01-0e9e24e33ea3.png)

**Comment by greggyb** [comment]
Note: I am having some trouble creating a simple reproduction of this with just a couple tables. I can probably share the vpax causing issues privately.

**Comment by JamesDBartlett3** [comment]
I've noticed this same issue also, when using the VertiPaq Analyzer on a live connected model. If the DAX Studio application window is small enough that the columns become too wide for all of them to display at once, it automatically adds a horizontal scrollbar at the bottom, and when I scroll horizontally, the data values move, but the column headers don't.
![dax_studio_column_glitch](https://user-images.githubusercontent.com/37491308/235258765-83b80cb0-234f-445c-ab65-63152580ce43.gif)

**Comment by dgosbell** [comment]
@JamesDBartlett3 - I was aware of this issue when the window size was small and I think I've found a difference in the styling of the details rows vs the headers rows which seems to be causing this so I think I have a fix for this one.

Thanks @greggyb - I think I've seen this once or twice, but I don't have a good repro. If you can share a vpax privately it will be interesting to see if the same fix addresses your issue.
