### ISSUE TITLE
Server Timings stuck at 'Waiting for Query End event'

### ISSUE THREAD

**Issue by TAPrill** [DaxStudio/DaxStudio#1100]
DAX Studio v3.0.5.767
Connection: PowerBIService - 16.0.78.23

## Summary of Issue
When 'Server Timings' is toggled on, it gets stuck on 'Waiting for Query End event...' most of the time. I have to close out of the entire program and reopen it to get it to stop.

## Steps to Reproduce
1. Toggle on Server Timings
2. Paste DAX query from Performance Analyzer in Power BI Desktop
3. Run

**Comment by dgosbell** [comment]
What sort of data source are you connecting to (PBI Desktop / XMLA Endpoint / SSAS / AAS / Power Pivot) ?
Are there any warnings or errors in the Log tab? The wait for the Query End should timeout after 30 sec.
Have you increased the timeout for either the Trace Startup or Server Timings End Event in the options?

**Comment by TAPrill** [comment]
XMLA Endpoint to a Power BI Premium Dataset.
After the timeout message, I adjusted the timeout settings and still no luck. 
No errors.

**Comment by dgosbell** [comment]
I cannot reproduce this on my premium datasets. Is this a busy premium capacity? It is possible if the capacity is under heavy usage that some trace events might get dropped (since the service will prioritize answering queries over raising trace events) but this should be pretty rare and should not happy consistently. 

Are you connected over a VPN or through a corporate firewall or proxy? On occasions I've seen those things seriously slow the trace event traffic. For some reason it seems to effect those long running streams more than the request/response pattern used by queries.

**Comment by dgosbell** [comment]
Closing due to a lack of response. Feel free to re-open if you have more information on this

**Comment by miguel2810** [comment]
Hello, I have the same issue described.
I'm connected via VPN also.
Have you a solution? thank you

**Comment by dgosbell** [comment]
@miguel2810 - it appears that some corporate VPN / proxy servers cause issues at the networking layer with the long running nature of the trace requests. I don't have any work around from a DAX Studio side. My only suggestion is to run a VM inside the network and remote desktop onto that to run DAX Studio.

**Comment by miguel2810** [comment]
Thank you!
So, at this moment the problem is not at the DAX Studio level i see.
So no easy work around to achieve this.
Have you knowledge if a possible update in DAX Studio will resolve this issue?
Thank you!

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dgosbell** [comment]
> Have you knowledge if a possible update in DAX Studio will resolve this issue?

If your VPN is blocking the network traffic I cannot bypass this. You will need to talk to the people running your VPN to see if they can identify and fix the issue.

**Comment by miguel2810** [comment]
Ok thank you a lot for your anwsers!
