### ISSUE TITLE
Missing Digital Signature in DaxStudio.exe after 3.0.5

### ISSUE THREAD

**Issue by fedmts** [DaxStudio/DaxStudio#1104]
3.0.6 and 3.0.7 without Digital Signature in DaxStudio.exe in portable and installer version.

https://daxstudio.org/docs/installation/smart-screen/

**Comment by dgosbell** [comment]
Thanks for logging this. This was also mentioned by someone on twitter a few days ago. A fix for the build script has been checked in which will correct this situation in the next release.
