### ISSUE TITLE
Terminating ")" of CallbackDataID is not highlighted

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1105]
In the xmSQL queries, the call to CallbackDataID is highlighted in yellow except for the terminating ")". This ")" should be highlighted in yellow as well especially since the "(" is already highlighted in yellow.

**Comment by dgosbell** [comment]
Thanks for logging this. We have a fix checked in which will go out in the next release.

**Comment by Kenneth-Barber** [comment]
Does this also fix the issue where the highlighting of CallbackDataID can end prematurely just before a ")" in a column name?

**Comment by marcosqlbi** [comment]
It is possible that there are cases not handled well depending on the content of the DAX expression, because we use Regex and we know it's not perfect. However, if you have an example that doesn't work well it would be helpful. Thanks!

**Comment by marcosqlbi** [comment]
I guess it will stop on unit]) skipping the last )
That's harder to fix by using RegEx - I'll keep you posted.

**Comment by Kenneth-Barber** [comment]
The highlighting stops just before the ")" that is after "unit". Now that I'm looking more closely, the xmSQL query added spaces that turn "(unit)" into "( unit )". I'm assuming that this is part of the general issue of DAX Studio not caring about where the parentheses are.

**Comment by marcosqlbi** [comment]
It should be improved in the latest build. The internal DAX code is still modified adding spaces but we are not going to fix that as it's more complex and provide low value.
