### ISSUE TITLE
can not connect to power bi desktop November 2018 release

### ISSUE THREAD

**Issue by klabir** [DaxStudio/DaxStudio#111]
I am just I am just using Power BI Desktop latest Version and Dual Storage Mode. I am not 100 % sure, but it looks like current DAX Studio can not connect to such models.using Power BI Desktop latest Version and Dual Storage Mode. I am not 100 % sure, but it looks like current DAX Studio can not connect to such models. 

It’s quite strange. It detects the power bi desktop instance, but after connect, it try’s to connect, but it ends without any error, just not connected.
<img width="1128" alt="1" src="https://user-images.githubusercontent.com/45362306/49020482-d66f4080-f190-11e8-9b33-9191fca988c6.png">
<img width="1120" alt="2" src="https://user-images.githubusercontent.com/45362306/49020486-d7a06d80-f190-11e8-95d9-0888c1829e24.png">
<img width="1128" alt="3" src="https://user-images.githubusercontent.com/45362306/49020488-d8d19a80-f190-11e8-8f5d-ee2b6a595d72.png">

[DaxStudio-20181126.log](https://github.com/DaxStudio/DaxStudio/files/2615955/DaxStudio-20181126.log)
[agg2.zip](https://github.com/DaxStudio/DaxStudio/files/2615958/agg2.zip)

**Comment by klabir** [comment]
it looks like an issue with enumeration of port or something like this. finding out the port in a different way let me connect with localhost:port

**Comment by alexey-formalmethods** [comment]
Same problem here

**Comment by dgosbell** [comment]
Version 2.8.0 has just been released with updated data providers, can you check if that has fixed this issue?

**Comment by dgosbell** [comment]
closing due to lack of response. Please feel free to open a new issue if this is still a problem under v2.8.1 or later
