### ISSUE TITLE
Error populating tooltip basic statistics data

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#1118]
### Discussed in https://github.com/DaxStudio/DaxStudio/discussions/1117

<div type='discussions-op-text'>

<sup>Originally posted by **Heidinger35** May 20, 2023</sup>
The error shown in the image below populates on my log screen sporadically. It appears to occur when I hovers over certain fields in the Metadata pane but I can not seem to locate specific columns, measures, or even the action that is causing this error.

Insight on what this error means and what is causing is would be helpful.

![image](https://github.com/DaxStudio/DaxStudio/assets/56665555/d519314a-4277-479f-a958-42c80b2d70d5)
 </div>

**Comment by Heidinger35** [comment]
Hi @dgosbell.

I am using version 3.0.7.

Could this be related to the dataset I'm connected to being direct query? One of the error messages seems directly related to this.

Two different error messages are produced. They seem to vary by table and not by data type. All fields of the same table, regardless of data type, produce either message 1 or 2 and the associated tooltip behavior outlined in the image. Measure fields do not produce an error.

image

I will provide the log file if needed once I've had time to take a look at what it contains.

Thank you for the continued assistance here!

**Comment by dgosbell** [comment]
The TOPNSKIP error would be related to the DQ mode, I have a fix in place for that. But the basic statistics are just doing a min, max and distinctcount - they should work fine in DQ mode.

**Comment by dgosbell** [comment]
The TOPNSKIP issue should be fixed in 3.0.8 but I still do not have any information on what is triggering the basic stats issue and I cannot reproduce it.

**Comment by dgosbell** [comment]
unable to reproduce
