### ISSUE TITLE
Query Builder does not save if you have read-only access to the data source

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#1119]
### Discussed in https://github.com/DaxStudio/DaxStudio/discussions/1115

DAX Studio throws an error trying to access the measure expression if the current user only has read-only access to the data source. A user should be able to save the current state of the query builder even if they have only have read-only access to the data source

**Comment by Heidinger35** [comment]
Hi @dgosbell. Sorry to prod, but any idea if this solution has been tested / when this bug will be fixed? Is there a set rollout schedule of new versions or is this on an as needed basis? Thank you again for your help here!

**Comment by dgosbell** [comment]
I have a couple of datasets at work where I only have read access so I was able to reproduce this issue and test the fix against those.  There is no fixed schedule for releases it's just best efforts when I get spare time, but I will try and get 3.0.8 out in the next few days.

**Comment by Heidinger35** [comment]
@dgosbell excellent thank you so much!

**Comment by dgosbell** [comment]
This should now be fixed in the 3.0.8 release. Sorry for the delay in getting this out.
