### ISSUE TITLE
DAX Studio won't connect to Power Pivot Workbook

### ISSUE THREAD

**Issue by elaticus** [DaxStudio/DaxStudio#112]
I read the previous ticket about this and I don't found solution to my problem to open in Dax Studio Excel Power Pivot Model (don't detect it)
My Excel in this case is an xlsm file
Reading previous ticket I activate the log from DAX studio and Excel Add In, that I attach to you
[DaxStudioExcel-20181129.log](https://github.com/DaxStudio/DaxStudio/files/2628526/DaxStudioExcel-20181129.log)
[DaxStudio-20181129.log](https://github.com/DaxStudio/DaxStudio/files/2628527/DaxStudio-20181129.log)

Thanks in advance

**Comment by dgosbell** [comment]
Unfortunately there are no error messages in these logs. The next version will have some improvements in the error logging that may help identify this issue, but without some sort of error or some way of reproducing this issue we have no way of fixing it at the moment.

**Comment by dgosbell** [comment]
Version 2.8.0 has just been released, can you check this issue using that version? v2.8.0 has updated data providers and I've enhanced some of the logging in the Excel addin. So if it does not work maybe it will log the issue.

**Comment by dgosbell** [comment]
closing due to lack of response. Please feel free to open a new issue if this is still a problem under v2.8.1 or later
