### ISSUE TITLE
Error Connecting - PowerBI Request Failed (StorageInvalidData)

### ISSUE THREAD

**Issue by Arklur** [DaxStudio/DaxStudio#1122]
**Describe the bug**
When I try to connect to a PBI Dataset, I get the following error:
```
2023. 05. 22. 14:41:54		The following error occurred while updating the connection: PowerBI Request Failed.

Action: Generating MWC token from AAD token

Description: {"error":{"code":"StorageInvalidData","pbi.error":{"code":"StorageInvalidData","parameters":{},"details":[]}}}
```

**To Reproduce**
1. Open DAX Studio
2. Try to connect to a PBI Dataset
3. See error

**Expected behavior**
Connection should be successfull.

**Screenshots**
![image](https://github.com/DaxStudio/DaxStudio/assets/9089026/3166370b-d288-483e-ac67-e514e36f8555)

**Additional context**
I'm using 3.0.7 version of the application.
I'm trying to connect to a PBI Dataset that is located on another tenant's workspace / I have to switch organization.
MFA is enabled for my account.
I can access the workspace from other tools (SSMS or TE for example):
![image](https://github.com/DaxStudio/DaxStudio/assets/9089026/bc998e25-073d-4275-b89d-e848294356d6)
Before I didn't have any problem connecting to the workspace, although I did have a problem trying to use the Advanced tab, see #1005.

**Comment by dgosbell** [comment]
That error is coming back from the Power BI service. Does it happen all the time? Have you tried closing and re-opening DAX Studio? I think the Adomd client libraries cache the AAD token, so I don't know if there is any way of switching or connecting to another tenant other than re-starting the application.

**Comment by Arklur** [comment]
Yes, it happens everytime, even after turning off-and-on my laptop. Tried from another computer (my personal computer), same result. I have no issues connecting to a workspace hosted on my company's tenant. Right now I can't test with another tenant's workspace.

P.S Sorry for the late response!
