### ISSUE TITLE
Rename "PowerPivot" to "Power Pivot"

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1123]
"PowerPivot" refers to the Excel 2010 version of Power Pivot, which is no longer supported and which most people would not be using. The name given to current versions of Power Pivot is "Power Pivot". Please replace "PowerPivot" with "Power Pivot" wherever it appears in DAX Studio. This includes but is not limited to:
- 2 instances in the window that appears when you first open DAX Studio
- 1 of the "Timeouts" options

**Comment by dgosbell** [comment]
Thanks for logging this. I'll fix all these instances and check and see if I can find any others.
