### ISSUE TITLE
Label the zoom level more clearly

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1124]
The zoom level is indicated in a dropdown box in the bottom right corner of the DAX query pane. However, the function of this dropdown box is not immediately obvious. Please make it clearer that this is the zoom level by:
- Labelling the dropdown box with "Zoom:" or a zoom icon (e.g. magnifying glass(es) with a "+" or "−" in the middle of the glass)
- Indicating the unit (%) somewhere. The unit can be added after each value in the dropdown menu or can be part of the zoom label (e.g. "Zoom (%):").

**Comment by dgosbell** [comment]
Thanks for logging this. We used to have the % symbol but accidentally dropped it in the v3 UI updates. I'll look into fixing this and maybe adding an icon and/or updating the tooltip.
