### ISSUE TITLE
Selected cell copy improvement in result table

### ISSUE THREAD

**Issue by samaguire** [DaxStudio/DaxStudio#1128]
**Is your feature request related to a problem? Please describe.**
Whenever I right click on the results grid and select copy, it always copies the whole table even when only one cell is selected. This makes it hard to easily add filters to the query builder when try to write quick queries when testing.

**Describe the solution you'd like**
It only copies the selected cells. Have different options (which include to copy with headers) when selecting a row or the whole table using the row and column selectors around the results table.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by dgosbell** [comment]
Interestingly if you click on a cell and use ctrl-c it copies just that cell. Something about the right-click menu seems to be changing the selection or something. I'll see if I can figure out what is wrong here.
