### ISSUE TITLE
Clearing sort order in result table

### ISSUE THREAD

**Issue by samaguire** [DaxStudio/DaxStudio#1129]
**Is your feature request related to a problem? Please describe.**
Whenever I do a column sort in the results table i'm unable to remove the sort without running the query again

**Describe the solution you'd like**
Cycle through three options for sorting the columns: asc, desc, none.
A bonus would also be being able to also have multiple column sorting by holding 'ctrl' when selecting columns.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by dgosbell** [comment]
Sorry, but a sort order of "none" is not a simple thing. The only way to reliably do this is to duplicate the entire result set in memory if you change the sort order (or to automatically re-run the query). Given that the result set can get very large, and the query could be very expensive to run I think the current work approach of re-running the query if you need to return to the default sort order is the better option.

> A bonus would also be being able to also have multiple column sorting by holding 'ctrl' when selecting columns.

You can already do this by holding 'shift' when selecting columns.
