### ISSUE TITLE
Add columns from a hierarchy when adding a hierarchy to query builder

### ISSUE THREAD

**Issue by samaguire** [DaxStudio/DaxStudio#1130]
**Is your feature request related to a problem? Please describe.**
As per the title. It's frustrating having to add them one by one.

**Describe the solution you'd like**
Have not only the hierarchy parent object added, but also all the child columns as well

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by dgosbell** [comment]
So technically a hierarchy is not directly queryable in DAX, it's just a collection of columns. So, I've fixed it now so that when you add a hierarchy it automatically expands all the levels when it runs the query.

**Comment by samaguire** [comment]
Brilliant! 😁

Regards
Stephen

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
