### ISSUE TITLE
exporting data to sql server table: the given columnmapping does not match up with any column in the source or destination.

### ISSUE THREAD

**Issue by hamedelbhrawy** [DaxStudio/DaxStudio#1136]
exporting data to sql server table: the given columnmapping does not match up with any column in the source or destination.

**Comment by hamedelbhrawy** [comment]
i load all Tabels from bi Dataset except on table its rows more than 14 million  i get this error when export data to SQL server : 
exporting data to sql server table: the given columnmapping does not match up with any column in the source or destination.

**Comment by dgosbell** [comment]
What version of DAX Studio are you using?
Are you exporting to a new or existing table?
Does it work if you let the export wizard create the table?

**Comment by hamedelbhrawy** [comment]
Version 3.0.7 (2023-04-18)
export to new table 
 no it doesn't

**Comment by hamedelbhrawy** [comment]
i think this column name  "[HH:MM:SS (AM/PM)] "  case the problem put i can't edit it because i don't have data source any reconditions

**Comment by hamedelbhrawy** [comment]
[Coulmns name.csv](https://github.com/DaxStudio/DaxStudio/files/11660162/Coulmns.name.csv)

you will find columns name here if there any other thing i could help with just ask me to do  . 

thanks for your effort

**Comment by hamedelbhrawy** [comment]
kindly could you explain what should i do make update or how i could use  your code ?

**Comment by dgosbell** [comment]
I think I have a fix in place for this now. If you are interested in testing a preview build you can download one here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/47231146/artifacts otherwise this fix will be in the next release.

**Comment by hamedelbhrawy** [comment]
> I think I have a fix in place for this now. If you are interested in testing a preview build you can download one here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/47231146/artifacts otherwise this fix will be in the next release.

Thank you for your invaluable assistance

**Comment by hamedelbhrawy** [comment]
i hope if i could export certain query to sql too .
