### ISSUE TITLE
View the OLEDB connection string

### ISSUE THREAD

**Issue by rvgfox** [DaxStudio/DaxStudio#1141]
Whe you connect to a Tabular Server it would be nice to see the connection string in the green area for example to be used in Power Query for example to connect to the server:

![image](https://github.com/DaxStudio/DaxStudio/assets/72302636/08f8dee1-1545-439e-9cd0-adc4ab3c1ada)

**Comment by dgosbell** [comment]
You cannot paste connection strings into Power Query, the Power Query connectors typically generate their connection strings internally and not all the options are supported. So, I don't think this would be of much value.

**Comment by dgosbell** [comment]
Are there any other scenarios where you need to copy the OLEDB connection string?

**Comment by dgosbell** [comment]
closing due to lack of response, feel free to re-open if you have more information to share
