### ISSUE TITLE
Translations - Sort by Translationed name

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#1146]
### Discussed in https://github.com/DaxStudio/DaxStudio/discussions/1144

<div type='discussions-op-text'>

<sup>Originally posted by **bluehenve** July  8, 2023</sup>
Hi

I see translated names in the explorer section on the left side of Dax Studio:

- The translated names are sorted by model names ... how can I sort by translation names?
</div>

The default should be to sort by the name the user sees in the metadata pane

**Comment by bluehenve** [comment]
Cant wait for this one :-)
