### ISSUE TITLE
DAX Formatter

### ISSUE THREAD

**Issue by gtraub** [DaxStudio/DaxStudio#1149]
DAX Studio v3.0.8.945
Connection: AnalysisServices - 15.0.35.33

## Summary of Issue
Receive the error message "DAX Formatter.com error: The operation has timed out. Others on my team not having this issue.

## Steps to Reproduce
1. Enter DAX code
2. Click format query

**Comment by dgosbell** [comment]
We send a request to https://www.daxformatter.com/ to get the DAX formatted. Are you able to access that site?

**Comment by dgosbell** [comment]
closing due to lack of response, feel free to re-open if you have more information to share
