### ISSUE TITLE
Dax Studio crashing after win update

### ISSUE THREAD

**Issue by Fcoatis** [DaxStudio/DaxStudio#115]
After windows update v 2.7.4 is crashing in the middle of an evaluate

**Comment by dgosbell** [comment]
What operating system are you running?
Which update did you apply?
Is there any error message?
Does the crash report dialog popup and if so what is the description of the issue and did you submit this bug?
Can you open an Explorer window, paste the following path into the location bar and hit enter `%APPDATA%\DaxStudio\log` if you find a log file there can you attach it to this issue?

**Comment by Fcoatis** [comment]
I´m running win 10 pro 1803 build 17134.471

I dont know the update once I just realized the crash these days. I think it must be one of the last updates since I was not running DAX for a while.

No error messages just DAX shuts down.

[DaxStudio-20181213.log](https://github.com/DaxStudio/DaxStudio/files/2681105/DaxStudio-20181213.log)

**Comment by Fcoatis** [comment]
event viewer reports errors related to kernellbase.dll

Nome do Log:   Application
Fonte:         .NET Runtime
Data:          16/12/18 10:24:08
Identificação do Evento:1026
Categoria da Tarefa:Nenhum
Nível:         Erro
Palavras-chave:Clássico
Usuário:       N/D
Computador:    Dell-7460
Descrição:
Aplicativo: DaxStudio.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma exceção sem tratamento.
Informações da Exceção: System.NullReferenceException


Nome do Log:   Application
Fonte:         Application Error
Data:          16/12/18 10:24:13
Identificação do Evento:1000
Categoria da Tarefa:(100)
Nível:         Erro
Palavras-chave:Clássico
Usuário:       N/D
Computador:    Dell-7460
Descrição:
Nome do aplicativo com falha: DaxStudio.exe, versão: 2.7.4.102, carimbo de data/hora: 0x5a8c0e68
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.17134.441, carimbo de data/hora: 0x428de48c
Código de exceção: 0xc000041d
Deslocamento da falha: 0x000000000003a388
ID do processo com falha: 0x35b8
Hora de início do aplicativo com falha: 0x01d4953a2b15e88d
Caminho do aplicativo com falha: C:\Program Files\DAX Studio\DaxStudio.exe
Caminho do módulo com falha: C:\WINDOWS\System32\KERNELBASE.dll
ID do Relatório: 33d70d32-3c07-4cda-9843-5ca73aa6d1c6

**Comment by dgosbell** [comment]
V2.8.0 has just been released. Can you install that and see if this issue still exists?

**Comment by Fcoatis** [comment]
Thank You,

As far as I used, It is stable now.

Best regards,


Fábio Coatis
