### ISSUE TITLE
Typo in Version 3.08

### ISSUE THREAD

**Issue by Tamiri** [DaxStudio/DaxStudio#1152]
DAX Studio v3.0.8.945
Connection: PowerBIDesktop - 16.0.87.16

## Summary of Issue
When trying to create a new measure, using the Query Builder, the tooltip has a typo.
"The Measure Expression is blank. This can happen if **uou** do not...." 
uou should be -> you

see image.
![image](https://github.com/DaxStudio/DaxStudio/assets/10829435/2289c233-52f2-45b2-bf3c-6def651582b8)

## Steps to Reproduce
1. Create a new measure using the Measure Builder
2.

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fix checked in that will go out in the next release and I've tagged this issue so it will auto close when that release is published

**Comment by Tamiri** [comment]
With pleasure. Happy to contribute to this amazing project. Thank you!!
Tamir
