### ISSUE TITLE
Generating query for referenced objects results in syntax error if name contains apostrophe

### ISSUE THREAD

**Issue by mrisump** [DaxStudio/DaxStudio#1155]
**Describe the bug**
When showing objects that reference a measure with a name that contains an apostrophe `'` (Char 39), the generated SQL does not escape the apostrophe, causing a syntax error.

**To Reproduce**
1. Create a measure in your model with a name like `'Measure`
2. Right-click on the measure in the Metadata pane, and select "Show Objects That Reference Measure"
3. The query will run and result in a syntax error on the `WHERE [REFERENCED_OBJECT] = ''Measure'` line

**Expected behavior**
No syntax error should result, and referenced objects should be be found: i.e. the generated query should escape the `'`, so it would read `... = '''Measure'`.

**Screenshots**
![image](https://github.com/DaxStudio/DaxStudio/assets/30776472/ba37295b-f2ed-418d-9da2-8401b5b4d0fd)

**Additional context**
DAX Studio: 3.0.8 (2023-07-03)

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fix checked in that will be part of the next release.
