### ISSUE TITLE
Can't Enable DAX Studio

### ISSUE THREAD

**Issue by winstonsnyder** [DaxStudio/DaxStudio#1157]
Hi,

Just installed 3.0.8 including Excel.
When I fire up Excel, I do not see DAX Studio.

I checked COM Add-ins, the tick mark is missing.
I tried to tick the Add-in. I still do not see DAX Studio.

I checked Diasbled Add-ins - nothing.
I am running Smart View (COM) and Htsbar (Excel) add-ins which could be causing an issue?

Thanks.

**Comment by dgosbell** [comment]
Can you run DAXStudioChecker https://daxstudio.org/docs/troubleshooting/daxstudio-checker/ and paste the output back to this issue on github?

**Comment by dgosbell** [comment]
Closing due to lack of response
