### ISSUE TITLE
Advance Tab of Dax Studio doesn't show Metrics (View Metrics) Section

### ISSUE THREAD

**Issue by GagsGit** [DaxStudio/DaxStudio#1160]
**Describe the bug**
Unable to see any Metrics option under Advance Tab of Dax Studio specially View Metrics

**To Reproduce**
I've enable to Advance Tab by selecting a Feature from option under File, Aggregation review does nothing so selected others and all.

**Expected behavior**
On Selecting a feature from option tab I should be able to see Metrics section with option like "View Metrics" , "Export Metrics", "Import Metrics"

**Screenshots**
![image](https://github.com/DaxStudio/DaxStudio/assets/141735434/75471c94-8f13-4761-a373-bbdd10cbfeb8)

![image](https://github.com/DaxStudio/DaxStudio/assets/141735434/238b8f00-bc16-460c-be81-b60bee6a2960)

![image](https://github.com/DaxStudio/DaxStudio/assets/141735434/3c04111b-8896-4248-af14-8ab6bc32fe7b)

**Additional context**
I'm actually trying get the partition size of a Tabular cube, couldn't find any SQL or DAX query to get the same hence trying this option.

**Comment by marcosqlbi** [comment]
From the Options screenshot, it seems you're using an old version of DAX Studio. Can you try to get the latest version first?

**Comment by dgosbell** [comment]
Marco is correct v2.8 is over 4 years old I don't think we had the view metrics back then.
