### ISSUE TITLE
DAX containing the text string "]" is breaking parameter identification

### ISSUE THREAD

**Issue by edgerley** [DaxStudio/DaxStudio#1163]
**Describe the bug**
When my DAX contains a parameter and performs an operation with the character "]" the following error is returned in DAX Studio: "The query contains the 'test' parameter, which is not declared.".  I expect DAX Studio to pop-up the Query Parameters popup but this error is returned instead.

**To Reproduce**
Open DAX Studio and paste the following and run it:
EVALUATE
VAR parameter = @test
VAR bracket = "]"
RETURN bracket

**Expected behavior**
I expect the "Query Parameters" dialog to pop-up prompting me to enter a value for the parameter named @test.  Instead I receive the error message "The query contains the 'test' parameter, which is not declared."  If you change the ] character to any other character DAX Studio works correctly and pops-up the Query Parameters popup prompting for the @test parameter.

**Screenshots**
Current behavior:
![image](https://github.com/DaxStudio/DaxStudio/assets/11369572/ce62c321-8101-4652-a174-7b772c6287ec)

Expected behavior:
![image](https://github.com/DaxStudio/DaxStudio/assets/11369572/a0bc5dd8-4844-45aa-a305-e68f045b1d67)

**Additional context**
I am testing in the latest 3.0.8 version of DAX Studio.
The example provided is a simplified scenario, our actual code is attempting to perform text replace operations on the "]" character which results in the same issue.  It appears that the existence of the ] character in a string causes DAX Studio to not to detect certain parameters correctly.

**Comment by dgosbell** [comment]
Thanks for logging this. I can reproduce this on my PC and I believe I have a fix that will address this issue

**Comment by edgerley** [comment]
Thanks Darren, that was a very fast turnaround.
I just tested v3.0.9 and everything is working as expected now, thank you!!

Ryan

**Comment by dgosbell** [comment]
:) - I was just about to publish 3.0.9 when your bug report came in and because it had a clear repro and I have a suite of tests around the parameter detection code already it was not too hard to fix and test.
