### ISSUE TITLE
Unable to apply filter in "All Queries"

### ISSUE THREAD

**Issue by MarcusXIV** [DaxStudio/DaxStudio#1167]
**Describe the bug**
I run some queries in my report and when I tried to filter them in DAX Studio, any filter is working.

**To Reproduce**
1. Go to 'All Queries'
2. Click on 'Filter'
3. Write a filter

**Expected behavior**
It should filter the queries by duration, type...

**Screenshots**
![Captura de pantalla 2023-08-22 114448](https://github.com/DaxStudio/DaxStudio/assets/127067922/84d265f6-e63e-42d4-9fac-988ddc47fcb8)

**Comment by dgosbell** [comment]
Thanks for logging this. Most of the filter columns work except the duration one. There is meant to be a dropdown to enable you to pick the operator =,<,>,>=,<= but it's not showing for some reason. I need to drill into this further to try and figure out why it's not displaying.

**Comment by dgosbell** [comment]
This should be fixed in the 3.1 release
