### ISSUE TITLE
the result set returned by the server is not a rowset

### ISSUE THREAD

**Issue by PedroEscalanteL** [DaxStudio/DaxStudio#117]
Been trying to run a query i did on power bi which i have connected to dax studio but everytime i try tu run it this message appears and io dont know whats the problema. 

"the result set returned by the server is not a rowset"

**Comment by dgosbell** [comment]
Closing due to lack of response, feel free to re-open if you have more information to add

**Comment by JanSieb** [comment]
I am experiencing the same error message in DAX Studio when trying to analyze a PBIX with an OData connection.
As far as I can tell, the data is returned in JSON format.
Is this already the clue? Do I receive the error on the data not being a rowset, because it is in JSON format?

**Comment by dgosbell** [comment]
@JanSieb -  What do you mean by "analyze a PBIX"? 
Are you trying to running a query? if so what is the text of the query? Can you provide a full screenshot of the DAX Studio UI?
Or are you trying to use the View Metrics feature?

**Comment by JanSieb** [comment]
Sorry Dosbell, 
PBIX is the file extension of Power BI Desktop files.
When starting DAX Studio with NEW you can choose "PBI/SSDT Model" and the Power BI Desktop (PBIX) file.
![image](https://user-images.githubusercontent.com/72790040/95842449-d6599900-0d46-11eb-851f-ac399a5662a3.png)
Now if I e.g. select the "Contract" table of my model and click the RUN button I receive the error message stated by Pedro two years back.
![image](https://user-images.githubusercontent.com/72790040/95842906-67c90b00-0d47-11eb-9d52-a3cdf34d504c.png)

**Comment by marcosqlbi** [comment]
DAX Studio requires writing DAX queries.
You can try writing EVALUATE Contract in the query window.
You can also try the query builder in DAX Studio or read these articles:
https://www.sqlbi.com/topics/from-sql-to-dax/

**Comment by JanSieb** [comment]
Ah, thanks Marcosqlbi!
