### ISSUE TITLE
No results displayed on Load Perf Data

### ISSUE THREAD

**Issue by gsilluzio** [DaxStudio/DaxStudio#1171]
DAX Studio v3.0.10.962
Connection: PowerBIDesktop - 16.0.92.17

## Summary of Issue
After selecting the exported PowerBIPerformanceData.json file, Load Perf Data doesn't show any data.
Error: Error Loading Power BI Performance Data: the value cannot be null. Parameter name: value.

## Steps to Reproduce
1. Export PowerBIPerformanceData.json from Power BI
2. Click Load Perf Data in DAX Studio

[This](https://github.com/DaxStudio/DaxStudio/files/12436728/PowerBIPerformanceData.json.txt) is the PowerBIPerformanceData.json file causing the error.

**Comment by dgosbell** [comment]
Thanks for logging this. The example file really help. One of the visuals has an error and the code is not coping with that. I have a preview version with the fix here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/47880270/artifacts and I'll try and push out an official release in a week or two
