### ISSUE TITLE
The name of file of the model is always  "Unknown.pbix"

### ISSUE THREAD

**Issue by stanislav-plesk** [DaxStudio/DaxStudio#1172]
DAX Studio v3.0.10.962
Connection: PowerBIDesktop - 16.0.92.17

## Summary of Issue
model file name is always  "Unknown.pbix"

## Steps to Reproduce
I encountered this problem after July 2023. Before that, the Advanced->VertiPaq Analyzer->Summary menu section showed the correct name of the connected model
1.
<img width="610" alt="UnKnown_FileName" src="https://github.com/DaxStudio/DaxStudio/assets/54673797/0cb9ebe2-70d6-403b-8077-c1c23db9a06b">

2.
<img width="292" alt="Old_with_ProperFileName" src="https://github.com/DaxStudio/DaxStudio/assets/54673797/7678796d-64cb-434d-8abc-38fd2329ad33">

**Comment by dgosbell** [comment]
Thanks for logging this I have a fix checked in that will be part of the next release and this issue with automatically close when I publish that.

**Comment by stanislav-plesk** [comment]
Thanks a lot
Looking forward to the next update

вс, 27 авг. 2023 г. в 10:30, Darren Gosbell ***@***.***>:

**Comment by stanislav-plesk** [comment]
Yeah. I got it right. Thank you and good luck !

вт, 21 нояб. 2023 г. в 11:12, Darren Gosbell ***@***.***>:
