### ISSUE TITLE
DAX Studio Query Builder error: "You do not have admin rights to the model"

### ISSUE THREAD

**Issue by Christine-NWD** [DaxStudio/DaxStudio#1178]
**Describe the bug**
In DAX Studio, once connected to the PBI model and going to the Query Builder to create a new message, the following error pops up: "The measure expression is blank. This can happen if you do not have admin rights to the data model". The learn more link provides additiional info: "The most common cause for this is that you do not have admin rights on the data model. This is a permissions issue and there is no way to bypass this to get access to the expression. You can still type in your own measure expression to override the one in the datamodel for you current query or you can cancel out of the edit dialog and your query will still run using the expression in the data model."

**To Reproduce**
1. Go to DAX Studio and connect to the PBI model
2. Click Query Builder
3. Click on NEW to add a new measure
4. The error pops up

**Expected behavior**
Being able to create a measure and get the result, as in older versions

**Screenshots**
![image](https://github.com/DaxStudio/DaxStudio/assets/144633210/80f810a2-03eb-4465-bd08-67c783afc8b4)

** Our Findings"

A team of 4 IT specialists checked permission extensively. We compared a new laptop with version 3.0.10 of DAX Studio to an older device with version 3.0.7 on which it worked. Permissions were exactly the same of both devices. We then rolled back to previous versions of DAX Studio on the new device and found that the last 3 versions have that error. Which makes us wonder if the problem is permission related or rather a bug in the latest versions. 
3.0.10 NOT OK
3.0.9 NOT OK
3.0.8 NOT OK
3.0.7 WORKING

**Comment by dgosbell** [comment]
Thanks for logging this, that warning bar should not be appearing for new measures. I have a fix checked in that will go out in the next release. But it is just a warning, you can still add measure logic and it will work correctly.

**Comment by Christine-NWD** [comment]
Thanks Darren. As silly as it seems, when we saw the message, we assumed it wasn't working and tried to find out which admin permissions were missing ;-)

**Comment by dgosbell** [comment]
It's not silly, it's definitely a bug. I really appreciate you taking the time to report this and help make DAX Studio better. I'm going to re-open this issue in case anyone else runs across it. It will automatically close when I publish the next release.

**Comment by sjthedatatechie** [comment]
I have this issue and I am the creator of the .pbi file. Is this still a bug?

**Comment by dgosbell** [comment]
@sjthedatatechie - yes this issue is still open. I do have it fixed in the source code and this will go out in the next release
