### ISSUE TITLE
Microsoft.Excel.AdomdClient reference in ADOTabular source is missing

### ISSUE THREAD

**Issue by spascoe** [DaxStudio/DaxStudio#118]
I pulled down the latest repo this morning, and after restoring nuget packages, compilation fails due to the reference to Microsoft.Excel.Adomdclient.  This dll doesn't exist on my machine (Windows 10 x64, Office 2016 x64).  I've searched for installers, but am coming up empty.

Is this dll available in a nuget package somewhere or does it require a particular provider to be installed on the system?

Thanks.
(I'm having a similar problem to Issue #84, and was trying to so my own troubleshooting...)

**Comment by spascoe** [comment]
The compile error I'm getting is:
CS0430: The extern alias 'ExcelAdomdClientReference' was not specified in a /reference option

The ADOTabular References looks like this:
![2019-01-07_13-09-17](https://user-images.githubusercontent.com/323367/50785062-826e7600-127d-11e9-87a8-196b445c5e4b.png)

**Comment by dgosbell** [comment]
Yeah, the Excel.AdomdClient references are the only tricky bit with getting a build environment setup. There is a file in the root of the repo called `setup-build-env.ps1` which attempts to find the 3 required dlls and copy them to a /lib folder. You can either try running that powershell file or just read through the script and copy those files manually. There is no nuget package for these files as they are internal to Excel and I don't really like adding binaries like this to source repos. 

Note: the files in the /lib folder are only needed by the compiler for typechecking. At run time we dynamically bind to the versions of these files that are already loaded into memory by Excel. 

It would be great if you could figure out what's going on with #84 as it's not logging any errors and I don't have any way of reproducing this issue at the moment so I have no way of fixing this.

**Comment by spascoe** [comment]
@dgosbell, Thanks for that information.  Office 2016 needed an OFFICE16 folder as well in the script.  I've got a PR to fix that, correct a version issue, and add a readme to document what you told me.

**Comment by dgosbell** [comment]
merged pull request to develop branch
