### ISSUE TITLE
Upgrade to .NET Framework 4.7.1

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#119]
It seems NET Framework 4.7.1 is required to support TLS 1.2 calling external services - does it make sense to upgrade the target to .NET 4.7.1 ?

**Comment by dgosbell** [comment]
This does make sense as most services now require TLS 1.2. Upgrading the projects is not too hard. We'd just need update and test the install script so that it can download and install .Net 4.7.1 if required

**Comment by Styxxy** [comment]
Does the application have to target .NET 4.7.1? Preferably the application doesn't need to target the newer version; only the computer should have installed the newer version in order to use TLS 1.2.

**Comment by dgosbell** [comment]
Yes, it needs to target 4.7.1 or later in order to use TLS 1.2. But the targetting is trivial, it's the changes to the installer and the extra download and install that the end user may have to do that is the painful bit.
