### ISSUE TITLE
Zoom for Editor and Results pane should be independent

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1190]
Currently if you zoom in on the Results pane then it doesn't affect the Editor pane, but if you zoom in on Editor pane then it resets the zoom of Results pane.

Can they both be independent?

https://github.com/DaxStudio/DaxStudio/assets/73054674/10a793db-3c31-4106-b688-efb3c828282a

**Comment by dgosbell** [comment]
Yes, you just turn off the scale results with editor setting
![image](https://github.com/DaxStudio/DaxStudio/assets/8241830/e5ed0f81-5a36-4d56-8db3-02b1e1597c93)
