### ISSUE TITLE
DAX Calculated Columns

### ISSUE THREAD

**Issue by DrYSG** [DaxStudio/DaxStudio#1195]
Sorry for the newbie questions. I have searched your documents and did some testing, but tid not find an article.

Is it possible to do a DAX calculated column in DAX studio:

newCol = IF('table'[col2] >= 0, "positive", "negative")

right now I get syntax errors in DAX studio (but not PBI desktop) for this expression.

**Comment by marcosqlbi** [comment]
DAX Studio executes only DAX query syntax.
You can create a query column by using the DEFINE COLUMN syntax described here: 
https://dax.guide/st/column/

**Comment by RainerHollmannGH** [comment]
Hi Marco, could it be that the DEFINE COLUMN statement in DAX Studio will not work with an Tabular Model from Excel? I received in error message that the "test" - column could not found in the table or is not allowed in this expression? What's strange is that I can't find any reference to this possible restriction anywhere (not even in https://www.sqlbi.com/)

DEFINE 
COLUMN PO[test] = 1

**Comment by dgosbell** [comment]
@RainerHollmannGH - I've answered in the discussion here #1198 where you asked the same question
