### ISSUE TITLE
Command line automation for Exporting Data / using export feature to csv / SQL Server

### ISSUE THREAD

**Issue by LithiumMetalman** [DaxStudio/DaxStudio#1197]
**Is your feature request related to a problem? Please describe.**
Heya, looking for a way to automate the export feature in DAX studio either from cmd line or powershell.

**Describe the solution you'd like**
Ideal solution would be being able to interface with the DAX export feature via cmdline / power shell / or any other scripting methodology for automation

**Describe alternatives you've considered**
Definitely interested in other alternative methods for automating this process from VM / Serverside with powershell / python or any other method recommended

**Comment by Ljupch0** [comment]
There is a big history of this request :) Is it somewhere on the backlog @marcosqlbi?

**Comment by marcosqlbi** [comment]
It's @dgosbell area here :)

**Comment by dgosbell** [comment]
We already have request #92 for this same thing so I might close this as a duplicate. However, I have been working on a prototype for this which is looking promising and hope to get a preview out soon.

**Comment by Ljupch0** [comment]
@dgosbell absolutely great! looking forward to it

**Comment by LithiumMetalman** [comment]
Ditto! Looking forward to this!

**Comment by LithiumMetalman** [comment]
Heya All, Was wondering how the preview is going, any good indicator when this might bloom?

**Comment by dgosbell** [comment]
I'm getting there slowly. I've started working on the documentation and it's highlighted a few scenarios I want to support but need to test.

**Comment by LithiumMetalman** [comment]
@dgosbell much appreciated!!! Thanks and keep up the wonderful work!

**Comment by DrYSG** [comment]
@dgosbell This will be a great feature. Looking forward to testing it.
