### ISSUE TITLE
Double quotes around column values persist on export.

### ISSUE THREAD

**Issue by aplou** [DaxStudio/DaxStudio#1199]
DAX Studio v3.0.10.962
Connection: PowerBIDesktop - 16.0.102.18

Options, Custom Export Format, "Quote String Fields" is switched off.
When I look into the exported CSV file, all the columns have values that are flanked with double-quotes.
These do not exist in source.

## Steps to Reproduce
1. Set Options, Custom Export Format, "Quote String Fields" to off.
2. Set output to "file"
3. Run query
4. Specify file name and output directory when the prompt appears.
In my case this shows all values in every column flanked by double-quotes.

**Comment by dgosbell** [comment]
Did you also choose the custom format in the type dropdown? 
![image](https://github.com/DaxStudio/DaxStudio/assets/8241830/11dc1ebc-ec38-4ee1-9763-ba9182936a3a)

**Comment by aplou** [comment]
I did. But I've also discovered that it seems the export options in app are being ignored.
A pipe is specified as the delimiter here.
![image](https://github.com/DaxStudio/DaxStudio/assets/90292936/8e559a6d-6bcb-4932-8d66-9a62f92d26cc)
But export result still shows comma being used.
![image](https://github.com/DaxStudio/DaxStudio/assets/90292936/fae143c3-5ce7-4a00-956e-4143d8f234e1)
