### ISSUE TITLE
Support for PBI Desktop Windows Store App

### ISSUE THREAD

**Issue by karaoan** [DaxStudio/DaxStudio#12]
Currently Windows Store App is not recognised as a PBI source in the Studio.

**Comment by marcosqlbi** [comment]
Can you clarify what is the behavior of DAX Studio in that condition?

**Comment by karaoan** [comment]
That it is recognised as a source for PBI model. I.e. here: 
![image](https://user-images.githubusercontent.com/32475223/31116675-bd57ca30-a872-11e7-8d01-121d7c9e33c9.png)

**Comment by marcosqlbi** [comment]
I understand the problem. The issue is that we need to be able to reproduce the situation, and we need a version of Power BI Desktop that works on our PC to do that.
I hope Darren will have the ability to test it.

**Comment by karaoan** [comment]
Darren: I didn't have any problems intstalling the PBI desktop app.  If I can assist with anything le me know we are in the same time zone and I am available on Managility contact details.

**Comment by dgosbell** [comment]
I can see what the issue is - the location of the data folder looks like it's abstracted by the App. I'll need to test a few options to see how best to work around this.

**Comment by dgosbell** [comment]
OK, I have a preview of build 2.7.1 up on my [OneDrive](https://1drv.ms/f/s!AnSKp2UbblSYgZsQ_xzxrPM-A1gfmQ) if you would like to try it out. It has a new and improved method for locating local instances of tabular engines that seems to be working with Power BI Desktop, the Power BI Desktop App and the Visual Studio designer instances.

**Comment by karaoan** [comment]
This works great. Thanks a lot Darren!

**Comment by dgosbell** [comment]
Support for this was added in v2.7.1
