### ISSUE TITLE
I cant use Dax studio to connect to Analize Services anymore. What changed?

### ISSUE THREAD

**Issue by CarolinaGuve** [DaxStudio/DaxStudio#1201]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
It still works fine for me.

What error message are you getting?
What version of DAX Studio are you using?
What version of Analysis Services are you trying to access?
Is this a tabular model or a multi-dimensional?

**Comment by dgosbell** [comment]
Closing due to lack of response. Feel free to re-open this if you have more information to add
