### ISSUE TITLE
Cannot create connection

### ISSUE THREAD

**Issue by eccolo33** [DaxStudio/DaxStudio#1203]
Hello, 

I have correctly installed and loaded both PowerPivot and DaxStudio.
I have this PowerQuery that returns more than 2Mln records that I would like to export to csv.

I have been trying to create a connection to the model, but I keep on running on the error below:

![image](https://github.com/DaxStudio/DaxStudio/assets/30812946/5d25cc40-b059-4f80-a19a-ea8738d2028b)

I have DAX Studio 3.0.0
Excel version 2310 32-bit
Can you please help me understand why is this?

**Comment by dgosbell** [comment]
The first thing I would suggest is trying the current release which is v3.0.11 
And do you know the exact version of Excel? (which you can get from File > Account > About Excel)
There was a bug Excel introduced that caused issues when loading this DLL, but that was fixed some time ago.

**Comment by eccolo33** [comment]
![image](https://github.com/DaxStudio/DaxStudio/assets/30812946/a33a743d-6428-4c60-ad1c-0002a150e12d)

**Comment by dgosbell** [comment]
Closing due to lack of response
