### ISSUE TITLE
Error When Connecting To A Power BI Workspace

### ISSUE THREAD

**Issue by bartonl2** [DaxStudio/DaxStudio#1205]
We used to be able to pop a URL into DAX studio which would connect to a Premium Power BI workspace and we could write DAX against the datasets that live in that workspace.

What happens now is we get the error "The following error occurred while updating the connection. An item with the same key has already been added".

To make sure the error wasn't being populated due to an issue with one of our existing datasets - we created a new premium workspace and only uploaded one dataset to that workspace.

 We then tried to connect to this new Premium Power BI workspace in Dax studio via the URL but are still getting the same error.

This has only started happening since last week and was working fine prior. The expected behaviour is that Dax studio connects to the workspace and lists our datasets that are stored on the workspace its pointing too.

Please see below a screenshot of the error we are receiving when trying to connect. Any help would be greatly appreciated

<img width="767" alt="image" src="https://github.com/DaxStudio/DaxStudio/assets/143518125/e0073c3a-8a05-4cd3-aac4-86801b69ce46">

**Comment by coyang1990** [comment]
we are experiencing the same issue, i just posted an issues on the same.

**Comment by dgosbell** [comment]
What version are you running? There was a fix for this error in v3.0.11

**Comment by bartonl2** [comment]
Hello @dgosbell

This is the version we are currently running in DAX Studio. Does this mean we need to install the new version?

 
<img width="391" alt="image" src="https://github.com/DaxStudio/DaxStudio/assets/143518125/9edbca57-0530-4623-b61d-2cdc5e78ef6a">

**Comment by bartonl2** [comment]
This was fixed now I downloaded the latest version - thanks for all the help
