### ISSUE TITLE
The following error occurred while updating the connection: An item with the same key has already been added.

### ISSUE THREAD

**Issue by coyang1990** [DaxStudio/DaxStudio#1206]
DAX Studio v3.0.10.962
Connection: PowerBIService - 16.0.108.21

## Summary of Issue
We are getting the error message when trying connecting to Workspace from DAX studio

## Steps to Reproduce
1. Click Connect
2. Type in server address for Tabular Server
3. error shows up and couldn't connect.

**Comment by dgosbell** [comment]
This has already been fixed in v3.0.11 as per #1200
