### ISSUE TITLE
Excel 2019 Addin won't automatically load (works fine if manually enabled)

### ISSUE THREAD

**Issue by Newboy1975** [DaxStudio/DaxStudio#1207]
The Dax Studio Addin isn't visible unless I manually enable it, I've just installed Office 2019 and updated to the most recent Dax studio to try and resolve.  Below is Dax checker output.

    Version =  v3.0.11.982
    DaxStudio.exe Version =  v3.0.11.982
 
Checking Operating System
=======================     OSCaption       = Microsoft Windows 10 Enterprise
    OSRelease       = 2009
    OSVersion       = 10.0.19045
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.88
    FreeMemoryGB    = 8.86
 
    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = dd-MM-yyyy
 
Checking Displays
======================= Display: \\.\DISPLAY6            X: 3840 Y: 0 Width: 3840 Height: 2160 Display: \\.\DISPLAY5 (Primary)          X: 0 Y: 0 Width: 3840 Height: 2160 DPI X: 192 Y: 192 (Scaling: 200.0%) 
Checking .Net Framework
=======================     v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.09037
    v4\Client\1033 -> 4.8.09037
    v4\Full -> 4.8.09037
    v4\Full\1033 -> 4.8.09037
    v4.0\Client -> 4.0.0.0
    v4\Full\Release = 533325 (4.8)
    PASS > .Net Version 4.8 is above the required minimum
 
DAX Studio Configuration
=======================     Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 21
    AMO : <default>
    ADOMD : <default>
 
Checking Excel Add-in
=======================     Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
	HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe
    Excel Architecture: x64
 
    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3
 
    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.     Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.     Checking for Excel 2016 Disabled Add-ins
      N/A  >  - c:\program files\bentley\projectwise\bin\msoffice\pwofficeaddin.dll

**Comment by dgosbell** [comment]
closing due to lack of response
