### ISSUE TITLE
Comma Delimiter Export Format

### ISSUE THREAD

**Issue by IlyaGolubovsky** [DaxStudio/DaxStudio#1210]
DAX Studio v3.0.11.982
Connection: PowerBIDesktop - 16.0.104.22

## Summary of Issue
csv file is always saved with delimiter ;  and Quote string Field true

## Steps to Reproduce

![image](https://github.com/DaxStudio/DaxStudio/assets/86312453/be39060f-be60-4f5c-bd03-4d64d23a17d9)

**Comment by dgosbell** [comment]
Have you selected the "Custom Export Format" as the type when exporting?
![image](https://github.com/DaxStudio/DaxStudio/assets/8241830/a5987584-ce5b-4d6a-8fdb-d8235f514007)
