### ISSUE TITLE
Formatted files and results grid not showing correct formats

### ISSUE THREAD

**Issue by Bayesd12** [DaxStudio/DaxStudio#1213]
I experienced the exact error described in the bug report on this link.
https://github.com/DaxStudio/DaxStudio/issues/1209

I followed advice and updated my Dax Studio. It had the desired result and the error disappeared. 

Unfortunately it affected the "Output" section of Dax Studio resulting in the "formatted files"  losing there format when running my query.

I am attaching 2 images to reflect the before and after. As you can see the Date and Time columns are not formatted.
Before fix
![image 2](https://github.com/DaxStudio/DaxStudio/assets/123781209/0f1fd463-0fd1-4751-bdbd-03671c17f2f3)
After fix
![image 1](https://github.com/DaxStudio/DaxStudio/assets/123781209/4c50da20-f449-41fc-bee5-19bfe3246a06)

Am i missing a setting on Dax studio ? is this another bug as a result of the fix?

Thank you for any assistance.

**Comment by dgosbell** [comment]
I've updated the title since this bug has nothing to do with issue #1209 it was accidentally introduced a few releases before that.

**Comment by Bayesd12** [comment]
Thank you, will you be able to tell me when you have it fixed please.

**Comment by Bayesd12** [comment]
dgosbell, thankyou for the fix... how do i save the code to my Dax Studio... apologies if I am been naive here!

**Comment by dgosbell** [comment]
It's probably easier to wait for the next release, but I have a few other features in flight that I need to finish testing. This issue will automatically close once the release including this fix is published.

Otherwise if you have Visual Studio and know how to clone from github - in theory you could clone the repo and build your own version with the fix that was checked in.

**Comment by dgosbell** [comment]
Actually, you could also try the preview build from our build  server here: https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/48814189/artifacts 
I have not tested this in isolation, but it does contain the checkin for the fix that works in my development branch.

**Comment by Bayesd12** [comment]
dgosbell... you are a legend. Great work. thank you for addressing it so quickly. Dax Studio is a great tool and you are providing a really good service around it.
