### ISSUE TITLE
Unable to view Query in Dax Studio from Power BI Desktop

### ISSUE THREAD

**Issue by Prabu2401** [DaxStudio/DaxStudio#1215]
DAX Studio v2.17.3.683
Connection: PowerBIDesktop - 16.0.109.17

## Summary of Issue
Showing Error

## Steps to Reproduce
![image](https://github.com/DaxStudio/DaxStudio/assets/154493733/8bd64fb5-69b6-47b8-a020-43b97fdb59eb)

2.

**Comment by dgosbell** [comment]
This was fixed in v3.011 as per #1200

**Comment by Prabu2401** [comment]
Thanks, Now its working fine. :)
