### ISSUE TITLE
Error refreshing table list: Un élément avec la même clé a déjà été ajouté.

### ISSUE THREAD

**Issue by mjidinio** [DaxStudio/DaxStudio#1217]
DAX Studio v3.0.10.962
Connection: PowerBIService - 16.0.110.20

## Summary of Issue
Error refreshing table list: Un élément avec la même clé a déjà été ajouté.

## Steps to Reproduce
1.connect to powerbi service workspace using link : powerbi://api.powerbi.com/v1.0/myorg/<workspace>
2.using tabular server option

**Comment by dgosbell** [comment]
This was fixed in v3.0.11 as per #1200

**Comment by Mardurolla** [comment]
I got the same error but in English. Unfortunately need to wait for my admin to authenticate the 3.0.11 exe ...)
![DAXStudioErroritemWsameKey](https://github.com/DaxStudio/DaxStudio/assets/75253784/dd8c742b-adc9-40fe-9dd3-3ca154457982)

**Comment by Mardurolla** [comment]
I got the 3.0.11 update and it is all working now. Thank you dgosbell!
