### ISSUE TITLE
Error when connecting to PIBIX file

### ISSUE THREAD

**Issue by FowmyM** [DaxStudio/DaxStudio#1218]
Following error comes up when trying to connect to any PBIX file. Please note the PBIX were created in Dec 2023 release of Power BI Desktop. I tried with different files, even that were created in older versions, the issue is there.

Errors:

25-Dec-23 11:54:30 AM		The following error occurred while updating the connection: An item with the same key has already been added.

25-Dec-23 11:54:30 AM		Error refreshing table list: An item with the same key has already been added.

**Comment by dgosbell** [comment]
Yes, this issue was fixed in the 3.0.11 release as per #1200

**Comment by FowmyM** [comment]
Thank you @dgosbell, appreciate it.
