### ISSUE TITLE
Table names not appearing in DAX studio

### ISSUE THREAD

**Issue by Im0303** [DaxStudio/DaxStudio#1219]
I have connected to a simple pbix file that has just one table. Though I can run the query using Evaluate the table names do not appear in the side bar.
![Capture](https://github.com/DaxStudio/DaxStudio/assets/154840461/322bfb08-598a-4c9b-8e89-76b18ebaa6ec)

**Comment by dgosbell** [comment]
This was fixed in v3.0.11 as per #1200
