### ISSUE TITLE
Increase security of daxstudio.org

### ISSUE THREAD

**Issue by DubbySlashy** [DaxStudio/DaxStudio#122]
Please redirect HTTP requests to HTTPS (or drop support for HTTP entirely) and submit daxstudio.org for HSTS preloading to help prevent SSL stripping attacks. Please also drop support for the weaker cipher suites and make sure that daxstudio.org scores an A+ in the SSL Server Test. See the links below:
https://hstspreload.org/?domain=daxstudio.org
https://www.ssllabs.com/ssltest/analyze.html?d=daxstudio.org

To be clear, for a website like daxstudio.org, privacy is not the issue with HTTP. The problem is that a "man in the middle" can modify the web page maliciously before it gets to the user. See this video:
https://www.youtube.com/watch?v=_BNIkw4Ao9w

**Comment by dgosbell** [comment]
So I've been able to switch on the setting to always use HTTPS. But I don't believe that I can setup HSTS as we are using Github Pages to host daxstudio.org and they don't currently provide any way to add custom http headers. 

SSLlabs now gives us an A, but unfortunately I can't see any indication of what an "A" means or how to improve to an "A+" - I'm happy to look into any suggestions you may have if you know more about this.

**Comment by DubbySlashy** [comment]
Thank you for switching to HTTPS. It looks like someone has already noticed and reported the lack of HSTS on GitHub Pages:
https://github.com/isaacs/github/issues/1249

The scoring is documented here, and it looks like HSTS is essential to get A+:
https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide

However, the SSL Server Test still pointed out some security issues with daxstudio.org. For example, 2nd certificate is for github.com and not daxstudio.org, and daxstudio.org still supports some weak cipher suites. Basically anything in red or orange. You might need to click on "Click here to expand".

**Comment by dgosbell** [comment]
Yes, I found that issue too. Unfortunately I think both HSTS support as well as the secondary certificate and removing the weaker cipher suites are all under Github's control. Because we are not hosting our own server we don't have a lot of control over some of these server side things. 

I'll do some more research and see if there are any other options to help improve this that are not too expensive.

**Comment by dgosbell** [comment]
I think I've done everything that is in my power regarding this issue now so I'm going to close this issue
