### ISSUE TITLE
#1219 further details

### ISSUE THREAD

**Issue by Im0303** [DaxStudio/DaxStudio#1220]
Further to the issue #1219 the initial screen comes up as the screenshot, prior to using the evaluate command
![Capture 2](https://github.com/DaxStudio/DaxStudio/assets/154840461/66c28ed2-e854-4062-8317-8ad0ba762d1e)

**Comment by dgosbell** [comment]
It's better to add a second comment to an existing issue than to open a new one.

This was fixed in v3.0.11 as per https://github.com/DaxStudio/DaxStudio/issues/1200

**Comment by Im0303** [comment]
Works now with an updated version. Thanks.
