### ISSUE TITLE
DAX Studio not connecting via PBI Desktop upgrade Dec 2023

### ISSUE THREAD

**Issue by Jonathan2037** [DaxStudio/DaxStudio#1221]
DAX Studio v3.0.3.762
Connection: PowerBIDesktop - 16.0.109.17

## Summary of Issue
After upgrading to PBI Desktop 2.124.1052.0 64-bit (December 2023) can not connect to DAX Studio. When connecting, get error on connection indicating "an item with same key has already been added" even if the semantic model is a single table with no duplicated fields. Only experience this after update to Dec 2023 PBI Desktop

## Steps to Reproduce
1. Loaded new .pbix with single table
2. Connect via "External Tool" on PBI Desktop ribbon

**Comment by dgosbell** [comment]
This was fixed in v3.0.11 as per #1200

**Comment by Jonathan2037** [comment]
Thank you! Completely my fault for not confirming version. Appreciate it!
