### ISSUE TITLE
DAX Studio Ver 3.0.11 is crashing while Start up.

### ISSUE THREAD

**Issue by souvikmazumdar** [DaxStudio/DaxStudio#1222]
**Application Crash**
I have installed the current version of DAX Studio in my pc. But it is crashing while I am trying to launch it in windows.
**Problem**
This application is running in background though not opening.

**Screenshots**
[Capture](https://github.com/DaxStudio/DaxStudio/assets/154298654/a9a9044f-8cb1-4c22-a942-501b37e26f5f)

**Comment by dgosbell** [comment]
If it's running in the "background" it has not crashed and could be tricky to diagnose as I do not believe we have had anyone else with an issue like this.

Are you seeing an error message of some sort? If so what is the text of that message?

Did you have an earlier version of DAX Studio and did that run correctly? If so what was the previous version number?

Have you checked the Windows Event Log? Are there any errors orr messages in there relating to DAX Studio?

Can you enable the diagnostic logging as per https://daxstudio.org/docs/troubleshooting/logging-settings/ while attempting to start DAX Studio and then attach the log file to this issue on github?

**Comment by souvikmazumdar** [comment]
![Capture 3](https://github.com/DaxStudio/DaxStudio/assets/154298654/0eb3b7a6-3cc8-4763-83af-54fb6c36e232)
Sir,  
1. I am not seeing any error messages.
2.  I never had any earlier version of DAX Studio installed in my pc.
3. There is no issue in installing DAX Studio but whenever I am trying to open the application it is showing the logo only.

**Comment by souvikmazumdar** [comment]
Sir,
1. I am not seeing any error messages.
2.  I never had any earlier version of DAX Studio installed in my pc.
3. There is no issue in installing DAX Studio but whenever I am trying to
open the application it is showing the logo only.

**Comment by dgosbell** [comment]
The log file I requested above would be really helpful in trying to diagnose this issue. 

This could be related to previously reported issues like this one #513 so you could try solutions posted there. 

It could also possibly be an issue with your video card or video drivers. You could try enabling software rendering as outlined here https://daxstudio.org/docs/troubleshooting/known-issues/UCEERR_RENDERTHREADFAILURE/

**Comment by dgosbell** [comment]
closing due to lack of response
