### ISSUE TITLE
Power BI Connection Issue: An item with the same key has already been added

### ISSUE THREAD

**Issue by Adriaanjac** [DaxStudio/DaxStudio#1224]
DAX Studio v3.0.10.962
Connection: PowerBIDesktop - 16.0.109.17

## Summary of Issue
I am trying to connect a power BI model to DAX Studio and get the following error messages:
* The following error occurred while updating the connection: An item with the same key has already been added.
* Error refreshing table list An item with the same key has already been added.

I am not sure why this is happening. Can someone please assist me with this.

Also refer to the screenshot attached.

Thank you so much

Adriaan

![2024-01-04_05-30-13_Image](https://github.com/DaxStudio/DaxStudio/assets/58063612/2868e234-c308-4c40-b09e-060100063a5e)

**Comment by dgosbell** [comment]
This issue has already been fixed in v3.0.11 as per #1200

**Comment by Ldy92** [comment]
I have the same problem too. are you solved?

**Comment by dgosbell** [comment]
Yes, as per the comment immediately above yours. This was fixed in the current release.
