### ISSUE TITLE
Export DAX Results to simple text, not columned file - for quick GIT / Version Control

### ISSUE THREAD

**Issue by TickboxPhil** [DaxStudio/DaxStudio#1225]
**Is your feature request related to a problem? Please describe.**
Need to version control DAX and not the whole shebang.

**Describe the solution you'd like**
Simply export Results of $SYSTEM.TMSCHEMA_MEASURES as pure text not tabbed/columned or excel. Then it's clearer in the Git diffs.

**Describe alternatives you've considered**
Power BI Desktop Project Export, Tabular Editor 3, various overly complex and easily outdated solutions on GitHub.

**Additional context**
I know the ordering of Measures in the output may make diffs trickier, but this simple output file will be a lifesaver for quick VC.

**Comment by marcosqlbi** [comment]
Did you try the "Define All Measures" in the editor? It creates a script with all the measures.

**Comment by TickboxPhil** [comment]
Where is that, I can't see it as option in DAX Studio 3.0.11 (presuming you don't mean PBI Desktop)?

Currently I run "select * from $SYSTEM.TMSCHEMA_MEASURES" to generate them all in your editor.

**Comment by TickboxPhil** [comment]
Sorry to be a pain, I just can't see that option.

Just to be clear here - all that is needed is the same DAX Studio functionality to output the Results of only the "<MeasureName> = " + Expression column, and not include the other columns which get in the way. 

Surprised I can't find anywhere else to do it, but extra handy to stay in DAX Studio anyway!

**Comment by TickboxPhil** [comment]
Ah I see - flip back to Metadata and then the "Define All Measures" appears on any table/query right click. But there's still no way to quickly dump this great result into text file - you have to copy all then paste into a text document and save! Each time.

Outputting as suggested would provide a 1 or 2 click workflow which doesn't get in way of dev.

**Comment by marcosqlbi** [comment]
I get your point, but if you want to automate everything, how do you obtain that with DAX Studio without any interaction?

**Comment by TickboxPhil** [comment]
I don't need to automate it, just enable a couple of clicks to create the file (pretty much what it does now, just an option without the extra columns) instead of navigating to that particular project in file explorer (often takes ages in itself, similar with "save as"), opening the text file, and pasting results manually into it then saving... Even when working on same project, it's still a disrupting hassle to copy and paste manually into text file and save each substantial change. Would be nice to focus more on DAX, which worse than SQL (where Git version control is crucial) produces very different results with very subtle changes.

Better to export without extraneous columns making it easy for later Git diff comparisons - much less clutter to compare, let alone easier to focus on the DAX without metadata in-between each Measure. Game changer in my opinion.

**Comment by marcosqlbi** [comment]
Thanks for the feedback.
I don't think that DAX Studio is the best tool for the job (after all, Tabular Editor has a better integration for source control), but I get your point.

**Comment by dgosbell** [comment]
If you just want the measure name and expression you could just run the following query 
```
select [MEASURE_NAME], [EXPRESSION] from $SYSTEM.MDSCHEMA_MEASURES
```
But I agree with Marco, I don't think DAX Studio is the best tool for managing schema changes. 

I think a better option would be to look at scripting your models out as TMDL https://learn.microsoft.com/en-us/analysis-services/tmdl/tmdl-how-to?view=asallproducts-allversions there are preview nuget packages which support this now. It can script the whole model out to a text based, diff-able format so you could also capture things like relationships changes which can also impact on measure results and shortly you will be able to edit and save using this TMDL format from Power BI Desktop.

You could even build a powershell script or small c# utility to script out to TMDL and include this in your CI/CD process.

**Comment by TickboxPhil** [comment]
Thanks guys. Waited years for Microsoft "save as project" but the artefacts still don't allow easy measure text version handling. My Tab Editor 3 trial expired, will look at using again. And good heads up on the new TMDL even if in preview, will keep an eye on that.

It was just a "quick and dirty" suggestion as a handy productivity boost but do understand you may not want to encourage measure only code control in this software at this stage, fair enough - it is best linked with schema changes. Keep up the good works all round!

**Comment by dgosbell** [comment]
> Thanks guys. Waited years for Microsoft "save as project" but the artefacts still don't allow easy measure text version handling. 

The project format is still not finished yet. Microsoft is still working on it. The next phase of the preview will use the TMDL, text-based format for all the model metadata. The advantage there will be that you would not have 2 copies of the measure expressions in git. You can diff and merge the TMDL format or edit the measures in a text editor and when you open the report in Power BI desktop any changes will also be reflected there.
