### ISSUE TITLE
DAX Studio error while making connection with Power BI Desktop

### ISSUE THREAD

**Issue by Bob-Wong** [DaxStudio/DaxStudio#1226]
DAX Studio Ver: 3.0.5.767

After I clicked DAX Studio from the Power BI Desktop 'External Tools Tab', it did launch the DAX Studio. But after DAX Studio had launched, There were 2 lines of red text saying;
"The following occurred while updating the connection: An Item with the same key has already been added.
An Item with the same key has already been added."

I have another PC running the same applications and also got this issue with both PCs that I never encountered any issue before.
Please help to resolve this problem.

I sincerely thank you for your kind attention.

**Comment by dgosbell** [comment]
This has already been fixed in v3.0.11 as per #1200
