### ISSUE TITLE
Automation or scheduler for export

### ISSUE THREAD

**Issue by Ressno** [DaxStudio/DaxStudio#1227]
would be nice to have the export capability with a scheduler so we dont do it manually

**Comment by dgosbell** [comment]
I'm working on adding a command line option so that you could run certain DAX Studio tasks unattended like exporting data. Would this meet your needs?

**Comment by Ressno** [comment]
oh yes! thank you to have relied !Sent from my iPhoneOn Feb 1, 2024, at 01:13, Darren Gosbell ***@***.***> wrote:﻿
I'm working on adding a command line option so that you could run certain DAX Studio tasks unattended like exporting data. Would this meet your needs?

**Comment by dgosbell** [comment]
Great, so I might close this issue as I'm already tracking a request for command line support in issue #92
