### ISSUE TITLE
default seperator/delimiter is not taken into account by query builder

### ISSUE THREAD

**Issue by RainerHollmannGH** [DaxStudio/DaxStudio#1228]
DAX Studio v3.0.11.982
Connection: PowerPivot - 13.0.1700.1119

## Summary of Issue
a) If default delimiter/seperator is set to semicolon ";" query builder ignore this and use comma "," instead
b) in some cases (not always) swap delimiter will replace the comma "," not with an semicolon.  several clicks on "swap delimiter" in menue ribbon will lead only in a substitution from comma "," to point "." then. this issue seems to be mostly if you use "auto update" functionaly of query builder and after that try to use the "swap delimiter" which then alows no more to replace "," to semicolon. if the points "." than in the updated query builder statement the "swap delimiter" functionality is no more working.

## Steps to Reproduce
1. for a) In Options/Defaults/Defaults/  set "Seperators" to Other (a;b;c)
2. for a) Use Query-Builder to add Evalutate/Summarize-Statement in to the DAX-editor
3. for b) Update the the Query-Builder code in Editor with usage of the Query-Builder (note: in my case a measure is above the Query-Builder code ). 
4. for b) Than use "swap delimiter" to convert, once again, to semicolon ";". But than the result is a point "." and not a semicolon or comma. pressing again "swap delimiter" will not have any impact (it stays with the points....)

**Comment by dgosbell** [comment]
This is 2 separate issues. I can reproduce and fix a) but I cannot reproduce b) so I've split issue b) into a new issue here #1229

@RainerHollmannGH - could you possibly provide some example query text generated by the query build that breaks the swap delimiters function? If I can see the original text and reproduce the issue by clicking on swap delimiters a few times I should be able to fix it.
