### ISSUE TITLE
Cannot connect remotely to my data model

### ISSUE THREAD

**Issue by colbypeck** [DaxStudio/DaxStudio#1230]
I have a data model saved in my PowerBI web service. I am unable to open the model in the PowerBI app, so I cannot connect to it using the standard Power BI/ SSDT Model option. I am trying to connect to the model using the Tabular Server option, but it will not connect for me, even though all of my other team members are able to access it through this method. I have the same access/permissions as my coworkers who are able to connect to the model in DAX Studios. I also have the newest version of DAX downloaded (3.0.11), and I have restarted my computer multiple times to no avail. 

My coworkers said that they need to sign in to their account using the Initial Catalog dropdown in the Advanced Options section of the Connect tool. When I try clicking the dropdown, it is blank and does not give me the option to sign in.

Does anyone know why it is not connecting or how to resolve my issue?

**Comment by dgosbell** [comment]
"it will not connect" does not really give me any useful information to help diagnose this issue. 

Is there an error message of some sort? If so what does it say?

Have you tried logging in on one of your colleagues machines to see if this is a machine specific issue? Or have any of your colleagues tried to login on your machine?

Can you try enabling the diagnostic logging (see https://daxstudio.org/docs/troubleshooting/logging-settings/ ) then try and login, then close DAX Studio and upload the log to this issue.

**Comment by dgosbell** [comment]
closing due to lack of response
