### ISSUE TITLE
Permissions error when using server timings on Fabric DirectLake default model

### ISSUE THREAD

**Issue by charlespickettau** [DaxStudio/DaxStudio#1234]
**Describe the bug**
When trying to use server timings on the default DirectLake semantic model, users receive a permissions error despite being a workspace admin

**To Reproduce**
1. Create a Lakehouse in Fabric
2. Connect to the default model that is autocreated
3. Try to use server timings

**Expected behavior**
User should either be able to run server timings, or see an actionable error message.

In this case, this appears to be driven by limited permissions being given on the default model, even when a user is a workspace Admin.

Workaround is to duplicate the data model using e.g. Tabular Editor or SSMS Script to and then run server timings on that instead

**Screenshots**
![CleanShot 2024-02-13 at 14 15 40](https://github.com/DaxStudio/DaxStudio/assets/59814630/5cd534b1-58a5-4483-8e40-723886c69825)

**Additional context**

**Comment by dgosbell** [comment]
As we dicsussed offline this is an issue with the permissions on a default semantic model. If you use a custom semantic model all the traces should work OK.
