### ISSUE TITLE
Persist Parameters

### ISSUE THREAD

**Issue by aersam** [DaxStudio/DaxStudio#1235]
**Is your feature request related to a problem? Please describe.**
I use Dax Studio to write my dax queries for Power BI Paginated Reports. There I always need Parameters which is supported by DAX Studio. However on every execution of the query I have to reenter all parameters which I am too lazy for :) 

**Describe the solution you'd like**
Either keep by default the last entered parameters or even better display them on top of the query to that I can change them on demand only.

**Describe alternatives you've considered**
I can of course omit the parameters and replace them when copy-pasting them to Power BI. But that's also error-prone

**Additional context**
![image](https://github.com/DaxStudio/DaxStudio/assets/5270024/372a5aa3-8545-4f61-98f7-74c4db92d0a5)

**Comment by dgosbell** [comment]
The Write Parameter XML already does this although I can see how this is not obvious, maybe I should rename that button to "Save Parameter Values" or something like that. You can read more about how this works here https://daxstudio.org/docs/features/parameter-support/

**Comment by aersam** [comment]
Ah great, thanks! Sorry should have read the docs 🙂
