### ISSUE TITLE
Using DAX Studio for first time- need help with connecting

### ISSUE THREAD

**Issue by keithaul** [DaxStudio/DaxStudio#1241]
**Describe the bug**
Install DAX Studio for first time. When I open it I get the screen in the screen shot I attached

since this is my first time using it I'll need an explanation on the following

why are the options for Power BI and Power Pivot Model Grey Out? How do I get them to not be greyed out so I can enter something for them?

I have Power BI desktop and Excel 365 installed

What is Tabular Server and what do I enter into that field?

![DAX Studio](https://github.com/DaxStudio/DaxStudio/assets/22573911/b56865e2-07d1-45e0-a56b-e757bcea56a2)

**Comment by dgosbell** [comment]
The answers to all your questions should be in the following documentation https://daxstudio.org/docs/tutorials/getting-connected/

I still need to update the screenshots as they show the previous version of the connection dialog, but we just swapped the position of the **Power BI** and **Power Pivot** options

**Comment by dgosbell** [comment]
I'm assuming that this question was answered by the docs link
