### ISSUE TITLE
Dax Studio 3.0.11 - Windows 10 - Lockdown Enterprise Laptop "Could not load file or assembly 'DaxStudio.SqlFormatter' ... The system cannot find the file specified

### ISSUE THREAD

**Issue by dgwilson** [DaxStudio/DaxStudio#1242]
**Describe the bug**
Dax Studio 3.0.11 is installed on an Enterprise laptop, along with Power BI February Release. Dax Studio is invoked by using the external tools button.
Server timings are invoked - this is acknowledged in the log 'Query Trace Started'
The query is run and completes - 'Query Batch Completed'
However the server timings are not available and there is an error message

Could not load file or assembly 'DaxStudio.SqlFormatter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified

**To Reproduce**
1. Prerequisite is a locked down laptop - only authorised .exe are allowed to run.
2. Go to Power BI, load PBIX model file, run visual in performance analyzer, copy DAX code
3. Click on 'External tools', run Dax Studio
4. Paste in the DAX Code
5. Click on Server Timings
6. Click on Run
7. See error

**Expected behavior**
Completes successfully with Server timings

**Screenshots**
![2024-03-05 11_31_58-DAX Studio - 3 0 11](https://github.com/DaxStudio/DaxStudio/assets/217399/6eb7f6d3-285d-46a7-a84b-03e521f818b6)

**Additional context**
This is likely to be a config/lockdown laptop issue. What message do we need to give to the System admins for install/configuration such that the Server Timings feature will work.

**Comment by dgwilson** [comment]
Thank you for the quick response Darren.
The file is not present. I will follow up with the system admins to fix. 
It is fantastic to know where to look - the admins can make a specific check as part of the install process etc.
Very much appreciated. Thank you.

**Comment by dgosbell** [comment]
I've double checked the 3.0.11 installer and this file gets correctly written out on my machine. If you want a quick fix this file can also be found in the portable .zip download and simply copying it into the correct folder should fix this issue.

**Comment by dgwilson** [comment]
Thanks Darren. I've tried to copy the file off my Virtual Desktop - copying into the bin folder requires Admin privileges.

**Comment by dgwilson** [comment]
Friendly admin has copied the file in place and I can confirm that Server timings now work.
They will investigate as to why the file is not present as part of the install. Their documentation has One checkbox (security related) being ticked as part of the install - but I can't see it when I do the install on my Virtual Desktop. Anyway... for the admins to resolve now. Thank you for your guidance.
