### ISSUE TITLE
Power BI Easy option to make model case sensitive in DAX Studio

### ISSUE THREAD

**Issue by andboliver** [DaxStudio/DaxStudio#1243]
**Is your feature request related to a problem? Please describe.**
Our organization uses SalesForce record ID which are case sensitive.  We are unable to use dax measures in our Power BI model/analysis.

**Describe the solution you'd like**
An easy way to turn case sensitive vs case insensitive on or off

**Describe alternatives you've considered**
doing 100% of analysis via power Query, but that will inefficient.  Trying to figure out using Tabular Editor and/or Microsoft Fabric to update the collation within power bi

**Additional context**
The keys of our data warehouse (snowflake) are numerical.  But the record ids from SalesForce are alpha and numeric and case sensitive.

**Comment by dgosbell** [comment]
Sorry but the case sensitive collation needs to be set in Power BI when the model is first created. We cannot change this from DAX Studio.
