### ISSUE TITLE
Dax studio 

### ISSUE THREAD

**Issue by danicode31** [DaxStudio/DaxStudio#1244]
DAX Studio v3.0.11.982
Connection: not connected

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
You can find information on the various ways to connect here: https://daxstudio.org/docs/tutorials/getting-connected/

**Comment by dgosbell** [comment]
I'm assuming the documentation solved your issue.

**Comment by danicode31** [comment]
thank you @dgosbell
