### ISSUE TITLE
Connect button disabled

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#125]
This sequence leave the connect button disabled:
- Open DAX Studio
- Click Cancel in the Connect dialog box

Also this one
- Create a new page
- Click Cancel in the Connect dialog box

I also get a crash if I try to format DAX code in a page that has no connection available.

**Comment by dgosbell** [comment]
Yes, I just found this too. There was an issue with the Ribbon not having a connection to the ActiveDocument after the Cancel button had been clicked. Fixing this appears to have fixed both these issues
