### ISSUE TITLE
Server Timings and Query Plan only work once

### ISSUE THREAD

**Issue by SchneFre** [DaxStudio/DaxStudio#1250]
**Describe the bug**
I seem to be unable to use DAX Studio properly (3.0.11 portable). Whenever I connect to the Dataset (PBI Premium Workspace – Dataset compatibility level 1601) and run a Query with Server Timings and a Query Plan it works only once. If I try to run the same Query again then it returns empty results and I have to restart the Tool in order to run the Query again. After restarting and it works again – but again only once. In this manner it is quite tedious to work on Performance Issues because i always have to reselect the Datamodel and restart the traces etc. Is there a size Limit for the DAX Studio? My Dataset is currently at 8,3 GB and I can not find an explainantion why DAX Studio behaves this way.

**To Reproduce**
1. Connect to Tabular Server & login 
2. Switch Datamodel
3. start Trace for Server Timings
4. wait until successful
5. start Trace for query plan
6. wait until successful
7. activate Clear Cache on run
8. Paste DAX Qury
9. Run 
10. works fine (Server Timings and Query Plan produce Results)
11. klick run again for the same query (unchanged)
12. Server Timings and Query Plan return no results
13. Restart necessary to get results again

**Expected behavior**
it should work more than one time

**Comment by dgosbell** [comment]
Can you check the Log pane and let me know if there are any errors or warnings there? I cannot reproduce this issue consistently, but I do see occasional timeouts or errors when running traces connected to a model on the service.

**Comment by dgosbell** [comment]
closing due to lack of response
