### ISSUE TITLE
Very minor correction in Writing DAX Queries documentation

### ISSUE THREAD

**Issue by Farsk** [DaxStudio/DaxStudio#1253]
**Describe the bug**
I believe there's a very minor typo in the Writing DAX Queries documentation.

**To Reproduce**
1. Go to https://daxstudio.org/docs/tutorials/writing-dax-queries/
2. Click on 'Basic Queries' in the table of contents
3. Scroll down to the paragraph between the first screenshot and first code block.
4. See: "...[VALUES](https://dax.guide/values) function which returns a table with a single **row**..."

**Expected behavior**
I believe it should say: "...[VALUES](https://dax.guide/values) function which returns a table with a single **column**..."

**Comment by dgosbell** [comment]
Thanks for logging this. I've just corrected this typo and it should be live in a few minutes.
