### ISSUE TITLE
dax studio not accepting short server address

### ISSUE THREAD

**Issue by katespejo01** [DaxStudio/DaxStudio#1256]
DAX Studio v3.0.11.982
Connection: not connected

## Steps to Reproduce
1.
2.

**Comment by katespejo01** [comment]
Hello!

I am trying to connect a server to DAX Studio. For example, the server “FinHubAS” is successfully used by my peers who have Dax Studio, but I cannot, even though we have the exact same access. “AzureDashboardPBI” is also something I can connect to in Excel, but for some reason cannot use in Dax Studio. However, when I use something like “powerbi://api.powerbi.com/v1.0/myorg/MSXIAnalyst” I am able to connect in Dax Studio.

See below the error message I get:

[A screenshot of a computer  Description automatically generated]

This is happening even though I’m connected to VPN. ☹

Kat Espejo
WE GPS Finance Manager - ISV
***@***.******@***.***>
WE GPS Finance Empowering WE business to scale through partners by providing actionable insights.


[A picture containing clipart  Description automatically generated]

We work flexibly and I am sending this now because it’s convenient for me. I do not expect you to read, respond and/or take action outside of your business hours.

**Comment by dgosbell** [comment]
Unfortunately when you reply via email all the images get stripped out so I cannot see the error. If you can send the text of the message or log back into the Github website and paste it into a reply on the website itself that would work.

**Comment by dgosbell** [comment]
closing due to lack of response
