### ISSUE TITLE
Load Perf Data export icon doesn't work

### ISSUE THREAD

**Issue by ricky7uio** [DaxStudio/DaxStudio#1257]
DAX Studio v3.0.11.982
Connection: not connected

## Summary of Issue
It's not possible to export the PBI performance data:

![image](https://github.com/DaxStudio/DaxStudio/assets/44656050/a6b55cf1-e75b-486d-ad37-3f83b259b322)

## Steps to Reproduce
1.import json from perf analyzer
2.try to export the results

**Comment by dgosbell** [comment]
Yes this is a generic toolbar button that should have been hidden in the Performance Data pane. I've already removed this in the code for the next release.

**Comment by ricky7uio** [comment]
oh ok, thanks. @dgosbell So it's not actually possible to export the summary table presented there?

**Comment by dgosbell** [comment]
I suppose that would not be too hard to implement. What would you do with the exported file? I've always just re-opened the file with DAX Studio if I've wanted to see the data again.

**Comment by ricky7uio** [comment]
Well, what I wanted to achieve is to do a comparison of the performance of the same page after some model adjustments. So I was planning to compare them in excel to see the exact impact in all the visuals. 

And this view is already a simplified version of that the JSON contains so it was a good starting point.

**Comment by dgosbell** [comment]
OK that makes sense. I'll have a look at including this.

**Comment by ricky7uio** [comment]
@dgosbell thank you!
