### ISSUE TITLE
Cannot connect to SSAS tabular DB: Error connecting: No such host is know

### ISSUE THREAD

**Issue by sandeepereddyvt** [DaxStudio/DaxStudio#1259]
DAX Studio v3.0.11.982
Connection: not connected

## Summary of Issue
 SSAS tabular DB: Error connecting: No such host is know

## Steps to Reproduce
1.Open new query and connect to DB gives that error. SQL Browser service is running and i even tried restarting the browser service. I am able to connect same DB from powerbi desktop. Was trying to troubleshoot a query using DAX studio
2.

**Comment by dgosbell** [comment]
DAX Studio does not do anything at the network connection layer, we rely on the Microsoft libraries for this. When you connect to an on-prem tabular instance there are 2 parts to the name <host>\<instance>.  If there is no <instance> name the libraries connect directly to port 2383 on the <host> machine. If there is an <instance> then the libraries connect to the SQL Browser instance to find the dynamic port for the specific instance name. 

In your case the error it's reporting means that the Microsoft libraries cannot find a machine on the network with the <host> name. So either there is a typo in the name or some other networking issue outside of DAX Studio. Power BI Desktop uses the same connection libraries as DAX Studio so if it works in one it should work in the other. 

But if you can connect in Power BI Desktop the other option is to use the External Tools ribbon there as Desktop can pass the connection details it is using directly on to DAX Studio.
