### ISSUE TITLE
View As - not usable

### ISSUE THREAD

**Issue by MathewWest** [DaxStudio/DaxStudio#1268]
DAX Studio v3.0.11.982
Connection: AzureAnalysisServices - 16.0.138.22

## Summary of Issue
View As - window does not allow resize, is not displaying all items, window is too big to enable us to click buttons at the bottom of the window. As a result unable to use this function

## Steps to Reproduce
1. We have over 70 roles
2. Go to -> Advanced -> Security -> View As

**Comment by dgosbell** [comment]
Thanks for logging this. A fix for this will be part of the next release and this issue will automatically close when that gets published

**Comment by MathewWest** [comment]
Your very welcome - is there any idea on when the next release is likely to be (sorry to ask, currently review RLS on a AAS tabular model)

**Comment by dgosbell** [comment]
The next release is feature complete, I'm working on the docs and double checking some of the new features so hopefully in the next week or so. If you want to test a preview build there is one on the automated build server here that includes the View As fix: https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/50109249/artifacts

**Comment by MathewWest** [comment]
Hi @dgosbell - I've noted this as closed - is there an update for DAX Studio that fixes in this issue on the main release? - I checked this morning on app and I was still getting an issue

**Comment by dgosbell** [comment]
Yes, I pushed out the 3.1 release last night which triggered the automatic closure of this issue. If you update to that there is now a max height on the role list which will force the list to display a scroll bar so the buttons should now always be visible

**Comment by MathewWest** [comment]
Thank you so much - that is much better - would it be possible to have the roles sorted - I'm finding roles with numbers sometimes at the top of the list, sometimes at the bottom of the list
