### ISSUE TITLE
bug HUb

### ISSUE THREAD

**Issue by Hubbyone6775** [DaxStudio/DaxStudio#1270]
EVALUATE
'Sales Order'[Channel]

01/07/2024 18:49:23		Query (2, 1) Il est impossible de déterminer une valeur unique pour la colonne «Channel» de la table «Sales Order». Cela peut se produire quand une formule de mesure fait référence à une colonne qui contient de nombreuses valeurs, sans spécifier d'agrégation telle que min, max, count ou sum pour obtenir un résultat unique.

**Comment by dgosbell** [comment]
This is not a valid DAX query. You should use the VALUES function if you want to get a table of values from a single column

eg.

EVALUATE
VALUES( 'Sales Order'[Channel] )

as per the second example in this tutorial https://daxstudio.org/docs/tutorials/writing-dax-queries/
