### ISSUE TITLE
Measure Definition only visible for SSAS-Model Admins

### ISSUE THREAD

**Issue by MarioMue13** [DaxStudio/DaxStudio#1271]
With the update to SQL Server 2022, measure definitions can only be seen for Admin (on SSAS) not for readers anymore:

![image](https://github.com/DaxStudio/DaxStudio/assets/74975641/fe92941a-f8a7-43a0-92cc-1093154cb41f)

it is crucial for business user the read DAX Code (Measure definitions) of SSAS Models.

**Comment by dgosbell** [comment]
Sorry, but this is not something we can change from the DAX Studio side of things. It was a change in the security model of SSAS 2022 where Microsoft decided not to show measure expressions to non-admins.
