### ISSUE TITLE
Automate the export function

### ISSUE THREAD

**Issue by Fred792** [DaxStudio/DaxStudio#1278]
I use the Export Data function daily to copy records from a Power BI dataset into a SQL table. This is a manual process and takes about 10 minutes daily. As the size of the database grows, it will eventually take longer.

I would like to automate this process and schedule it to run in the middle of the night or other times and save the manual steps.

Do you have any suggestions of how to automate it?

**Comment by dgosbell** [comment]
This should now be possible using the new command-line interface I released last night https://daxstudio.org/docs/features/command-line/

**Comment by Fred792** [comment]
Hello Darren,

This is super exciting news!

I have set this up and while it does work, I cannot get the -t command to work. Consequently, it is loading 16 tables when I need only one.

Here is the script. Do you see anything obvious? I am running the script from Powershell ISE and the table I want to download is called GLD.

***@***.***




James Webb
M +1 604-374-8540  O +1 604-273-4311
W conetec.com<https://www.conetec.com/>

**Comment by dgosbell** [comment]
Hi James, sorry but when you reply to a GitHub issue it strips any attachments so I can't see your script. Can you either paste it into this issue on the GitHub site or fwd it to  darren 'at' daxstudio.org

**Comment by dgosbell** [comment]
Hi @Fred792 - I can reproduce your issue with the -t parameter. I've created a new issue to track this here #1283
