### ISSUE TITLE
Unable to send results to excel(linked or file)

### ISSUE THREAD

**Issue by nikmugveBD** [DaxStudio/DaxStudio#1279]
Results to excel both linked and static file returns error
Path cannot be null.
Parameter name: path

**To Reproduce**
1. Connect to data set
2. Write query and confirm runs with results to grid
3. Choose results to excel
4. Run->Receive error

**Expected behavior**
File opens or file dialog opens to save location

**Screenshots**
![image](https://github.com/user-attachments/assets/088f2e7b-2b2c-427f-a5ab-23f9d12597f9)

**Additional context**
Only started happening after 3.1.0 download.

**Comment by dgosbell** [comment]
Thanks for logging this. I cannot reproduce this with the linked Excel output, but there is a bug with the Excel static output that was accidentally introduced by a change for the command line support.
