### ISSUE TITLE
Add License.txt file

### ISSUE THREAD

**Issue by GMedlin** [DaxStudio/DaxStudio#128]
I'm trying to get DaxStudio approved by my corporate IT. They have some strict guidelines for approving open source software. What would really help me out with this is if a copy of the [Microsoft Permissive Open Source License](https://opensource.org/licenses/MS-PL) were put into a License.txt file at the root of the repository. I noticed this with [GitHub's guidelines](https://help.github.com/articles/licensing-a-repository/) as well.

**Comment by dgosbell** [comment]
That should not be hard to do. But in the mean time, the license is currently in the repo under `installer/eula.rtf` and it also displays on the first screen of the installer. The project originally started on codeplex where the project page had it dedicated license page so we did not need to have it checked in to the repo.
