### ISSUE TITLE
dscmd is asking for server when the connection string is passed to it

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#1284]
### Discussed in https://github.com/DaxStudio/DaxStudio/discussions/1281

<div type='discussions-op-text'>

<sup>Originally posted by **tnhurst57** August  3, 2024</sup>
Here is the dialog - Docs says server not required if passing connection string. Trying to query our Power BI datasets:
dscmd csv myfile.csv --connectionstring "Data Source=powerbi://api.powerbi.com/v1.0/myorg/IBCE
_Dev;Initial Catalog=IB Targeting Dashboard" -q "EVALUATE 'Master'"
Error: You must specify a Server option</div>

**Comment by dgosbell** [comment]
Thanks for logging this. It is a bug with the `csv` command, I'll push out an update with a fix shortly. In the short term it should work if you use the `--server` and `--database` options instead.

eg

`dscmd csv myfile.csv --server "powerbi://api.powerbi.com/v1.0/myorg/IBCE_Dev" --database "IB Targeting Dashboard" -q "EVALUATE 'Master'"`

**Comment by tnhurst57** [comment]
Thanks so much.
