### ISSUE TITLE
Funtion SUMARIZECOLUMNS problem with "<>" character

### ISSUE THREAD

**Issue by mtacuri** [DaxStudio/DaxStudio#1292]
DAX Studio v3.2.0.1036
Connection: PowerBIDesktop - 16.0.126.27

## Summary of Issue
When using "><" characters in the name parameter for **SUMARIZECOLUMNS** function doesnt show results in result table.

## Steps to Reproduce
1.Execute function with name column example: "AB". Result showing.

<img width="444" alt="image" src="https://github.com/user-attachments/assets/ab9589d5-3b66-482c-aa1b-4797b12775e0">

2.Execute same funtion adding ">" or "<" character in column name . Doesnt show results

<img width="458" alt="image" src="https://github.com/user-attachments/assets/479b3269-d470-47fa-95fb-0c46355ed7cc">

**Comment by dgosbell** [comment]
Thanks for logging this, I've found the issue and the fix will be included in the next release
