### ISSUE TITLE
Vertipaq Analyzer Metric Options "Learn More" error

### ISSUE THREAD

**Issue by nphadro** [DaxStudio/DaxStudio#1293]
**Describe the bug**
When I click "Learn More" in the Metric options when trying to do the "Vertipaq Analyzer"... "View Metrics" window. I get taken to this URL which does not load "http://localhost:3000/docs/features/model-metrics/#metric-options-dialog"

**To Reproduce**
1. Go to 'Advanced'
2. Click on 'View Metrics and when the "metric option window opens, then click Learn more'
4. See error that the url does not load

**Expected behavior**
Expected it to take me to documentation.

**Screenshots**
![image](https://github.com/user-attachments/assets/a90f77e4-9722-4fbf-a30a-1ea232797395)

**Additional context**

**Comment by dgosbell** [comment]
thanks for logging this. The `localhost:3000` should be daxstudio.org. A fix for this will go out in the next release
