### ISSUE TITLE
Column with name Test gets Currency formatting

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1297]
Inside SUMMARIZECOLUMNS if the name of the column is 'Test' then it gets formatted as Currency.

![image](https://github.com/user-attachments/assets/c0efbe3b-726a-4afb-84d6-3666b9227ba9)

and 

![image](https://github.com/user-attachments/assets/6b1181e5-6c58-4376-9bc4-c1a536b51dcb)

**Comment by dgosbell** [comment]
Do you possibly have a measure in your model called [Test] which has currency formatting applied?

I don't have a full DAX parser/semantic analyzer in DAX Studio so I simply match the names of the output columns with the model metadata and apply the formatting. If we fail to find a match in the metadata we then fallback to some default data type formatting, none of those apply currency formatting.

**Comment by SharmaAntriksh** [comment]
Yup, that was the case, DAX Studio is taking formatting of existing measures when the names match. Thanks!
