### ISSUE TITLE
Excel Export File Size doubled Since version 3.0.11 !

### ISSUE THREAD

**Issue by abuhafs** [DaxStudio/DaxStudio#1298]
**Describe the bug**
**Since upgrading to version 3.0.11,** the file size of Excel exports has more than doubled for the same dataset.
**Default settings**
**ScreenShot**
![image](https://github.com/user-attachments/assets/fb8a9a39-17fc-43e5-a890-6e7a00637639)

**Comment by dgosbell** [comment]
Thanks for logging this. There was a change in the underlying library I use to stream the data out to XLSX format. They made an update to make the files more compatible with other client tools. I can add an option to turn off this new option and I might add a setting to enable zip64 compression which will also allow for files larger than 4Gb to work.
