### ISSUE TITLE
can't install Dax Studio 2.7

### ISSUE THREAD

**Issue by amarines2605** [DaxStudio/DaxStudio#13]
I Run .exe file  an then it just exits and .exe file disappears(it deletes itself)

Any help please
Thank you

**Comment by dgosbell** [comment]
We don't have any code that deletes the installer. Have you checked your anti-virus logs or quarantine area?

**Comment by amarines2605** [comment]
Ohh yes, you're right, to the .exe file my antivirus detects it as a malicious file and deletes it, I already put it inside the exceptions and it was already installed.

Thank you!!
