### ISSUE TITLE
Non-Resident Columns When "DirectLake Scan Statistics from Data option" = "Full"

### ISSUE THREAD

**Issue by bgribaudo** [DaxStudio/DaxStudio#1302]
**Describe the bug**
When viewing metrics with "DirectLake Scan Statistics from Data option" = "Full", numerous columns are annotated with warnings about possible inaccurate statistics.

**To Reproduce**
1. In DAX Studio 3.2.0, ribbon tab _Advanced_, click _View Metrics_.
2. Set "DirectLake Scan Statistics from Data option" to "Full".
    ![image](https://github.com/user-attachments/assets/6922a8e0-869d-4b34-bb88-38af518b8f74)
3. Load statistics.
4. In the _VertiPaq Analyzer_ results tab, choose _Columns_.
5. Notice that various (but not all) columns have a warning that "Column not resident in memory, statistics may not be accurate".

**Expected behavior**
Since "DirectLake Scan Statistics from Data option" = "Full", not "ResidentOnly", seems like full data should have been read to assemble statistics, so non-resident errors should not be present.

**Screenshots**
![image](https://github.com/user-attachments/assets/7d38d72f-9ced-423b-94e3-522c891b028f)

Thank you very much for DAX Studio!

**Comment by dgosbell** [comment]
Thanks for logging this. I noticed this myself too. I have a fix in my dev branch and will get this out shortly

**Comment by bgribaudo** [comment]
Thanks much, @dgosbell!

**Comment by Cam111111** [comment]
Hello, i still have this problem, i've installed the 3.3.1 version
