### ISSUE TITLE
Running DSCMD

### ISSUE THREAD

**Issue by muhssamy** [DaxStudio/DaxStudio#1306]
i am running this command 
```powershell
 dscmd.exe vpax "C:\test\model.vpax" --server "powerbi://api.powerbi.com/v1.0/myorg/myorg" --database "MY DB"
``` 
and i am getting this issue

```
DSCMD - DAX Studio Commandline PREVIEW (3.2.0.1036)
Starting VPAX command
15:10:06 [INFO] Starting VPAX command
Error: Column batch size must be greater than zero.
Parameter name: columnBatchSize
```

**Comment by dgosbell** [comment]
Thanks for logging this I will have a fix in the next release which will use the default columnBatchSize if one is not specified.

The short-term workaround is to add ` --StatsColumnBatchSize 50` to the end of your command
