### ISSUE TITLE
Enable dscmd with service principle

### ISSUE THREAD

**Issue by muhssamy** [DaxStudio/DaxStudio#1308]
Dear Leaders

can we authorize login for dscmd using service principle ?
as i am getting this
![image](https://github.com/user-attachments/assets/36f007f2-dde7-4c64-83a4-6c60fceec2d8)

**Comment by dgosbell** [comment]
Yes, you can authenticate using a service principal. I've just added some more information here since I've just realised that the Msft docs on this are not all that clear https://daxstudio.org/docs/features/command-line/authentication/#authenticating-as-service-principal - I have some unit tests running as an SPN so it works for me. Does this work for you?

**Comment by muhssamy** [comment]
actually, i got the same error off Unable to obtain authentication token using the credentials provided.

this is my code
```powershell
[Int64]$currentdate = Get-Date -Format "yyyyMMdd"

$filePath = "xx"

Write-Host $filePath

$server = "powerbi://api.powerbi.com/v1.0/myorg/xx"

$database = "lxx"

$userID = "app:xx@xx"

dscmd.exe vpax $filePath -s $server -d $database -u $userID -p $Env:AppClientID
```

**Comment by dgosbell** [comment]
from your variable names it looks like you are passing the ClientId as the password, it should be the ClientSecret. 

And have you added the service principal to the workspace with rights higher than Viewer?

**Comment by muhssamy** [comment]
yes, I added it to the workspace, and I am using it with warehouse connections and other automations APIs.
for variable name it is only a wrong name, but it holds the correct value.

my problem is that this failure requiring token as per my understanding service principle should not require this tokens.

**Comment by dgosbell** [comment]
I am able to reproduce this error `Unable to obtain authentication token using the credentials provided.` by putting in an incorrect value for either the userId or password. If I use the correct values it is working fine for me with an SPN. If I remove the SPN from the workspace I get a different error about the dataset not being found

>my problem is that this failure requiring token as per my understanding service principle should not require this tokens.

Entra ID uses tokens internally. When you pass in the correct values to authenticate as the SPN you will get an access token. This error is indicating that the authentication failed.

**Comment by muhssamy** [comment]
Thanks for your patience. **you are 100% right** I found that I was using object id instead of Client ID.

**Comment by alisonpezzott** [comment]
Hi, I'm using an SPN, but every time I run this PowerShell script, the Microsoft authentication screen appears, and I have to confirm to complete the process.

My credentials are working normally with other Fabric APIs.

See my code below.

```ps1
# Credentials
$tenantId = $env:FABRIC_TENANT_ID
$clientId = $env:FABRIC_CLIENT_ID
$clientSecret = $env:FABRIC_CLIENT_SECRET

# Path DAX Studio CLI
$cmd = "C:/DaxStudio/dscmd.exe"

# Target Workspace and Dataset
$workspace_name = "ISVDemo_AdventureWorks_TenantA"
$dataset_name = "AdventureWorks"

# Connection String
$connection_string = "Data Source=powerbi://api.powerbi.com/v1.0/myorg/$workspace_name;Initial Catalog=$dataset_name;"

$query = @"
EVALUATE 'product'
"@

# Output path
$output_filename = "product"
mkdir "C:\Git\pbi-documentation\output\$workspace_name\$dataset_name" -Force
$output_path = "C:\Git\pbi-documentation\output\$workspace_name\$dataset_name\$output_filename.csv"

# Executing
& $cmd csv $output_path `
    -c $connection_string `
    -u app:$clientId@$tenantId `
    -p $clientSecret `
    -q $query `
    -n 
```
