### ISSUE TITLE
Clear Cache and Run Query Button disappeared in the latest DAX Studio 2.8.1

### ISSUE THREAD

**Issue by nickchobotar** [DaxStudio/DaxStudio#131]
Clear Cache and Run Query Button disappeared in the latest Version DAX Studio 2.8.1. 

![image](https://user-images.githubusercontent.com/29464803/51582418-f160e700-1e99-11e9-94de-9e396bcb73bd.png)

**Comment by dgosbell** [comment]
I can't see any errors in the build log and I just downloaded and installed the version off the website to be sure and I can see both buttons
![image](https://user-images.githubusercontent.com/8241830/51582750-9b378680-1f21-11e9-84f3-c0c5bd40d1b9.png)
Maybe try an uninstall and re-install. Or try using the [following technique](https://daxstudio.org/documentation/troubleshooting/logging-settings/) to enable the debug logging and post the log back here.

**Comment by dgosbell** [comment]
Unable to reproduce. Closing due to lack of response. Feel free to re-open this if you have more information to add
