### ISSUE TITLE
Frequent disconnects

### ISSUE THREAD

**Issue by danielpitz** [DaxStudio/DaxStudio#1311]
DAX Studio v3.2.1.1046
Connection: not connected

## Summary of Issue
My connection to the Power BI service disconnects frequently.  If I leave it sitting for any length of time, it disconnects.  Sometimes I can run a query, make a slight change, then try to run it again and I'll be disconnected.  If I'm using DAX Studio a lot, which is common, I'll get disconnected a couple dozen times a day.

## Steps to Reproduce
1. I'm not sure this applies.
2.

**Comment by dgosbell** [comment]
Are you able to start DAX Studio with the [diagnostic logging](https://daxstudio.org/docs/troubleshooting/logging-settings/#enabling-diagnostic-logging---standalone) enabled and see if you can reproduce one of these disconnections? In theory if the connection gets broken a retry should occur and you should be prompted to re-authenticate, but it does depend on the type of error that gets thrown.

**Comment by dgosbell** [comment]
closing due to lack of response
