### ISSUE TITLE
winget install DaxStudio.DaxStudio: Create daxstudio.pbitool.json

### ISSUE THREAD

**Issue by bluehenve** [DaxStudio/DaxStudio#1316]
**Is your feature request related to a problem? Please describe.**
C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools\daxstudio.pbitool.json
is not created when installing Dax Studio with winget

**Describe the solution you'd like**
Create daxstudio.pbitool.json when installing Dax Studio with winget - like with DaxStudio.setup.exe

**Comment by dgosbell** [comment]
you need to use `--sccope machine` when installing with winget if you want the Power BI integration since this requires admin rights

**Comment by bluehenve** [comment]
works - that awesome, thanks man :-)
