### ISSUE TITLE
DAX Studio doesnt launch 

### ISSUE THREAD

**Issue by GordiPordi366** [DaxStudio/DaxStudio#1318]
Dax Studio 3.2.1 doesn´t launch. Just the window to connect to a model appears and ist usable. 
After clicking connect or cancel nothing happend. 
The programm seems to run in the background but the frontend doesn`t load properly.
If i start with an user with admin permission it runs fine but in the before i didnt have to do that.

**Comment by dgosbell** [comment]
Can you startup DAX Studio holding down the SHIFT key to start the diagnostic logging as per https://daxstudio.org/docs/troubleshooting/logging-settings/ then upload the generated log file to this issue on github? 

DAX Studio should not require any admin rights for anything it does. I never run it as admin and I've never heard of an issue like this before. The connection dialog does look for running copies of Power BI Desktop - do you maybe have some sort of AV software that might be interpreting that as malicious code?

**Comment by dgosbell** [comment]
closing due to lack of response
