### ISSUE TITLE
Automatic Format Results not working

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1327]
Options > Results > Automatic Format Results doesn't seem to be working, it is returning the same format that is set in PBI.

https://github.com/user-attachments/assets/f76f8bd4-0277-4036-ad76-a612637a0551

Is this expected behaviour because I remember it used to change the formatting earlier.

**Comment by dgosbell** [comment]
This is the expected behaviour. The auto formatting is designed as a fallback behaviour. If a format is defined on the column/measure we use that. If no formatting is defined and the auto formatting is enabled, then we use that otherwise we let the default formatting of the .net framework apply.

**Comment by SharmaAntriksh** [comment]
Thanks for the clarification!
