### ISSUE TITLE
How to connect to PowerBI.com

### ISSUE THREAD

**Issue by fmms** [DaxStudio/DaxStudio#133]
Hi,

to my understanding the 2.8.0 supports to connect to a PowerBI.com workspace. In the source I have seen powerbi:// as adress for that.

How do i find the connection string for my PowerBI.com dataset? 

Having the nice connection dialog #126 would be cool, but is just the second step ;)

regards

**Comment by dgosbell** [comment]
You currently have to be part of the preview program in order to have this ability enabled on your PowerBI Premium capacity. If you are in the preview you can find details of how to connect in the associated Yammer group. I don't think the uri format is a secret, but I'm not sure if it might change before the public release.

**Comment by dgosbell** [comment]
Apparently the uri format has been announced somewhere and it uses the following format:
`powerbi://api.powerbi.com/v1.0/[your domain]/[your workspace name]`

Where:
- **your domain** is the domain for your tenant
- **your workspace** is the _case sensitive_ name of your workspace

So in some of the microsoft demos you will see people connecting to endpoints like:
`powerbi://api.powerbi.com/v1.0/**microsoft.com**/**Demo Workspace**`

When you attempt to connect to an endpoint like this the Adomd provider used by DAX Studio will prompt you for your Power BI credentials and will then connect you to the first dataset it finds. You can then select other datasets in that workspace from the database dropdown in DAX Studio.

**Comment by fmms** [comment]
ok, i have tried this with my Power BI premium workspace an get the following:
![image](https://user-images.githubusercontent.com/908734/51671709-d2fa0900-1fc9-11e9-9c56-3a53dba7616d.png)
When entering a "/" at the end of the URL it says "workspace does not exist". 

So this what is expected when that workspace is not part of the preview? Where can I register for that preview?

regards

**Comment by dgosbell** [comment]
Yes, that is what you would expect if you are not part of the preview. 

As far as I am aware this feature is still in a private preview phase (so invite only at the moment). According to [this page](https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/planned-features) they are aiming for a public preview next month.
