### ISSUE TITLE
Auto complete table names issue

### ISSUE THREAD

**Issue by dmgdotnet** [DaxStudio/DaxStudio#134]
Hi,

We have an issue with autocomplete for table names containing an underscore.  

For example, with a table name of "Dim_Calendar", if we type "Dim_C" and then hit TAB to use auto-complete function, the text "Dim_Dim_Calendar" is inserted.

Let me know if you need more information.

Thanks.

**Comment by dgosbell** [comment]
Thanks for reporting this. I can reproduce this so I should be able to fix it without too much trouble. 

I personally always remove underscores from my tabular object names, so I've never run into this before.

**Comment by dgosbell** [comment]
If you are interested you can test a [preview build](https://ci.appveyor.com/api/buildjobs/9y0uirhujbbw53qj/artifacts/package%2FDaxStudio_2_8_2_setup.exe) of this fix now.

**Comment by dmgdotnet** [comment]
That's great, thanks for the fast turnaround. Using the preview now.
