### ISSUE TITLE
Export Data text box bug

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#136]
All text boxes in the Export Data dialog box have the same issue, which is displayed in this GIF:
![expandwindow](https://user-images.githubusercontent.com/10683126/51810104-fb4f7380-22f9-11e9-8c16-7a735a7672d1.gif)

**Comment by dgosbell** [comment]
Thanks for reporting this, the next release (after 2.8.1) will include a fix for this
