### ISSUE TITLE
"Inline" all "Defined" measures

### ISSUE THREAD

**Issue by erapade** [DaxStudio/DaxStudio#145]
When "extracting" measures from the table view to see them in the code editor we have a choies to also include all dependent measures inline in the code. This menue option is called "Define and Expand Measures".

When tracking server traces we get a list of measures executed in the "All Queries" tab and we can double-click to export the measure to the code editor window. Doing so, there are a lot of "Define", from filter settings, legend calculations, etc

It would be nice if you instead could right-click on the trace and choose "Define and Expand" to get all these defines inline in the code. An alternative would be if you in the code editor could marked the code (and the defines) and choose "Expand", or "Inline defines", whatever is most suitable

The reason for this is to in some cases make the code more readable, the same way as done with "Define and Expand"

**Comment by marcosqlbi** [comment]
If I understand correctly we might:
1) Scan all the measures in the model finding a match (without table name) in the query.
2) Mark all the measures included in the query as "To be included in define"
3) For each measure, apply a recursive scan of the referenced measures with the same technique
4) Once the recursive scan has been applied to all the measures, export the measures that are referenced in the query in a direct or indirect way.

This is possible and has the same "issues" of Define and Expand Measures feature - which would include measures with the same name of column that could appear in the expresson.

**Comment by erapade** [comment]
To exemplify Darren:
Suppose we have double-clicked the executed measure in the "All Queries" windows (as we do today) and extracted the code below
```
DEFINE VAR __DS0FilterTable = 
  TREATAS({1}, 'Fact Sales'[Category])

EVALUATE
  SUMMARIZECOLUMNS(
    __DS0FilterTable,
    "SumPrice", IGNORE(CALCULATE(SUM('Fact Sales'[Price])))
  )
```
If we instead would have right-clicked the executed measure and selected "Define and Expand", my suggestion is that we should end up with the code below:
```
EVALUATE
  SUMMARIZECOLUMNS(
    TREATAS({1}, 'Fact Sales'[Category]),
    "SumPrice", IGNORE(CALCULATE(SUM('Fact Sales'[Price])))
  )
```

Depending on where in the DaxStudio code you are doing this, the implementation is more or less complicated. And it's only intended for the variables created by the Power BI Desktop Application
In it's simplest form, its just a text find and replace:
```
while( DEFINE VAR xxx = yyy Exists ) ( I guess this needs to be restricted to only the outermost DEFINEs,  i.e. those created by the Power BI Desktop application
{
  Delete DEFINE VAR xxx = yyy //Delete the variable definition
  Replace all xxx with yyy //Replace all existing references to the variable definition
}
```

Doing this way, I see no need for recursively drilling through the code and the model. It's just an extra step (a find and replace) before publishing the code to the code window.
I know I'm simplifying, makes my life easier ;-) I'm also not sure if this is always possible without changing the execution of the code, but I'm sure Marco immediately has a good feeling for that ;-)

I know the current implementation gives a better structured view of the code, but depending on your own brains memory depth and stack, it's more or less harder to remember all the previous defined variables.

**Comment by marcosqlbi** [comment]
Yes, modifying the variables would break the semantic - that is not possible.

**Comment by dgosbell** [comment]
Yes, I could see a couple of possible interpretations of your original request, which is why I thought it better to ask for clarification. But as you've pointed out "in-lining" the variables would change the query plan. Although I think I see where your motivation for this request comes from. :)

I'm thinking that if we can get a full blown parser working that something like showing a variable's definition in a tool tip when you hover over it might be useful. Or maybe even a "smart rename" where we could convert treatas filters from PowerBI from this format: 

```
DEFINE VAR __DS0FilterTable = 
  TREATAS({1}, 'Fact Sales'[Category])
```

To something like this to improve the readability of the code:

```
DEFINE VAR __filter_Fact_Sales-Category = 
  TREATAS({1}, 'Fact Sales'[Category])
```

**Comment by erapade** [comment]
@dgosbell Yes you're right, A smarter rename would kind of help out a bit. But then again, the output would be kind of complex anyway so I don't know how much it will help. You might need to accept the output being complex and do the work :-) 
For example I did a simple stacked bar chart with calendar[dates] on x-axis and count of facts on y-axis ~1 M rows. To add some more complexity I also added a Legend and two external filters (a relative date filter and a fact category filter). The output is listed below and kind of "punch you in you face". But I don't know if changing some names really will make this easier to understand. Maybe adding some extra comments or if possible divide into sections could help, but maybe it's just to accept that in some cases code inspection is complex ;-)

```
DEFINE
  VAR __DS0FilterTable = 
    FILTER(
      KEEPFILTERS(VALUES('Calendar'[Full_Date])),
      AND(
        'Calendar'[Full_Date] >= DATE(2018, 1, 1),
        'Calendar'[Full_Date] < DATE(2019, 2, 1)
      )
    )

  VAR __DS0Core = 
    SUMMARIZECOLUMNS(
      'Calendar'[Full_Date],
      'call_req'[type],
      __DS0FilterTable,
      "Countref_num", CALCULATE(COUNTA('call_req'[ref_num]))
    )

  VAR __DS0PrimaryBase = 
    SUMMARIZE(__DS0Core, 'Calendar'[Full_Date])

  VAR __DS0SecondaryBase = 
    SUMMARIZE(__DS0Core, 'call_req'[type])

  VAR __DS0IntersectionCount = CALCULATE(COUNTROWS(__DS0Core))

  VAR __DS0PrimaryCount = CALCULATE(COUNTROWS(__DS0PrimaryBase))

  VAR __DS0SecondaryCount = CALCULATE(COUNTROWS(__DS0SecondaryBase))

  VAR __DS0SpaceCount = (__DS0PrimaryCount * __DS0SecondaryCount)

  VAR __DS0SparseFactor = MIN(5, DIVIDE(__DS0SpaceCount, __DS0IntersectionCount))

  VAR __DS0TargetIntersectionCount = CEILING(3500 * __DS0SparseFactor, 1)

  VAR __DS0InitTargetPrimaryCount = 
    IF(
      __DS0IntersectionCount <= 3500,
      IF(
        __DS0SpaceCount <= __DS0TargetIntersectionCount,
        3500,
        FLOOR(
          SQRT(__DS0TargetIntersectionCount * DIVIDE(__DS0PrimaryCount, __DS0SecondaryCount)),
          1
        )
      ),
      IF(
        AND(__DS0PrimaryCount > 800, __DS0SecondaryCount > 60),
        CEILING(DIVIDE(__DS0TargetIntersectionCount, 60), 1),
        IF(
          __DS0SecondaryCount > 60,
          __DS0PrimaryCount,
          CEILING(DIVIDE(__DS0TargetIntersectionCount, __DS0SecondaryCount), 1)
        )
      )
    )

  VAR __DS0InitTargetSecondaryCount = 
    IF(
      __DS0IntersectionCount <= 3500,
      IF(
        __DS0SpaceCount <= __DS0TargetIntersectionCount,
        3500,
        FLOOR(
          DIVIDE(__DS0TargetIntersectionCount, FLOOR(
            SQRT(__DS0TargetIntersectionCount * DIVIDE(__DS0PrimaryCount, __DS0SecondaryCount)),
            1
          )),
          1
        )
      ),
      IF(
        AND(__DS0PrimaryCount > 800, __DS0SecondaryCount > 60),
        60,
        IF(
          __DS0SecondaryCount > 60,
          CEILING(DIVIDE(__DS0TargetIntersectionCount, __DS0PrimaryCount), 1),
          __DS0SecondaryCount
        )
      )
    )

  VAR __DS0MinPrimaryCount = MIN(10, __DS0PrimaryCount)

  VAR __DS0MinSecondaryCount = MIN(10, __DS0SecondaryCount)

  VAR __DS0TargetPrimaryCount = 
    IF(
      __DS0InitTargetPrimaryCount < __DS0MinPrimaryCount,
      __DS0MinPrimaryCount,
      IF(
        __DS0InitTargetSecondaryCount < __DS0MinSecondaryCount,
        CEILING(DIVIDE(__DS0TargetIntersectionCount, __DS0MinSecondaryCount), 1),
        __DS0InitTargetPrimaryCount
      )
    )

  VAR __DS0TargetSecondaryCount = 
    IF(
      __DS0InitTargetPrimaryCount < __DS0MinPrimaryCount,
      CEILING(DIVIDE(__DS0TargetIntersectionCount, __DS0MinPrimaryCount), 1),
      IF(
        __DS0InitTargetSecondaryCount < __DS0MinSecondaryCount,
        __DS0MinSecondaryCount,
        __DS0InitTargetSecondaryCount
      )
    )

  VAR __DS0Primary = 
    SAMPLE(__DS0TargetPrimaryCount + 2, __DS0PrimaryBase, 'Calendar'[Full_Date], 1)

  VAR __DS0Secondary = 
    TOPN(__DS0TargetSecondaryCount + 1, __DS0SecondaryBase, 'call_req'[type], 1)

  VAR __DS0BodyIntermediate = 
    NATURALINNERJOIN(
      __DS0Core,
      __DS0Secondary
    )

  VAR __DS0KeyValues = 
    GROUPBY(
      __DS0BodyIntermediate,
      'call_req'[type],
      "MinCountref_num", MINX(CURRENTGROUP(), [Countref_num]),
      "MaxCountref_num", MAXX(CURRENTGROUP(), [Countref_num])
    )

  VAR __DS0KeyPoints = 
    SELECTCOLUMNS(
      KEEPFILTERS(
        FILTER(
          KEEPFILTERS(NATURALINNERJOIN(
            __DS0BodyIntermediate,
            __DS0KeyValues
          )),
          AND(
            AND(
              OR([Countref_num] = [MinCountref_num], [Countref_num] = [MaxCountref_num]),
              NOT([MinCountref_num] = [MaxCountref_num])
            ),
            NOT([Countref_num] = 0)
          )
        )
      ),
      "'Calendar'[Full_Date]", 'Calendar'[Full_Date],
      "'call_req'[type]", 'call_req'[type],
      "Countref_num", [Countref_num]
    )

  VAR __DS0KeyPrimaryLimit = CEILING(DIVIDE(350, __DS0TargetSecondaryCount), 1)

  VAR __DS0KeyPrimaryValuesLimited = 
    TOPN(
      __DS0KeyPrimaryLimit,
      SUMMARIZE(__DS0KeyPoints, 'Calendar'[Full_Date]),
      'Calendar'[Full_Date],
      1
    )

  VAR __DS0PrimaryKeyPoints = 
    DISTINCT(UNION(__DS0Primary, __DS0KeyPrimaryValuesLimited))

  VAR __DS0KeyPrimaryLimitedCount = 
    CALCULATE(COUNTROWS(__DS0KeyPrimaryValuesLimited))

EVALUATE
  ROW(
    "DS0IntersectionCount", __DS0IntersectionCount,
    "DS0PrimaryCount", __DS0PrimaryCount,
    "DS0TargetPrimaryCount", __DS0TargetPrimaryCount,
    "DS0SecondaryCount", __DS0SecondaryCount,
    "DS0TargetSecondaryCount", __DS0TargetSecondaryCount,
    "DS0KeyPrimaryLimitedCount", __DS0KeyPrimaryLimitedCount,
    "DS0KeyPrimaryLimit", __DS0KeyPrimaryLimit
  )

EVALUATE
  __DS0Secondary

ORDER BY
  'call_req'[type]

EVALUATE
  NATURALLEFTOUTERJOIN(
    __DS0PrimaryKeyPoints,
    SUBSTITUTEWITHINDEX(
      __DS0BodyIntermediate,
      "ColumnIndex",
      __DS0Secondary,
      'call_req'[type],
      ASC
    )
  )

ORDER BY
  'Calendar'[Full_Date], [ColumnIndex]

```

**Comment by erapade** [comment]
Looking at the code above, I noticed that the format of the code is not exactly the same formatting as produced by the DAX Formatter. 
It's kind of the same, but you are inserting an empty row between each Variable definition, makes it easier to read for me. 
But on the other side, You have a more compressed format of functions parenthesis than DAX Formatter, and in some cases I see a )) on empty rows, something I don't think DAX Formatter will produce. I don't know if code formatting is expected to be the same, it's up to you, maybe the code you extract is formatted as is from the start

**Comment by marcosqlbi** [comment]
There is a property in the option "Dax Formatter / Default format style" that you can set to Short Line or Long line - you get the non-default behavior by pressing CTRL-F6 instead of F6.

**Comment by dgosbell** [comment]
We don't actually do any formatting of the captured queries. That formatting must be the way Power BI generates it's code. I think you are probably right and this is just a degree of inherent complexity here.

**Comment by dgosbell** [comment]
Given our discussion above I've decided to close this issue as I don't think there is anything we can do here.
