### ISSUE TITLE
Timeout after 3600 second

### ISSUE THREAD

**Issue by devon59** [DaxStudio/DaxStudio#146]
Hi, I am trying to export a table from power BI to csv using simple

Evaluate [tablename] but getting timeout after 1 hour of run time.  The table is large with 10 million records.  How do I solve this problem? 
Thank you

**Comment by devon59** [comment]
Thank you.  I'll try that.

**Comment by dgosbell** [comment]
Closing this issue as this timeout is coming from the data engine, not from something imposed by DAX Studio directly. Feel free to re-open this if adding the timeout setting does not help
