### ISSUE TITLE
External Tools buttons show up without being enabled

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#147]
The External Tools buttons show up (and sort of work) even without being enabled. Here are my settings:
![image](https://user-images.githubusercontent.com/10683126/52189426-b5ac2100-288c-11e9-9f4d-5dda6c01e633.png)

And yet I see the External Tools buttons:
![image](https://user-images.githubusercontent.com/10683126/52189443-ca88b480-288c-11e9-820d-6181c459e72d.png)

SQL Profiler starts all right, but Excel won't start:
![image](https://user-images.githubusercontent.com/10683126/52189504-0885d880-288d-11e9-94e5-91f3ce93b745.png)

It doesn't matter whether I have the External Tools buttons enabled -- Excel won't start anyway (even after closing and opening DAX Studio again).

**Comment by dgosbell** [comment]
Thanks for filing this. I've accidentally linked the preview option as one of the conditions to the visibility of the "Advanced" ribbon, but not to the buttons themselves. But the access denied error is a different issue. Can you tell me if you have a "My Data Sources" folder in your "Documents" folder? I thought this was created by Excel, but maybe it's not (or maybe it gets translated based on regional settings)

**Comment by DaniilMaslyuk** [comment]
> But the access denied error is a different issue. Can you tell me if you have a "My Data Sources" folder in your "Documents" folder? I thought this was created by Excel, but maybe it's not (or maybe it gets translated based on regional settings)

Yes, I have that folder, and I even have DaxStudio.odc in it:
![image](https://user-images.githubusercontent.com/10683126/52244921-b2b83b80-2933-11e9-8deb-5f9cd43eadaa.png)

I even ran DAX Studio as an administrator, but that didn't help.

Given that this is a separate issue, would you like me to create a separate issue thread?

**Comment by dgosbell** [comment]
Someone else already noted the permissions issue in #148 You can download a preview of the fix off our build server [here](https://ci.appveyor.com/api/buildjobs/tmrpug045ap17r6a/artifacts/package%2FDaxStudio_2_8_3_setup.exe)
