### ISSUE TITLE
Could not connect , after version 2.4.3 with excel 2010 

### ISSUE THREAD

**Issue by nVenticDW** [DaxStudio/DaxStudio#15]
The Issue from id #4360  remains with version 2.7
"I´m not to able to connect Excel Power Pivot Data Model. The following message error appears in the window output "Could not connect to "Power Pivot model". the connection has timed out or lost"

with version 2.43. everything works fanatastically, all subsequent versions fail to connect on start of the addin.

Maybe it has something to do with Excel 2010.
I have 2010 Office professional, excel 2010 32 bit (version 14.0.7188.5002) with the powerpivot from 29.11.15 (the latest I believe). 
p.s.  I also tried manually installing AMO and ADOMD from SQL server 2012 tools  (32 bit) and then installing manually AMO and ADOMD SQL server 2016 tools (32 bit)  as well before installing the update, thinking 2010 needs SQL server 2012 as well. that didn't work. 
Dan

**Comment by nVenticDW** [comment]
The checker finds something wrong 
Below are th results from DAxstudio checker for the normal install without any manual install of AMO/AMOMD (format might not be perfect since it went hrough Wordpad first before being pasted here)

Checking .Net Framework
=======================v2.0.50727 -> 2.0.50727.4927v2.0.50727\1031 -> 2.0.50727.4927v2.0.50727\1033 -> 2.0.50727.4927v3.0 -> 3.0.30729.4926v3.0\Setup -> 3.0.30729.4926v3.0\Setup\1031 -> 3.0.30729.8795v3.0\Setup\1033 -> 3.0.30729.4926v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902v3.5 -> 3.5.30729.4926v3.5\1031 -> 3.5.30729.5003v3.5\1033 -> 3.5.30729.4926v4\Client -> 4.7.02046v4\Client\1031 -> 4.7.02046v4\Client\1033 -> 4.7.02046v4\Full -> 4.7.02046v4\Full\1031 -> 4.7.02046v4\Full\1033 -> 4.7.02046v4.0\Client -> 4.0.0.0
Checking AMO
=======================PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Checking ADOMD.NET
=======================PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Dax Studio Configuration
========================Dax Studio registry key not found.
Checking Excel Add-in
=======================Detected Excel Version: 14 - Excel_2013DAX Studio Excel Add-in Registry keysWARNING: DAX Studio Excel addin registry keys not found!
Checking for Excel 2010 Disabled Add-ins  N/A  >  - ࠧÀ䘀Previewer: Microsoft Excel-Vorsch  N/A  >  - c:\users\dan\documents\00. wip\eio\wilo\elight 5+1\original matthias\cp\111.x  N/A  >  - p:\office\6br9f\stockszrbn_gauss_ib+.xlamstockszrbn_gauss_iChecking for Excel 2013 Disabled Add-ins  PASS > No Disabled items found.Checking for Excel 2016 Disabled Add-ins  PASS > No Disabled items found.
Attempting to load Excel Add-in:   PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.0.97, Culture=neutral, PublicKeyToken=null

**Comment by marcosqlbi** [comment]
I hope that Darren will provide you more details on that - but I think we no longer have any test made on Excel 2010, nor PCs running it, so it's also a challenge to debug it.
Probably you should keep using the version that worked well.

**Comment by nVenticDW** [comment]
next try Excel 2013 64 bit    (the stand alone version) with Power pivot and dax studio v2.7 under W10 creators edition on a 16GB PC.
(I have already discovered that the 32 bit 2010 version can't handle the amount of data I'm dealing with)

when in excel, pressing the DAX studio ribbon button has no effect.  ??
Starting Dax studio from the run command can't find the model.


below the output of the checker  for v2.7 of DAXstudio
(v2.4.3  exhibits the same behaviour - installing ADOMD and AMO for 2012 )
(v2.1.1 exhibits the same behaviour - installing net 4.5)

Is the main testing platform Excel 2013 or Excel 2016  ?


Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.4927
v2.0.50727\1033 -> 2.0.50727.4927
v3.0 -> 3.0.30729.4926
v3.0\Setup -> 3.0.30729.4926
v3.0\Setup\1033 -> 3.0.30729.4926
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
v3.5 -> 3.5.30729.4926
v3.5\1033 -> 3.5.30729.4926
v4\Client -> 4.7.02046
v4\Client\1033 -> 4.7.02046
v4\Full -> 4.7.02046
v4\Full\1033 -> 4.7.02046
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET
=======================
PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
========================
Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
Processing DaxStudio.exe.config file...
Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
Bindings Found: 9
AMO : 13.0.0.0
ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
Detected Excel Version: 15 - Excel_2016
DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  N/A  >  - c:\windows\system32\mscoree.dll

**Comment by dgosbell** [comment]
If you close all your Excel windows, then hold down left-shift while Excel starts up the add-in should start up with diagnostic logging enabled. If you can then click on the Excel add-in button to try to launch the DAX Studio UI hopefully the logs will capture some information about what is causing the issue here. If you then close Excel and paste the following path into a Windows Explorer window ```%AppData%\DaxStudio\Log``` you should see a file called DaxStudioExcel-yyyymmdd.log where the yyyymmdd reflects today's date. If you can attach that file to this issue we can have a look through it.

**Comment by nVenticDW** [comment]
This issue, with excel 2010 and no connection should be closed. Response is : See if past versions work. For my 2010 configuration I should remain with v2.43, the last before ADOMD.

For the "no response on pressing the DAX button in Excel 2013 + " I will open a new issue

**Comment by dgosbell** [comment]
Closing this old Excel 2010 issue
