### ISSUE TITLE
Query run issue

### ISSUE THREAD

**Issue by KateHamster** [DaxStudio/DaxStudio#153]
Hello, I am trying to run DAX queries on AAS model connected via Visual Studio project.
When I try to run simple queries, such as:
`EVALUATE
Delivery`
Where is Delivery is the name of the table. But when I try to run some slightly more complicated queries, like:
`EVALUATE
MAX ( Delivery[ShiftEndDateTime] )`
it doesn't work. I have tried to format differently but it provides no better experience. What I am doing wrong, or there is a problem with DAX Studio, because Dax formatter tells me that everything is great.
![errors](https://user-images.githubusercontent.com/11301284/53028197-b20cc280-3466-11e9-860d-c8f223fb31fb.jpg)
I am completely lost, and I hope that this issue will be treated in shortest delay. 
Thank you.

**Comment by marcosqlbi** [comment]
EVALUATE requires a table expression.
DAX Formatter doesn't get the error because it does not perform a full parse of the syntax.

In order to create a table you can use:
EVALUATE { [measure] }
EVALUATE ROW ( "x", [measure] )
