### ISSUE TITLE
Azure Analysis Services, wrong database showing when first loads

### ISSUE THREAD

**Issue by ZoeBD** [DaxStudio/DaxStudio#157]
I have Azure Analysis Services with 3 databases (prod, uat, stg).  When I connect to it in DAX Studio, the left nav shows prod is selected and I see all the tables.  When I query it, I find it's actually stg.  If I then change the database to stg, and back to prod, the query will give me the data in prod.

**Comment by dgosbell** [comment]
Yep, there is an issue when first connecting when the default database is not the first in the list. This will be fixed in the next release. This affects any data source that supports multiple databases.
