### ISSUE TITLE
Add option to apply IsHidden flag

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#159]
As a developer
I want to have the option to hide "Hidden" tables, columns and measures from the model view tree
So that I can reduce the number of items being shown on concentrate on the "public" entities

Given DaxStudio's "ShowHiddenItems" option is true
When I connect to a model
Then the model viewer shall contain all entities regardless of the value of the "IsHidden" attribute

Given DaxStudio's "ShowHiddenItems" option is false (default case)
When I connect to a model
Then the model viewer shall contain all only display entities that have IsHidden = false

Given DaxStudio's "ShowHiddenItems" option is false (default case)
And the model contains a hidden table
And the hidden table contains columns and/or measures that are not hidden
When I connect to a model
Then the model viewer shall contain not contain the table
And the model view shall not contain any columns and/or measure within the table

**Comment by dgosbell** [comment]
Closing as this overlaps with #167
