### ISSUE TITLE
Switching off DAX studio inside excel

### ISSUE THREAD

**Issue by nVenticDW** [DaxStudio/DaxStudio#16]
I would like to be able to switch on/off DAX studio from inside Excel due to the amount of addins I use. If I go to addins/com  and click remove Excel informs me that DAX studio has been installed for all users and therefore only an admin can do this. I am admin.  I suggest there should be a simple question for the installer to ask if the ser only wants it to install for the current user. My workaround is either to deinstall and reinstall DAX studio.

Config: Excel 2010 32 bit, plus powerpivot, Dax Studio  v2.4.1 (I seem to remember later versions also have this issue when I tested them) 

Dan

**Comment by dgosbell** [comment]
We're currently stuck a little here as the core Microsoft libraries we need require an admin install. But Microsoft is looking to change this soon and when that happens we'll probably re-work the entire install process and possibly even make a non-admin install the default.

**Comment by nVenticDW** [comment]
All clear. Thanks

**Comment by dgosbell** [comment]
When you install DAX Studio for the first time you now get asked if you want to install for all users or just for the current user (so if it is already installed you will need to do an uninstall first). If you choose the Current User option you should now be able to turn off the DAX Studio addin
