### ISSUE TITLE
Query Batch Completed with errors

### ISSUE THREAD

**Issue by janscas** [DaxStudio/DaxStudio#162]
Hi, i'm using Dax studio 2.8.2 to connect to a pbix file and check some dax measures.

I can connect just fine but if I execute any statements the dax studio always throws this error "Query Batch completed with errors".

I started the app in debug mode but I don't see any errors on the logs.

Do you have any clue on what can cause this error?

I also tried 2.8.1 with the same result.

My environment is in spanish btw.

**Comment by dgosbell** [comment]
It's possible to run a batch with multiple resultsets so we always output that  "Query Batch completed with errors" at the end of the batch in case the error message has scrolled off the top of the window. However sometimes the error text is so large that it scrolls up off the screen when there is just one query in the batch. 

If you scroll up or increase the size of the output pane you should find the full error message above the  "Query Batch completed with errors" message.

**Comment by janscas** [comment]
Nope, no errors in the output or in the logs.

![image](https://user-images.githubusercontent.com/7224106/53946766-b8d14180-40c4-11e9-96a6-8408fbac8fa0.png)

**Comment by dgosbell** [comment]
Yes there is I can see it in your screenshot. It says something like "The end of the input has been reached" when I put it into google translate. What you have there is an incomplete statement. A dax query must have a evaluate clause.

The simplest query you could do would be something like the following. 

```
DEFINE
MEASURE _Ventas[VentasBaseMes] = CALCULATE(SUM(_Ventas[ImporteVentas]), DATESMTD(Fechas[Fecha])
EVALUATE
ROW("VentasBaseMes" , [VentasBaseMes] )
```

But since you have DATESMTD you may want to do something with dates on the rows.

```
DEFINE
MEASURE _Ventas[VentasBaseMes] = CALCULATE(SUM(_Ventas[ImporteVentas]), DATESMTD(Fechas[Fecha])
EVALUATE
ADDCOLUMNS( VALUES(Fechas[Fecha]), "VentasBaseMes" , [VentasBaseMes] )
```

**Comment by janscas** [comment]
Thanks!
