### ISSUE TITLE
Dax Studio Export Data to SQL Server

### ISSUE THREAD

**Issue by dpserfaty** [DaxStudio/DaxStudio#165]
Hello!

I am having a problem exporting data through the Export All Data tool as is explained here [https://xxlbi.com/blog/dax-studio-export-all-data/](https://xxlbi.com/blog/dax-studio-export-all-data/)
I cannot connect via SQL Server (the idea is to take it to an Azure SQL Data Warehouse) I don't know why. It tries to download the first table but apparently fails. 

Has anyone tried it that can help me with this?

Thanks a lot in advanced!

**Comment by dgosbell** [comment]
What error message are you seeing when this fails?

**Comment by dpserfaty** [comment]
@dgosbell 
> What error message are you seeing when this fails?

No message is shown. In the lower left corner I can see that the first table is being extracted and after two seconds stops and says READY.

**Comment by dgosbell** [comment]
What version of DAX Studio are you using? If you are not on 2.8.3 can you download and install that as it has improved error trapping for the export function. 

Can you also turn on the debug logging using [this procedure](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then retry your export and post the log here.

**Comment by dpserfaty** [comment]
@dgosbell Thats it! with the new version works quite well.

Thanks a lot!

**Comment by dgosbell** [comment]
Very strange, we did not change any of the core logic we just added some extra error logging. Glad it's now working for you.
