### ISSUE TITLE
Bug: DAX editor panel Copy & Paste Issue

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#166]
Most editors allow the cloning of a region of text by highlighting, copying then pasting.  1st past overwrites selection then subsequent pastes insert a copy

DAX studio 2.8.1 (and just tried in 2.8.3) doesn't allow this

However, changing the text caret or changing the highlighted region does allow the paste operation

**Comment by dgosbell** [comment]
It looks like it's probably not too hard to enhance the paste behaviour to work in this way, so I should be able to include this enhancement in the next release.
