### ISSUE TITLE
Query Trace is not getting started.

### ISSUE THREAD

**Issue by VivekGuptamn** [DaxStudio/DaxStudio#168]
Getting Following Error while try to start query trace.

This operation is not allowed by azure analysis service product as the current contex is read only.

Thanks
Vivek

**Comment by dgosbell** [comment]
That sounds like you connected to the readonly endpoint. You need need to be a server admin and you need to connect to the management server URL (the one that ends in ":rw") if you want to start traces on Azure AS.

**Comment by dgosbell** [comment]
I'm assuming that connecting to the rw endpoint resolved this issue
