### ISSUE TITLE
multiple query tabs not available

### ISSUE THREAD

**Issue by TinyTimothy2** [DaxStudio/DaxStudio#170]
I have dax studio 2.8.3
I only have one query tab available which severely limits what I can do.
The documenation states that multiple tabs are available.  How do I enable multiple query tabs

**Comment by dgosbell** [comment]
File -> New or the Ctrl+N hotkey will open a new tab
Ctrl+Shift+N will open a new tab with the same connection as the current tab

**Comment by dgosbell** [comment]
I just pushed an update to the documentation to include this information. Thanks for pointing this out.
