### ISSUE TITLE
Issue in connect pop up box

### ISSUE THREAD

**Issue by spoojary668** [DaxStudio/DaxStudio#172]
Installed DaxStudio 2.8.4 in my laptop windows 10. But in the Connet option only 'Tabular Server' bullet is active. Other two options 'PowerPivot Model' and 'PBI/SSDT Model' bullets are  not active. Please help.

**Comment by dgosbell** [comment]
Have you tried hovering over the help icons next to the disabled options? This should tell you why they are disabled.

![image](https://user-images.githubusercontent.com/8241830/55508603-f619f680-56a5-11e9-80f1-95e8bbc88966.png)

But you can only connect to PowerPivot if you launch from inside Excel while a file with a PowerPivot model is open, using the DAX Studio button on Addins ribbon. And for Power BI Desktop DAX Studio searches for running copies of Power BI Desktop on your machine.

**Comment by spoojary668** [comment]
Thank you for the reply. Dax studio has been added in the Addins ribbon. Trying to connect inside a powerpivot Excel. But still it shows error warning: Powerpivot model not detected. Please help

**Comment by dgosbell** [comment]
What version of Excel are you using? 
Do you have an Excel file open that contains a PowerPivot model?
Can you create a pivot table against that model in the active file?

**Comment by spoojary668** [comment]
Its done. Thank you so much

On 4/5/19, Darren Gosbell <notifications@github.com> wrote:
> What version of Excel are you using?
> Do you have an Excel file open that contains a PowerPivot model?
> Can you create a pivot table against that model in the active file?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/DaxStudio/DaxStudio/issues/172#issuecomment-480030234


-- 
Santosh
