### ISSUE TITLE
Dax Studio ECCN

### ISSUE THREAD

**Issue by EGChevron** [DaxStudio/DaxStudio#176]
Greetings:
 
I am an Export Compliance Officer for Chevron.  Would you please provide the ECCN (Export Control Classification Number) for the Dax Studio software?

If one is not available, would you please assist me by answering the following:
1.	What is the function of the software?
2.	Does the software have any encryption capabilities? Y/N
a.	If yes, does the encryption (Y/N): 
i.	_______ Encrypt the data in files (scramble data for illegibility)
ii.	 _______ Does the software utilize encryption capabilities of other programs (i.e. “crypto with a hole” or “open cryptographic interface”)
iii.	 _______ Encrypt only the password to ensure user authenticity
 
Thank you.

**Comment by dgosbell** [comment]
Hi there, No - we do not have an ECCN number.

> What is the function of the software?

DAX Studio is a tool for sending queries to products using the Microsoft Tabular data engine (eg. SQL Server Analysis Services, Azure Analysis Services, Power BI, Excel Power Pivot). We enable people to author queries, execute them against the tabular model and see the results. 

> Does the software have any encryption capabilities? Y/N
> a.	If yes, does the encryption (Y/N):
> i.	_______ Encrypt the data in files (scramble data for illegibility)
> ii.	_______ Does the software utilize encryption capabilities of other programs (i.e. “crypto with a hole” or “open cryptographic interface”)
> iii.	_______ Encrypt only the password to ensure user authenticity

No we don't explicitly encrypt anything or explicitly call any cryptographic interfaces. We don't store any "data" as such, we just allow people to query data stored in other products. People can save their queries (these are stored as plain text) and they can export the results of queries to csv text files but we don't store or encrypt the data ourselves. 

I believe that all the network communication between DAX Studio and the various data sources is encrypted, but that is handled at the Microsoft Analysis Services .Net library level. It's not an explicit feature that we can control or turn on and off. It's effectively functionality built-in to the database driver provided by Microsoft.

**Comment by EGChevron** [comment]
Thank you very much.  I appreciate your details and quick response.

Regards,
Esmeralda Gonzalez | Tel 713 372 4994
