### ISSUE TITLE
DAXStudio Export Data error

### ISSUE THREAD

**Issue by BrunoAtGit** [DaxStudio/DaxStudio#178]
I'm trying to export a pretty big table (~16Mio lines, pbix file ~390MB) from my PowerBI Desktop model with DAXStudio via the Export Data function. The error message is:
"Error Exporting 'table_name': Memory error: Memory Allocation failure . Try simplifying or reducing the number of queries."
In the Task Manager I can see that the memory consumption is going through the roof (beyond 13GB) on a process belonging to PowerBI Desktop (Microsoft SQL Server Analysis Services).
I have also tried to export the same table via PowerBI Service (Premium capacity)). The error message is slightly different but still indicates a memory issue:
"Error Exporting 'table_name': Memory error: You have reached the maximum allowable memory allocation for your tier. Consider upgrading to a tier with more available memory."
- DAXStudio version 2.8.4 and also tried 2.8.5 prerelease
- PowerBI Desktop version is 2.68.5432.841 64-bit (April 2019)

**Comment by dgosbell** [comment]
Unfortunately there is nothing we can really do about this from the DAX Studio perspective this is a limitation of the current tabular engine. DAX Studio is using a streaming architecture to write out the results to file so you'll find that the daxstudio.exe process should be stable in it's memory usage regardless of the number of records that are exported. 

However the tabular engine itself was designed around doing aggregate queries, not bulk data extracts. The main issue here is that the engine materializes the entire, uncompressed resultset in memory before sending it to the client. This is fine for normal queries generated by visuals on a report, but not for large data extracts. The compressed data in the pbix file can expand by anywhere between 10 to 100 times. So a 380MB file can easily expand to roughly anywhere from 3.9GB to 39GB. 

You have a couple of options you could explore here.

- You could look at running this code on a machine with more memory or expanding your premium capcacity (although that could get expensive)
- Power BI had to pull the raw data from another source in the first place, so you could go back to that for detail level data.
- You could use a date or id column to export smaller ranges of records using the file output option in DAX Studio to write out to a csv file

eg. the following query would get transactions for 2018
```
EVALUATE 
CALCULATETABLE( 
  table_name ,
  DATESBETWEEN( table_name[Transaction Date], "2018-01-01", "2018-12-31")
)
```

**Comment by BrunoAtGit** [comment]
Thanks Darren for your detailed explaination! I've now used the code provided to extracts batches of data in smaller chunks.
