### ISSUE TITLE
2.8.4 Cannot connect to PBIX using Direct Query against Oracle database

### ISSUE THREAD

**Issue by PedroReis-PBIPT** [DaxStudio/DaxStudio#179]
Hello dear Marco and Alberto. Should Dax Studio work in Direct Query mode? I am finding the following issue when attempting to connect to an SSAS cube in Direct Query mode (connected to Oracle database)

_"No Databases were found in the when connecting to localhost:xxxxx (PBI Desktop)
If your Power BI File is using a Live Connection please connect directly to the source model instead"_

It works fine if connected to the same cube in Import mode.

**Comment by dgosbell** [comment]
So if your PBIX file is connected to SSAS you are using a Live Connection and there is no data model in the PBIX file for us to connect to.  As the error message implies you need to connect to the source model (ie. connect to the same SSAS database that the PBIX file is connected to). Then everything should work fine.

**Comment by PedroReis-PBIPT** [comment]
Thanks @dgosbell , so this means I have to be connected as a 1st Tier connection (PBI -> DB or SSAS -> DB), and a 2nd Tier doesn't work (PBI -> SSAS - DB or Excel -> SSAS - DB).

Is there any way to facilitate evaluating the queries ran by my model which is connected via PBI -> SSAS - DB, without having to completely rebuild my report directly in SSAS?

**Comment by dgosbell** [comment]
> Is there any way to facilitate evaluating the queries ran by my model which is connected via PBI -> SSAS - DB, without having to completely rebuild my report directly in SSAS?

There is no need to change your report, Just connect DAX Studio to SSAS, then turn on the all queries trace and then open your PBIX file and you will see all the queries that Power BI Desktop is sending to SSAS.

**Comment by PedroReis-PBIPT** [comment]
Works perfectly! Thank you very much @dgosbell
