### ISSUE TITLE
Honouring slicers

### ISSUE THREAD

**Issue by gvggvg** [DaxStudio/DaxStudio#18]
I believe it would be of great value for the beginners if DAX Studio was able to take into consideration existing slicers.

**Comment by marcosqlbi** [comment]
DAX Studio ignores the filters you apply in Power BI. You can capture the queries from Power BI (which honor slicers) and then execute them in DAX Studio.

**Comment by dgosbell** [comment]
Slicers don't change the state of the model in any way. Slicers interact with other visuals and cause them to alter they way they generate their queries. So it's not that we _actively_ ignore them, but they are actually invisible to DAX Studio as they only interact with other objects inside their client application.

Using Marco's suggestion of running the All Queries trace, then change a selection in your slicer will allow you to see how the queries on your other visuals are altered by that slicer.

**Comment by gvggvg** [comment]
OK, thanks for the comments. Anyway DAX Studio is a great tool.
