### ISSUE TITLE
Query plan not working if using a specific role in connection string

### ISSUE THREAD

**Issue by Alberto-Ferrari** [DaxStudio/DaxStudio#180]
When connecting to AS with an admin account, specifying the role in the connection string, query plan and server timings are not grayed out (as expected) but trying to enable them fires a "fatal error". Therefore, it is impossible to check low-level queries sent to SE for a specific role.
Same scenario works with SQL Server profiler.
It would be nice to have the feature available :)

**Comment by dgosbell** [comment]
I just traced Profiler using Profiler and I it looks like it is actually stripping out the Roles=xxx property. I think we should be able to do the same thing fairly easily as we actually run the traces on a cloned copy of the connection for the current window.
