### ISSUE TITLE
Cannot expand list of fields in a table with folders

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#184]
I've installed DAX Studio at work (Surface Book 2, April 2019 Power BI Desktop) and at home (XPS 15, May 2019 Power BI Desktop), and I've got the same issue on both computers: I can't expand the list of fields in a table with folders:
![image](https://user-images.githubusercontent.com/10683126/58873281-5a3e5280-8709-11e9-9bfa-98856f9eb33e.png)
Double-clicking does not work (it only puts the table name in the query pane).
Both machines have Windows 10, and both have HiDPI screens if it helps. I tried running DAX Studio in compatibility mode (Windows 8) and also override HiDPI settings -- unsuccessfully.

**Comment by dgosbell** [comment]
Do you have the hidden objects visible or hidden? This looks like a SSAS model are you able to generate a create script and attach it to this issue so that I can try and reproduce this?

**Comment by DaniilMaslyuk** [comment]
I'm using the default settings -- hidden objects are visible. I am only using Power BI, not SSAS.

This issue appears everywhere:

- In the Contoso.pbix file from _The Definitive Guide to DAX_ companion files
- In a file I just received from a client
- When connected to a Power BI Premium dataset

Attaching the Contoso file just in case.

[Contoso - Copy for Darren.zip](https://github.com/DaxStudio/DaxStudio/files/3251996/Contoso.-.Copy.for.Darren.zip)

**Comment by dgosbell** [comment]
I've found this issue and just checked in a unit test and a fix, I'll release 2.9.1 in a few minutes. Thanks for letting us know about this :)
