### ISSUE TITLE
Missing Visual Name

### ISSUE THREAD

**Issue by FrankFromGermany** [DaxStudio/DaxStudio#185]
The initial comment with the metrics of the query collected in the JSON file should also include the Visual name.

// =================
// Operation       : 34 
// Query Start     : 04.06.2019 14:35:09
// Query End       : 04.06.2019 14:35:13
// Render Start    : 04.06.2019 14:35:13 
// Render End      : 04.06.2019 14:35:13
// Query Duration  : 3878 ms
// Render Duration : 84 ms
// Total Duration  : 3962 ms
// Row Count       : 502
// =================

**Comment by dgosbell** [comment]
That is a good idea, I think I figured out how to link to the visual name after I built the header comment. This will be easy to add to the next release.
