### ISSUE TITLE
Catch SSRS parameter values?

### ISSUE THREAD

**Issue by Arklur** [DaxStudio/DaxStudio#186]
So I tried to check something when creating an SSRS report using AS tabular, and I was very curious how parameters are send to the server (don't want to get into details). 

Unfortunately I had to realize passing parameters are handled differently as I thought, since I see the exact DAX query what is provided in the dataset. So instead of seeing the actual values being passed, I see them as @Parameter. E.g.:

```
DEFINE    
VAR DataCategory1CodeAllSelectedFl = 
    PATHLENGTH ( @DataCategory1Code ) > 1 
      && PATHITEM ( @DataCategory1Code, 1, 1 ) < 1  
```
Instead of something like:

```
DEFINE    
VAR DataCategory1CodeAllSelectedFl = 
    PATHLENGTH ( "asd|qwe" ) > 1 
      && PATHITEM ( "asd|qwe", 1, 1 ) < 1  
```

Is there a way to see these in DAX Studio? If yes, how, if not, is there a plan for making it? :)

Thanks,
Ark

**Comment by dgosbell** [comment]
The information about the parameters is visible in the QueryBegin trace event. If you have SQL Profiler and run a trace just for this event you will see these parameters in an XML fragment. You can actually copy and paste the query with the XML fragment into DAX Studio and run it as we have special handling for the XML parameter block.

Unfortunately at the moment we are not capturing this as part of the All Queries trace, we are only currently capturing the QueryEnd event as that has the duration information. We have talked about also listening for the QueryBegin event as part of the All Queries trace as this would also allow us to see the Effective Username as requested in #62 (which is another feature sometimes used by SSRS reports) 

This probably won't be too hard to do, but it will probably be a few weeks before I'll have time to investigate this properly.

**Comment by Arklur** [comment]
I see, thanks for the detailed answer and recommending using the SQL Profiler in this case, for the time being.

**Comment by dgosbell** [comment]
Closing this as the All Queries trace has been capturing parameter values from other clients for some time now
