### ISSUE TITLE
Custom delimiter when export to CSV

### ISSUE THREAD

**Issue by Drabiv** [DaxStudio/DaxStudio#188]
Could you please add functionality or explain how to do export in CSV with custom delimiter, for example pipe symbol "|"?

**Comment by dgosbell** [comment]
We currently just have options to export using tab or comma delimiters. Are there problems with these formats or do you just have to import into some other system that can't handle commas or tabs? Are the quoted strings a problem too?

Currently if you output to csv you will get data like:
```
123, "some string"
```
or if you do .txt
```
123<tab>"some string"
```

would you want output like the following?
```
123|"some string"
```
or would you also want the option to switch off the quoting of string fields?
```
123|some string
```

**Comment by Drabiv** [comment]
I need to import to other system pipe delimited file. The files are big (much more than 1M lines), hence cannot do the export using just Excel. 
BTW, quoted string might be a problem too (I'm not sure right now as I have not tested ). It would be great if user can decide on qualifier and delimiter (as it is in MySQL Workbench).

**Comment by e3500** [comment]
Having issues with a quoted string as well so would def appreciate the option to export as tab but no quoting:

123<tab>some string

**Comment by e3500** [comment]
123 <tab> some string

**Comment by e3500** [comment]
* that was supposed to be a tab between 123 and  some string
