### ISSUE TITLE
Crashes while connecting to PowerPivot Model

### ISSUE THREAD

**Issue by WSAyan** [DaxStudio/DaxStudio#19]
I am running DaxStudio from excel Add In. It crashes during PowerPivot model connection. Screenshot of the exception:
![sda](https://user-images.githubusercontent.com/7785995/31664389-05f3b4da-b367-11e7-8801-05c43e77047c.PNG)

And here is the output of DaxStudio.Checker.exe 

`Checking Operating System
=======================
OSCaption       = Microsoft Windows 10 Pro
OSVersion       = 10.0.10240
OSArchitecture  = 64-bit
VisibleMemoryGB = 7.87
FreeMemoryGB    = 3.87

Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.4927
v2.0.50727\1033 -> 2.0.50727.4927
v3.0 -> 3.0.30729.4926
v3.0\Setup -> 3.0.30729.4926
v3.0\Setup\1033 -> 3.0.30729.4926
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
v3.5 -> 3.5.30729.4926
v3.5\1033 -> 3.5.30729.4926
v4\Client -> 4.6.01055
v4\Client\1033 -> 4.6.01055
v4\Full -> 4.6.01055
v4\Full\1033 -> 4.6.01055
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
Dax Studio registry key not found.

Checking Excel Add-in
=======================
Detected Excel Version: 15 - Excel_2016
Excel Path: C:\PROGRA~2\MICROS~1\Office15\EXCEL.EXE
Excel Architecture: x86

DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  N/A  >  - c:\program files (x86)\microsoft office\office15\addins\powerpivot excel add-in\powerpivotexcelclientaddin.dll`

**Comment by dgosbell** [comment]
Sorry for the delay in responding. We've just been closing out some of the fixed issues and I've realised that I never got back to you on this. Is this still a problem for you? If so, are you able to open the "Manage" window from the PowerPivot ribbon when you have the file open that you were trying to connect to with DAX Studio? The error that you are getting would usually only happen if the PowerPivot addin for Excel is not enabled.

**Comment by dgosbell** [comment]
Closing due to lack of response. If this is still an problem feel free to open a new issue
