### ISSUE TITLE
Unable to export large CSV files from Excel Data Model using DAX Studio

### ISSUE THREAD

**Issue by Drabiv** [DaxStudio/DaxStudio#190]
I'm trying to export large Excel Data Model (>70mln lines; based on 40 GB source file) using DAX Studio into CSV file and get Memory Error and "Query batch completed with errors" messages in output.

What is the limit on CSV output file size? I have 16GB RAM on my machine.
Is there a way to export big CSV files?

**Comment by dgosbell** [comment]
I have good news and bad news. 

The good news is that DAX Studio has no limit on the CSV file size. We use a streaming read/write approach and have written out a few GB worth of data and DAX Studio only uses a constant few hundred MB of memory. 

The bad news is that the tabular data model is designed for returning aggregate data sets. It's not designed for returning a large amount of detail data. One of the current "issues" with the tabular engine is that it materializes the entire uncompressed resultset in memory before sending it to the client. So it's probably trying to re-build the 40Gb of data in your 16Gb of RAM. (if you check in task manager while trying to run an export you should see the memory for DAX Studio staying stable while that for excel is constantly climbing).

Unfortunately the only work around is to export smaller chunks of data. For example if you have 10 years worth of data, try running an export for each year into 10 separate files.

**Comment by dgosbell** [comment]
I'm assuming that my comment above answers your question so I'm going to close this issue. Let us know if you need any further clarification

**Comment by Drabiv** [comment]
Thanks @dgosbell, makes a lot of sense.
