### ISSUE TITLE
Export to CSV Options - ' vs Space

### ISSUE THREAD

**Issue by Chublo** [DaxStudio/DaxStudio#191]
Hi there,
I have noticed that spaces in Column headers get exported with a ' in the place of the space. The specific use case I have has intentional spaces. It would be great to have some options of how the data is exported including this option. 
Many thanks
Chuck

**Comment by dgosbell** [comment]
Hi Chuck, I think that should not be too hard to fix. We mainly use the version of the name with the backtick ` for internal use, so I think it would actually makes sense to use the "display name" in the CSV column headers as the default option.

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10 release
