### ISSUE TITLE
What happened to the contents of my file? Oh, It's me... but maybe DAX Studio can help...

### ISSUE THREAD

**Issue by ScottStauffer** [DaxStudio/DaxStudio#193]
In DAX Studio...
If you:
1. Open DAX Studio,
2. Enter some code and save the file, 
3. Exit DAX Studio, 
4. Move the file you just saved in Step #2, 
5. Go back in to DAX Studio
6. Attempt to open the file through “Recent Files” link

DAX Studio will give you a new tab with the filename on it with a new empty file in the old location the stale "Recent Files" link referenced.  You might think... "What happened to the file?" - I feel a better solution would be not to create a new file with the same old file name... but instead just have a message in a dialogue box saying "This file does not exist there anymore... It has either been deleted or moved"... and then don't open a new tab...

Yes the error message is telling you this in the collapse-able pane, if you haven’t hidden the pane, or like to ignore it... If the file has been moved, Please let me find where it is now, instead of creating a new empty file in the old location.  Just a thought... 

Thanks for building this FANTASTIC product!

**Comment by dgosbell** [comment]
Ah - I did see your comment on twitter and wondered what had happened :)

I think you are completely correct here and that the current behaviour can be misleading. I'm thinking of changing it to this in the next release, so you also have the option of removing the entry from the recent files list.

![image](https://user-images.githubusercontent.com/8241830/59804176-e4550080-9330-11e9-91b5-3728a2fd83c9.png)
