### ISSUE TITLE
Tabs vs spaces

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#195]
When you select some code and press the Tab key, DAX Studio inserts tabs. While I realize that tabs vs spaces is often a matter of taste, there are a couple of reasons to consider using spaces:
1. DAX formula bar in Power BI Desktop uses spaces by default
2. DAX Formatter converts tabs to spaces
I propose four spaces instead of tabs to be consistent with Power BI Desktop and DAX Formatter.

**Comment by dgosbell** [comment]
I never actually made a deliberate decision about tabs vs spaces. What we currently have is just the default behaviour of the edit control that we are using. But that control does expose options for tabs vs spaces so it should not be too hard to change this behaviour (and maybe also add this to our options incase someone else feels strongly about wanting tabs)
