### ISSUE TITLE
Cancel button disabled

### ISSUE THREAD

**Issue by cboneill0099** [DaxStudio/DaxStudio#196]
I see there was an issue reported on Jan 19 with the cancel button, but mine seems to be different.  This seems to happen with queries that have issues I'm trying to troubleshoot.  While the query is running, the cancel button is grayed out and when I hover over it, it says a query is not running, but the timer is still going, and if I leave it alone, results are eventually returned.  There are other times, where the query ends up returning an error.  I've included a screenshot of what my screen looks like when this happens, as well as the errors that are returned in instances where the query does not end up finishing.
![DAX Studio 2](https://user-images.githubusercontent.com/34543385/60029916-04a5f780-9670-11e9-8b2c-e16344aae3ed.png)

**Comment by dgosbell** [comment]
This could actually be an issue with the "Clear Cache and Run" option. If you use just the standard "Run" button does this issue occur?

**Comment by cboneill0099** [comment]
Sorry it took a couple of days to respond.  I'll give that a shot and see if I experience the same behavior and get back to you.

**Comment by dgosbell** [comment]
I've just been doing some testing between the "Run" and "Clear Cache and Run" commands and I can reproduce this issue. The issue with the clear cache command is that it not only clears the data cache, but it also clears the global scope for the current session, so we run an empty query after clearing the cache to re-establish the session. It was this empty query that was triggering the "QueryComplete" state too early - I have a fix for this that will go out in the next release..
