### ISSUE TITLE
Launch from Excel obfuscates database list

### ISSUE THREAD

**Issue by danielpitz** [DaxStudio/DaxStudio#197]
We're having a problem when launching Dax Studio from Excel, if using a version of DS > 2.7.4.  Our latest attempt has been with 2.9.1.
After launching Dax Studio and connecting to the SSAS server, the "database" list (right under the word [Metadata]), does not list the databases.  Instead it lists the file path to the Excel file, once for each available database.  If I know where my target database exists within the list, I can select that spot in the drop down and things will work as I expect.

This behavior does not appear to exist when launching Dax Studio on its own.  Trouble is, then we don't have the option to output to Excel, and that's important to have available.
This is what we see when launching DS on its own (please excuse my lame attempt at redactions):

![NormalDatabaseList](https://user-images.githubusercontent.com/39717046/60051305-b1986880-96a0-11e9-8aa7-1243cba1493a.png)

This is what we see when launching from Excel:
![BadDatabaseList](https://user-images.githubusercontent.com/39717046/60051336-c2e17500-96a0-11e9-8f2c-f59335ec9277.png)

**Comment by dgosbell** [comment]
Thanks for reporting this issue. In 2.7.4 and earlier we used to report the internal name of the model when connecting to PowerPivot which was just a big long guid. This feature was meant to just replace the display name when connected to PowerPivot. It's a simple fix and a preview build including this fix is available [here](https://ci.appveyor.com/api/buildjobs/5i72hb93pojjchuw/artifacts/package%2FDaxStudio_2_9_2_setup.exe) although I will be publishing a production release of v2.9.2 in the next few days.

**Comment by danielpitz** [comment]
I just installed the fix (2.9.2 preview), and the problem is solved.  I still don't see the option for exporting to Excel if I launch Dax Studio on its own (not from Excel), but that might be by design.
Thank you.  I can finally upgrade!

**Comment by dgosbell** [comment]
> I still don't see the option for exporting to Excel if I launch Dax Studio on its own (not from Excel), but that might be by design.

Yes it is. Writing data to Excel when you are running inside Excel is easy. Generating an Excel file from scratch when running standalone is possible, its just going to be a lot more work. So at the moment, we've just focused on making sure that the CSV export option also imports into Excel properly.

**Comment by danielpitz** [comment]
I thought that might be the deal.  Thank you for everything – I can certainly launch from Excel when I need to export it back to a spreadsheet.

Thanks.

Dan Pitz
Business Intelligence Developer
Cellular Sales, Inc.
9040 Executive Park Dr.
Knoxville, TN 37923
