### ISSUE TITLE
Small quirk on copy.

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#198]
When you right-click a cell or cells in the result grid the path to the copy icon instead of the icon itself is shown in the right-click menu.

![pathtextinsteadoficon](https://user-images.githubusercontent.com/52240599/60172078-394eb600-980c-11e9-8c21-cb887247be26.png)

**Comment by dgosbell** [comment]
Thanks for pointing this out. I found a few other context menus where the image binding had broken. This will be fixed in the next release after 2.9.2
