### ISSUE TITLE
Shift + double click in Meta data pane – feature request.

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#199]
**Background:**

When you create a query you often double click the columns/measures and tables in the Metadata pane. A double click on a table, unfortunately, collapses the table's columns/measures. You'll then have to expand the table again to get to the columns/measures.

_I'm aware that you can use drag and drop; however, double click is faster to do and saves a few hand movements._

**Suggestion:**

**Shift + double click on table name:**  Adds the table name to the editor and **doesn't** collapse the column tree.
Shift + double click on column name/measures: The same behaviour as the current version.
Double click on table name: The same behaviour as the current version.
Double click on column name/measures: The same behaviour as the current version.

Thanks.

**Comment by dgosbell** [comment]
I like this idea, I tend to use intellisense more than double-click. I have this working on my local branch at the moment. I'm also considering adding a setting to the option page to allow people to turn off the expand/collapse when double clicking (as you can still toggle this by clicking on the expand icon)
