### ISSUE TITLE
Unable to install DAX Studio 2.7.1

### ISSUE THREAD

**Issue by cmcubism** [DaxStudio/DaxStudio#20]
Hi,
when I try to install DAX Studio 2.7.1 on my Win10 machine I get the following error:
"Unable to execute file in the temporary directory. Setup aborted.
Error 5: Access denied."

I do have admin rights though. 
Am I doing something wrong? Never had this issue before.
Kind regards
Christian

**Comment by dgosbell** [comment]
Sorry, but I have no idea. Does this happen straight away or do you get a few steps into the setup? I've even tested the installer with a non-admin user, it just prompts for an admin user's credentials and then it installs fine. Have you tried right-clicking on the downloaded fine and unblocking it? Sometimes that can have an affect on things.

**Comment by cmcubism** [comment]
@dogsbell: I found the problem. It was Kaspersky AntiVirus identifying DAX Studio as Malware!

Sorry for any inconveniences.
Kind regards
Christian

**Comment by dgosbell** [comment]
Interesting, we had one other user send us an email about an issue with Kaspersky too... although we ran the installer through virustotal.com and it said Kaspersky reported it as being clean. Glad you got this sorted out.
