### ISSUE TITLE
Language tag in status bar – feature request.

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#200]
**Background:**

When you install Power BI desktop the language version defines the sort order (collation). SSAS let you choose which one you prefer. Excel/power Pivot uses the OS-language etc.

**Suggestion:**

Would it be possible to show the culture-id/ Language tag (en-US;da-DK;de-CH;sv-SE etc) for the current model in the blue status bar at the bottom of the DAX Studio window.

I believe a recent addition to the DMV collection will be able to do this?? 

_select * from $SYSTEM.TMSCHEMA_CULTURES_

Since not all versions of the engine will support the new DMV out of the box it will be necessary to test for the existence of the DMV.

**Comment:**

On a project going back prior to the DMV we used the English version of Power BI desktop to prototype reports at 3 different sites that had 3 different locales and hence possibly 3 different sort orders. Users were used to seeing the data sorted differently and even though this was described in the project text the issue kept returning. (This is the short version of the story :-) ). It would, to a certain degree, have helped Support, if they - via DAX Studio - could have seen the language tag of the model being reviewed.

Thanks.

**Comment by dgosbell** [comment]
I'll have a look into this. I don't think TMSCHEMA_CULTURES is the correct DMV for this, I think this one exposes the different "languages" that have Q&A synonyms loaded. But it looks like TMSCHEMA_MODEL has the culture for the current model, but it is also in the DISCOVER_CSDL_METADATA DMV that we are already using for loading the metadata.
