### ISSUE TITLE
Tooltip text missing.

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#202]
Just noticed this. The 'Load Perf Data' button in the Home toolbar doesn't show any tooltip text.

![NoTooltipText](https://user-images.githubusercontent.com/52240599/60651923-80a9f780-9e47-11e9-93e6-4f973603013c.png)

**Comment by dgosbell** [comment]
Thanks for reporting this. I've just added text for the tooltip to a local branch that I'm working on so this will go out in the next release.
