### ISSUE TITLE
Multi-line paste crashes Dax Studio/pastes only on one line

### ISSUE THREAD

**Issue by eligoldner** [DaxStudio/DaxStudio#204]
Dax Studio seems to support multi-line select/copy/paste, though I've found 2 instances of unexpected behavior.

1. If I try to select/copy/cut on multiple lines (using ALT + SHIFT to select multiple lines) that works fine; however if I decide to paste on multiple lines on empty text, it will paste just on the last line, yet leave the cursor on multiple lines.
2. If I try to do multi-line paste where I'm replacing text, Dax Studio will crash.

I'm using version 2.9.2

**Comment by dgosbell** [comment]
I can't reproduce either of these issues using the 2.9.2 release, although I'm not entirely sure I understand what you are doing in item 1. I can copy paste multiple lines and paste over the top of existing text without crashing. 
![DaxStudioCopyPaste](https://user-images.githubusercontent.com/8241830/61835215-35bb5700-aebe-11e9-86fa-58bfc4c20cfe.gif)

Did you get the option to submit a crash report? As have not seen any crash reports submitted in the last few weeks.

Maybe it's something specific about the text you are working with. Are you able to upload an example .dax file that exhibits these issues and explain what to select in that file to reproduce this issue? Or maybe explain what you are doing differently to the operations in the image above.

**Comment by eligoldner** [comment]
> I can't reproduce either of these issues using the 2.9.2 release, although I'm not entirely sure I understand what you are doing in item 1. I can copy paste multiple lines and paste over the top of existing text without crashing.
> ![DaxStudioCopyPaste](https://user-images.githubusercontent.com/8241830/61835215-35bb5700-aebe-11e9-86fa-58bfc4c20cfe.gif)
> 
> Did you get the option to submit a crash report? As have not seen any crash reports submitted in the last few weeks.
> 
> Maybe it's something specific about the text you are working with. Are you able to upload an example .dax file that exhibits these issues and explain what to select in that file to reproduce this issue? Or maybe explain what you are doing differently to the operations in the image above.

**Comment by eligoldner** [comment]
I can reproduce it at will, though there is something which you are doing differently, and that is why you're not reproducing the error. 
Please try to follow these instructions so that you can reproduce it on your own; if you're unable to do so, I'll get myself a recording/GIF of the issue happening.  I've also attached the log for today so that you can see what went awry. 

You're showing me how you select multiple lines with your mouse followed by copy/paste, though I was referring to multi-line copy/paste, which some refer to as mutli-cursor. It is a common editing exercise used in many IDE's to be able to type on multiple lines simultaneously (this part works correctly in DAX Studio). In order for you to reproduce the error, you'll need to edit the text using just your keyboard. 
When you hold down ALT + SHIFT and press the up/down keys you'll see your cursor extend over the line(s) which you have selected and you'll be able to type on all of the selected lines simultaneously. Using this mode, pasting text causes trouble, where simply pasting exhibits unexpected behavior (pasting just on the last line), whereas pasting over text, i.e replacing text, will crash the application. I didn't submit a crash report as I wasn't offered the opportunity to do so post-crash.


[DaxStudio-20190725.log](https://github.com/DaxStudio/DaxStudio/files/3431861/DaxStudio-20190725.log)

**Comment by dgosbell** [comment]
Ok, thanks for the update. Using the keyboard was the trick. I can now reproduce these issues so I'll see if I can find the root cause and figure out a fix.

**Comment by eligoldner** [comment]
You're very welcome.
Thanks for jumping on this one.
