### ISSUE TITLE
Error trying to format/access website:   "DaxFormatter.com  Error:  Invalid URI:  the hostname could not be parsed"

### ISSUE THREAD

**Issue by cosminioan** [DaxStudio/DaxStudio#205]
hi Darren,
for some reason, I am getting  the error above on a Windows 7 laptop.  
I tried to do ipconfig/dnsflush, I tried to change the DNS to Google or my ISP, still nothing.

In options, I tried unchecking the Proxy (system), restarted the app, still nothing (I do not use any proxies.   

any thoughts on what might be wrong?
thanks much,
Cos

**Comment by IanHopewell** [comment]
Hi Darren & Cos, 

I can confirm the same error for our team as well.  

Regards Ian.

**Comment by cosminioan** [comment]
funny, not sure what is going on as:
a.  On another Windows 10 laptop, on the same network I'm using DaxStudio without any problem!
b.  Moreover, in a VMWare guest using Win 2012R2, within the same problematic Windows 7 host, DaxStudio also works very well!  (go figure).

So, I'm a bit at a loss, whether it is Windows 7 or my laptop, or some Proxy or DNS settings, as I've done ipconfig/flushdns, I've also tried to add the IP of the daxformatter.com site on the hosts file, I've disabled the Norton firewall (the Windows firewall is disabled).  

Any help, anyone, is much appreciated, not sure if fully qualifying the site may http://www.daxformatter.com  may help.    

thanks bunches,
Cos

**Comment by dgosbell** [comment]
I'm not really sure what could cause this. I've just double checked this with and without going through a proxy and it's working for me. The uri we use for daxformatter.com is a constant, it's just the body of the request that changes. It could maybe be a Windows 7 specific issue. 

Is this a new problem on a machine where this feature used to work? 

Or is this a new install of DAX Studio and this feature has never worked on this machine?

**Comment by cosminioan** [comment]
unfortunately I have not used SSAS/DAXStudio for years and now getting back to it, due to a job change, so not sure if DAXStudio has ever worked on the now problematic Windows7 machine.

I have just installed a brand spanking new Windows 7 Pro guest within my problematic Windows 7 Pro  host, and voila, it appears that it is NOT working.... so it could be an OS related issue.

@IanHopewell, are you having the same issue on Windows 7 (64 bit)?

@dgosbell Darren, would it be possible to build a quick beta with the fully qualified "http://www.daxformatter.com"   (in case that's not what's actually stuffed in and only  "daxformatter.com"  is currently being issued?)   I think the older OS's are a tad handicapped, as far as needing to know whether it is an ftp, or http or https call, I'm venturing to say).

many thanks, Darren... and Ian, for confirmation,
Cos

**Comment by dgosbell** [comment]
@cosminioan - the URI we use is already fully qualified so that is not the issue. We are using https:// though so it could be an issue with encryption/TLS 1.2 support as Win 7 does not support this by default - although I would expect an error relating to encryption support if that was the issue.

**Comment by cosminioan** [comment]
ok, thanks Darren. Looks like I may have to settle for working within any of my Win 10/Win2kR2 guests then, as I can't find any other setting working w/ Windows 7. 

thanks again --

**Comment by dgosbell** [comment]
@cosminioan - could you try enabling debug logging using the [following instructions](https://daxstudio.org/documentation/troubleshooting/logging-settings/), then try to format something with DAX Studio and shut it down and attach the log file to this issue? I'm not sure if it will capture much more detail than the current error message, but it's worth a try.

Otherwise I'll need to build a new Win7 test VM as I don't have a working one handy at the moment.

**Comment by cosminioan** [comment]
very funny, now!  In a great way!   As soon as I held down the left Shift key to start the app in Debug mode, it's now working fine with no problem (2.9.0 and 2.9.2).  Problem magically solved somehow, although I see in the log something about log file permission.... not sure if that had something to do with it.  Here's the (last) log file though.

many thanks Darren,
Cosmin
[DaxStudio-20190731.zip](https://github.com/DaxStudio/DaxStudio/files/3450961/DaxStudio-20190731.zip)

**Comment by IanHopewell** [comment]
Yes, also running Windows 7 on one of the workstations, it is working on the others Windows 10. The debug did not correct the error and this is in the logs:

2019-07-31 12:00:29.077 +01:00 [Debug] "DocumentTabViewModel" "OpenFileInActiveDocumentWindow" "Opening C:\Workspace\data-dax-code\Trading Action Plan Audit.dax"
2019-07-31 12:00:31.697 +01:00 [Debug] "DaxFormatter" "PrimeConnectionAsync" "Start"
2019-07-31 12:00:32.137 +01:00 [Error] "DaxFormatter" "PrimeConnectionAsync" "The underlying connection was closed: An unexpected error occurred on a send."
2019-07-31 12:00:32.137 +01:00 [Debug] "DaxFormatter" "PrimeConnectionAsync" "End"
2019-07-31 12:00:32.140 +01:00 [Error] "DaxFormatter" "CallDaxFormatterAsync" "Invalid URI: The hostname could not be parsed."
2019-07-31 12:00:32.140 +01:00 [Debug] "DaxFormatter" "CallDaxFormatterAsync:End"
2019-07-31 12:00:32.150 +01:00 [Error] "DocumentViewModel" "FormatQuery" "One or more errors occurred."
2019-07-31 12:00:57.434 +01:00 [Information] "MetadataPaneViewModel" "RefreshTables" "Metadata Refreshed (duration: 29170ms)"
2019-07-31 12:01:26.600 +01:00 [Debug] "ShellViewModel" "OnApplicationActivated"
2019-07-31 12:01:26.600 +01:00 [Debug] "RibbonViewModel" "Handle:ApplicationActivatedEvent:Start" ApplicationActivatedEvent {  }
2019-07-31 12:01:27.037 +01:00 [Debug] "RibbonViewModel" "RefreshConnectionDetails" "" ""
2019-07-31 12:01:27.040 +01:00 [Debug] "RibbonViewModel" "Handle:ApplicationActivatedEvent:End" ApplicationActivatedEvent {  }
2019-07-31 12:01:29.682 +01:00 [Debug] "DocumentViewModel" "OnDeactivated (close)" Close:True Doc:"Trading Action Plan Audit.dax"
2019-07-31 12:01:30.026 +01:00 [Information] ============ DaxStudio Shutdown =============
2019-07-31 12:01:52.561 +01:00 [Error] "DaxFormatter" "PrimeConnectionAsync" "The underlying connection was closed: An unexpected error occurred on a send."

We are in the process of upgrading developer machines and all will be Windows 10 in the coming weeks.

Regards
Ian

**Comment by dgosbell** [comment]
@cosminioan The debug logging does not change any behaviour, it just outputs extra messages to the logs. So I don't think this fixed your issue, but based on what I found it's possible that a group policy or registry change or the installation of a security patch could have affected this.

@IanHopewell  That last error line from the PrimeConnectionsAsync method about the underlying connection being closed is one of the errors you see if a machine attempts to use the older TLS 1.0 on a HTTPS site that only supports TLS 1.2 

I've just finished building a new Win 7 SP1 VM and could reproduce this error. I've made a change to force the web requests to use TLS 1.2 encryption (which is the default for Operating Systems after Win 7) and this appears to fix this issue on my test VM.

I have a beta build available [here](https://ci.appveyor.com/api/buildjobs/l9sceujbbhbkdbun/artifacts/package%2FDaxStudio_2_9_3_setup.exe) if you want to try this for yourselves.

**Comment by cosminioan** [comment]
great, although I'm getting this resource error:
![DaxStudioError](https://user-images.githubusercontent.com/14153647/62211009-7e19bf80-b36b-11e9-85fd-5002fbad836f.JPG)

**Comment by dgosbell** [comment]
Sorry, I have another issue I'm working on related to theming. (the build off the build server crashes the same way on my test VM) I've fixed both issues now and the latest beta for 2.9.3 is available [here](https://ci.appveyor.com/api/buildjobs/l9sceujbbhbkdbun/artifacts/package%2FDaxStudio_2_9_3_setup.exe)

**Comment by cosminioan** [comment]
almost same error as above, except without Stack Trace
![DaxStudioError2](https://user-images.githubusercontent.com/14153647/62302391-446ab680-b448-11e9-9fc8-440f6c2e9c71.JPG)

thx

**Comment by dgosbell** [comment]
Sorry, I must have accidentally copy the same download link twice - that version is showing the same build as the previous one (2.9.3.**128**) I fixed the theme issue in 2.9.3.**129** and that download for that one is [here](
https://ci.appveyor.com/api/buildjobs/i266x20mith3rs5w/artifacts/package%2FDaxStudio_2_9_3_setup.exe)

**Comment by cosminioan** [comment]
looks good now.  thanks bunches, Darren!  :-)

**Comment by IanHopewell** [comment]
Thanks, Darren, it is now working and formatting.
