### ISSUE TITLE
DAX Studio fails to appear in Excel 2016

### ISSUE THREAD

**Issue by Sparta100** [DaxStudio/DaxStudio#206]
I've downloaded and installed DAX studio for Excel to allow for the export of large CSV files from Power Query. However, the DAX Studio Addin-In fails to appear on my Excel ribbon despite being enabled. How can I actually access DAX Studio?

**Comment by dgosbell** [comment]
The addin should appear in the Add-ins ribbon.
![image](https://user-images.githubusercontent.com/8241830/62095155-dd6fc500-b2c2-11e9-98f0-5806f7227d15.png)
You could try right-clicking on the ribbon and choosing the "Customize the Ribbon..." option and checking that the Add-ins tab is ticked as being visible. 
Note that some badly behaved addins can sometimes re-name the Add-ins ribbon to something else. So in this case DAX Studio may appear under a differently named ribbon tab.

**Comment by Sparta100** [comment]
Thank you for the quick response: The add-In is now appearing. Thank you.

Steven Weydert
Senior Financial Analyst
Customer Support Center
1855 Gateway Boulevard, Suite 400
DIRECT: 925.391.3253 ext. 1253
CELL: 949.648.8575
sweydert@saxco.com

[cid:image001.png@01D54642.3514F750]<http://www.saxco.com/>
[cid:image002.png@01D54642.3514F750]<https://www.instagram.com/saxco_international/> [cid:image003.png@01D54642.3514F750] <https://www.facebook.com/saxcoint>   [cid:image004.png@01D54642.3514F750] <https://twitter.com/SaxcoInt>  [cid:image005.png@01D54642.3514F750] <https://www.linkedin.com/company/saxco-international-inc-/>
