### ISSUE TITLE
On the Help ribbon on 2.9.2 none of the links work.

### ISSUE THREAD

**Issue by ScottStauffer** [DaxStudio/DaxStudio#208]
In my mind **_Low Priority_**: 

• The following error occurred while trying to open the http://daxstudio.org: The system cannot find the file specified

• The following error occurred while trying to open the http://daxstudio.org: The system cannot find the file specified

• The following error occurred while trying to open the http://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlanalysisservices: The system cannot find the file specified

**Comment by dgosbell** [comment]
Yes, Alberto emailed me about this a week or so ago. It's a silly issue with accidentally swapping the parameter order on a function. It will be fixed in the 2.9.3 release

**Comment by dgosbell** [comment]
This has been fixed in the recent 2.9.3 release
