### ISSUE TITLE
Query Plan Tracing

### ISSUE THREAD

**Issue by jacoblawler** [DaxStudio/DaxStudio#21]
The query plan tracing does not display any traces (Power Pivot Excel 2013). Both the physical query plan and the logical query plan are blank. However, the query plan trace does work when tracing from Power BI Desktop files.

Using version 2.7.1.

**Comment by FrankFromGermany** [comment]
I have the same issue with Excel 2016. No query plans for Power Pivot anymore. 

Furthermore, for some reason v2.7.1 cannot be launched from the Power Utilities add-in.

**Comment by dgosbell** [comment]
This will be fixed in the next release (2.7.2)
