### ISSUE TITLE
Date Parameter -- Syntax for Entering Date in Parameter window at Runtime

### ISSUE THREAD

**Issue by Kealkil4** [DaxStudio/DaxStudio#216]
Trying to enter a Date to a DAX Query via parameter.

Getting an error ... "Dax comparison operation do not support comparing values of type Date with values of type Text.  Consider using VALUE or FORMAT function to convert one of the values."

The following works ok ...

EVALUATE
CALCULATETABLE (
    SUMMARIZECOLUMNS (
        'Department'[Department],
        'Dates'[Datekey],
        "Total Sales", [Total Sales]
    ),
    Department[Department] = "Admissions"
    ,Dates[Datekey] = DATE(2019,08,31)
//    ,Dates[Datekey]] = @Date
)

Can you indicate the precise syntax to enter in the Query Parameters Window when using the @Date Parameter?

Thanks.

**Comment by dgosbell** [comment]
Parameters in DAX always have a string data type. So you would need to use something like DATEVALUE() to parse it to a strongly typed date/time. And typically I use the ISO date format "yyyy-mm-dd" when passing in parameter values to avoid any ambiguity.

eg

EVALUATE
CALCULATETABLE (
SUMMARIZECOLUMNS (
'Department'[Department],
'Dates'[Datekey],
"Total Sales", [Total Sales]
),
Department[Department] = "Admissions"
 ,Dates[Datekey]] = DATEVALUE( @Date )
)

**Comment by Kealkil4** [comment]
Thanks Darren.

Had tried using VALUE in Parameter but not DATEVALUE.
