### ISSUE TITLE
Error Exporting Metrics - DaxStudio 2.9.4

### ISSUE THREAD

**Issue by denglishbi** [DaxStudio/DaxStudio#218]
Wanted to export metrics to import into new Vertipaq Analyzer 2.0, but received the following message: 

Error exporting metrics: Query (1, 100) Too few arguments were passed to the UNION function. The minimum argument count for the function is 2.

**Comment by dgosbell** [comment]
I think I found this issue. Vertipaq-Analyzer is using a pattern like the following to get the column cardinality 
```EVALUATE UNION( ROW( <columnname>, DISTINCTCOUNT( <columnname>) , ...```
but it is also calling this in batches of 50 columns at a time... So if you had 51 or 101 or 151 etc columns in your model I think the last batch will fail with this error.

Are you able to check if the number of columns in your model is a multiple of 50 , plus 1 ?

The row count from the following query should give you this.
```
select *
from $system.TMSCHEMA_COLUMNS
where State = 1
```

**Comment by marcosqlbi** [comment]
Thanks for catching this! I'll work on a fix soon.

**Comment by dgosbell** [comment]
@marcosqlbi - I just pushed a potential fix for this to the VPA repo which checks the batch size before wrapping the ROW() call with UNION() :)

**Comment by marcosqlbi** [comment]
Great - thanks!

**Comment by denglishbi** [comment]
Yes, the query returned 201 rows:)

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10 release
