### ISSUE TITLE
Problems with specifying a security role while connecting to a Power BI model

### ISSUE THREAD

**Issue by OmriAvissar** [DaxStudio/DaxStudio#22]
I've tried to use DaxStudio in order to connect to a Power BI Model.
The "Roles" option in the "Connect" form in inactive.
![image](https://user-images.githubusercontent.com/33004447/31863776-47a3bb62-b75b-11e7-911b-2e36a31d9492.png)

I can insert a role by: 
1. Choosing the "Tabular Server" Data Source option.
2. Speciping a Role.
3. Connecting to the Power BI model.

![image](https://user-images.githubusercontent.com/33004447/31863783-6a3d9f4e-b75b-11e7-8810-82a0e73859ab.png)

![image](https://user-images.githubusercontent.com/33004447/31863789-82f5ac5c-b75b-11e7-8858-739ade64ed7d.png)

The queries seems to take into account the security role (as does the tables in the Metadata panel), but the traces option is grayed out.

![image](https://user-images.githubusercontent.com/33004447/31863817-cb25cbd8-b75b-11e7-9eb5-9889ec7a0971.png)

If some traces windows were opened beforehand, the following message appears : "You must have Admin rights on the server to enable traces".

![image](https://user-images.githubusercontent.com/33004447/31863852-4f1ad384-b75c-11e7-8f0f-89878714d20c.png)

![image](https://user-images.githubusercontent.com/33004447/31863866-7755b99a-b75c-11e7-87b5-1307b4aee828.png)

**Comment by dgosbell** [comment]
The problem here is that you are an admin user impersonating a non-admin. So it's an unusual situation. It's probably best to test your role in one query window and run your traces in another

**Comment by OmriAvissar** [comment]
I want to view the xmSQL code, and trace info, generated by DAX queries under a security role. The purpose is optimising DAX measures.

Is thare a way in which I can manage this using DaxStudio?

**Comment by marcosqlbi** [comment]
Maybe we should study how to implement this scenario. The problem is that you should use two different processes, but the current implementation of DAX Studio runs the query analysis within the same process (and user) that is receiving profiling events - and that user must be an administrator.

**Comment by otykier** [comment]
I am facing exactly the same scenario at a client. A handful of measures slow down tremendously when RLS is applied, and I really wanted to look at the xmSQL and query plans. Would I need SQL Profiler to capture the information, when executing the queries as a user with RLS, or is there something we can do within DAX Studio in this case?

**Comment by dgosbell** [comment]
You could use profiler to capture the Vertipaq SE End events, but this should now work in the 2.9.2 release. I just did a quick double check against the June PowerBI Desktop and SSAS 2017 and I could activate tracing while connected with Role=... and I could see the role predicate pushed down into the xmSQL. Do you have a scenario where this is not working?

![image](https://user-images.githubusercontent.com/8241830/60544964-406e4a80-9d5d-11e9-9432-815836ff0a3a.png)

**Comment by otykier** [comment]
I just discovered that I'm not using 2.9.2 yet - how embarassing! Thanks, Darren!
