### ISSUE TITLE
exporting PowerBI tables as CSVs produce UTF-8 with BOM (remove the BOM!)

### ISSUE THREAD

**Issue by dan-reznik** [DaxStudio/DaxStudio#222]
When using DaxStudio to export a whole PBI table as a CSV, the exported file is a UTF-8 (good) but with a BOM (not necessary)

The UTF-8 BOM is a sequence of Bytes at the start of a text-stream (EF BB BF) that allows the reader to more reliably guess a file as being encoded in UTF-8. Normally, the BOM is used to signal the endianness of an encoding, but since endianness is irrelevant to UTF-8, the BOM is unnecessary.

**Comment by dgosbell** [comment]
Thanks for pointing this out. It turns out that historically Microsoft chose to include the BOM with UTF8 back in the early 2000's so they left this as the default option so as not to break existing code. I've switched this option off now and the fix will be in the next release
