### ISSUE TITLE
when exporting a PBI table with a weird name the program breaks

### ISSUE THREAD

**Issue by dan-reznik** [DaxStudio/DaxStudio#223]
consider a PBI connection where one of the tables has a name with a slash, e.g., "my table / hello". if you attempt to export this table as a CSV the program simply hangs.

**Comment by dgosbell** [comment]
Thanks for reporting this. I think there are actually 2 issues here. One is that the close button was not enabling correctly after a failure in one of the tables, the other is that I am potentially generating invalid file names if the tables have names with characters that are not valid in file names. I have fixes for both of these issues and this will be included in the next release.

If you are interested in testing a preview build you can download one from our build server [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/27729120/artifacts) there is both an installer and a _new_ portable version. With the portable .zip file you can just download it, unzip it to a folder then double click on DaxStudio.exe.
