### ISSUE TITLE
"OnDragEnter Fired" debug message printing to Output

### ISSUE THREAD

**Issue by verhey** [DaxStudio/DaxStudio#226]
**Description**
When you attempt to drag a file, or text into the DAX Studio window, a "OnDragEnter Fired" message (which appears to be for debugging purposes) prints to the "Output" pane. 

**Repro Steps**
1. Open an existing query and select some of the text
2. With the text selected, click, hold, and drag it around the DAX Studio window
3. Depending on where in the application the text is dragged, a "OnDragEnter Fired" message appears in the output window
4. Repeat step 2-4 with a file, or other item to see the same behavior appear 

**Expected behavior**
When text is dragged around the application, the "Output" window should not contain debug information

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/22968861/66233299-8929fc80-e6da-11e9-80d5-3fd3c2867a69.png)

**Additional context**
Version 2.94

Behavior was originally discovered when trying to drag a `.dax` file into the application to open it in a new tab, which doesn't appear to be implemented, but would be a nice improvement.

**Comment by dgosbell** [comment]
Thanks for reporting this issue. I've removed the debug messages from the code, so this will go out in the next release. I'll have a look at the ability to drop a .dax file as that shouldn't be too hard to add.
