### ISSUE TITLE
Parameter request appears for @ in column names

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#227]
The presence of @ in a column name shows the parameters dialog executing the query, which is not expected

For example this query should not show the parameter dialog box: 

EVALUATE
ADDCOLUMNS ( {"Hello"}, "@test", 42 )

**Comment by dgosbell** [comment]
What version was this issue observed on? I've tested with the current release and the test query above worked fine. We did fix a bug a while ago with @ symbols in strings, but from memory that may have even been one of the 2.8.x releases

![image](https://user-images.githubusercontent.com/8241830/66517934-c6a1e600-eb2f-11e9-8dca-d20ff30a98b9.png)

**Comment by marcosqlbi** [comment]
You're right, I received a report about 2.8.1 and I tested on 2.8.0 - it works on 2.9.4.
Sorry for not testing immediately with the latest version!
