### ISSUE TITLE
A measure's format string is not being honored in results table (v2.7.1)

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#23]
I have a measure with the json properties: 

```
          "formatString": "0.00;(0.00)",
          "annotations": [
            {
              "name": "Format",
              "value": "<Format Format=\"General\"/>"
            }
          ]
````
but am surprised to see values like 45 and -67.8 appearing in result table's column for the measure

**Comment by marcosqlbi** [comment]
Result table in DAX Studio ignores the format string. It is not a priority for this tool. What is your use case for this requirement?

**Comment by dgosbell** [comment]
Actually we do apply formatting :) . We use the format specification that we get from the DISCOVER_CSDL_METADATA call which should be the same method used by Power BI. However with DAX Queries the formatted value is not returned from the server, it's up to the client tools to apply the formatting. You also have to have the identical column name in the results for the formatting to be applied as we don't do any deep parsing to try and figure out if you've aliased a measure using a different name using something like ADDCOLUMNS or SUMMARIZE

How does this measure appear when queried from Power BI Desktop? There seems to be a conflict between the annotation and the formatString settings.

**Comment by jm98** [comment]
Yes the formatting is applied in both PowerBI Desktop and the PowerBI Service when showing data in a table.

The reason that I raised this is just that DaxStudio is my preferred tool for validating models, tuning existing measures and creating new measures prior to deploying them.  I just got thrown by seeing a deployed formatted measure not being displayed as expected where as a column of type Date with the formatting:

```
"formatString": "yyyy-MM-dd",
"annotations": [
            {
              "name": "Format",
              "value": "<Format Format=\"General\"/>"
            }
          ]
```

is displayed correctly

**Comment by jm98** [comment]
> if you've aliased a measure using a different name using something like ADDCOLUMNS or SUMMARIZE

This is the reason that formatting was not applied.  DaxStudio was running an
`EVALUATE SUMMARIZECOLUMNS()`
And for speed I had abbreviated the alias names of the measures

**Comment by marcosqlbi** [comment]
Ops! :) I didn't remember that! :)

**Comment by dgosbell** [comment]
That's good. So just to clarify for anyone else that comes across this behaviour.  if you write:

```EVALUATE ROW( "X", [Sales Amount] )```

we will go looking for the format string for a measure called ```X```. But if you change the query to the one below, so that the output has a column with the same name as the measure the formatting should be applied

```EVALUATE ROW( "Sales Amount", [Sales Amount] )```

I'm pretty sure Power BI uses a similar trick, the difference being that they have 100% control over how the query is constructed.
