### ISSUE TITLE
View Metrics fails with timeout.

### ISSUE THREAD

**Issue by gjc-rbh** [DaxStudio/DaxStudio#231]
When I attempt to view or save metrics against my model (large model with a lot of tables) I keep getting the following;
The XML for Analysis request timed out before it was completed. Timeout value: 30 sec. The XML for Analysis request timed out before it was completed. Timeout value: 30 sec.

The query it runs is sending a 30 second timeout setting and I cannot find a way of overriding this, preferable setting timeout to 0.

**Comment by dgosbell** [comment]
The metrics library is using a slightly different method of connecting and the 30 seconds is a default timeout. I've found where to override this and have submitting the fix for it which we'll include in the next release.

**Comment by marcosqlbi** [comment]
The new NuGet package for VertiPaq Analyzer libraries (1.0.9) includes the fix you made.

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10 release
