### ISSUE TITLE
Azure AS - User field is not populated during trace

### ISSUE THREAD

**Issue by gflores1023** [DaxStudio/DaxStudio#237]
**Describe the bug**
I'm running an All Queries trace on my Azure Analysis Services tabular model. I see the Queries being run on the database but I see blank values for username field.  The users are Azure Active Directory users. When I run a trace using SQL Server profiler, I _do_ see the User under NTUserName. 

**To Reproduce**
1. Connect to Azure AS model.
2. Start AllQueries trace
3. Run any queries on model for trace to capture (using SSMS, Excel, etc)

**Expected behavior**
User field should populate with UserName 

**Screenshots**
DaxStudio
![image](https://user-images.githubusercontent.com/286903/67814623-7f45b000-fa72-11e9-9fbe-9209845a26f0.png)

SQL Server Profiler
![image](https://user-images.githubusercontent.com/286903/67814661-96849d80-fa72-11e9-8c28-3c3d94743d50.png)

Using v2.9.4. Let me know if you need more information.

**Comment by dgosbell** [comment]
Thanks for logging this. I've been able to reproduce this issue and I now have a fix in place which will go out as part of the next release.

**Comment by gflores1023** [comment]
Thank you for the quick turnaround!

**Comment by gflores1023** [comment]
Do you know why sometimes the name appears in parenthesis and sometimes not? See image from first post. This isn't an issue with Dax Studio since the Profiler also has the same behavior. Just wondering for my curiosity.

**Comment by dgosbell** [comment]
No, I don't know why it sometimes adds that extra text.
