### ISSUE TITLE
Vertipaq Analyzer - Two columns with the same title 'Encoding'

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#238]
**Describe the bug**

You may already know this, however, just to be on the safe side … on choosing the Vertipaq Analyzer(View Metrics) the columns tab have 2 columns with the same title: 'Encoding'. I think the last one should be Data type??

**Screenshots**
![image](https://user-images.githubusercontent.com/52240599/68003933-ccdb3c00-fc6f-11e9-9c39-b714ca62f1f7.png)

**Comment by dgosbell** [comment]
Yes, it should be data type. This will be fixed in the next release.
