### ISSUE TITLE
Quering does not work

### ISSUE THREAD

**Issue by paullevchuk** [DaxStudio/DaxStudio#24]
Hi there!

Before I started using DAX Studio 2.7 I could use it in that way.
I started new DAX Query, then switched to another task. Query worked in background and when query was finished results appeared in Output window.

Now when I switch focus from DAX Studio to another app I experience an issue - DAX studio is freezing in some time and then generates errors:
10/24/2017 13:37:20 Error Connecting to server: The server sent an unrecognizable response.
10/24/2017 13:37:20 Cannot access a closed Stream.

Please, fix this.

**Comment by dgosbell** [comment]
What data source are you using - Excel, SSAS or Power BI Desktop ?
Can you reproduce this issue consistently? If so can you hold down the left shift key while starting up DAX Studio (or Excel) as [outlined here](http://daxstudio.org/documentation/troubleshooting/logging-settings/) and then reproduce the issue and upload those logs to this issue?

**Comment by paullevchuk** [comment]
I use XL. Unfortunately I can't reproduce this issue consistently. 
So far DaxStudio is working normally (and that's great). 
It seems that the issue was related to Windows Updates (which I assume replace some .Net libraries).
