### ISSUE TITLE
DaxStudio 2.9.4 and 2.9.5 crash on startup

### ISSUE THREAD

**Issue by WojtekK78** [DaxStudio/DaxStudio#240]
DaxStudio 2.9.4 and 2.9.5 are crashing when launched normally after choosing PBI or cancelling of Data Source on initial screen.

Briefly before that I see there is background screen that previous launch has creashed and report should be send. I've no option to approve sending that error log as immedietly screen is disapperaing and initial DaxStudio screen is loading where I can choose Data Source.

Whenever I'm choosing DataSource PBI (Open file) or Cancel selecting DataSource - this shutdowns DaxStudio with no error message.

Error log generated from 2.9.5:

`2019-11-03 00:02:45.943 +01:00 [Fatal] Class: "EntryPoint" Method: "Main" Error: "String was not recognized as a valid DateTime." Stack: "   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at DaxStudio.UI.Utils.RegistrySettingProvider.Initialize(IGlobalOptions options)
   at DaxStudio.Standalone.EntryPoint.Main()"
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at DaxStudio.UI.Utils.RegistrySettingProvider.Initialize(IGlobalOptions options)
   at DaxStudio.Standalone.EntryPoint.Main()`

Data from Dax Studio Checker:

`    Version =  v2.9.5.200
    DaxStudio.exe Version =  v2.9.5.200

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSVersion       = 10.0.17763
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.75
    FreeMemoryGB    = 9.94

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.03190
    v4\Client\1033 -> 4.7.03190
    v4\Full -> 4.7.03190
    v4\Full\1033 -> 4.7.03190
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 461814

Checking AMO (Local)
=======================
    Attempting to load: c:\Users\wojciech.kusnierek\Downloads\y\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    PASS > Microsoft.AnalysisServices, Version=18.0.9.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Users\wojciech.kusnierek\Downloads\y\bin\Microsoft.AnalysisServices.dll

Checking ADOMD.NET (Local)
=======================
    Attempting to load: c:\Users\wojciech.kusnierek\Downloads\y\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=18.0.9.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Users\wojciech.kusnierek\Downloads\y\bin\Microsoft.AnalysisServices.AdomdClient.dll

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 14
    AMO : 18.0.5.0
    ADOMD : <default>

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
      ERROR: DAX Studio Excel addin registry keys not found!

FATAL ERROR:
Object reference not set to an instance of an object.
   at DaxStudio.CheckerApp.Checker.CheckExcelAddin()
   at DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

`

**Comment by dgosbell** [comment]
@WojtekK78 thanks for letting us know about this. I think I have an idea as to what is causing this. Could you please run the following command from a powershell prompt and paste the output back here?
```
Get-ItemPropertyValue -Path HKCU:\Software\DaxStudio -Name LastVersionCheckUTC
```

**Comment by WojtekK78** [comment]
Result was:
`20/09/2019 08:26:53`

**Comment by dgosbell** [comment]
So it looks like the date has been stored using a dd/MM/yyyy format, but your machine is using MM/dd/yyyy. I don't really know how this would have happened, but the latest build now has 2 fixes. Firstly it captures any errors parsing the date and just assumes a default minimum date. Secondly I am now forcing the date to write out using an ISO standard format so it will not be affected by regional settings on the local machine.

If you want to try this out a new preview build is available on our build server [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28613855/artifacts)

**Comment by WojtekK78** [comment]
I can confirm it works OK on current build. Date fromatting might be result of some Regional formatting changes as I had different locale (US/UK/PL) changed few times during "life" of this windows install and there might be some "leftover" configration not changed.
