### ISSUE TITLE
Excel2016 can't load dax studio

### ISSUE THREAD

**Issue by dqaudithillstone** [DaxStudio/DaxStudio#243]
Excel2016 can't load dax studio。The error message is as follows：
Managed Add-in Loader  Failed to initialize

**Comment by dgosbell** [comment]
That sounds like you might have .Net support switched off which is unusual as that should be on by default in Excel 2016. 

- Try going into "Add or Remove Programs" in Windows. 
- Then find the entry for Office 2016 and click on "modify" 
- then choose "Add or Remove features"
- then expand excel and make sure the following option for ".Net programmability is installed" is enabled
![image](https://user-images.githubusercontent.com/8241830/68355944-01199580-0165-11ea-95f5-1e8f06db5cb9.png)

**Comment by dqaudithillstone** [comment]
According to your suggestion, the same mistake still occurs

**Comment by dgosbell** [comment]
Maybe trying running a repair on Office then. The managed add-in loader is part of Excel, if that's not working it probably means there is a problem with your install of Excel.

**Comment by dgosbell** [comment]
Can I assume that repairing office fixed this issue since you just posted a suggestion about enabling write back to the Excel data model in #246 or were you using a different machine?

**Comment by dqaudithillstone** [comment]
1 uninstall office2016
2 Reinstall office2016 as recommended by dgosbell
3. Reinstall dax studio
4.ok
