### ISSUE TITLE
Parallel SQL requests

### ISSUE THREAD

**Issue by steveharveysyd** [DaxStudio/DaxStudio#244]
**Is your feature request related to a problem? Please describe.**
I am trying to improve the performance of a DAX query that generates many SQL statements

**Describe the solution you'd like**
For DAX Studio to support parallel SQL statements within a configurable limit ... 
Power BI default limit is 10 parallel statements
Adding start and end times in addition to duration to verify which statements are executing in parallel.

**Describe alternatives you've considered**

**Additional context**
The report I am generating contains around 50 measures / queries on a 180 million row dataset.

**Comment by marcosqlbi** [comment]
I assume you are describing a DirectQuery execution made through a DAX query executed within DAX Studio. In that case, what you describe entirely depends on the DAX engine (in either Power BI or Analysis Services) and not on DAX Studio.

**Comment by steveharveysyd** [comment]
Absolutely agree ... I need:
a) For Power BI to process in parallel
b) For Dax Studio to process in parallel
Both are currently processing with Parallel Query Limit = 1
I would like to adjust this figure to optimise performance.

**Comment by dgosbell** [comment]
> b) For Dax Studio to process in parallel
But we are not actually processing anything. We submit the DAX query to the data source (whether that be Power BI desktop or SSAS or Azure AS, etc). It then controls how the DAX is decomposed into SQL and whether or not it runs in parallel or not. 

We could maybe add the start time to the events in Server Timings so that you could see the parallelism. But I'm not sure what value this would provide as there is not really anything you can do from DAX Studio to directly influence the parallelism.

**Comment by dgosbell** [comment]
Actually I've been thinking about this a bit more and it's actually counter productive to try and control the parallelism at the Power BI end. 

Power BI will actually attempt to construct the minimum amount of queries possible (so ideally it will fold the DAX down to a single SQL query if it can). The reason for this is that the relational engine has a lot more information about the storage of the data, the available indexes and the statistics and distribution of the data, so it is in a much better place to implement the most efficient query plan possible. So if you want to tune the performance of a direct query based model you are better off looking at tuning the relational engine side of things (with indexes, partitioning, etc)

**Comment by steveharveysyd** [comment]
Thanks for your prompt responses!
I can add this as a new request but it would be great to add start and end times to server timings.  Optionally displaying it as a gantt chart or being able to export the information to excel to create a gantt chart.
An additional label / tag column to link related queries would also be great as per the following example:

Query						Label
1	Table Top N Filter (SQL)		Table Top N Filter
2	Sales (SQL)				Sales
3	Cost (SQL)				Cost
4	Profit = 					Profit
5		Sales (SQL?) - 			Profit
6		Cost (SQL?)			Profit

I would like to determine if there is 3 or 5 queries and if they are running in parallel or sequentially.

Cheers, Steve

**Comment by steveharveysyd** [comment]
Query                                        Label
1 Table Top N Filter (SQL)         Table Top N Filter
2 Sales (SQL)                             Sales
3 Cost (SQL)                              Cost
4 Profit =                                   Profit
5 Sales (SQL?) -                          Profit
6 Cost (SQL?)                             Profit

**Comment by steveharveysyd** [comment]
![image](https://user-images.githubusercontent.com/8425518/68721959-2b0d0500-0608-11ea-974b-37ce33e688c7.png)

**Comment by dgosbell** [comment]
>I would like to determine if there is 3 or 5 queries and if they are running in parallel or sequentially.

So as you probably know the current query timing window will show you exactly what SQL queries are being fired and how long they take to execute, but not if they are parallel or sequential. 

I suggest that you try running SQL Profiler and capture the query begin and end events and the Direct Query Begin and End events (if you go into the Advanced options in DAX Studio you can turn on a preview feature to enable a button to launch SQL Profiler against the current connection). Then you can capture the begin and end times and see if they provide any actionable insights.

My concern is that even if you find that the queries are sequential, that there is no way of forcing the engine to run more in parallel, so this information will not add any value. But I suppose the first step is to figure out if the lack of parallelism is an issue. If it does turn out to be an issue *and* there are some settings that can be changed to impact this then I'm more than happy to look at adding this extra information into the timings trace. 

In the mean time I've also just emailed some contacts I know on the dev team at Microsoft to double check that my understandings are correct. I'll reply back here with their response.

**Comment by steveharveysyd** [comment]
You are absolutely correct, there is no way of forcing the queries to process in parallel.  Under File > Options and Settings > Options > Current File > Direct Query, you can set "Maximum connections per data source" to 1, 10 or 100 ... default is 10.  I thought it would equate to the "Maximum number of parallel queries".  However, it has no impact on performance and is effectively stuck at 1!
I have raised an issue on the PBI community site and I guess Microsoft will fix it in a future release hopefully.
As you can see from the image below, there are 42 queries that take 43 seconds to process sequentially.  If they processed in parallel (x10) they would process in 4-5 seconds...
Happy to phone you to clarify.  I would be interested in what MS dev team has to say... 
Not sure what time zone you are in ... Sydney here steveharveysyd@outlook.com
![image](https://user-images.githubusercontent.com/8425518/68811363-91eff400-06c4-11ea-9761-1f8dd444c6da.png)

**Comment by dgosbell** [comment]
> Under File > Options and Settings > Options > Current File > Direct Query, you can set "Maximum connections per data source" to 1, 10 or 100 ... default is 10. I thought it would equate to the "Maximum number of parallel queries". However, it has no impact on performance and is effectively stuck at 1!

Yes, that actually controls the number of concurrent queries that can run. So you could have 10 users simultaneously run queries, but the 11th would get queued until one of the other queries finishes.

> I would be interested in what MS dev team has to say...

The Microsoft dev team was completely aware of this situation and said it was one area they might investigate more in the future, but it's not currently on their short term roadmap. 

And these things are always a trade off. Increasing the parallelism for a single query will reduce the number of concurrent queries that can be run. And it's very rare that database queries can be perfectly parallelised. The best case scenario would be that all 42 queries run in parallel and don't take any additional time so the result is returned in 1.4 seconds. The worst case is that the additional parallelism causes overhead and cache thrashing that actually slows down all the queries and they take longer than running them sequentially. I think in most scenarios the actual performance will be somewhere in between these 2 extremes. 

Until Microsoft gives us a setting to enable/control the parallelism I don't think it's worth altering anything in DAX Studio. But when/if they do enable something like this I definitely think it would be worth adding a gantt style view or something similar.
