### ISSUE TITLE
VertiPac Analyser (Preview) - Nothing happens when I click on it

### ISSUE THREAD

**Issue by jainn4** [DaxStudio/DaxStudio#248]
We use "Virtualised  application (APPV)" to deploy DAX studio to all our users. Currently when I click on "View Metrics", nothing happens. If there is any log I can send you, please let me know

**Comment by dgosbell** [comment]
This looks like a duplicate of issue #235 have you read through the responses there?

**Comment by jainn4** [comment]
> This looks like a duplicate of issue #235 have you read through the responses there?

It's possible it is linked to the same issue. I will try to use 2.9.5 to see if it works. 

Thanks
