### ISSUE TITLE
unable to view advanced tab in dax studio

### ISSUE THREAD

**Issue by gkgk01** [DaxStudio/DaxStudio#249]
**Describe the bug**
unable to view advanced tab in dax studio

**To Reproduce**
1. Open Dax studio
2. Open PBI file
3. Connect pbi file
4. Connected but unable to see advanced tab in dax studio

**Expected behavior**
unable to view advanced tab in dax studio

**Screenshots**
![image](https://user-images.githubusercontent.com/57851713/69002486-7430c200-0944-11ea-8ac0-924608f0530c.png)

**Additional context**

**Comment by dgosbell** [comment]
The advanced ribbon tab currently only appears when you go into File > Options and turn on one of the preview features under the Advanced options

**Comment by gkgk01** [comment]
Thanks!

**Comment by gkgk01** [comment]
I'm trying to view metrics, it shows ready but vertipac tab doesn't open...can you please tell the issue?

**Comment by dgosbell** [comment]
This is most likely related to issue #235 which appears to be related to the specific model you are trying to analyze. There is a link on that issue to a download for a preview build of the next release.

**Comment by gkgk01** [comment]
Thanks, you are right. Preview version works fine for my model.
