### ISSUE TITLE
KES 10 found Trojan Win32.Bazon.a in "daxstudio_2_7_1_setup.exe"

### ISSUE THREAD

**Issue by RomanRonam** [DaxStudio/DaxStudio#25]
Hi there!

When system administrator in my company was trying to install version 2.7.1 for me, Kaspersky Endpoint Security 10 found this:
![trojan](https://user-images.githubusercontent.com/33114836/32039245-041737b0-ba36-11e7-90dd-1cd963f5a025.png)

Downloaded from here: https://github.com/DaxStudio/DaxStudio/releases/download/v2.7.1/DaxStudio_2_7_1_setup.exe

Is there really Trojan?

**Comment by dgosbell** [comment]
We don't believe so. We had someone else report a false positive from Kaspersky for v2.7.1 [here](https://github.com/DaxStudio/DaxStudio/issues/20) but as linked in that post, we ran the installer through virustotal.com and 60 odd other anti-virus engines reported it as being clean.
