### ISSUE TITLE
Export to TXT menu ICON Disappeared 

### ISSUE THREAD

**Issue by shawne004** [DaxStudio/DaxStudio#250]
**Describe the bug**
Option to export as TXT gone from the menu. Cannot cue an export, I am in the current version. 

**To Reproduce**
Try to export as text.....

**Expected behavior**
Expect see the icon and be able to select to export to TXT
![image](https://user-images.githubusercontent.com/42221402/69014869-a0583d00-095c-11ea-8da3-a3dfc509437a.png)

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
What is the exact version number you are running? I can't see because the version number is cut off in your screen shot, but it looks like it might be an old 2.7 series release from a couple of years ago. Please try downloading and installing the current release.

**Comment by shawne004** [comment]
I took a screen shot from a remote system which has the old version installed.  But the behavior is the same on my machine with an updated install of 2.9.4

**Comment by shawne004** [comment]
![image](https://user-images.githubusercontent.com/42221402/69054396-76912b80-09d9-11ea-9e33-73f2d85efe99.png)

**Comment by shawne004** [comment]
Also tried back installing.......same issue.  Please advise, I have a large table extract that a process is dependent on!

**Comment by shawne004** [comment]
Ok....., I found out why that was gone.......the controls are now under the advanced tab.   Tested and working.  Apologies for overlooking. 

![image](https://user-images.githubusercontent.com/42221402/69060400-48b1e400-09e5-11ea-85f3-a20b2b4e4cbb.png)

**Comment by shawne004** [comment]
![image](https://user-images.githubusercontent.com/42221402/69060410-4ea7c500-09e5-11ea-82be-295272f868b1.png)

**Comment by dgosbell** [comment]
No, that is something different. The new "Export Data" option is an additional feature. It does not replace the ability to send the results of an ad-hoc query to a file. But we don't have any code which dynamically shows and hides the File output target, it's effectively hard coded to be always available (same as the Grid and Timer targets). Can you try starting up DAX Studio with Debug Logging switched on using the [following process](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then shutdown DAX Studio and upload the resulting log file to this issue?

**Comment by shawne004** [comment]
had to use Dax Studio Checker - I could not locate the AppData folder on my system.

Let me know if this works: 

    Version =  v0.0.0.0

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSVersion       = 10.0.17763
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.84
    FreeMemoryGB    = 6.73

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.03190
    v4\Client\1033 -> 4.7.03190
    v4\Full -> 4.7.03190
    v4\Full\1033 -> 4.7.03190
    v4.0\Client -> 4.0.0.0

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    PASS > Microsoft.AnalysisServices, Version=18.0.5.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=18.0.5.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll

Checking AMO (GAC)
=======================
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET (GAC)
=======================
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 14
    AMO : 18.0.5.0
    ADOMD : <default>

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.9.4.133, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

**Comment by dgosbell** [comment]
No, DAX Studio checker is really only useful in situations where the app will not start up at all (which we don't see much anymore). If you go into Help - About there is a link on the About screen which will open the log folder.

**Comment by shawne004** [comment]
When I click that link it doesnt do anything.  Tried that first.

**Comment by dgosbell** [comment]
hmm, that works fine on my machine - that should point to a standard location that is part of your user profile. You should also just be able to paste ```%APPDATA%``` into the address bar in Windows Explorer and hit the enter key.
![image](https://user-images.githubusercontent.com/8241830/69099054-f5f02f00-0aad-11ea-9dcd-45ada62c8b95.png)
This should navigate you to ```c:\users\<username>\appdata\roaming``` (although it is possible for IT departments to re-direct this folder which is why we use the special %APPDATA% variable)
And you should find a DaxStudio folder there with a Logs folder under that.

**Comment by shawne004** [comment]
When I use the %APPDATA% in the file finder this is all i get in return ....no log folder: 

![image](https://user-images.githubusercontent.com/42221402/69099828-bbdd4980-0a29-11ea-9baf-10c67d0c1cd5.png)

**Comment by shawne004** [comment]
I am on windows 10 v1809

**Comment by dgosbell** [comment]
That would explain why the link in Help > About does not work. 

The only other time I've seen this issue was when the DaxStudio.exe.config file had been edited to point to another location. Can you check the [instructions for changing the logging manually](https://daxstudio.org/documentation/troubleshooting/logging-settings/) and maybe try doing that and pointing the logs to somewhere like  ```c:\temp```?

**Comment by shawne004** [comment]
[Default.zip](https://github.com/DaxStudio/DaxStudio/files/3861332/Default.zip)

**Comment by dgosbell** [comment]
No sorry, I'm talking about the section that talks about "Manually Enabling Diagnostic Logging" which I've copied out below:

### Manually Enabling Diagnostic Logging
You can manually enable detailed application logging by enabling serilog in the daxstudio.exe.config file.

The start of the daxstudio.exe.config file looks like the following:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
  <appSettings>
    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:write-to:RollingFile.pathFormat" value="D:\temp\DaxStudio-{Date}.txt" />
    <add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="10" />
  </appSettings>
  -->
  <runtime>
  .....
```
To capture a detailed application log perform the following steps:

1. remove the ```<!--``` comment start from before the ```<appSettings>``` tag and the ```-->``` comment end tag from after the ```</appSettings>``` tag
2. change the value for the pathFormat section to point to a folder on your system
3. repeat the steps that trigger the error
4. add the ```<!--``` start and end ```-->``` comment tags back to switch off the logging

**Comment by shawne004** [comment]
![image](https://user-images.githubusercontent.com/42221402/69108043-775da800-0a41-11ea-88c4-3baa1f1aa9d2.png)

Not sure I can be of much help here.  I do want to see this resolved but after all of this it seems we are still were we started.  I am not much of a coder, do you have anyother way I can get you needed info?  Would you want to set up a live session?  
.

**Comment by dgosbell** [comment]
Do you have admin access to your PC? (ie. were you the one who installed DAX Studio?)

If so you could save the ```DaxStudio.exe.config``` file to somewhere like ```c:\temp``` and then copy it back to ```c:\program files\Dax Studio``` (at this point you should get prompted to provide admin approval for the copy)

**Comment by shawne004** [comment]
I do.  I took your steps above, made the edit, replaced the exe and ran DaxStudio.  Still no log.  Also, just noticed that the run and clear cache control is blank as well.....

![image](https://user-images.githubusercontent.com/42221402/69108937-2c915f80-0a44-11ea-9e52-ecb3940112c5.png)
![image](https://user-images.githubusercontent.com/42221402/69108957-361ac780-0a44-11ea-8d2e-b6f7f5972958.png)

**Comment by dgosbell** [comment]
You could maybe try the 2.11.0 installer. I don't really have any other ideas about this as I'm not able to reproduce it

**Comment by dgosbell** [comment]
Can you check if this still happens with the 2.14 release?

**Comment by dgosbell** [comment]
Closing due to lack of response
