### ISSUE TITLE
Crashing error String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by periscope2019** [DaxStudio/DaxStudio#251]
I downloaded dax studio today - before I realized my computer was formatted to a different time zone. It was working fine. Then I changed my regional settings date/time and now dax keeps crashing when I try to open it with the error: String was not recognized as a valid DateTime. I've tried uninstalling and reinstalling but I keep having the same issue. PLEASE HELP!!

**Comment by dgosbell** [comment]
This has been reported before in #240 and will be fixed in the next release. There is a link to a download of a preview build for the next release in that issue which has the fix. Or if you open regedit you can deleted the LastVersionCheckUTC under HKEY_CURRENT_USER\Software\DaxStudio

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10.0 release
