### ISSUE TITLE
Dedicated Measure Table Export Error

### ISSUE THREAD

**Issue by minnydawg** [DaxStudio/DaxStudio#254]
I have a dedicated (stand alone) measure table in my Power BI model.  When I run MDSCHEMA_MEASURES on that measure table it appears correctly in grid.  When I try and export those results to Excel, CSV, or SQL Table I get "Error Check Output Pane".  The application freezes and I have to Ctrl=>Alt=>Delete out to exit.  If the measure is inside an existing table, it works.  It's only with the "dedicated" measure table do I have this problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/58049423/69371460-79a04c00-0c65-11ea-9084-1ec69ec965cd.png)

**Comment by dgosbell** [comment]
What version of DAX Studio are you running? We had some issues with the export wizard freezing in prior versions but these were fixed in 2.9.4. And note that the Export Data Wizard only exports columns, not measures. This is because we are exporting row level detail and measures are aggregate functions. So it probably does not make any sense to export a measures table as there won't be any meaningful rows of data in there (but the app still should not crash) 

If you are running 2.9.4 is it possible to upload a pbix file with some dummy tables that includes a similar measures table that triggers this crash?

**Comment by minnydawg** [comment]
I am running 2.9.4.  The "original" pbix contained all these tables:

[image: 2019-11-22 10_48_51-Azure Consumption Insights EXAMPLE - Power BI
Desktop.png]

It's company data, so I didn't want to violate any data privacy rules, so
I deleted all those tables and just left the MeasureTable in the attached
pbix so you can see the issue.
I was asked to document my measures, which is how I found DAX Studio in the
first place.
I ran  select * from $SYSTEM.MDSCHEMA_MEASURES  in DMV and the grid shows
me exactly what I want to see.

Now I export to .csv
[image: image.png]

and I get the same error that I see in my original pbix file.
[image: image.png]

**Comment by minnydawg** [comment]
Forgot the example pbix file....

**Comment by dgosbell** [comment]
I think you need to visit the github site to upload a file. If you use the email reply option it strips out attachments.

**Comment by dgosbell** [comment]
Oh and images don't come through in email replies either...

> It's company data, so I didn't want to violate any data privacy rules, so
I deleted all those tables and just left the MeasureTable in the attached
pbix so you can see the issue.

That's fine, I don't think I need any data for this. I think it's probably a structure issue.

> I was asked to document my measures, which is how I found DAX Studio in the
first place.
I ran  select * from $SYSTEM.MDSCHEMA_MEASURES  in DMV and the grid shows
me exactly what I want to see.


So Export Data won't document any measures unless you created the MeasuresTable as a calculated table from the MDSCHEMA_MEASURES somehow.

If you just want the output of an MDSCHEMA_MEASURES query you can selected all and copy the data out of the results grid or you can change the output to a file and export that data to a CSV which you could import into Excel and then format nicely.

Another option for documenting your model would be to run the Vertipaq Analyzer tool from SQLBI [https://www.sqlbi.com/tools/vertipaq-analyzer/]((https://www.sqlbi.com/tools/vertipaq-analyzer/)
