### ISSUE TITLE
Error exporting measures

### ISSUE THREAD

**Issue by PauBsAs** [DaxStudio/DaxStudio#256]
Hi,

Trying to use the new feature to export semantic data model, I have this error because of the "no columns" tables I use to contain my measures.

Thanks!
Paula

![Captura](https://user-images.githubusercontent.com/58194553/69586362-214caf80-0fc1-11ea-9bb4-78709e3bf748.PNG)

**Comment by dgosbell** [comment]
So I think we fixed this issue as part of  the fixes for #235 so the next version should handle models with these sorts of tables. If you are interested in testing a preview build of the next release you can try the latest build [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/29090285/artifacts)

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10 release
