### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#26]
These documentation URLs are not working, but I don't understand why (it seems they exists in documentation folder):
http://daxstudio.org/documentation/features/query-editor/
http://daxstudio.org/documentation/features/output-panes/
http://daxstudio.org/documentation/features/statusbar/

**Comment by dgosbell** [comment]
The github pages engine only builds output for md files that have "front-matter" which usually looks something like the following at the top of the file:
```
---
title: My Page Title
---
```
those 3 pages were missing the front-matter settings, so I fixed that.

**Comment by marcosqlbi** [comment]
There are other pages not working:
http://daxstudio.org/documentation/features/ribbon-control/Find_Replace
http://daxstudio.org/documentation/features/ribbon-control/Find_Replace
http://daxstudio.org/documentation/features/ribbon-control/connection-dialog

Is there a way we can automate the control?

**Comment by dgosbell** [comment]
that second lot of links are mistakes I made when converting the markdown from codeplex to github. I fix those and a few more which I found using brokenlinkchecker.com :)
