### ISSUE TITLE
New file opens two query windows

### ISSUE THREAD

**Issue by hernandemczuk** [DaxStudio/DaxStudio#261]
**Describe the bug**
When clicking on "File/New", 2 query windows are opened.

**To Reproduce**
1. Go to 'File'
2. Click on 'New'
3. 2 query windows are opened

**Expected behavior**
One query window should be opened.

**Additional context**
DaxStudio - 2.9.4

**Comment by dgosbell** [comment]
Thanks for logging this. We've had someone submit a fix for this #241 already - this fix will be part of the next release which will be released soon.

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10 release
