### ISSUE TITLE
Connecting to dataset (model) in PBI Premium workspace

### ISSUE THREAD

**Issue by sivajan** [DaxStudio/DaxStudio#264]
I am getting a connection error when trying to connect to a Power BI model (dataset) in a Premium capacity workspace. Steps as follows: 

1) Power BI Service: 

1. Go to Premium capacity workspace
2. Click on Datasets 
3. Click on "schedule refresh" of the dataset I want to connect to
4. Click on "Server settings" and click "Copy" under Connection String. 

2) DAX Studio: 

1. Open DAX Studio
2. Paste copied Connection String into "Tabular Server" data source 
3. Authentication menu opens up (I click on the ID that's logged into Windows, which is the same as the Power BI Service where this model is deployed). 
4. Encounter connection error 

![image](https://user-images.githubusercontent.com/5615039/70870646-d42a8080-1f63-11ea-91d4-eec1c906c9e2.png)

**Comment by dgosbell** [comment]
What version of DAX Studio are you using?

**Comment by sivajan** [comment]
> What version of DAX Studio are you using?

2.9.4

**Comment by dgosbell** [comment]
hmm, 2.9.4 works fine against my Premium workspaces.

Can you check in the Power BI Admin portal that both the following settings are enabled (as listed under the Security Requirements on [this blog post](https://powerbi.microsoft.com/en-us/blog/power-bi-open-platform-connectivity-with-xmla-endpoints-public-preview/) ):

- The tenant-level Analyze in Excel setting in the Power BI Admin Portal must be enabled for the current user.
- The new capacity-level setting for XMLA endpoints must be enabled by setting the value to 1 for read only.

**Comment by sivajan** [comment]
- The tenant-level Analyze in Excel setting is on (I can connect to that model from PBI Desktop). 

- Yes - this is also set to 1. 
![image](https://user-images.githubusercontent.com/5615039/70871235-e0fea280-1f6a-11ea-984f-a50466bcbcb3.png)

**Comment by dgosbell** [comment]
actually this does not sound right:

> Go to Premium capacity workspace
Click on Datasets
Click on "schedule refresh" of the dataset I want to connect to
Click on "Server settings" and click "Copy" under Connection String.

It should be more like:

In Power BI, in **Edit Workspace** (under the "..." menu) , in the **Advance** section, in **Workspace Connection**, click **Copy**.

This should give you a connection string that looks like:
```powerbi://api.powerbi.com/v1.0/myorg/[workspace name]```

If your connection string does not start with ```powerbi://``` it's not a valid xmla endpoint connection

**Comment by sivajan** [comment]
That gives me the same error (see screenshot). The connection string based on my steps looks like this: 

powerbi://api.powerbi.com/v1.0/myorg/[workspace name];initial catalog=[dataset name]

![image](https://user-images.githubusercontent.com/5615039/70871563-3b4d3280-1f6e-11ea-9e04-3f54c9755375.png)

**Comment by dgosbell** [comment]
I just double checked and I can connect fine to my test workspaces both with and without the ```initial catalog``` setting.

There are a number of features that are not supported by the XMLA endpoint. Do the datasets you are trying to connect to contain any of features listed at the [following docs page](https://docs.microsoft.com/en-au/power-bi/service-premium-connect-tools#unsupported-datasets)?

**Comment by sivajan** [comment]
No, it does not contain any of those unsupported dataset. It only has data from a single source, an Azure SQL DW.

**Comment by dgosbell** [comment]
Establishing the connection (including the authentication) is a single line call on our side and is all handled by the Microsoft AODMD library.

Have you tried connecting with SSMS (SQL Server Management Studio) to see if that works?

**Comment by sivajan** [comment]
I cannot connect from SSMS either. I will try to fix this first. 😊

![image](https://user-images.githubusercontent.com/5615039/70921159-c3c0e700-1ff1-11ea-95a9-c5ec47d8b391.png)

**Comment by dgosbell** [comment]
OK, so it sounds like this is not a DAX Studio specific issue. If you can't spot anything obvious I think you can raise a defect here [https://powerbi.microsoft.com/en-us/support/](https://powerbi.microsoft.com/en-us/support/). Since this feature is still in preview Microsoft are keen to hear about any issues like this.

**Comment by dgosbell** [comment]
I'm going to close this issue as it appears to be something on the powerbi side, not a DAX Studio problem. If you have further issues feel free to re-open this or raise a new issue.
