### ISSUE TITLE
Tracing Timeout Exceeded when running Server Timings

### ISSUE THREAD

**Issue by jburns7744** [DaxStudio/DaxStudio#265]
When connecting to new tabular model (compatibility 1500, built through Tabular Editor, hosted on Azure Analysis Services, pretty small (for my personal testing)), whenever I run Server Timings, the results (xmSQL queries) will show for about 8 seconds after the query is done.  Then, they disappear completely.  I have no idea why this could be.  Important to note - I do NOT get this error when working against a large production cube that is 1400 compatibility, also hosted on Azure Analysis Services.

To Reproduce:
1.  Connect to a 1500 compatibility Tabular Cube hosted on Azure
2.  Run a query with Server Timings (after clearing cache)
3.  Look for the Server Timing results - they might disappear

When all is said and done though - what a great product DAX Studio is!  Use it 6+ hours a day.

**Comment by dgosbell** [comment]
So do you get an actual Timeout Exceeded warning message when the results disappear? We don't do anything different in the timing for the different compatibility modes and I can't see any obvious difference in the server output.  I have seen  this happen once before, but I don't have a stable way of reproducing this which makes it harder to figure out what's happening

**Comment by jburns7744** [comment]
Hi Darren,

I do get the actual Timeout Exceeding warning.  I have tried bumping the thresholds in the Options to 30+ seconds to no avail.  Another interesting fact is that it SOMETIMES works fine.  The days prior to 12/19, it was not working.  12/19, it was working spottily (the server timing results were sticking most of the time).  Today, it's not working again!  

Understand if it's tough to replicate and solve.  I'll let you know if I have any other information - maybe I will try to scale back to 1400 compatibility and see if that will fix it.

Thank you sir!

**Comment by dgosbell** [comment]
If you are still seeing this issue can you test with the 2.14 release. I did some work on improving the Server Timings in this release. Note that I have been seeing some long trace startup times on AzureAS and sometimes have to increase the timeout setting in the Options up to 90 or 120 seconds

**Comment by jburns7744** [comment]
Really helpful to know... Thank you Darren...

Jake


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dgosbell** [comment]
Are you able to double check this issue again. Microsoft has push some improvements to both Azure Analysis Services and the Power BI XMLA endpoint and I'm seeing traces start in 5-6 seconds or less now.

**Comment by dgosbell** [comment]
I believe this is no longer and issue
