### ISSUE TITLE
Error Connecting: The given path's format is not supported

### ISSUE THREAD

**Issue by mywebcakes** [DaxStudio/DaxStudio#267]
**Describe the bug**
I am just starting with DAX studio. First, I managed to successfully connect to PowerPivot
models in Excel, but then started getting this error: 
"Error Connecting: The given path's format is not supported"
First I got it just for one excel workbook, but now I receive this error for all excel workbooks I try to connect to

**Comment by mywebcakes** [comment]
I managed to resolve the issue but don't understand what happened....

My excel files are on OneDrive 
     C:\Users\....\OneDrive\Documenten\Learn\DAX\
     connecting to a file on this location produces the error

I then copied one of the files to a local folder (which is actually a folder on my Mac - I'm running Win10 in via Parallels)
      \\Mac\Home\Documents\Temp
     with the file placed there, I managed to connect.

If I then tried to connect again to the file on OneDrive (C:\users\....), and now it works.

Strange

**Comment by dgosbell** [comment]
When we connect to a PowerPivot model we need to pass in the absolute path to the file. It appears that something has changed in OneDrive at some point and Excel now reports the path as being the http:// address to the file one OneDrive, not the local path. I'm not sure if how to fix this at the moment, I'll need to do some investigating.

In the mean time temporarily copying the file to a local path is probably the best temporary work around.

**Comment by mywebcakes** [comment]
I noticed the following:
- when opening the excel file via explorer, I can successfully connect to DAX Studio
- when opening the excel file via the recent files menu in excel or the taskbar, I get the connection error.

**Comment by mywebcakes** [comment]
(oops, I did not meant to close)

**Comment by dgosbell** [comment]
v2.11.0 has just been released which should resolve this issue. There should no longer be any issues connecting to Excel files stored on OneDrive
