### ISSUE TITLE
No advanced tab on my ribbon

### ISSUE THREAD

**Issue by nadavsnear** [DaxStudio/DaxStudio#269]
Hi 
I there supposed to be an advanced tab in the top ribbon of the DAX studio. 
I downloaded the latest version 2.10.1 but I don't have it. 
any help will be highly appreciated

**Comment by marcosqlbi** [comment]
You should enable the button in the options as described here> https://www.sqlbi.com/blog/marco/2019/09/15/vertipaq-analyzer-2-0-preview-1/

**Comment by nadavsnear** [comment]
Thanks, It helped.
