### ISSUE TITLE
Cannot connect to Azure Analysis Service

### ISSUE THREAD

**Issue by rapout83** [DaxStudio/DaxStudio#27]
Hi,

I saw an exactly same issue reported below, but could not find a proper solution there.
I tried whatever that was recommended in the report, but they didn't help me.

When I'm trying to connect to Analysis Service, it pops me an error as below.
![image](https://user-images.githubusercontent.com/28618571/32425012-06a16c18-c2eb-11e7-9895-79ea0437b77a.png)
![image](https://user-images.githubusercontent.com/28618571/32425016-17078a38-c2eb-11e7-86c5-796c6cfefd79.png)

According to the log, it tells me the input string was not in a correct format.

`2017-11-06 11:47:01.639 +08:00 [Error] "ConnectionDialogViewModel" "Connect" Error Connecting using: "Data Source=asazure://northeurope.asazure.windows.net/dbname;MDX Compatibility=3;;;Application Name=DAX Studio (SSAS) - 488f5715-1f73-4097-b637-487ecd19d976"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: The connection string is not valid. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.GetInstancePort(ConnectionInfo connectionInfo)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.ConnectionDialogViewModel.Connect()
`

Please tell me if i'm doing anything wrong.

**Comment by dgosbell** [comment]
So one possible reason for this error is that DAX Studio is using an older version of the Microsoft ADOMD library (that is not Azure aware). You need to be using the v14 libraries - these should be the ones that get installed when you choose the optional Azure AS support option in the installer.

Can you run the [DAX Studio Checker](http://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) program and paste the output back to this issue. That should tell us if you have the v14 providers installed and whether the DAX Studio config is set to use them.

**Comment by rapout83** [comment]
Thanks for the prompt reply.
Here's the result. from DAX Studio Check.

`Checking Operating System
=======================
OSCaption       = Microsoft Windows 10 Pro
OSVersion       = 10.0.16299
OSArchitecture  = 64-bit
VisibleMemoryGB = 15.83
FreeMemoryGB    = 7.38

Culture Name              = en-US
Culture DisplayName       = English (United States)
Culture EnglishName       = English (United States)
Culture 2-Letter ISO Name = en
Culture DecimalSeparator  = .
Culture GroupSeparator    = ,
Culture CurrencySymbol    = $
Culture ShortDatePattern  = M/d/yyyy
Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.4927
v2.0.50727\1033 -> 2.0.50727.4927
v2.0.50727\1042 -> 2.0.50727.4927
v3.0 -> 3.0.30729.4926
v3.0\Setup -> 3.0.30729.4926
v3.0\Setup\1033 -> 3.0.30729.4926
v3.0\Setup\1042 -> 3.0.30729.8795
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
v3.5 -> 3.5.30729.4926
v3.5\1033 -> 3.5.30729.4926
v3.5\1042 -> 3.5.30729.5003
v4\Client -> 4.7.02556
v4\Client\1033 -> 4.7.02556
v4\Client\1042 -> 4.7.02556
v4\Full -> 4.7.02556
v4\Full\1033 -> 4.7.02556
v4\Full\1042 -> 4.7.02556
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
Processing DaxStudio.exe.config file...
Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
Bindings Found: 9
AMO : 13.0.0.0
ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
Detected Excel Version: 16 - Excel_v16
Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
Excel Architecture: x64

DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2016 Disabled Add-ins
  PASS > No Disabled items found.

Attempting to load Excel Add-in: 
  PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.1.99, Culture=neutral, PublicKeyToken=null

Checking VSTO Configuration
Architecture: x64
  v4
    Version 10.0.60301
    Install 1
    InstallerPath C:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
  v4M
    VSTOMFeature_UNM 1
    VSTOMFeature_CLR35 1
    VSTOMFeature_CLR40 1

`

**Comment by dgosbell** [comment]
Yep, that's the issue. While you have both the v13 and v14 providers installed the DAX Studio config entries to tell it to use the v14 providers are not present. The installer should add these when you choose the Azure Analysis Services install option, but you can just copy the attached file into your ```c:\program files\dax studio``` folder and remove the ```.txt``` extension so that it's just called ```daxstudio.exe.config``` (you'll have to delete the existing config file or rename it to something else first)
[DaxStudio.exe.config.txt](https://github.com/DaxStudio/DaxStudio/files/1445631/DaxStudio.exe.config.txt)

**Comment by rapout83** [comment]
This worked perfectly!! Thanks a lot for your help!!!

**Comment by dgosbell** [comment]
Cool, I'm glad that you are up and running :) Microsoft is working on a different method for distributing these providers, so hopefully in an upcoming release we can remove the need for the installer to try and insert the correct bindings into the config file.
