### ISSUE TITLE
Useful to indicate (Administrator)/Login if running as Admin/different user

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#270]
**Is your feature request related to a problem? Please describe.**
Our live servers don't allow us access to servers with standard accounts. We have to use an admin accounts if we want to use Metrics etc. This means that we often have 2 Daxstudio's running and it would be useful to distinguish between the two

**Describe the solution you'd like**
An indicator in title bar to show which user/administrator the current Dax Studio is running as

**Describe alternatives you've considered**
- ability to impersonate for each connection. Probably more complex than the suggestion.

**Additional context**
NA

**Comment by dgosbell** [comment]
This should be pretty easy to add, I'll have a look at including an option in the next release to display this info in the title bar

**Comment by dgosbell** [comment]
This has just been added as an option you can enable under File -> Options in v2.10.2
