### ISSUE TITLE
Power Query Studio...please

### ISSUE THREAD

**Issue by gfane1** [DaxStudio/DaxStudio#271]
Marco and Darren now you guys have nailed DAX how about some hooks and a Power Query M editor aka ‘Power Query Studio’. Of course I realise this is more of an entire product than a feature/epic but if anyone could get that going its you guys. Maybe with a little help from Redmond to hook and call out to the editor Power Query assemblies.

**Comment by dgosbell** [comment]
Sorry, but this is not currently possible. Microsoft does not provide any public hooks for third party tools to hook into PowerQuery.
