### ISSUE TITLE
Vertipaq Tab does not appear when I select View Metrics analyzing my PBIX File

### ISSUE THREAD

**Issue by gspmbrown** [DaxStudio/DaxStudio#272]
![image](https://user-images.githubusercontent.com/59618903/71916559-32561800-314c-11ea-995a-6ca7d8e9f75c.png)

**Comment by marcosqlbi** [comment]
It seems we have a bug when a table name contains a single quote character. Thanks for reporting it! You can temporarily workaround by renaming the table "Returns_RTM's Prev Week" to "Returns_RTMs Prev Week"

**Comment by gspmbrown** [comment]
WOW...Thanks for the quick response!

Thanks,

Mike
