### ISSUE TITLE
Can't connect to PowerPivot workbook using addin for Excel 2010

### ISSUE THREAD

**Issue by Osophoso** [DaxStudio/DaxStudio#273]
DaxStudio is not able to connect to the PowerPivot model in Excel 2010.

I have tried version 2.9.4 then 2.10.1.233 and finally even rolled back to 2.9.2 but none will work.

When I open the addin I get with 2.9.2 and 2.10.1.233
![image](https://user-images.githubusercontent.com/37143507/71986040-a57e8d80-3223-11ea-9489-38a47025513f.png)

Using 2.9.4 I would get a slightly different error relating to "system.Threading.Tasks.Task" (sorry, didn't take a screenshot at the time).

Attached is the log from efforts using 2.10.1.233.
[DaxStudio-20200108.log](https://github.com/DaxStudio/DaxStudio/files/4035730/DaxStudio-20200108.log)

PowerPivot Version: 11.0.3
Excel: 14.0.7237.5000 (32-bit)

**Comment by dgosbell** [comment]
I've never actually seen anyone hit this error before so I don't know what is going on here. But there is a bug in the error logging that is not trapping the actual error. I'll fix this in the next release, then you'll need to try again so we can get the actual error.

**Comment by dgosbell** [comment]
I've just released v2.10.2 which fixes the issue with the Excel diagnostic logging. Can you try starting up Excel with the SHIFT key held down (using the instructions here [https://daxstudio.org/documentation/troubleshooting/logging-settings/](https://daxstudio.org/documentation/troubleshooting/logging-settings/) ) and then post the log file from the Excel addin?

**Comment by dgosbell** [comment]
I think this might be the same as issue #291 there is a link on that thread to a new preview built if you want to try that and see if this works with Excel 2010.

**Comment by dgosbell** [comment]
This is possibly fixed in v2.11.0 can you please try that and let me know?

**Comment by Osophoso** [comment]
Hello ,

Will give it a go and let you know!

Thank you for remembering !

Opale

**Comment by dgosbell** [comment]
closing due to lack of response
