### ISSUE TITLE
Word Wrap

### ISSUE THREAD

**Issue by gitcoderx** [DaxStudio/DaxStudio#274]
Please add word wrap similar to SQL Server, Sublime Text, etc.  It would be very helpful.  Thanks for a great application for data model development.

**Comment by dgosbell** [comment]
Can you expand a bit more on what you mean here? Do you want word wrapping in the editor, in the results, in one of the timing panes? Can you maybe post some screen shots showing issues where you think word wrapping would help? 

Have you tried using the Dax Formatter button? That will usually produce much more readable results than just doing arbitrary line wrapping.

**Comment by gitcoderx** [comment]
Hi Darren –

 

Thanks for your reply.  As a member of the PowerPivotPro team, I’ve appreciated your development of DAX Studio for quite some time.  My request is for word wrap in the application editor similar to SSMS, Sublime Text, etc. (see screenshots attached).  I use DAX formatter all the time but word wrap in the editor would be really helpful.

 

Additionally, it would be awesome if a Dax Studio like editor could be integrated within Power BI desktop in some way.  The benefits of this for accelerating development of data models is self-evident.  DAX formulas can become rather complex and convoluted over time.

 

Lastly, it would be terrific to have ribbon icons to list measures / calc columns similar to PP Utilities (Excel Add-In).  The measures DMV already exists and I’ve included the custom DMV query for calc columns below (extracted from PP Utilities VBA script).

 

The word wrap request would be first and foremost with the others listed in rank priority/preference order.

 

Thanks for your time.

 

Joe

 

P.S.  I recently noticed a bug in the application.  When a user has a query open, upon selecting new query it creates two rather than one query window.  Perhaps it’s a simple fix.

 

Select Distinct * from (select REFERENCED_TABLE as [Table],  REFERENCED_OBJECT as [Column], [EXPRESSION] as [DaxExpression] from $SYSTEM.DISCOVER_CALC_DEPENDENCY   WHERE OBJECT_TYPE = 'CALC_COLUMN' and REFERENCED_OBJECT_TYPE = 'HIERARCHY') as A

 

<seems to work well enough but not entirely accurate – tweaking may be needed on this custom DMV for calc columns>

**Comment by dgosbell** [comment]
Sorry, but when you reply via email any images get stripped out so I cannot see any screenshots that you've attached, you'll need to upload these directly on github.

> P.S.  I recently noticed a bug in the application.  When a user has a query open, upon selecting new query it creates two rather than one query window.  Perhaps it’s a simple fix.

This was a bug in the 2.9.4 release, it's been fixed in the current release

**Comment by gitcoderx** [comment]
Here are the screenshot attachments as requested.  Thanks again.

![2020-01-12_17-06-43](https://user-images.githubusercontent.com/41758664/72226353-3d4ee500-355e-11ea-9d60-f7ed405fc54e.png)

![2020-01-12_17-07-36](https://user-images.githubusercontent.com/41758664/72226355-417b0280-355e-11ea-9a79-03577dc375d6.png)

**Comment by dgosbell** [comment]
So it turns out that the editor control we are using already has a WordWrap property, so enabling this is just a matter of exposing this in the Options window. So this option will be in the next release. It's not something I personally use, so I've never gone looking for it.

> Additionally, it would be awesome if a Dax Studio like editor could be integrated within Power BI desktop in some way.  The benefits of this for accelerating development of data models is self-evident.  DAX formulas can become rather complex and convoluted over time.

While it would be nice to extend Power BI Desktop Microsoft does not currently provide any hooks for 3rd party extensions to do anything like this. So providing the ability for third party extensions would be a good idea to post on ideas.powerbi.com.

**Comment by gitcoderx** [comment]
Awesome, thanks Darren, much appreciated...

**Comment by gitcoderx** [comment]
Awesome,thanks Darren, much appreicated...
