### ISSUE TITLE
View Metrics Error in DAX Studio

### ISSUE THREAD

**Issue by seethb** [DaxStudio/DaxStudio#275]
**To Reproduce**
1. Go to 'DAX Studio'
2. Click on 'View Metrics'
3. Scroll down to 'Output window'

After we connected with Azure Analysis Services Tabular Server and pressed view metrics and it came out with an error that "Error Viewing Metrics: one or more errors occurred" conversion failed when converting the "nvarchar" value "xyz" to data type int. the exception was raised by IDbCommand interface.

This error is repeating when we tried "export metrics" also our AAS model is pointing to a view which reads set of tables and most of our tables column data type are "NVARCHAR"

Could you please help us ? are we missing anything here.

Thanks for your kind help in advance

**Expected behavior**
Metrics should be visible in the DAX Studio with set of objects mapped for the Azure Analysis Services Tabular Model
**Screenshots**
Forgot to take.
**Additional context**
None

**Comment by marcosqlbi** [comment]
This is probably related to something specific in your data model.
Can you reproduce it on a sample database you can share (through the BIM file)?

**Comment by seethb** [comment]
Thanks Marco. we used Star schema of Azure SQL DW and it has fact and dimension tables and views.
could you please throw light on BIM file? I am not clear please.

Thanks for your help again.

**Comment by marcosqlbi** [comment]
The BIM file is the project file you create in Visual Studio or Tabular Editor to deploy the Analysis Services Tabular model.

**Comment by seethb** [comment]
Sure. will send across. Thanks

**Comment by dgosbell** [comment]
Is this issue also based on a direct query model?

**Comment by seethb** [comment]
Yes. we just given the AAS (Azure Analysis Services) server name and chosen the model from left side frame of DAX Studio.

asazure://<server name.net>

**Comment by dgosbell** [comment]
So Vertipaq is the name of the in-memory storage. If your model is using Direct Query then there is no Vertipaq data for us to analyze. We should maybe look at disabling the VPA buttons when we are connected to a direct query model

**Comment by seethb** [comment]
Thanks, could you please share any other options for capturing performance metrics to confirm whether the model is good or not.

**Comment by marcosqlbi** [comment]
VertiPaq Analyzer provides information to optimize the VertiPaq engine.
When you use DirectQuery, you are not using VertiPaq so the optimization approach is totally different. You have a relational database receiving SQL Queries, so you should use tools and techniques you use to optimize a SQL database. You can see how to optimize a DirectQuery model in this white paper: https://www.sqlbi.com/whitepapers/directquery-in-analysis-services-2016/

**Comment by seethb** [comment]
Thanks Marco
