### ISSUE TITLE
Vertipaq Analyzer Excel Output

### ISSUE THREAD

**Issue by seethb** [DaxStudio/DaxStudio#276]
**Describe the bug**
Post we connected Azure Analysis Services through Power Pivot via Vertipaq macro enabled Excel and after we refresh the model from Power Pivot screen and seen the output of metrics in the excel. we couldn't see the "Cardinality" populated with values. it shows zero for all the tables where the table size is not matching with the actual table size of Azure SQLDW.

Am I missing anything?

**Comment by marcosqlbi** [comment]
Sorry I'm not sure to understand,.
Are you saying that you see number in DAX Studio different than those you see in Excel once you import the VPAX file you exported from DAX Studio?

**Comment by seethb** [comment]
No Marco. I couldn't see any output in DAX Studio. Excel is showing "Zero" in the cardinality columns. Thanks

**Comment by marcosqlbi** [comment]
Try View Metrics before - if you don't see data there, you are not able to get the metrics of your database - maybe you are using DirectQuery?

**Comment by seethb** [comment]
Yes we are using Direct Query. In that case where do we need to change any settings in excel pleaes

**Comment by marcosqlbi** [comment]
VertiPaq Analyzer only works with imported data, it cannot work with DirectQuery.

**Comment by seethb** [comment]
Thanks Marco.
