### ISSUE TITLE
Add export capability to the all queries

### ISSUE THREAD

**Issue by cdataminer** [DaxStudio/DaxStudio#277]
It will be great to be able to export the ALL Queries information , so that we can create a report with baseline information and another all queries when performance has been improved.
thank you
Tomas

**Comment by dgosbell** [comment]
That's a good idea and should not be too hard to do. 

However if you are interested there is a work around for this at the moment. If you save the current tab where the trace is running DAX Studio will save a .allqueries file along side the .dax file. So if you save your tab as run01.dax you will also get a run01.allqueries (if the All Queries trace is open in that tab) This allows DAX Studio to re-open a .dax document with any trace data that was also open at the time the dax file was saved. These trace files are just .json files so you should be able to use Power Query in Excel or Power BI to import them and produce reports against.
