### ISSUE TITLE
One Issue and one item for wish list.

### ISSUE THREAD

**Issue by MurderWeapon** [DaxStudio/DaxStudio#28]
Cursor seems to disappear when we use the mouse to get around the window - not all the time but frequently enough for us to be an irritant.

Wish List:
Drag and Drop function - highlighting text and moving it to a different placement in the code.
Currently doesn't work - can highlight, but can't drag it to the position we want to move it to.

**Comment by MurderWeapon** [comment]
One more request for our group for the wish list:
when pushing ctrl+F for the find box, I would like the focus to automatically be in the find box instead of having to click within.

**Comment by dgosbell** [comment]
So I've fixed the drag/drop and the setting of the focus for ctrl+F. These will be in the next release (which should be 2.7.2) 

But I've never seen the cursor disappear and without being able to reproduce this issue we won't be able to fix it.  So if you do happen to figure out a sequence of events that consistently triggers this issue please let us know.
