### ISSUE TITLE
Add a tooltip on the editor tabs with the full path to the file, similar to Visual Studio.

### ISSUE THREAD

**Issue by dmarkle** [DaxStudio/DaxStudio#280]
**Is your feature request related to a problem? Please describe.**
I very often have many DAX files of the same name, and I need to differentiate which is which, exactly.  I can't do that now.

**Describe the solution you'd like**
A tooltip on the UI tab of the editor.

**Comment by dgosbell** [comment]
v2.11.0 has just been released which should resolve this issue
