### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by Zahra-1** [DaxStudio/DaxStudio#285]
Issue #103 mentioned that the EULA could be found at https://github.com/DaxStudio/DaxStudio/raw/master/installer/eula.rtf, but it's not there anymore. Where did it go? Procurement at my organization is very likely to ask for it.

**Comment by marcosqlbi** [comment]
I think it has been moved to the root folder:
https://github.com/DaxStudio/DaxStudio/blob/master/license.rtf
