### ISSUE TITLE
Problems connecting to SSAS Tabular 2016

### ISSUE THREAD

**Issue by UweMester** [DaxStudio/DaxStudio#29]
Hi,
I'am struggeling with connecting the latest version of DAX Studio to my workspace SSAS Tabular database. It seems as if DAX Studio has problems rendering the Metadata-Pane. 

Translated error message: "An element with the same key already has been added" 

I attached the log file and a screenshot with the translation of the german parts in the log-file:

[DaxStudio-20171113.log](https://github.com/DaxStudio/DaxStudio/files/1466067/DaxStudio-20171113.log)
![screenshot log file](https://user-images.githubusercontent.com/33618823/32717192-04616160-c859-11e7-9309-25b5a268686d.png)

It seem as if DAX Studio tries to connect to the same database twice. I have no clue how to resolve this.

Any ideas?

Thanks and regards from germany

Uwe

**Comment by dgosbell** [comment]
I don't know what would cause this. I can't reproduce this behaviour on any of my local solutions. Does it happen on other solutions or just with this one? Is it possibly to share the .bim file or a version of it?

**Comment by dgosbell** [comment]
Actually can you even just paste in a list of the table names in your model? Are there any tables which have similar names? Maybe varying by accent or something like that?

**Comment by UweMester** [comment]
Hey Darren,

unfortunatelly there is no other solution existing at the moment. 

Here is a screenshot of the table names in the model and the name the tables have in the DWH from which I'am loading them:
![table names](https://user-images.githubusercontent.com/33618823/32774638-3a08e412-c92d-11e7-9df3-a98b8dc5cebf.PNG)

I' am using a calculated table in the model which is named "Measures". We are using this for centralized hosting of the measures for the users. It seems as if thats the reason. When I delete it, everything works fine. I guess the term "Measure" is a reserved term in DAX Studio? Should have thought about that from the beginning. 

Thanks

**Comment by dgosbell** [comment]
Yes, the "Measures" table could be the issue. Do you remember how you got that table into your model? I tried creating a calculated table called Measures and I get the following error:
![image](https://user-images.githubusercontent.com/8241830/32777437-37877818-c98a-11e7-89d1-dca48aee326b.png)

**Comment by marcosqlbi** [comment]
The name "Measures" is a reserved word in MDX. You probably have a problem even if you open the model in Excel (do you use Power BI as only client now?)

**Comment by UweMester** [comment]
Thats strange. I used SSDT 2015 and was just able to create that table with that name without any error messages. 
The model is productive since nine months now and we are just using Excel as client at the moment. We never had any problems with that model/table or Excel

But now (after deleting the table in the model) when I try to open a copy of the project file still containing that table to rename it, SSDT doesn't open it anymore. It now refuses opening the project with the message that there can't be a table named "Measures", because its a reserved word.

Tried to rename the table in the metadata-file but wasn't successful.

So my problem now is how to rename the table in the project because I don't want to lose all the measures.

**Comment by marcosqlbi** [comment]
You should do the rename deep in the model. I suggest you trying to edit the BIM file using Tabular Editor: https://github.com/otykier/TabularEditor/releases/tag/2.6

**Comment by UweMester** [comment]
I'll give that a try. Thanks

**Comment by UweMester** [comment]
That seems to work very well and easy with Tabular Editor.
Marco, Darren thank you very much! You guys saved my life
