### ISSUE TITLE
PBI / SSDT Model option grayed out in DAX Studio

### ISSUE THREAD

**Issue by philipworks** [DaxStudio/DaxStudio#293]
I just downloaded DAX Studio and as I attempt to connect, the PBI / SSDT Model option is grayed out.

How can I enable this option?

![image](https://user-images.githubusercontent.com/61437919/75198840-698d8200-5716-11ea-8241-fbf8e6c7fb44.png)

**Comment by marcosqlbi** [comment]
That option is enabled when you have one or more instances of Power BI Desktop or SSDT for Visual Studio open on your desktop. DAX Studio can connect only to an open instance of those tools and the combo box shows the available instances using the window name to identify the right instance.
