### ISSUE TITLE
PBI / SSDT Model option disabled 

### ISSUE THREAD

**Issue by itsgkbi** [DaxStudio/DaxStudio#295]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![Dax error](https://user-images.githubusercontent.com/61793273/75893722-3f684e00-5e01-11ea-8e43-98e6813071c1.PNG)

**Comment by dgosbell** [comment]
That probably means you do not have any copies of Power BI Desktop or SSDT currently open. If you hover over the question mark next to the option it will tell you why that option is disabled.
