### ISSUE TITLE
Column view for results

### ISSUE THREAD

**Issue by snama2020** [DaxStudio/DaxStudio#296]
Hi There, I was wondering whether we can have a columnar view of the results. Currently it shows in a horizontal view(like a grid) and scrolling through all the columns is time consuming. I feel having an option to view the current row in a column view will allows us to a quick glance. 

Thanks,
SN

**Comment by dgosbell** [comment]
I'm not sure I entirely understand the issue you are trying to solve here or what you mean by "Current Row". Are you proposing some sort of extra popup window when you click on a row? Or do you run queries that only return a single row? Why do you have so many columns that scrolling causes an issue? Are you reading them all or are you only reading certain ones?

**Comment by dgosbell** [comment]
Closing due to lack of response
