### ISSUE TITLE
When executing a run and wantto save the result into Excel or other file type when you click on the Output in the ribbon nothing happens or maybe the resulted file is saved somewhere butno idea where. It wouldbe nice to select where the result should be sent to by providing the full path where it will be located.

### ISSUE THREAD

**Issue by chamdan0150** [DaxStudio/DaxStudio#298]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dgosbell** [comment]
Once you've changed the output target to file the **next** time you click on the **Run** button you should be prompted for the path and file name and format - currently we support txt and csv, (the csv format has been designed to work well with Excel) . And each time you click run you will be prompted for a file name.

**Comment by chamdan0150** [comment]
Hi Darren,

Thank you for your prompt reply and I tried what you suggested and it
worked.

Thank you!

Chuck Hamdan
Email: chuck.hamdan@gmail.com
[image: https://www.linkedin.com/in/chuckhamdan/]
<https://www.linkedin.com/in/chuckhamdan/>
