### ISSUE TITLE
Commented Code Disappears

### ISSUE THREAD

**Issue by MurderWeapon** [DaxStudio/DaxStudio#30]
When commenting code using the comment button on the ribbon, then hit the Format Query button on the ribbon, the commented code disappears.

If only DaxStudio could be more of a Magician and pull a rabbit out of it's hat to fix some of the reports I'm working on. ;)

**Comment by marcosqlbi** [comment]
This could be an issue of DAX Formatter. Can you send a report (exact code you write that lose the format)?

**Comment by MurderWeapon** [comment]
I will comment out this:

            "Manager", CALCULATE (
                VALUES ( Employee[FullName] ),
                Employee[FullADName] = VALUES ( SecurityEmployeeEmployee[FullADName] ),
//                ALL ( employeeemployeerole ),
//                ALL ( salesorder )
            )

Run Format Query and get an error - noticed I left a comma in the code and remove it, then run Format Query and then the commented code disappears.

**Comment by marcosqlbi** [comment]
This is a known bug in DAX Formatter. Comments at the end of a function call disappears. It's not easy to fix, it's in the backlog... try to write another parameter or comment the lines before the last parameter! :)
