### ISSUE TITLE
Downloading Dax Studio

### ISSUE THREAD

**Issue by braveheart2** [DaxStudio/DaxStudio#300]
Hi 

I have recently downloaded Dax Studio and have the following error messages 

    Version =  v2.10.1.233
    DaxStudio.exe Version =  v2.10.1.233

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Home
    OSVersion       = 10.0.18362
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.81
    FreeMemoryGB    = 3.43

    Culture Name              = en-GB
    Culture DisplayName       = English (United Kingdom)
    Culture EnglishName       = English (United Kingdom)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = £
    Culture ShortDatePattern  = dd/MM/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 3840 Height: 2160

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Users\Brian Titus\AppData\Local\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Users\Brian Titus\AppData\Local\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
=======================
    Path: "C:\Users\Brian Titus\AppData\Local\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Users\Brian Titus\AppData\Local\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Users/Brian Titus/AppData/Local/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.10.1.233, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

Registry Settings
=======================
    LastVersionCheckUTC = 2020-03-26T14:19:53Z
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>0</flags><showCmd>1</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>432</Left><Top>0</Top><Right>3792</Right><Bottom>2040</Bottom></normalPosition></WINDOWPLACEMENT>

**Comment by braveheart2** [comment]
Hi 

When I try to load the add-in I get the following error

![image](https://user-images.githubusercontent.com/62703829/77675505-efeeeb00-6f84-11ea-85ab-7889ad073d00.png)

**Comment by dgosbell** [comment]
The DAX Studio add-in is digitally signed so this must mean that your appdata location is not trusted on your machine. Can you try uninstalling and re-installing using the "All Users" option?

**Comment by braveheart2** [comment]
Hi 

This is the 1st message I get 
![image](https://user-images.githubusercontent.com/62703829/77734022-d0e16f00-6fff-11ea-8c4d-3b34d75434b2.png)

And now I have appeared to gone backwards because excel does not even tell me there is an error with this add-in and does not appear on the ribbon at all. 

Also can't find the Dax file to run the checker.

**Comment by dgosbell** [comment]
That is just Windows Smart Screen trying to protect you. DAX Studio is a fairly specialized piece of software and even though we have over 26,000 downloads it's not enough for Windows to recognize us as "commonly downloaded". You would need to click "Run anyway" if you want to run the installer again. 

But if you want to change from "Current User" to "All Users" mode you would need to uninstall from the "Add or Remove Programs" in windows.

> And now I have appeared to gone backwards because excel does not even tell me there is an error with this add-in and does not appear on the ribbon at all.

The error you got previously would have blocked the addin from starting

> Also can't find the Dax file to run the checker.

I don't think you need to run checker, it looks like your machine has all it needs to run DAX Studio.

**Comment by braveheart2** [comment]
Hi 

Thank you, I have done all the above and it has worked. 
The only difference being I clicked all users. 

Thank you very much.

When you have a new version would it update automatically or do I need to re- install.

Now to continue my Dax journey.

**Comment by dgosbell** [comment]
> When you have a new version would it update automatically or do I need to re- install.

It won't update automatically, but you will get a pop-up to let you know when a new version is released.
