### ISSUE TITLE
Intellisense / Autocomplete deletes following statements

### ISSUE THREAD

**Issue by kabootle** [DaxStudio/DaxStudio#301]
In some cases, the IntelliSense/autocomplete feature is too aggressive and deletes following Statements. 
example: I have the following Filter Statement:
`OR ( PATHCONTAINS ( @Store, 'Store'_[Store]_ ), @Store = "All" )`
Lets say, I want to change the `[Store]` to `[Store Key]` so I delete "]". 
The Statement now reads 
`OR ( PATHCONTAINS ( @Store, 'Store'[Store ), @Store = "All" )`
If I start entering " K..." IntelliSense will suggest to autocomplete to …Store Key which I'm usually happy to accept to avoid mistakes.
Unfortunately, autocomplete changes the Statement now to 
`OR ( PATHCONTAINS ( @Store, 'Store'[Store Key]"All" )`
Everything until "All" has been deleted for some reason. Adding extra spaces doesnt help to solve the issue

**Comment by dgosbell** [comment]
Thanks for logging this, I'll try and have a look at this soon
