### ISSUE TITLE
Measure Definition override in query editor not working with Power BI Desktop Version: 2.79.5768.1082

### ISSUE THREAD

**Issue by pauld42** [DaxStudio/DaxStudio#306]
**Describe the bug**
When using the March 2020 version of Power BI desktop with DaxStudio, DaxStudio appears to be ignoring measure definitions in the query editor if the measure already exists in the model.

**To Reproduce**
Follow guide at https://www.sqlbi.com/articles/capturing-power-bi-queries-using-dax-studio/
Download pbix file
Open in March 2020 version of Power BI desktop
Connect DaxStudio to model
Add long running query to query editor.
Add measure definition for Sales[Customers] measure
Make change to measure definition as suggested in the guide.
Run query

**Expected behavior**
Query should use updated measure definition and query time should reduce significantly. 

**Screenshots**

**Additional context**
This is working as expected using the same pbix file in the Feb 2020 Power BI desktop version.

**Comment by dgosbell** [comment]
> DaxStudio appears to be ignoring measure definitions in the query editor if the measure already exists in the model.

We don't do anything special with measure definitions in the query. We send the text in the query window directly to the tabular engine in Power BI Desktop. So this appears to be a change in behaviour of the engine in Power BI Desktop. I'll try and see if I can find out from Microsoft why this behaviour appears to have changed.

As a work around you can either change the measure expression in your model. Or use a measure name in your query that does not exist in your model and update the query to use this new name.

**Comment by dgosbell** [comment]
This is an issue in Power BI Desktop which MS are working on.
