### ISSUE TITLE
Weird Character in Field Titles  - Excel Export

### ISSUE THREAD

**Issue by BlierM** [DaxStudio/DaxStudio#308]
First comment here. 
Anytime I export to Excel, all fields names that have a space in DAX are replaces with a french accent character. this has been ongoing since I have been using DAX.. and now still visible in 2.10.2.

The issue not seen on text file export. Uploaded a screen shot.
Any hints?

![Capture2](https://user-images.githubusercontent.com/44618332/78765344-8d3c1d00-7990-11ea-964a-6281f093903b.PNG)

![Capture](https://user-images.githubusercontent.com/44618332/78765015-0be48a80-7990-11ea-93aa-9ff2e64746f4.PNG)

**Comment by dgosbell** [comment]
This has always been the case. It's a side effect of how the data needs to be serialized in order to pass it from DAX Studio to Excel. The simplest work around is to use the CSV export which does not suffer from this limitation. 

I can maybe have  a look at replacing these back-tick characters with spaces after the data hits Excel.

**Comment by BlierM** [comment]
Thx. Ok to see it is a known issue.. 
Yes, CSV has other benefits... or its easy to  Search & Replace once in Excel.
But considering the "perceived" simplicity of the issue, I found interesting to see this visible bug being there for years.

Regards, 

Martin

**Comment by dgosbell** [comment]
It not so much a "known issue" as I double checked the source history and it's just always been like this. Honestly I have more ideas for things to add than I have time. And I don't use the Excel output at all anymore so it's not something that worries me directly. But it's a relatively simple fix which I've just implemented so it will be part of the next release.

**Comment by BlierM** [comment]
Thx!
