### ISSUE TITLE
Automation via Powershell or SDK

### ISSUE THREAD

**Issue by isaac-gritz** [DaxStudio/DaxStudio#309]
Automation via Powershell or SDK

**Comment by dgosbell** [comment]
Automation of what? What sort of scenarios and use cases are you thinking of? DAX Studio is a UI over the AdomdClient SDK from Microsoft so you can already use this from Powershell to run DAX and DMV queries

**Comment by dgosbell** [comment]
Closing due to lack of specific requirements. Feel free to re-open if you have more information to add

**Comment by isaac-gritz** [comment]
This is good insight. AmondClient is very C# specific and there aren’t great solutions for using it with python or Powershell for automation of pulling data from Analysis Services cubes. There’s also no connector to SSAS or AAS for Azure Data Factory for automated ingestion pipelines.

DaxStudio is really nice because it makes it easy to connect to a cube and export to CSV.

Luckily I found some really elegant Powershell code here that uses the OleDB connector to connect to a cube and export it to Excel which I used for my automated pipeline: https://www.kasperonbi.com/dump-the-results-of-a-dax-query-to-csv-using-powershell/

So you can go ahead and close this.

**Comment by dgosbell** [comment]
> This is good insight. AmondClient is very C# specific and there aren’t great solutions for using it with python or Powershell for automation of pulling data from Analysis Services cubes.

No it's not. It's a .Net API so it works fine with anything that can interop with .Net. I've never tried to use it with Python, but I use it with Powershell all the time and have connected to Power BI Desktop, SSAS on-prem, AzureAS and the Power BI XMLA endpoint using Powershell.

> There’s also no connector to SSAS or AAS for Azure Data Factory for automated ingestion pipelines.

I don't use ADF so I can't really comment on this.

> Luckily I found some really elegant Powershell code here that uses the OleDB connector to connect to a cube and export it to Excel which I used for my automated pipeline:

With one extra line of code and changing a few object references you can run the same code using AdomdClient (since System.Data.OleDb.OleDbConnection is also a .Net API)

eg

```
$connectionString = “Data Source=.\tab19;Initial Catalog=Adventure Works;”
$query = “evaluate 'Date'”

$filename = “tofile.csv”
 
[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices.AdomdClient")

$connection = New-Object -TypeName Microsoft.AnalysisServices.AdomdClient.AdomdConnection

$connection.ConnectionString = $connectionString
$command = $connection.CreateCommand()
$command.CommandText = $query
$adapter = New-Object -TypeName Microsoft.AnalysisServices.AdomdClient.AdomdDataAdapter $command
$dataset = New-Object -TypeName System.Data.DataSet
$adapter.Fill($dataset)

$dataset.Tables[0] | export-csv $filename -notypeinformation
  
$connection.Close()
```
