### ISSUE TITLE
DAX-query issue

### ISSUE THREAD

**Issue by paullevchuk** [DaxStudio/DaxStudio#31]
I would like to export raw data from table in PP using such DAX-query:

EVALUATE

SELECTCOLUMNS(
	TOPNSKIP(2300000, 0, traffic),
	"date", [date],
	"deviceCategory", [deviceCategory],
	"landing", [landing],
	"language2", [language2],
	"newUsers", [newUsers],
	"sessions", [sessions],
	"source", [source],
	"traffic_type", [traffic_type]
)

I have no problems up to 2M rows. After that I get such error:

11/15/2017 19:05:07		The server sent an unrecognizable response.

How can I export raw data to .CSV if table in PP has big volume (millions of rows)?

**Comment by marcosqlbi** [comment]
Maybe there is some limit in the file generated - never tried to export such a volume.
Did you try to export in different files splitting the rows by using different arguments of TOPNSKIP?

**Comment by dgosbell** [comment]
There is an inherent limit at the moment based on a maximum 2Gb XMLA response size. If the generated response is larger than that it gets truncated and you get the "unrecognizable response" error.  This equates to roughly a few million rows depending on how wide the rows are.  This has to do with the way we marshal the response between PowerPivot and DAX Studio. There might be a way to switch over to a streaming style interface, but I'll need to do some investigation as I don't know if this is even possible yet. 

In the short term your options would be to break the export into smaller chunks or to go back to the original source data and extract from there.

**Comment by paullevchuk** [comment]
Guys, 
First of all, thanks for responses. @dgosbell looking forward to results of your research.

Sure, I can do export several times using different ranges. And I, actually, do this.
Issue here is that I can't automate this process via DAX Studio :(

P.S.
Actually I need to export data from PP because I can't connect to them from another PP model.
I have one model which has data loaded from Google Analytics and cleaned via PQ.
Unfortunately I can't just connect to this **preprocessed** data, so I need to duplicate PQ-queries and load and process them again on every new report. And it's huge pain for me.

**Comment by dgosbell** [comment]
This limitation has been lifted as of v2.7.2
