### ISSUE TITLE
Dax Studio not working in Exce,

### ISSUE THREAD

**Issue by ricafonyat** [DaxStudio/DaxStudio#310]
Could you help me with this problem below?

As you will see there are some Fails.

    Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSVersion       = 10.0.18362
    OSArchitecture  = 64 bits
    VisibleMemoryGB = 7,90
    FreeMemoryGB    = 2,17

    Culture Name              = pt-BR
    Culture DisplayName       = Português (Brasil)
    Culture EnglishName       = Portuguese (Brazil)
    Culture 2-Letter ISO Name = pt
    Culture DecimalSeparator  = ,
    Culture GroupSeparator    = .
    Culture CurrencySymbol    = R$
    Culture ShortDatePattern  = dd/MM/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY2  
         X: -1920 Y: 0 Width: 1920 Height: 1080

Checking .Net Framework
=======================
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Client\1046 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4\Full\1046 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > O sistema não pode encontrar o arquivo especificado. (Exceção de HRESULT: 0x80070002)
    FAIL > Não foi possível carregar arquivo ou assembly 'Microsoft.AnalysisServices' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > O sistema não pode encontrar o arquivo especificado. (Exceção de HRESULT: 0x80070002)
    FAIL > Não foi possível carregar arquivo ou assembly 'Microsoft.AnalysisServices.AdomdClient' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - ࠧ

**Comment by dgosbell** [comment]
The only issue in that output is a bug in the Checker app due to a change in they way I bind to the AMD/Adomd libraries. That bug will be fixed in the next release but I'm actually thinking about taking that section out as I no longer see any issues due to version issues for those libraries. Everything else looks normal.

So what exactly is your problem?

**Comment by ricafonyat** [comment]
Thanks Darren!
The funny thing is that I have two accounts in my windows notebook and Dax Studio is working perfectly in one of those. How is that possible?

**Comment by dgosbell** [comment]
I don't know as I still have no idea what you mean by "not working". Is the addin not appearing? Does it appear but not find the PowerPivot model? Does it throw an error in Excel? Does it throw and error in the UI? Does the UI crash on launch? I need more detailed description of the steps you are following and the behaviours you are observing.

It could be a permissions issue, a problem with one of your profiles, you may have used the "install for current user" option so it's only installed for one of the accounts.

**Comment by ricafonyat** [comment]
Darren, thanks for your support!
