### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by niczingerb** [DaxStudio/DaxStudio#312]
Please help!

When I start dax studio, the program logo appears, but the application does not start.

The DAX studio checker shows the following. What could be the problem?
    
Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSVersion       = 10.0.17763
    OSArchitecture  = 64 bites
    VisibleMemoryGB = 7,69
    FreeMemoryGB    = 3,19

    Culture Name              = hu-HU
    Culture DisplayName       = magyar (magyarországi)
    Culture EnglishName       = Hungarian (Hungary)
    Culture 2-Letter ISO Name = hu
    Culture DecimalSeparator  = ,
    Culture GroupSeparator    =  
    Culture CurrencySymbol    = Ft
    Culture ShortDatePattern  = yyyy.MM.dd.

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY2  
         X: 2400 Y: 0 Width: 2100 Height: 1313

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1038 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1038 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1038 -> 3.5.30729.4926
    v4\Client -> 4.7.03190
    v4\Client\1033 -> 4.7.03190
    v4\Client\1038 -> 4.7.03190
    v4\Full -> 4.7.03190
    v4\Full\1033 -> 4.7.03190
    v4\Full\1038 -> 4.7.03190
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 461814

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > A rendszer nem találja a megadott fájlt. (A kivétel HRESULT-értéke: 0x80070002)
    FAIL > A(z) „Microsoft.AnalysisServices” fájl vagy szerelvény, illetve annak egyik függősége nem tölthető be. A rendszer nem találja a megadott fájlt.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > A rendszer nem találja a megadott fájlt. (A kivétel HRESULT-értéke: 0x80070002)
    FAIL > A(z) „Microsoft.AnalysisServices.AdomdClient” fájl vagy szerelvény, illetve annak egyik függősége nem tölthető be. A rendszer nem találja a megadott fájlt.

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.10.2.240, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4R
        VSTORFeature_UNM 1
        VSTORFeature_CLR35 1
        VSTORFeature_CLR40 1
        Version 10.0.60724
        Revision 00
        ProductCode {7C0242A3-8B66-35D1-9FE0-13B426ACB609}

Registry Settings
=======================

FATAL ERROR:
Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra.
   a következő helyen: DaxStudio.CheckerApp.Checker.CheckRegistrySettings()
   a következő helyen: DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by dgosbell** [comment]
The registry error is just a bug in the Checker app that gets triggered if DAX Studio has not been run before.

Can you try enabling the diagnostic logging by holding down the shift key during startup as outlined [here](https://daxstudio.org/documentation/troubleshooting/logging-settings/). If that produces a log file can you upload that to this issue on GitHub?

If the diagnostic logging does not produce a log file can you try enabling the "Startup Logging" which is outlined at the end of the [logging settings](https://daxstudio.org/documentation/troubleshooting/logging-settings/) page and post the logs generated by that.

**Comment by niczingerb** [comment]
Here are the log files. Thanks for the help.

[DaxStudio-20200415.log](https://github.com/DaxStudio/DaxStudio/files/4482831/DaxStudio-20200415.log)
[DaxStudioExcel-20200415.log](https://github.com/DaxStudio/DaxStudio/files/4482832/DaxStudioExcel-20200415.log)

**Comment by dgosbell** [comment]
This looks very similar to issue #286 - the person in that issue re-installed the .Net framework 4.7.1.

Could you maybe trying running a repair or re-installing this (you can get the download links from [here](https://daxstudio.org/documentation/installation/single-installer/) )

**Comment by niczingerb** [comment]
Installing .Net solved the problem. Thanks for the help. ;)
