### ISSUE TITLE
[Error] "AutoSaver" "GetAutoSaveIndex" "Error loading auto save index

### ISSUE THREAD

**Issue by Matheusbf** [DaxStudio/DaxStudio#313]
Hi,

After open application, it close...

I'm get the error:

2020-04-15 11:19:53.975 -03:00 [Error] "AutoSaver" "GetAutoSaveIndex" "Error loading auto save index: Já foi adicionado um item com a mesma chave."
System.ArgumentException: Já foi adicionado um item com a mesma chave.
   em System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   em System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   em DaxStudio.UI.Utils.AutoSaver.LoadAutoSaveMasterIndex()

How to resolve it?

Thanks!!

**Comment by dgosbell** [comment]
What version of DAX Studio are you running? Are you on the latest 2.10.2?

Depending which release you are running you will find an autosave folder under either of the following folders (we changed to the local folder recently)):

%appdatalocal%\DaxStudio
%appdata%\DaxStudio

If you type WindowsKey+R and paste either of the above in to the run box it should open in windows explorer. 

If you delete any index-*.json files or move them to another folder this should let you open DAX Studio.

**Comment by dgosbell** [comment]
closing due to lack of response
