### ISSUE TITLE
New query button doesn't work

### ISSUE THREAD

**Issue by snama2020** [DaxStudio/DaxStudio#318]
When I click the New query icon available under the quick Access tool bar, nothing happens. It will only work if I go to the File menu(and exit it) and then click the New query icon. No too sure if this is a user error.

**Comment by dgosbell** [comment]
This is not something you have done wrong. It's definitely a bug in DAX Studio.

I've been struggling with this issue with the ribbon control for some time now. I thought I had figured out a solution last release, but you are correct that the Quick Access Icons only work after you have opened the file menu once.

However the good news is that I've found a different way of configuring the Quick Access items in the Ribbon which appears to be working all the time (see #314) and this will be part of the 2.11 release which should be out shortly.

**Comment by snama2020** [comment]
Yes, #314 was raised by me as well 😊

**Comment by dgosbell** [comment]
v2.11.0 has just been released which should resolve this issue
