### ISSUE TITLE
Error with Linked excel output

### ISSUE THREAD

**Issue by jakobbbeck** [DaxStudio/DaxStudio#32]
When select static output it works fine, but linked input created a connectionstring that does not include the cubename. If i add" Cube=[Cubename];" it works

**Comment by dgosbell** [comment]
Would I be correct in assuming that you are connecting to an Analysis Service server in multi-dimensional mode when this issue occurs?

**Comment by jakobbbeck** [comment]
Spot on.

**Comment by dgosbell** [comment]
Yeah, I could not think of any other scenarios where this would be an issue, but I just wanted to double check. I found the cause of this issue and the fix will be in the next release v2.7.2 which should be out shortly.

**Comment by jakobbbeck** [comment]
great
