### ISSUE TITLE
unable to export to .vpax

### ISSUE THREAD

**Issue by Jawroy** [DaxStudio/DaxStudio#320]
getting this error message when trying to export to .vpax in order to analyze with vertipaq_analyzer.

![image](https://user-images.githubusercontent.com/16524111/80909801-6375dc00-8d2b-11ea-9d44-fa493a10c252.png)

do I need to have a server running? probably won't happen, as this is a company laptop. 

note; one thing that strikes me as odd is that the name of the connection shown in the connect dialogue box of DaxStudio changes from the one my excel file has. the first underscore is left out. I've tried removing all underscores, but still no luck. what am I missing?

**Comment by dgosbell** [comment]
> do I need to have a server running? probably won't happen, as this is a company laptop.

No, in the context of this error message the "server" is just whatever process is hosting your data model. You mention and Excel file so I'm assuming this is a Power Pivot model - is this correct?

If so what version of Excel are you using and what version of DAX Studio?

> note; one thing that strikes me as odd is that the name of the connection shown in the connect dialogue box of DaxStudio changes from the one my excel file has. the first underscore is left out. I've tried removing all underscores, but still no luck. what am I missing?

That's just a display issue, underscores are treated differently in labels, I can fix that.

**Comment by Jawroy** [comment]
hi Darren,

powerpivot, yes
excel 365 version 1910, 64 bit
daxstudio version 2.10.1

**Comment by dgosbell** [comment]
OK, so can you try using the latest version of DAX Studio (currently 2.10.2) as there were a number of issues with Vertipaq Analyzer that we fixed.

**Comment by Jawroy** [comment]
nope, doesn't work. still the same message

**Comment by dgosbell** [comment]
You are right, there was a minor difference between the view and export options which broke exports, but just for PowerPivot models and our unit tests were passing the parameters correctly. I've fixed this and it will be part of the next release.
