### ISSUE TITLE
Excel add-in install issue

### ISSUE THREAD

**Issue by mitch2300** [DaxStudio/DaxStudio#322]
Installed DAX Studio and standalone app works fine but Excel Add-in is not showing up.  Checked to confirm that the "Add-ins" tab in Excel is checked as being visible (it is) and that DAX studio is listed in the COM add-ins list and is checked as active (it is).  I have uninstalled an re-installed several times to no avail.  Any suggestions?

**Comment by dgosbell** [comment]
Can you run DaxStudio Checker (see [https://daxstudio.org/documentation/troubleshooting/daxstudio-checker/](https://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) ) and paste the output back on this issue? That should show what versions you are running and if you have any other add-ins loaded.

One other thing you could try that might provide more information is to enable VSTO Alerts. VSTO is the framework from Microsoft that the add-in uses to talk to Excel. To do this you need to close any open Excel windows, then from DaxStudio.Checker you can use the File menu to enable these alerts (this option will change to Disable so that you can switch them off afterwards)
![image](https://user-images.githubusercontent.com/8241830/81235545-8a3f5580-903e-11ea-90ae-25c6bcf54e3b.png)

Then start up Excel, if there are any issues with VSTO loading DAX Studio you should now see some alert dialogs. If you do see any messages can you post the text or screenshots back here?

**Comment by mitch2300** [comment]
Thanks for the reply.  The VSTO alerts was already enabled and I got no errors.  However, I did run the DAX Studio Checker (pasted below) and it appears that it identified a couple of missing dll files.  I'm not sure how to resole this.

-----------------------------------------------------------------------------------------
DAX Studio Checker result:

    Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Home
    OSVersion       = 10.0.18362
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.86
    FreeMemoryGB    = 8.54

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 2560 Height: 1440

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - ࠧ

**Comment by dgosbell** [comment]
>  it appears that it identified a couple of missing dll files. 

No, I changed the way those files are deployed and forgot to update the checker app. I'm actually removing that section from the checker in the next release as the new deployment method means we no longer have issues with those libraries.

But is that the full output from the checker? There are some sections missing including a key one where it should check the VSTO configuration.

As a long shot have you tried re-booting in between the re-install attempts? I have seen issues where a hung version of Excel.exe that is still still running but has no visible windows can cause issues with addins loading.

**Comment by mitch2300** [comment]
Thanks for the reply.  I uninstalled, rebooted the computer and reinstalled to no avail.  I re-ran DaxStudio Checker and results below.  I see the add-in in Excel Com add-ins but it is unchecked.  I check it, close dialog, re-open Com add-ins and it is again unchecked.  Basically won't let me activate it.  

    Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Home
    OSVersion       = 10.0.18362
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.86
    FreeMemoryGB    = 9.81

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 2560 Height: 1440

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - ࠧ

**Comment by dgosbell** [comment]
I can only think of a few possible things that might cause this.

1. You could check the "Disabled Items" section in the Excel addins. If an add-in gets put in this section you need to remove it from there or Excel will not load it. (although the installer and DAX Studio checker both look for this, so this is unlikely)

2. Another add-in might be causing issues. If you have multiple VSTO add-ins the first one to load will trigger a load of the .Net framework. The DAX Studio Excel addin requires at least v4.5 of .Net - if you have another addin which only needs .Net 2.0 for example and it loads first, then DAX Studio will fail to load. But I'm pretty sure that the VSTO alerts should display an issue if this is the case. Try temporarily turning off any other 3rd party add-ins, then close and re-open Excel and try to enable DAX Studio.

3. Your install of Excel might not have the .Net support enabled. Try going into Add/Remove programs and find the entry for Microsoft Office, choose Modify then Add/Remove features and check that the following is enabled

![image](https://user-images.githubusercontent.com/8241830/81458473-e7254200-91dd-11ea-8ca6-ff61274930c3.png)

Otherwise if this is a company PC check with your IT department that they don't have any policies limiting the add-ins that Excel can use.

**Comment by luconsta** [comment]
Hello @dgosbell ,

I have the same problem with Excel Addin that dont want to be enabled.

Here is the DaxStudio Checker results:

    Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSVersion       = 10.0.18363
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 31.96
    FreeMemoryGB    = 3.47

    Culture Name              = ro-RO
    Culture DisplayName       = Romanian (Romania)
    Culture EnglishName       = Romanian (Romania)
    Culture 2-Letter ISO Name = ro
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = lei
    Culture ShortDatePattern  = dd.MM.yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.10.2.240, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

Registry Settings
=======================
    DaxFormatterRequestTimeout = 10
    EditorEnableIntellisense = True
    EditorFontFamily = Lucida Console
    EditorFontSize = 11
    EditorShowLineNumbers = True
    ExcludeHeadersWhenCopyingResults = True
    LastVersionCheckUTC = 2020-06-04T09:57:25Z
    ProxyAddress = 
    ProxyPassword = 
    ProxyUser = 
    ProxyUseSystem = True
    QueryEndEventTimeout = 5
    QueryHistoryMaxItems = 200
    QueryHistoryShowTraceColumns = True
    ResultAutoFormat = False
    ResultFontFamily = Segoe UI
    ResultFontSize = 11
    ScaleResultsFontWithEditor = True
    ShowAggregationRewritesInAllQueries = False
    ShowExportAllData = False
    ShowExportMetrics = False
    ShowExternalTools = True
    ShowTooltipBasicStats = True
    ShowTooltipSampleData = True
    TraceStartupTimeout = 30
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>2</flags><showCmd>3</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>234</Left><Top>5</Top><Right>1354</Right><Bottom>725</Bottom></normalPosition></WINDOWPLACEMENT>

What could I do to activate it?

Kind Regards,
Lucian

**Comment by dgosbell** [comment]
@luconsta - everything looks fine in the checker output. I cannot see any reason why the addin would not be loading. 

Have you tried turning on the VSTO alerts option? If so did that show any errors?

Do you have any other add-ins loaded in Excel? If you disable everything except for PowerPivot and DAX Studio does that allow the add-in to load?

Have you checked if .Net support is enabled in your copy of Excel (as in the screenshot above your post)

**Comment by luconsta** [comment]
Hello @dgosbell ,

Thank you for your suggestion but with just PowerPivot Addin, still not able to load the DaxStudio Addin. I have the Dax Studio Excel Addin available in the COM Addins list... but checking it will not load it.

I have even uninstall DAX Studio and Office and reinstalled Office 64bit version then DAX Studio and still the same problem. I have reattached the DAX Studio Checker results with the 64bit Excel with VSTO Alerts activated but no any other warnings. Also in my previous message I had VSTO Alerts activated but no other warnings.

    Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSVersion       = 10.0.18363
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 31.96
    FreeMemoryGB    = 25.46

    Culture Name              = ro-RO
    Culture DisplayName       = Romanian (Romania)
    Culture EnglishName       = Romanian (Romania)
    Culture 2-Letter ISO Name = ro
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = lei
    Culture ShortDatePattern  = dd.MM.yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.10.2.240, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

Registry Settings
=======================
    DaxFormatterRequestTimeout = 10
    EditorEnableIntellisense = True
    EditorFontFamily = Lucida Console
    EditorFontSize = 11
    EditorShowLineNumbers = True
    ExcludeHeadersWhenCopyingResults = True
    LastVersionCheckUTC = 2020-06-04T09:57:25Z
    ProxyAddress = 
    ProxyPassword = 
    ProxyUser = 
    ProxyUseSystem = True
    QueryEndEventTimeout = 5
    QueryHistoryMaxItems = 200
    QueryHistoryShowTraceColumns = True
    ResultAutoFormat = False
    ResultFontFamily = Segoe UI
    ResultFontSize = 11
    ScaleResultsFontWithEditor = True
    ShowAggregationRewritesInAllQueries = False
    ShowExportAllData = False
    ShowExportMetrics = False
    ShowExternalTools = True
    ShowTooltipBasicStats = True
    ShowTooltipSampleData = True
    TraceStartupTimeout = 30
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>2</flags><showCmd>3</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>234</Left><Top>5</Top><Right>1354</Right><Bottom>725</Bottom></normalPosition></WINDOWPLACEMENT>

**Comment by luconsta** [comment]
Hello @dgosbell 

It seems that I have solved the problem.... in a strange way but at least for me it finally worked. :)

First I have tried the new 2.11.0 version but did not solved the problem. Neither installing over the 2.10 version or uninstalling and reinstalling.

Looking in Excel at the COM addins I have saw the addin file mentioned: **"C:\Program Files\DAX Studio\bin\DaxStudio.vsto|local**".

Going to the VSTO file and double clicking on it the "**Microsoft Office Customization Installer**" appeared on screen and pressing the "**Install**" button did the trick.

In fact this action it seems to add a new entry in the **"Control Panel\Programs\Programs and Features**" named "**DaxStudio**" (no space between names) and on the version column it shows **2.10.0.0** besides the initial entry of "**DAX Studio 2.11.0.290**".

Also in Excel in the Add-ins ribbon I had two entries for Dax Studio and checking the COM addins also found two entries - the second entry was without "**|local**" after the VSTO file. This second entry could not run the DAX Studio but the initial entry could run the app.

After I've installed the "strange" second entry "DaxStudio" / 2.10.0.0 it remains only one entry in the Excel addin and is working perfectly.

So, for me problem is solved.

Kind Regards,
Lucian

**Comment by dgosbell** [comment]
@luconsta thanks for letting us know about this. That is a bit strange, but good that it worked for you.

The install steps for the Add-in are very simple, it's basically a couple of registry keys that point to the location of the vsto file and set the load behaviour. I would guess that double clicking on the vsto file does a similar thing. 

The |vstolocal string after the path to the .vsto file simply tells Excel not to cache a second copy of the add-in in the click-once cache, but to just load it directly off disk. It's really just a performance optimization that Microsoft recommends for locally installed add-ins. 

But I really appreciate you letting me know about this. I might do some investigation and see if I can find any differences in the way the add-in gets registered.

**Comment by ImkeF** [comment]
Hi @dgosbell ,
I'm also having the problem that my Excel-Add-On will not show. 
Have uninstalled, reinstalled, repaired windows,... everything I can think of.
BTW: After each uninstall, the Excel-Add-On remained. I then had to repair windows to get it out off my ComAdd-ins.
So I tried Lucians approach to install the solution directly from the vsto-file.
Then I got this error:

![image](https://user-images.githubusercontent.com/18321412/93015415-92456e00-f5b9-11ea-8a0c-e0425721cecc.png)

I don't see any option to move ahead from here on. Do you have any idea?
Thanks, Imke

**Comment by dgosbell** [comment]
Thanks @ImkeF that error is really helpful.

I was under the impressions that Excel used to ask on the first install of the DAX Studio addin if you wanted to trust it (which should be similar to what double clicking on the vsto file does). But either I'm mistaken or something has changed. I think I can get the installer to add the certificate which the addin is signed with to the Trusted Publishers store which should fix this for future releases.

Or if you want to get this working now you can either change the trust setting in Excel to not require that addins are signed or you can manually add the certificate to the Trusted Publishers.

The trust setting for Excel is in File > Options > Trust Center
Then Click on Trust Center Settings and go to the Addins tab
You can then turn off the setting requiring add-ins be signed by a Trusted Publisher

This is the easiest way to test if this is the issue. You should then be able to go into the COM addins settings in Excel, re-enable DAX Studio and then close and re-open Excel and the addin should now load (assuming the issue is the trust settings)

**But this is not the most secure long term solution as it trusts any addin.** 

To add DAX Studio to the Trusted Publishers you could either wait for the next version or try the following steps.

1. Find **DaxStudio.dll** in the /bin folder under where the program is installed
2. Right click on it and view the **Properties**
3. Go to **Digital Signatures**
4. Click on the "Darren Gosbell" signature
5. Click on **Details**
6. Click on **View Certificate**
7. Click on **Install Certificate**
8. Click **Next**
9. Click on "Place all certificates in the following store"
10. Click on **Browse**, then choose **Trusted Publishers**
11. Click **Next**, then **Finish**

Once this is done you should be able to enable DAX Studio in the COM addins and then close and re-open Excel and it should load.

**Comment by ImkeF** [comment]
Hi @dgosbell ,
thanks a lot for this detailed answer.
Going to wait for the new build, as the following steps didn't work. Just posting it here in case it helps with the new build:

1. Added the certificate to the trusted publishers as mentioned above
2. Opened Excel but the Add in still wouldn't show up
3. But now I could install from the VSTO.
4. This lead to the Add-In being shown twice in the window:
![image](https://user-images.githubusercontent.com/18321412/93172271-d3a95b00-f72a-11ea-8d6b-e33379c08d88.png)
5. But it was still not shown in the ribbon pane. But what I recognized was that the Add-On-ribbon quickly flashed up once before disappearing forever...
6. Uninstalled both DAX Studio programs.
7. Reinstalled DAX Studio without the Excel-AddOn
8. Tried to manually add the Excel-AddOn by executing the VSTO manually again gives this error:
![image](https://user-images.githubusercontent.com/18321412/93172431-271ba900-f72b-11ea-90c1-ddcec913de89.png)

As I've worked around the original requirement I'm happy to wait for the new build.

**Comment by dgosbell** [comment]
I'm not sure if the new build will fix this. All it does is automate the installation of the certificate to the Trusted Publishers. 

But I don't really know what that VSTO installer does, there is not a lot of documentation on it and I can't see why it's trying to get the DaxStudio.dll.config file, but that file does exists so I don't know why it would fail.

Maybe now that you've installed the certificate try using the installer to re-install the Excel add-in.

**Comment by ImkeF** [comment]
Thanks @dgosbell ,
but with the latest install (without the Excel Add-In), this file didn't came with it:

![image](https://user-images.githubusercontent.com/18321412/93241985-6a573580-f786-11ea-99cb-ca38d9d5528e.png)

Could this cause the problem?

**Comment by dgosbell** [comment]
Yes, if you don't install the add-in this file is not written out by the installer. 

I used to avoid writing out any of the add-in files if you chose not to install the add-in, but at one point I started trying to add my own code for a "current user" install, but then the installer program I use added a built-in feature for this so I stopped work on that, but as a side effect some, but not all of the Excel add-in files get installed regardless of the option you select.

**Comment by ImkeF** [comment]
Thanks Darren and no worries.
There must be something wrong with my Office, obviously.
Running fine on my VM, so will hop over there, once I need it again.
