### ISSUE TITLE
Problem during Installation Windows10 "IPersistFile::Save failed; code 080070005"

### ISSUE THREAD

**Issue by LQ0202** [DaxStudio/DaxStudio#323]
Hello:

During the installation at the end appears a setup window error:

"IPersistFile::Save failed; code 080070005
Access Denied".

Thanks for your help.
Regards,
LQ

**Comment by dgosbell** [comment]
Is this the first time you've installed or is this an upgrade?
Did you choose the All Users or Current User option?
Did you use the default location or did you change it to something else?

Can open a command prompt, navigate to the folder where you downloaded the setup and run:
```
DaxStudio_2_10_2_setup.exe /log=c:\temp\daxstudio-setup.log
```
And then upload the log file to this issue after the setup is finished attempting to install.

**Comment by LQ0202** [comment]
First time installation.
I choose All and Currrent use to test if the error appears in both cases. In both cases appear.
[DaxStudio.exe.log](https://github.com/DaxStudio/DaxStudio/files/4593585/DaxStudio.exe.log)
Thank you.

**Comment by dgosbell** [comment]
That is not the log file from the setup, I'm not sure where you found that one. So it's hard to be sure but it could be releated to a relatively new issue called Controlled Folder Access in Win 10 blocking the creation of the desktop shortcut ([as noted here]( https://stackoverflow.com/questions/54484900/inno-setup-can-not-create-desktop-icon-in-windows-10)) . So you could try running the installer, but just unticking the option for a desktop icon and see if that works.

PS. If you have the option I always recommend choosing the All Users option, it's safer and all the features are enabled. With the Current User option we cannot enable the Excel add-in

**Comment by LQ0202** [comment]
Solved.
All Users option and unticking the option for a desktop icon.
Thank you.
