### ISSUE TITLE
Setting values for dynamic measures

### ISSUE THREAD

**Issue by BlierM** [DaxStudio/DaxStudio#324]
Gents, 
I try to use DaxStudio to query a Model (in PowerPivot) that has dynamic measures based on user selection. Within Excel, all works. Selections are applied and measures calculated accordingly.

![image](https://user-images.githubusercontent.com/44618332/81290445-c25f8c00-9070-11ea-914d-2056d051bfb4.png)

Above only show the logic area for selection. And variable are defined (not shown).

In DaxStudio, I tried DEFINE MEASURE but it ignored by the measure being calculated. Hence the results is the default message to the user "Set Cal. Mode" even if DEFINE sets it to "Actuals"

![image](https://user-images.githubusercontent.com/44618332/81290614-0ce10880-9071-11ea-8419-8543b0896a62.png)

![image](https://user-images.githubusercontent.com/44618332/81290670-27b37d00-9071-11ea-84c6-a5993e736bea.png)

How could DaxStudio be used to set a value for a dynamic calculation? Parameters? did not work.
Note, my measure is not within DaxStudio but in the model and variables are define but not shown.

Pls route be to correct thread to ask this questions if I used the wrong one.

Much appreciated.

**Comment by BlierM** [comment]
Adding... I sense what is happening.. Even if I define the 
MEASURE 'Utility_Measures'[Selected Calculation Mode]="Actuals" in the DAX query, 
It still fetches its value from the one in the model.  

![image](https://user-images.githubusercontent.com/44618332/81293170-88dd4f80-9075-11ea-8a1a-a7d8fe8a317f.png)

So the question is how to override a value in the Model by one set in the DaxStudio Query?

**Comment by BlierM** [comment]
Agreed, this is not a bug, but an idea to improve DaxSturio. Would be useful to force (overwrite) the value of a measure that is used within the Model; hence, allow simulation. This is different than a parameter or a Variable being defined in the query itself. Anyhow, I guess it's a very small priority in all view of things.

**Comment by marcosqlbi** [comment]
You can already define a measure that overrides the behavior of an existing measure in the model by using the syntax DEFINE MEASURE. However, because of a bug in March 2020 and April 2020 releases of Power BI Desktop, that technique doesn't work, but it works in earlier or following releases.

**Comment by BlierM** [comment]
Thx Mr. Russo for prompt input. 
This is exactly what I did, DEFINE MEASURE. See second image in first post. However, it does not work. 
Note: I am using PowerPivot in Excel 16.0.12730.20188 64 bits. Maybe related to the same issue you raised.

**Comment by marcosqlbi** [comment]
I don't think so - you have to use DEFINE MEASURE ... followed by EVALUATE and the complete DAX query.
If you use Excel you have to use WITH MEASURE ... followed by the MDX query. 
These temporary measures only apply to the queries executed within DAX Studio, not to the queries you execute in Excel or Power Pivot or Power BI.

**Comment by BlierM** [comment]
Hum. Interesting to try "WITH MEASURE"... But DaxStudio does not recognize this "WITH" Keyword.
Pls advise. 
Much appreciated.

![image](https://user-images.githubusercontent.com/44618332/81472862-3336ad80-9203-11ea-96da-5d2d835f84ce.png)

**Comment by dgosbell** [comment]
WITH works fine in DAX Studio, but it's an MDX keyword not a DAX keyword so we don't syntax highlight it. But you also have to write the rest of the query as MDX and it still does not work the way you want it to.

And we just send the query to the tabular engine, the way the calculations are evaluated is not something we have control over. If you include the definition for [2020 PostPaid Comm SS NS Proratable] in the query so that the whole chain of measures was in the DEFINE block then it would work, but it appears that the engine does not let you overwrite just a single measure in middle of a dependency chain.

But the fix for your current query is simple. You just need to add a filter for the calculation mode (as I mentioned earlier) then there is no need to overwrite the [Calc. Mode] measure. If you simply swap the order of your CALCULATETABLE and SELECTCOLUMNS functions and add this as a filter this should work.

eg

```
EVALUATE
VAR LowerLimit = 20200401
VAR UpperLimit = 20200401
RETURN 
CALCULATETABLE( 
    SELECTCOLUMNS(
      'PS-DATA',
      "Service Order Num", [Service_Order_Num],
       "Test", [2020 PostPaid Comm SS NS Proratable],
       "Calc. Mode", [Selected Calculation Mode]
    )
   ,FILTER( 'Main Calendar', 'Main Calendar'[Datekey] >= LowerLimit
                                          && 'Main Calendar'[Datekey] <= UpperLimit )
   ,'PS-DATA'[Sales_Type] = "NS"
   ,'Calculation Mode'[Calculation_Mode] = "Actuals"
)
```

**Comment by dgosbell** [comment]
In fact this is similar to [this video](https://www.youtube.com/watch?v=ZIJDv3J9kko&feature=youtu.be) Marco posted recently about setting filter context for measures in DAX Studio

**Comment by marcosqlbi** [comment]
The MEASURE definition only affects the measure references within the query. If you have a measure B in the model that references A, if you redefine A in the query, this does not affect B. You have to redefine B, too.
For this reason, we have a specific feature "Define dependent measures" - if applied to B, it includes in the DEFINE MEASURE both A and B definitions.

**Comment by BlierM** [comment]
Thx Darren and Marco, 
Swapping the order of CALCULATETABLE and SELECTCOLUMNS worked. 

From KSA... Enjoy your day.
