### ISSUE TITLE
connexion failed between dax studio and excel

### ISSUE THREAD

**Issue by coolman0260** [DaxStudio/DaxStudio#325]
**Describe the bug**
First time I try to use Dax Studio : cannot connect to powerpivot 

**To Reproduce**
1. open excel
2. launch dax studio with shortcut in excel ribbon
3. validate connexion "powerpivot" to workbook
4. get error message "error connecting : connection expired or was lost"

**Expected behavior**
connection between excel and dax studio working properly

**Screenshots**
![image](https://user-images.githubusercontent.com/65031631/81421787-55242780-9152-11ea-9f66-d7302cd14b3f.png)

![image](https://user-images.githubusercontent.com/65031631/81421805-5ce3cc00-9152-11ea-941b-e8ee80157ad0.png)

**Additional context**
here is the log from dax checker
    Version =  v2.10.2.240
    DaxStudio.exe Version =  v2.10.2.240

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Famille
    OSVersion       = 10.0.18362
    OSArchitecture  = 64 bits
    VisibleMemoryGB = 7.99
    FreeMemoryGB    = 0.92

    Culture Name              = fr-FR
    Culture DisplayName       = Français (France)
    Culture EnglishName       = French (France)
    Culture 2-Letter ISO Name = fr
    Culture DecimalSeparator  = .
    Culture GroupSeparator    =  
    Culture CurrencySymbol    = €
    Culture ShortDatePattern  = dd/MM/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY2  
         X: 1920 Y: 32 Width: 1680 Height: 1050

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1036 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1036 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1036 -> 3.5.30729.5003
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Client\1036 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4\Full\1036 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Users\Arnaud\AppData\Local\Programs\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > Le fichier spécifié est introuvable. (Exception de HRESULT : 0x80070002)
    FAIL > Impossible de charger le fichier ou l'assembly 'Microsoft.AnalysisServices' ou une de ses dépendances. Le fichier spécifié est introuvable.

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Users\Arnaud\AppData\Local\Programs\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > Le fichier spécifié est introuvable. (Exception de HRESULT : 0x80070002)
    FAIL > Impossible de charger le fichier ou l'assembly 'Microsoft.AnalysisServices.AdomdClient' ou une de ses dépendances. Le fichier spécifié est introuvable.

Dax Studio Configuration
=======================
    Path: 
      WARN > Dax Studio registry 'Path' value not found.
      Attempting to use current path: C:\Users\Arnaud\AppData\Local\Programs\DAX Studio\daxstudio.exe
    Processing DaxStudio.exe.config file...
    Path: 'C:\Users\Arnaud\AppData\Local\Programs\DAX Studio\daxstudio.exe.config'
    Bindings Found: 17
    AMO : 18.2.3.0
    ADOMD : 18.2.3.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
      ERROR: DAX Studio Excel addin registry keys not found!

FATAL ERROR:
La référence d'objet n'est pas définie à une instance d'un objet.
   à DaxStudio.CheckerApp.Checker.CheckExcelAddin()
   à DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by dgosbell** [comment]
Where is your Excel file stored? Is it on OneDrive? If so can you try copying it to a local folder and see if that works?

**Comment by coolman0260** [comment]
You’re right ! it works with local file.

 

Thank you very much

 

Arno

 

De : Darren Gosbell <notifications@github.com> 
Envoyé : samedi 9 mai 2020 01:39
À : DaxStudio/DaxStudio <DaxStudio@noreply.github.com>
Cc : coolman0260 <coolman02@gmx.com>; Author <author@noreply.github.com>
Objet : Re: [DaxStudio/DaxStudio] connexion failed between dax studio and excel (#325)

 

Where is your Excel file stored? Is it on OneDrive? If so can you try copying it to a local folder and see if that works?

**Comment by asjones987** [comment]
I wanted to followup, is there an issue with Excel files (or PBIX files) stored on OneDrive? I was about to move more files to Onedrive from an old network share.

**Comment by coolman0260** [comment]
Yes, there is an issue with onedrive storage. No problem on local disk

 

De : Alan Jones <notifications@github.com> 
Envoyé : lundi 11 mai 2020 16:05
À : DaxStudio/DaxStudio <DaxStudio@noreply.github.com>
Cc : coolman0260 <coolman02@gmx.com>; Author <author@noreply.github.com>
Objet : Re: [DaxStudio/DaxStudio] connexion failed between dax studio and excel (#325)

 

I wanted to followup, is there an issue with Excel files (or PBIX files) stored on OneDrive? I was about to move more files to Onedrive from an old network share.

**Comment by dgosbell** [comment]
I think I found the issue that was causing errors when trying to connect to files stored on OneDrive. A fix for this will be included in the next release.

**Comment by coolman0260** [comment]
Great! Thank you so much, Arnaud-------- Message original --------Objet : Re: [DaxStudio/DaxStudio] connexion failed between dax studio and excel (#325)De : Darren Gosbell À : DaxStudio/DaxStudio Cc : coolman0260 ,Author 
I think I found the issue that was causing errors when trying to connect to files stored on OneDrive. A fix for this will be included in the next release.

**Comment by lucnicod** [comment]
I am experiencing the same issue with Excel beta version 2212 (Build 1594.20000). Any update on this issue?
Thanks

**Comment by dgosbell** [comment]
@lucnicod - this is not the same issue, just a similar error message. The current versions of Excel (from 2208 onwards) have a bug that is blocking the DAX Studio connection see issue #884. Once Excek releases a fix for this DAX Studio will start working again.
