### ISSUE TITLE
DateTime Data Type reported for Date column

### ISSUE THREAD

**Issue by lbendlin** [DaxStudio/DaxStudio#328]
Force a column in Power Query to use Date format. 
close and apply
open DAX Studio , connect to dataset, view metrics
observe that the Data Type for the column says "DateTime"

**Comment by dgosbell** [comment]
This is correct, Power Query has a different type system to the data model. Tabular data models only have a DateTime type they do not have separate Date and Time data types, they just zero out the unwanted portion of the date time and use a format string to only show the desired date or time component. (see [https://docs.microsoft.com/en-us/analysis-services/tabular-models/data-types-supported-ssas-tabular?view=asallproducts-allversions](https://docs.microsoft.com/en-us/analysis-services/tabular-models/data-types-supported-ssas-tabular?view=asallproducts-allversions)

**Comment by lbendlin** [comment]
How would you then know as a developer if you can decrease the cardinality of that column?  Say, you have a datetime source field, but you only need date granularity in your report.

**Comment by dgosbell** [comment]
So cardinality is only indirectly related to the datatype. And the decision to reduce cardinality is one the developer need to make in conjunction with the business requirements.

If you have date values like this in Power Query:

2020-05-21
2020-05-22

Internally in the Tabular model they are stored as follows with a 00:00:00 time portion. 

2020-05-21 00:00:00
2020-05-22 00:00:00

So you still have just 2 distinct values and the zero time portion will effectively get stripped out by the compression at the storage layer. This is not something we can change from DAX Studio, we are just displaying the actual data types used in the model. This is a design decision Microsoft made when building the tabular engine.
