### ISSUE TITLE
Output to Excel Missing

### ISSUE THREAD

**Issue by MattAlington** [DaxStudio/DaxStudio#33]
I am using 2.7.1.  I notice that Output to Excel options are not available (when connecting to Power BI Desktop anyway).  Is that a design change or a bug?  There is a section for All, Standard and Excel, but there is nothing under Excel

**Comment by dgosbell** [comment]
It's not a change or a bug. The output to Excel options are only available when DAX Studio is launched from the Addins ribbon in Excel (we don't actually generate xlsx files, we send data through the Excel object model). When you launch DAX Studio from a direct shortcut these options are not available.

**Comment by MattAlington** [comment]
Thanks Darren, sorry - I didn't realise.

**Comment by dgosbell** [comment]
No worries, the question has come up before :) I might look at changing this so the options are disabled, not hidden. Then I can add a note to the tooltip for _why_ they are disabled, it should make this more self documenting then.
