### ISSUE TITLE
Cannot enable both Query Plan and Server Timings at the same time?

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#331]
**Describe the bug**
Cannot enable both Query Plan and Server Timings

**To Reproduce**
1. Connect to server (AAS)
2. Click Query Plan, wait for the Query Trace Started message
3. Click Server Timings

Get immediate message like	The '19A67235-4372-4FE5-9B1D-D53D40533410' session ID cannot be found. Either the session does not exist or it has already expired.

Technical Details:
RootActivityId: 8edf7e7f-8abf-4ca1-bbed-4a62669dc2dc
Date (UTC): 5/19/2020 8:26:50 AM

**Expected behavior**
Expected to be able to use both Query Plan and Server Timings at the same time

**Screenshots**

**Additional context**
I've tried the other way (Server Timings, then Query Plan) around also - same issue, first one works but second gives session ID not found error

**Comment by dgosbell** [comment]
I can't reproduce this issue. Is this consistent in your environment? It could be caused by other activity on you AzureAS instance. Processing operations, schema changes, scaling or even Microsoft applying patches or failing over to a different back end could all invalidate a session.

Are you able to check if any of the above were possibly occurring? 

I was able to activate both traces and run a number of queries without issue
![image](https://user-images.githubusercontent.com/8241830/82385016-764f1700-9a74-11ea-8809-6486f3efdfaf.png)

**Comment by o-o00o-o** [comment]
Thanks for confirming you can't repro. Yeah it was strange, it felt like the type of instability that would go away on a restart of the application or a new connection but everything I tried I could repro exactly as I wrote over several connections and restarts of daxstudio. I'll try a restart of machine and different aas server tomorrow and let you know. I'll provide aas server version so we can compare and take it from there. Only other thing is that the aas that I was using was a S0 not sure if could be memory limit hit perhaps?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by o-o00o-o** [comment]
Hi I've tried this again after upgrading to an S1 and a fresh restart and I still got the same problem

My dev instance version is 15.1.38.39

However I tried running without a vpn so I am going straight to the server and this seemed to solve the problem. 

My VPN sends all my traffic through my work (when I'm working from home)

Any idea what I could do to resolve this while connecting to the VPN?

**Comment by dgosbell** [comment]
> However I tried running without a vpn so I am going straight to the server and this seemed to solve the problem.

That does seem to sound like it's an issue with the VPN and that is not really my area of expertise.

I don't do any explicit session management in DAX Studio, that is all handled by the server. When you start the first trace we issue a create trace command and pass in the session id for the current connection. When you add the second trace we issue an alter trace command just adding the event types relevant to the second trace type. I can't think what would cause the alter command to report that the session id is not found. 

Maybe your VPN is doing some sort of load balancing and the requests are getting routed through different IP addresses and causing an issue. But I'm not even sure if that would cause an issue as the session id should be included in the XMLA envelope and you can have multiple connections to the one session. 

You might need to talk to someone on your VPN team and see if they can help diagnose what is going on.

**Comment by dgosbell** [comment]
I've re-worked the tracing engine in v3 and the different traces should all start independently without interfering with each other now.
