### ISSUE TITLE
bug -- intellisense and autocomplete

### ISSUE THREAD

**Issue by selster** [DaxStudio/DaxStudio#337]
*on a win 7 64 bit computer, intellisense works on the first level but no further that is typing "tab" with bring up the choice of" table," but typing "."  and any other characters --- no second intellisense choices appear.  My version is DaxStudio_2_10_2

**Comment by dgosbell** [comment]
The "." character has no special meaning in DAX. Columns are referenced using `'table_name'[column_name]`  so if you type a table name then an opening square bracket `[ `then DAX Studio should prompt you with a list of the columns in that table.

**Comment by dgosbell** [comment]
I'm assuming from the lack of response that the previous reply resolved your issue.

**Comment by selster** [comment]
The first response was not emailed to me, but the 2nd was.  I see what you mean about 'table_name'[column_name].  This works, Thanks. But what about auto complete when writing some in M code such as 

Now it would seem that there would be lots of opportunities for auto complete to respond after I type the first "Table" and then hit ".".  Normally, I would expect to see possibilities that could follow "Table.", one of which would be "ExpandTableColumn".

I probably don't know how to enter M code and am hoping you can help me understand how to do this with DaxStudio.

Thank you,
SE

#"Expanded table.Data" = Table.ExpandTableColumn(#"Kept First Rows", "table.Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8"}, {"table.Data.Column1", "table.Data.Column2", "table.Data.Column3", "table.Data.Column4", "table.Data.Column5", "table.Data.Column6", "table.Data.Column7", "table.Data.Column8"}),

**Comment by dgosbell** [comment]
> I probably don't know how to enter M code and am hoping you can help me understand how to do this with DaxStudio.

You cannot execute M code via DAX Studio. 

M is used to load data into a tabular model and DAX is then used to query that data from a tabular. Microsoft has not provided any official APIs that allows people to write their own tools to execute M code. You have to use the "Get Data" option inside Excel or Power BI Desktop.
