### ISSUE TITLE
Effective User Name 

### ISSUE THREAD

**Issue by child043** [DaxStudio/DaxStudio#338]
If you use the effective user name option(connection to tabular server), an error occurs:
  Error Connecting: The following system error occured: Insufficient system resources exist to complete the requested service.

I specify the domain username like DOMAINNAME\username.
The username is correct.

**Comment by dgosbell** [comment]
I cannot reproduce this issue. And the "insufficient resources" error is not the sort of message you get from an authentication issue. It sounds like you maybe have some other issue with your role or your server that is cause this error message. Are you able to connect using this user or role from other tools?

**Comment by child043** [comment]
Sorry, i checked this on other client tools (SSMS, Excel), the same issue.
