### ISSUE TITLE
Trying to cancel a query returns "could not load file or assembly"

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#339]
**Describe the bug**
If I start a query and then hit the cancel button I get an error

Could not load file or assembly 'Microsoft.Excel.AdomdClient, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

and the connection is rendered unsuable

**To Reproduce**
- write an evaluate statement that will take some time to run
- hit the cancel button
- see the error in the output pane

**Expected behavior**
query to be cancelled and ability to rerun a query on the same connection

**Screenshots**
NA

**Additional context**
Standard install.. version 2.10.2

**Comment by dgosbell** [comment]
Thanks for reporting this, it's a side effect of another change. A fix for this is checked in and will go out in the next release (which should hopefully be sometime in the next week or so)
