### ISSUE TITLE
New tab default as current connection

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#34]
Would not it be nice if – when using CTRL-N to open a new tab – DAX Studio replicated the same connection settings of the current one? It is just a few clicks, but whenever I open a new tab, I quite always want to run a new query on the same database with the same settings for query plan and server timings.

**Comment by cboneill0099** [comment]
I think this would be a great addition, I often find myself copying a query and pasting it into the connect dialog after the Ctrl-N keystroke because I'm so used to the way SSMS works.

**Comment by dgosbell** [comment]
In v2.8.0 we added Ctrl-Shift-N to open a new window with the same connection as the current window
