### ISSUE TITLE
Output to Clipboard

### ISSUE THREAD

**Issue by SalCag** [DaxStudio/DaxStudio#340]
**Is your feature request related to a problem? Please describe.**
I miss the possibility to click on the top left corner of the result and Copy/Paste the list to Excel.

**Describe the solution you'd like**
I would like to have the possibility to perform the action described above like it's possible in SSMS.
Alternatively, I would like to have an "Output to Clipboard" option

**Describe alternatives you've considered**
I looked at the Excel Plugin.
It's a good solution but this feature could help to support other work procedures.

**Additional context**

**Comment by dgosbell** [comment]
I'm not entirely sure why that doesn't work. I'll have to do some testing to see if it's a bug in the Microsoft datagrid or if it's something about the way we have it configured.

In the short term there is a work around. If you click on any cell in the results, then clicking in the top left corner appears to work to select everything (as does typing ctrl+A)

**Comment by dgosbell** [comment]
Output to Clipboard was added in the previous release.
