### ISSUE TITLE
Intellisense and autocomplete

### ISSUE THREAD

**Issue by selster** [DaxStudio/DaxStudio#342]
I did not receive a notification of your initial replay for issue #337 (so did not reply) but I did get an email when you closed the issue.  Therefore, I will keep track of this manually, from this point on, in case you post a response.

Yes, 'table_name'[column_name] works perfectly.  But what about entering M code such as the following taken from power bi's advanced editor:

#"Expanded table.Data" = Table.ExpandTableColumn(#"Kept First Rows", "table.Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8"}, {"table.Data.Column1", "table.Data.Column2", "table.Data.Column3", "table.Data.Column4", "table.Data.Column5", "table.Data.Column6", "table.Data.Column7", "table.Data.Column8"}),

At the very helpful http://darren.gosbell.com/, you say to write code like this.  I wish there was more writing like this?  Do you have more?  

EVALUATE
ADDCOLUMNS(VALUES('date'[Month])
,"Internet Total Sales"
, [Internet Total Sales]
)

This works great.  But if I type 

Table(E ([for ExpandTableColumn]

DaxStudio does not offer any possible choices that beging with the letter 'E'?  

I am hoping that you can help me with this as I would like to write M code in DaxStudio which is just wonderful!

Thanks,
selster

**Comment by dgosbell** [comment]
That's because there is no DAX fuction called ExpandTableColumns. 

> I am hoping that you can help me with this as I would like to write M code in DaxStudio which is just wonderful!

As I mentioned in the other issue you cannot run M directly in DAX Studio and currently Microsoft has not provided any APIs that would allow for a third party tool to do anything like this.
