### ISSUE TITLE
When using Query Builder with an "Is not" filter, KEEPFILTERS is misspelled as KEEPFLTERS in the DAX query

### ISSUE THREAD

**Issue by OwenAuger** [DaxStudio/DaxStudio#343]
**Describe the bug**
When using Query Builder with an "Is not" filter, the DAX generated contains "KEEPFLTERS" rather than "KEEPFILTERS".

In source code, appears to be on row 127 of /src/DaxStudio.UI/Model/QueryBuilder.cs

**To Reproduce**
1. Connect to a data source, then click Query Builder on Home tab.
2. Drag any field from the Metadata pane to the Builder pane Filters section
3. Select "Is not" as the filter type and enter any value
4. Click Edit Query
5. The query pane will show code containing "KEEPFLTERS"

**Expected behavior**
The DAX code should contain "KEEPFILTERS" rather than "KEEPFLTERS".

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/30336592/84141130-c71bc380-aaa6-11ea-95f0-bee27c26771c.png)

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fix for this checked in and I might do a small point release in the next week or two for it.

**Comment by dgosbell** [comment]
just released v2.11.1 which should fix this issue
