### ISSUE TITLE
Format Query (F6) doesn't work in Edit Measure Expression dialogue (new preview Query Builder)

### ISSUE THREAD

**Issue by BVMather** [DaxStudio/DaxStudio#347]
In the Edit Measure Expression dialogue where you author a new measure in the new preview query builder, if you click Format Query (F6) to try to format the measure on its own it is not a valid DAX expression and you receive the error response from DAXFormatter.com

_Syntax error, expected: +, -, *, /, ^, &, =, ==, >, <, >=, <=, <>, &&, ||, IN, .... etc_

Of course a work around is to click 'Ok' and then run the formatter in the Edit Query pane, but perhaps the Format Query (F6) option should be disabled when the Edit Measure Expression dialogue is open, or you might consider the following:

Either the Format Query (F6) could be disabled, or perhaps you might 'wrap' the measure in a simple DEFINE MEASURE 'Table'[MyMeasure] = _MyDAXMeasureExpresssion_ EVALUATE ROW("",[MyMeasure]) before posting it to DAXFormatter.com and then parse the response to only return the formatted _MyDAXMeasureExpression_

*To Reproduce**
1. Go to Query Builder
2. Click on +New to add a new Measure
3. Type a new DAX expression in the Edit Measure expression dialogue box
4. Click on Format Query (F6)
5. See error return from 

**Expected behaviour**
When you run Format Query (F6 ) in the Edit Measure Expression pane then the measure expression should be correctly formatted

**Comment by dgosbell** [comment]
Thanks for reporting this. I actually just noticed this myself and have just checked in a fix. I will probably do a small point release in the next week or two for this.

> perhaps you might 'wrap' the measure in a simple DEFINE MEASURE 'Table'[MyMeasure] = MyDAXMeasureExpresssion EVALUATE ROW("",[MyMeasure]) before posting it to DAXFormatter.com and then parse the response to only return the formatted MyDAXMeasureExpression

It's actually even simpler than this as daxformatter.com understands that an expression starting with "=" is a scalar expression. So I'm just injecting a leading "=" and then stripping it out. So one temporary work around is to do that manually until I get the update published.

**Comment by BVMather** [comment]
Now that is fast!! 😁 Awesome new feature, thanks!

**Comment by dgosbell** [comment]
just released v2.11.1 which should fix this issue
