### ISSUE TITLE
Metadata database context is retained after reconnect

### ISSUE THREAD

**Issue by xhead** [DaxStudio/DaxStudio#348]
When I am connected to an Azure Analysis Services instance, I frequently have my query window disconnected after inactivity (this happens in SSMS too, I think it's about AAD tokens or something). 

After I click Connect, the database context drop-down changes to the first model that is on the server, and the metadata refresh is performed against that model. I always have to wait until that is done, then select the database that I was using in my query, and wait for the metadata refresh for that database before I can run my query again. 

I would like it if when reconnecting, the database context remains set to the database that I had been using.

**Comment by dgosbell** [comment]
I think your suggestion in item #349 about automatically re-connecting would also solve this issue

**Comment by xhead** [comment]
I was unable to reproduce this issue yesterday, with version 2.11.0, connected to AAS. See #349

**Comment by dgosbell** [comment]
This should have been fixed in 2.13.1 which now automatically re-connects if the server drops the connection
