### ISSUE TITLE
Automatically reconnect to Azure Analysis Services

### ISSUE THREAD

**Issue by xhead** [DaxStudio/DaxStudio#349]
When I am connected to an Azure Analysis Services instance, I frequently have my query window disconnected after inactivity .

This happens in SSMS too, I think it's about AAD SSO refresh token lifetimes or something. But to some degree I find SSMS is slightly better at handling a disconnect than DaxStudio.

SSMS does not give an indication that the query connection has been dropped, so I only know this when I attempt to run the query. I get a error dialog, but after I dismiss it, I can immediately execute the query again, and SSMS will reconnect the query to the server (including database context) and execute. (This is behaviour for connecting to Azure SQL database instances, I don't use SSMS as much for Azure Analysis Services queries). 
(I'd like SSMS to automatically reconnect the first time, rather than giving me the error dialog, but at least I can just execute the query again which also reconnects. )

I would like it in Dax Sstudio, if I attempt to execute a query that has been disconnected, that it would automatically attempt to reconnect (including database context) and execute the query.

**Comment by dgosbell** [comment]
Do you know roughly how long it takes for your connection to timeout? Can you post the text or a screenshot of the error when you get disconnected? Does it mention something about the session no longer existing? I'm wondering if AAS has more aggressive idle session timeouts.

**Comment by dgosbell** [comment]
@xhead are you able to provide any more information about these connection issues? I don't have easy access to an instance of AzureAS I'll have to spin one up specially to test this so I'd like to gather as much information as I can beforehand to minimize the cost of that.

**Comment by xhead** [comment]
hi, sorry for the delay, I'll try to get you some further information this week.

**Comment by xhead** [comment]
Ok, yesterday, I was unable to reproduce this issue in the current version (2.11.0). 

I had a DAX query connected to a tabular model on AAS. I executed it, then left DAX editor in the background and came back in 10 minutes and ran it again. No issue. I left it 15 minutes and ran it again. 20 minutes and ran it. 30 minutes, 45 minutes, 60 minutes. Then overnight. All of these had no issues running the query.
![DaxEditor_Connection_Issue349](https://user-images.githubusercontent.com/19212199/84925275-4739be80-b08f-11ea-893c-d915850ac1ed.JPG)


I noticed a slight delay in the UI after the longer inactive periods - maybe 45 minutes and greater? Also, after these delays, the metadata window stayed with its current database focus.

**Comment by dgosbell** [comment]
Version 2.13 now includes automatic reconnection if the connection is dropped
