### ISSUE TITLE
Information need - Is there a License agreement/declaration for DAX Studio

### ISSUE THREAD

**Issue by tljthree** [DaxStudio/DaxStudio#35]
My company sees value in adopting DAX Studio to support build and execution of DAX Queries on Analysis Services Tabular data sources. I can't seem to find any declaration of DAX Studio's usage agreement, so that my company can understand that it is allowed to use this software. Can someone direct me to that verbiage?

Thanks,
Tom in Indy

**Comment by dgosbell** [comment]
Yes,  we use the [Microsoft Permissive Open Source License](https://opensource.org/licenses/MS-PL)
There is also a copy of this license in the first screen of the installer, so if you run that you can also read this from there.
