### ISSUE TITLE
Would love to see a winget package for DAX Studio

### ISSUE THREAD

**Issue by toddkitta** [DaxStudio/DaxStudio#350]
I would love to install DAX Studio via winget for repaves!

https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema
https://github.com/microsoft/winget-pkgs

**Comment by dgosbell** [comment]
This looks interesting although it looks like winget is still in tech preview at the moment. 

The initial submission process looks pretty simple, but I'd want to look at automating it somehow. Ideally I think I'd want to have this configured somehow, so when a new release is published it also triggers an update to winget. I've also been looking at publishing to chocolatey also and I don't want to manually go around updating multiple repositories.

**Comment by dgosbell** [comment]
I just had a go at pushing a manifest for v2.12.2 up to winget. It's a very manual process at the moment involving forking a github repo and creating a pull request. So if you wanted to try installing with winget I think it should work.

I'm now also pushing to chocolatey with each release, so if you have that you can do a `choco install daxstudio `

**Comment by dgosbell** [comment]
I've been able to automate the process of updating winget now so I'm going to close this issue
