### ISSUE TITLE
Error exporting data to SQL Server Table: Column 'RowCount' does not belong to table DAXResult.

### ISSUE THREAD

**Issue by bogomda** [DaxStudio/DaxStudio#351]
After installing last version of Dax Stuido, when importing data to SQL server from PowerBI (or excel), i get error.

In new version of Dax Studio,
1. I click Export Data
2. Choose SQL Table
3. Enter my instance of server and database
4. get error Error exporting data to SQL Server Table: Column 'RowCount' does not belong to table DAXResult.

**Expected behavior**
table should load into server as it's done in prior versions of Dax Studio

**Screenshots**
![Error](https://user-images.githubusercontent.com/66798479/84428072-db210b80-abf3-11ea-9649-b1be728ce3d5.JPG)

**Comment by dgosbell** [comment]
Thanks for reporting this. I have identified the issue and I should be able to get a fix out shortly.

**Comment by bogomda** [comment]
Thanks Darren! You tool is excellent!!!!

Danil Bogomazov
