### ISSUE TITLE
Define measure does not include certain comments

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#357]
**Describe the bug**
The "define measure" feature does not include comments at the beginning and at the end of a measure

**To Reproduce**
Create a measure like this in Power BI:
TestMeasure =
-- Comment at the beginning
SUMX ( 
    Sales, -- Comment in the middle
    Sales[Quantity 
)
-- Comment at the end

**Expected behavior**
The three comments should be included, but only the "Comment in the middle" is present in the code.

**Comment by dgosbell** [comment]
This appears to be an issue with us using MDSCHEMA_MEASURES to get the measure expression. We should check if TMSCHEMA_MEASURES is available and use that instead as that includes the leading and trailing comments. (this will be available in recent versions of the engine, I'm not sure about PowerPivot or older versions of SSAS)

**Comment by marcosqlbi** [comment]
If we change the code in MetaDataVisitorADOMD.cs, we should implement a logic that looks for TMSCHEMA_MEASURES and fallback to MDSCHEMA_MEASURES if the TMSCHEMA_MEASURES is not found, so we don't lose compatibility with PowerPivot and older AS engines.

**Comment by dgosbell** [comment]
Yep, that was my thought too. I just checked in a fix for this

**Comment by marcosqlbi** [comment]
Great - it works well!
