### ISSUE TITLE
Export VertiPaq Analyzer Metrics in .csv or excel or .json formats

### ISSUE THREAD

**Issue by ritu-lvn** [DaxStudio/DaxStudio#360]
Currently Export of VertiPaq Analyzer Metrics is possible as .vpax file format only. It would be very helpful if export is possible in .csv or .json or excel file formats.

**Comment by dgosbell** [comment]
The vpax file is just a zip format with json files inside. And the contents are just built up by running a number of DMV queries which you could also just do yourself. What use cases do you have for the raw data? Is there functionality we could add to DAX Studio?

**Comment by ritu-lvn** [comment]
Thanks for response. 
How can we unzip the vpax file so that i can use the json files inside. I want to create a standard Power BI Report to Analyze the data of the model obtained through vpax file.?

**Comment by marcosqlbi** [comment]
You can rename the VPAX into a ZIP file - or better you can open the VPAX file in Power Query with the same API that opens a ZIP file.
Look at the PowerQuery code used in VertiPaq Analyzer, you can use the very same code in Power BI.

**Comment by ritu-lvn** [comment]
Thanks for providing quick solution @marcosqlbi

**Comment by dgosbell** [comment]
since you have a solution for this I'm going to close this issue
