### ISSUE TITLE
Exporting Tables to SQL Server

### ISSUE THREAD

**Issue by rminder** [DaxStudio/DaxStudio#361]
I am attempting to export the tables in my Tabular model to SQL Server. There are six tables and each of them generates the same error:

Error exporting data to SQL Server Table: Column 'RowCount' does not belong to table DAXResult.

None of my tables have a column named 'RowCount'.

I am using v2.11.0.

**Comment by dgosbell** [comment]
duplicate of #351

**Comment by dgosbell** [comment]
just released v2.11.1 which should fix this issue
