### ISSUE TITLE
Query Builder misspells KEEPFILTERS

### ISSUE THREAD

**Issue by edhans** [DaxStudio/DaxStudio#364]
When using the Query Builder after enabling it in Advanced view, when it uses KEEPFILTERS it is misspelled, causing the query to fail.

**To Reproduce**
I have an "IsFuture" column in my date table that is true/false. To recreate the issue:
1. Drag the date to the Columns Measure portion of Query Builder
2. Drag IsFiltered field to the filters and set it to false.
3. Run query - errors out. This is the query it builds - notice the spelling of KEEPFILTERS below
// START QUERY BUILDER
EVALUATE
SUMMARIZECOLUMNS(
    Dates[Date]
    ,FILTER(KEEPFLTERS(VALUES( Dates[IsFuture] )), Dates[IsFuture] <> false())
)
// END QUERY BUILDER

**Expected behavior**
Expect it to not spell functions wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/45298358/85038282-43637600-b13b-11ea-9fd3-b28c6ef2657b.png)

**Additional context**

**Comment by marcosqlbi** [comment]
This is already fixed in the latest version 2.11.1.
