### ISSUE TITLE
data export 2 csv doesn't keep date format but convert to datetime format 

### ISSUE THREAD

**Issue by dub161** [DaxStudio/DaxStudio#365]
**Describe the bug**
when exporting a dataset from powerBI using data export feature, it doesn't retain the date format specified in PB but exports a date-time format with hours 00:00:00.000 

**To Reproduce**
1. create dataset with date format
2. export in csv with export data features

**Expected behavior**
keep the date format as specified in PB

**Screenshots**
in PowerBI : 
![image](https://user-images.githubusercontent.com/67265756/85275739-112a7f00-b481-11ea-861d-14f9e1a2cf40.png)
in CSV :
![image](https://user-images.githubusercontent.com/67265756/85275819-31f2d480-b481-11ea-858f-d9a65f906dc8.png)

**Additional context**

**Comment by dgosbell** [comment]
This is actually the way the export is designed to work. There are a number of underlying issues here.

1. the tabular engine actually only has a datetime data type. They "Date" and "Time" options in Power BI are just datetime fields with the the unwanted portion zeroed out and a default format string applied to hide the zeroed portion.

2. The assumption with exporting to a file is that you are after an accurate representation of the raw data that you then want to import into some other program. For this reason we chose to use the ISO 8601 standard format for datetime columns. This format is unambiguous (unlike other date formats) and should be read without issues by pretty much any program you can name.

Using the format specified in the model or the default format for the local machine can cause issues, specially with ambiguous formats like dd/mm/yyyy (UK, AU default) and mm/dd/yyyy (US default) or language specific formats like the one in your screenshot that include day names in a specific language. These can either cause issues with programs recognising the data as dates or in some cases can actually cause the data to be read incorrectly. This can specially be an issue if you create the file on one machine and then load it into another machine (which is often the whole reason why you are exporting to a file in the first place)

**Comment by dgosbell** [comment]
closing as by-design
