### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by rywilli** [DaxStudio/DaxStudio#369]
**Describe the bug**
Downloading of the DAX Studio 2.11.1 software is not working. I am getting the error 'DAXStudio_2_11_1_se....exe was blocked because it could harm your device.' Tested with another user from another organization and they are also reporting issues.

**To Reproduce**
1. Go to https://daxstudio.org/
2. Click on Dax Studio 2.11.1 installer

**Expected behavior**
Download software

**Screenshots**
Org 1:
![image](https://user-images.githubusercontent.com/47151758/86023686-f82e4a80-b9f9-11ea-870b-502fecebfd7a.png)

Org 2:
![image](https://user-images.githubusercontent.com/47151758/86023715-03817600-b9fa-11ea-85b8-62e49f434da9.png)

**Comment by dgosbell** [comment]
So the first issue is Windows Smartscreen. This has always been a feature of Edge and Windows 10, but it seems to have gotten more aggressive this year. The following documentation shows how you can still install around Smart Screen
[https://daxstudio.org/documentation/installation/smart-screen/](https://daxstudio.org/documentation/installation/smart-screen/)

We are exploring options to improve this, but there does not appear to be an easy/inexpensive solution.

The second issue looks to be a problem with github, I can't reproduce this so it may have been a temporary thing.

**Comment by dgosbell** [comment]
The new 2.12 release is now live with a new EV certificate which should prevent these warnings
