### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Smtz7** [DaxStudio/DaxStudio#37]
I am unable to get DaxStudio 2.7.1 to install . When I get to the accept agreement screen, it wont let me click on I accept the agreement, to move continue.

I also tried scrolling to the bottom and it didnt work then either. I tried an earlier version as well with the same issue.

Any ideas?

Thanks

**Comment by dgosbell** [comment]
I've never heard of this before. The license screen is just a standard part of the install tool that we are using. Are you saying that the radio buttons at the bottom of the screen are disabled or is it when you click on the accept option that the "Next" button does not enable? Can you post a screenshot of what you see for this screen?

**Comment by dgosbell** [comment]
Closing due to lack of response to request for more information
