### ISSUE TITLE
"Define Measure" not working in 2.11.1

### ISSUE THREAD

**Issue by matt5mitchell** [DaxStudio/DaxStudio#373]
**Describe the bug**
Right clicking on a measure and selecting "Define Measure" does not work in 2.11.1

**To Reproduce**
1. Connect to tabular server
2. Select tabular model in left metadata pane
3. Right click on a measure
4. Select "Define Measure"
5. Nothing appears in the main text editing window

**Expected behavior**
In prior versions of DAX Studio, the DAX code for the measure appears in the text editing window.

**Screenshots**
It's blank, so there's not much to show.

**Additional context**
Running Windows 10, hitting tabular models with compatibility level 1200
Re-installed 2.11.0 and "Define Measure" works as expected

**Comment by marcosqlbi** [comment]
I am not able to reproduce the issue. The behavior you describe exists for databases with a compatibility level lower than 1200 (e.g. 1100), but I tested models with compatibility level 1200 and it works as expected.
Please, can you confirm this happens on any database, or do you see the issue only in specific databases? Maybe there is something else causing the issue.

**Comment by matt5mitchell** [comment]
I did some further testing: installed 2.11.1 on another computer and tried multiple databases on multiple tabular servers.  I've narrowed down the behavior:
On one tabular server the icons in the "Traces" section of the ribbon are clickable and on a second tabular server these icons are grayed out (I'm not totally sure which permissions control this).  On the server where I don't have permissions to run traces, the "Define Measure" feature does not work.  This is a change from 2.11.0 (and other versions of DAX Studio I've used).

**Comment by dgosbell** [comment]
So the disabled trace buttons would mean that you do not have admin permissions on that server. We did a minor change to use TMSCHEMA_MEASURES (if it's available) instead of the MDSCHEMA_MEASURES DMV as the former one includes any leading/trailing comments which MDSCHEMA_MEASURES seesms to strip out. I can add an extra check to make sure the user also has admin rights before switching to use TMSCHEMA_MEASURES which should fix this issue
