### ISSUE TITLE
Microsoft Edge (the new one) blocks download

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#375]
When I try to download DAX Studio in the new Microsoft Edge, I get this:
![image](https://user-images.githubusercontent.com/10683126/87489600-c74f4600-c686-11ea-837d-03007c8554f0.png)

Yes, I can still download it by clicking a few extra buttons, though it may discourage some people.

**Comment by DaniilMaslyuk** [comment]
Windows Defender blocks it too:
![image](https://user-images.githubusercontent.com/10683126/87489819-52304080-c687-11ea-9069-b155943a40cc.png)

**Comment by dgosbell** [comment]
Yep, Defender/Smartscreen is the same thing. At the moment you just have to use the steps documented here
[https://daxstudio.org/documentation/installation/smart-screen/](https://daxstudio.org/documentation/installation/smart-screen/)

Apparently tens of thousands of downloads against my digital signature are not enough for "Smart" Screen to consider DAX Studio as a commonly downloaded file.... We are making some progress towards possibly getting this sorted out, but no timeline at the moment.

**Comment by marcosqlbi** [comment]
Yes I am confident this will be fixed with the next release, I hoped it was done by last week but there was a delay in getting the required certificate.

**Comment by dgosbell** [comment]
The new 2.12 release is now live with a new EV certificate which should prevent these warnings
