### ISSUE TITLE
Exporting empty results sets to csv or SQL SERVER tables

### ISSUE THREAD

**Issue by JonathanApam1970** [DaxStudio/DaxStudio#377]
When exporting an empty result set to csv or SQL SERVER tables , nothing is exported and an error is generated. It would be nice to export an empty result set without generating an error...The error is attached..
![DAX_STUD_ERR](https://user-images.githubusercontent.com/68335056/87549746-7b17fc00-c6ae-11ea-9843-78e870d1106c.JPG)

**Comment by dgosbell** [comment]
Thanks for logging this. I don't actually have any models with empty tables so this is not a scenario I tested for. A fix for this will be included in the next release

**Comment by JonathanApam1970** [comment]
Thanks and most appreciated


Jonathan

Jonathan Mukundu Mukundu |Technical Advisor, Data Management,
Zambia Defence Force Prevention, Care and Treatment Project.
Tiyende Pamodzi Road, Off Nangwenya Road, Farmers Village,
Next to ZNFU offices, Showgrounds Area |P.O. Box 320303 |Lusaka, Zambia
T: 260.211.368190-99 EXT 58141|D: 368141 F: 260.211.257 329 |
mailto:jmukundu@fhi360.org|FHI 360 Facebook<https://www.facebook.com/fhi360>|www.fhi360.org<http://www.fhi360.org/>
Personal Cells:+260 955 884 421,+260 977 395 507, +260762172464
Alternative E mail : jonamukundu@gmail.com<mailto:jonamukundu@gmail.com>
