### ISSUE TITLE
error of daxstudio.pbitools.json file

### ISSUE THREAD

**Issue by zhanglhz** [DaxStudio/DaxStudio#378]
**Describe the bug**
When I update or reinstall DaxStudio 2.11.2, the install path is not default path ( C:\Program Files\DAX Studio ), the installer will modifier the "path" element to default path

![image](https://user-images.githubusercontent.com/8307604/87740902-e7f9d600-c815-11ea-9d47-c23659f62f6e.png)

**Comment by dgosbell** [comment]
Thanks for reporting this. I did have code in the install to update this path, but it's not being triggered correctly. A fix for this will be included in the next release.

**Comment by zhanglhz** [comment]
Thanks. @dgosbell

**Comment by v-sasraj** [comment]
I had similar issue while installing this version of DAX, i have chosen "Installed for me" which caused me error, when i change to "Install for everyone" there was no bug or error, and the external tools in PBI desktop works fine

**Comment by zhanglhz** [comment]
> I had similar issue while installing this version of DAX, i have chosen "Installed for me" which caused me error, when i change to "Install for everyone" there was no bug or error, and the external tools in PBI desktop works fine

**Comment by zhanglhz** [comment]
@v-sasraj 
you can modify daxstudio.pbitools.json in "C:\Program Files (x86)\Common Files\microsoft shared\Power BI Desktop\External Tools\", edit "path" element to your install path.

**Comment by v-sasraj** [comment]
thanks for the support @zhanglhz
