### ISSUE TITLE
Install fails with error stating DaxStudio.vsto in use

### ISSUE THREAD

**Issue by Mixednuts9** [DaxStudio/DaxStudio#379]
![image](https://user-images.githubusercontent.com/39285167/87750144-39fa2600-c82d-11ea-8317-84c261cec959.png)

A reboot does not seem to correct this....

Note: The install is being attempted on a VM on which a PowerBI Enterprise gateway is also running.

**Comment by dgosbell** [comment]
I'm not entirely sure what this might be, I've never seen this issue before but there are a couple of things you could try.

I assume that you are trying to upgrade over the top of an earlier version, so you could try uninstalling that first, then installing the new version.

Or if that does not work you could trying going into the "Services" settings (I think if you search in the start menu for "services" this should come up) then temporarily stop the SMS Agent Host and then restart it after you've installed. Apparently from doing some google searches this is some service used by System Centre Operations Manager to deploy software, but I don't know why it would be holding the vsto file open, that file is part of the Excel Addin.

**Comment by Mixednuts9** [comment]
Thank you Darren. I ended up bouncing the VM once again, but before I attempted the install, I deleted the vsto file and re-started the install. It ran through to completion this time.

I can confirm that Excel was not running at the time, however it had been run previously....?

Either way, it is now working. 

Thank you!
John

**Comment by dgosbell** [comment]
Very strange, but I'm glad you got it sorted.
