### ISSUE TITLE
daxstudio.pbitool.json file issue

### ISSUE THREAD

**Issue by e5office** [DaxStudio/DaxStudio#383]
**Describe the bug**
the path in this file cannot automatically changed based on the installation path, so if the path is not what list below, the DAX Studio cannot open directly via power bi desktop.
"version": "1.0",
  "name": "DAX Studio",
  "description": "Use DAX Studio for DAX authoring, diagnosis, performance tuning and analysis.",
  "path": "C:\\Program Files\\DAX Studio\\DaxStudio.exe",
  "arguments": "/server=%server% /database=%database%",
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
This should be fixed now in the 2.12 release

**Comment by fdawans** [comment]
Hello,

I think I have a similar issue as DAX Studio does not appear in my ribbon.
The installation path is not C:\Program Files\DAX Studio\DaxStudio.exe (all users I assume).
But seems to be USER\AppData\Local\Programs\DAX Studio (only for the current user).
I also do not have a .json file in C:\Program Files (x86)\Common Files\microsoft shared\Power BI Desktop\External Tools

Thank you for your help,

**Comment by dgosbell** [comment]
> Is it possible to have the External Tools integration with a non-admin install?

@fdawans  No it's not. 

The location Microsoft chose for the json file requires admin rights, so I can only write out that file when doing an All Users install. I do have this noted in the documentation for the different [installation types](https://daxstudio.org/documentation/installation/) but I should probably also add an External Tools in the features section to make this information easier to find.

You can still connect to the same Power BI Desktop models with DAX Studio installed for the current user, You just have to launch it separately and choose the Power BI file from the connection dialog in DAX Studio.
