### ISSUE TITLE
Refresh metadata issue

### ISSUE THREAD

**Issue by VidasM** [DaxStudio/DaxStudio#385]
In my environment, it takes about 20 seconds to refresh metadata and this causes issues with DaxStudio.
1. When I open DAX file or first connect with DAX Studio I have to wait 20 seconds to get metadata for first random database from the server.
2. When I switch to my correct database, I have to wait again for 20seconds for metadata to refresh.
3. Any time I change measure code and deploy changes to the server, after I come back to DAX Studio, I have to wait 20seconds for metadata refresh.
If I will not wait for metadata refresh to complete and will try to execute my DAX statements, I will get an error message:
Probable I/O rate condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in thread-safe way...

Can you please make metadata refresh configurable with options: 
- autorefresh (default option as it is right now)
- ask if you want to refresh metadata when change detected
- do not refresh metadata

**Comment by dgosbell** [comment]
So we already have options to switch the automatic metadata refresh off. And you can even choose this based on the different types of connections.
![image](https://user-images.githubusercontent.com/8241830/88233253-aefcae00-ccba-11ea-9549-a44d867476db.png)
But also having some sort of prompt option is a good idea.

**Comment by VidasM** [comment]
Darren, Thank you! I totally missed that there is an options screen! This will save me lots of time and I also found there "Run Benchmark" option that I will try.
Thanks again! I cannot imagine my work without DAX Studio, it is greatest tool!
