### ISSUE TITLE
Add column headers to performance analyzer data when copying into Excel

### ISSUE THREAD

**Issue by m-kovalsky** [DaxStudio/DaxStudio#391]
**Is your feature request related to a problem? Please describe.**

After loading performance analyzer data into DAX Studio, you can copy the data and paste it into Excel. However, when you paste it into Excel there are no column headers.

**Describe the solution you'd like**
Would be great to have column headers when copying perf analyzer data from DAX Studio to Excel or a text editor.

**Describe alternatives you've considered**

**Additional context**

**Comment by m-kovalsky** [comment]
Also, when pasting it into Excel it doesn't paste the Query. It shows all columns besides the query.

And, you can only use Ctrl-C in DAX Studio for copying the perf analyzer data - there's no right click - copy option.

**Comment by dgosbell** [comment]
Thanks for logging this, I think they should all be relatively simple to fix
