### ISSUE TITLE
Application freezes during initial launch with partial assembly bind error (AvalonDock.Themes.VS2013)

### ISSUE THREAD

**Issue by jdepm** [DaxStudio/DaxStudio#392]
**Describe the bug**
Application freezes during initial launch (splash screen icon visible).

**To Reproduce**
1. Launch the application from a shortcut (or directly open the executable)
2. (freezes)
3. Close the application from task manager.

**Expected behavior**
Application loads

**Screenshots**
n/a

**Additional context**
Please see the following fusion error message:

*** Assembly Binder Log Entry  (7/28/2020 @ 2:28:22 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = AvalonDock.Themes.VS2013, Culture=neutral
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: AvalonDock.Themes.VS2013, Culture=neutral | Domain ID: 1
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/Program Files/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\DAX Studio\DaxStudio.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/bin/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/bin/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/bin/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/DAX Studio/bin/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.EXE.
LOG: All probing URLs attempted and failed.

**Comment by dgosbell** [comment]
This is just a warning not an error a fatal binding error would cause a crash before the splash screen starts. It's coming from one of the third party controls. 

Can you try starting up the application with [diagnostic logging enabled](https://daxstudio.org/documentation/troubleshooting/logging-settings/) and attach the log file to this issue?

**Comment by jdepm** [comment]
The program freezes before the log file can be generated, so there is nothing to attach.  I did confirm that the log file path is uncommented and files have previously been created in the log folder from months ago.

**Comment by dgosbell** [comment]
Often by the time you see the splash screen the logging should have started. The only other issue I can think of is some sort of corruption with the .Net framework on your machine. I'm not able to reproduce this problem on any of the machines I have access to and if I create a new Win10 VM and install DAX Studio it works fine.

Can you zip up and attach the fusion logs generated by DaxStudio as the VS2013 theme problem is a known issue but it does not crash the application.

Can you also post the output from DaxStudio.Checker.exe?

I'm assuming that you are running the latest 2.12.0 version - how did you install it - All Users/Current User/portable ?

**Comment by dgosbell** [comment]
closing due to lack of response
