### ISSUE TITLE
Export Output as a file

### ISSUE THREAD

**Issue by rchungsw2** [DaxStudio/DaxStudio#394]
**Describe the bug**

It only generates a single table executed by the last EVALUATE function even though there are several EVALUATE function for querying tables.

Before the recent update, I was able to get as many table outputs with csv extension such as _1.csv, _2.csv ... as triggered by EVALUATE function.  When multiple EVALUATE functions triggered for querying tables, the output shows the number of tables executed by EVALUATE statement. 

Please look into the issue. Thanks always for the great product.

**To Reproduce**
1. Go to 'Dax Studio'
2. Click on 'Output as a file'
3. Input multiple EVALUATE function for querying tables.
4. Save the result
5. Only 1 table will be generated.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
Thanks for logging this. I found the issue and a fix for this will be in the next release.
