### ISSUE TITLE
Files gone after a crash

### ISSUE THREAD

**Issue by darlove** [DaxStudio/DaxStudio#396]
Hi.

I was editing code and out of the blue DS crashed :( All my unsaved files are gone and I did spend a lot of time to create them :(((

Would it not be possible to save the files in the background every x minutes (settable?) so that after a crash one could recover the saved versions? Just the way it works in Office or SSMS?

Thanks.

**Comment by dgosbell** [comment]
We already have an autosave functionality that should do this, but there were circumstances where the autosave files got cleaned up when they should not have been. This should have been fixed in the 2.12.0 release. What version of DAX Studio are you using?

**Comment by dgosbell** [comment]
I'm pretty sure this is working in the current release as I just had a blue-screen and DAX Studio was able to restore all the files I had open so I'm closing this issue
