### ISSUE TITLE
Exception thrown when starting DaxStudio

### ISSUE THREAD

**Issue by thedaxshepherd** [DaxStudio/DaxStudio#398]
Version 2.12.1

When I start DaxStudio the connection window does not appear. I see in the output "Exception has been thrown by the target of an invocation". 

If I go to File->New the same thing happens. 

If I click Connect under Connection on the ribbon it repeats the error message every time I click the button. 

I do not see any way to actually select or change my connection. I had no issue with the previous version. I removed this new version and reinstalled but it did not fix it. 

![daxstudio](https://user-images.githubusercontent.com/60486315/89203745-b5244180-d57a-11ea-87a3-290b8027c129.png)

**Comment by marcosqlbi** [comment]
You can uninstall the latest version and install the previous one: https://github.com/DaxStudio/DaxStudio/releases/tag/v2.12.0
Darren will probably ask you some more details to reproduce the issue.

**Comment by thedaxshepherd** [comment]
I also tried the portable version to see if I could eliminate some variables and I get the same message. Here is one entry from the error log: 

2020-08-03 11:50:57.784 -05:00 [Error] "DocumentViewModel" "ChangeConnection" "Exception has been thrown by the target of an invocation."

**Comment by dgosbell** [comment]
Thanks for logging this. Unfortunately this seems to be an issue with a first time run where there is no history of previously connected servers. In this case the server name defaults to null and this error is thrown. I've fixed this and am just pushing out a 2.12.2 update

**Comment by thedaxshepherd** [comment]
The new version fixed the issue I was experiencing.

**Comment by kumarkk20** [comment]
Hello Team
Could you help me to connect data model in DAX Studio from Power BI Desktop , Attached error snapshot
![image](https://user-images.githubusercontent.com/68598100/90095591-bc9fd380-dd4e-11ea-93ae-4492a6769c41.png)

Thanks in advance.
![ConnectionError](https://user-images.githubusercontent.com/68598100/90095673-0092d880-dd4f-11ea-9f55-31fa04b37be0.JPG)

**Comment by dgosbell** [comment]
Can you please open an new issue rather than replying to one that is already closed? And can you attach an example PBIX file which exhibits this behaviour as I cannot replicate this issue.
