### ISSUE TITLE
Connecting issue in DAX Studio

### ISSUE THREAD

**Issue by ulissessd** [DaxStudio/DaxStudio#399]
I am getting the error message below every time I open DAX Studio and it will not allow me to connect to any source.
I tried reinstalling it, but it also did not work.

This is in portuguese and it would translate as something like "An exception was activated by a call destination."

![image](https://user-images.githubusercontent.com/69219685/89344670-9c9c5000-d67c-11ea-9eb6-b55ae25d54db.png)

**Comment by dgosbell** [comment]
What version are you running? There was an error like this in 2.12.1 (see #398) which was just fixed in 2.12.2

**Comment by ulissessd** [comment]
I was running version 2.12.1, I just changed to 2.12.2 and it works now.
Thank you!
