### ISSUE TITLE
DAX Studio can't connect to Azure Analysis Services

### ISSUE THREAD

**Issue by vbakh** [DaxStudio/DaxStudio#4]
For a full connection string like asazure://westcentralus.asazure.windows.net/dbname it says *Could not connect to 'as azure://westcentralus.asazure.windows.net/dbname': The connection string is not valid"*.

For the same connection string with the protocol name removed (westcentralus.asazure.windows.net/dbname) , it says "... *Ensure that the server is running*".

**Comment by marcosqlbi** [comment]
I am able to connect when I open a connection first with SQL Server Management Studio (SSMS), and once authenticated, the connection works smoothly from DAX Studio, too. Did you try that?

**Comment by vbakh** [comment]
Yes, just tried it. It throws the same "The connection string is not valid" error. I tried to use it with and without user name with the same result. My user name is from my company's AD federated with Azure AD.

**Comment by marcosqlbi** [comment]
The string asazure://westcentralus.asazure.windows.net/dbname  works for me - but did you try connecting with SSMS before?

**Comment by vbakh** [comment]
Yes, I did have SSMS connected before starting DAX studio

**Comment by vbakh** [comment]
I tried it from another computer sitting within my company's network with the same negative result. SSMS connects to that cube just fine.

**Comment by marcosqlbi** [comment]
Did you try connecting SSMS with Active Directory Password Authentication? Just trying to guess, but I'm blind. I hope Darren will take a look at it.

**Comment by vbakh** [comment]
Yes, I used Windows Authentication with the user logged in as AD user on AD-joined computer.
![image](https://cloud.githubusercontent.com/assets/24619419/25560043/03a40b02-2cfe-11e7-9248-c9411ec8e9f9.png)

**Comment by vbakh** [comment]
I used three options: default connection (assuming that it takes the current user name domain), explicit user name in DOMAIN\UserName format, and a user name in UserName@domain.com format, all with the same result.
![image](https://cloud.githubusercontent.com/assets/24619419/25560083/d16dfa84-2cfe-11e7-866c-9bde5e8beed6.png)

**Comment by marcosqlbi** [comment]
Maybe the problem is your SSAS Driver. In SSMS you should have three options in Authentication, including Active Directory Password Authentication. Try installing SSMS 17.0, probably it also updates your SSAS drivers.

**Comment by vbakh** [comment]
Installed SSMS 17.0, connected with all three possible Auth options, tried to connect from DAX studio after each one (with or without providing user name & domain).  It didn't help. 

I might be wrong, but IMHO, Dax Studio didn't reach the "Connect to AAS" step - it stopped earlier, on that 'invalid connection string' issue. 
Here is the connection string for Windows Auth as shown on Azure Portal:
Provider=MSOLAP;Data Source=asazure://westcentralus.asazure.windows.net/dbname;Initial Catalog=<Initial Catalog>
I don't know whether DAX studio's connection string is the same or different. And I don't know what the 'Initial Catalog' parameter means in the SSAS world.

**Comment by marcosqlbi** [comment]
You should use only "asazure://westcentralus.asazure.windows.net/dbname" as server name in DAX Studio. It works on my notebook. I'm not sure whether there could be something else. I wrote a note to Darren, let's see if he can help.

**Comment by vbakh** [comment]
Yes, that's what I did. Marco, thanks for your help!

**Comment by dgosbell** [comment]
I think this might mean that the version of ADOMD.NET on the client machine may not be the latest version. DAX Studio uses ADOMD and AMO while I think SSMS use the OLEDB provider. 

Last time I tried to connect to Azure AS was months ago and I was getting the same error but at the time they had not yet released updates to ADOMD that knew how to authenticate to Azure, I think the latest preview version of ADOMD fixes this. You can download the latest version of ADOMD from here [https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers](https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers)

**Comment by vbakh** [comment]
Thanks Darren. 
I have SSMS 2017, ADOMD CTP2 and AMO CTP2 installed on that machine, and still getting the same error. Is there any way to see what's the actual connection string is?

**Comment by bjlay2000** [comment]
When I try to connect to Azure using our connection string, DAX Studio automatically closes without giving an error.  I spoke with Marco and he mentioned this thread.  When downloading and installing the latest drivers, it does not fix the problem.  I have a coworker who has the latest version of DAX studio as well and he has no issues connecting to the Azure dataset.  I have also tried uninstalling and reinstalling the software.
