### ISSUE TITLE
Customize Quick Access Toolbar shows 'New' twice

### ISSUE THREAD

**Issue by m-kovalsky** [DaxStudio/DaxStudio#400]
**Describe the bug**
The 'Customize Quick Access Toolbar' shows 'New' twice.

![image](https://user-images.githubusercontent.com/29556918/89401565-24866680-d71e-11ea-8028-9ddc9c25cb99.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
Thanks for logging this, that second option should be 'New (Existing Connection)' this will be fixed in the next release

**Comment by m-kovalsky** [comment]
Precisely. Thanks!
