### ISSUE TITLE
After hiding a tab you can't get it back

### ISSUE THREAD

**Issue by m-kovalsky** [DaxStudio/DaxStudio#401]
**Describe the bug**
If you hide a tab on the bottom section (by Output, Results, Query History), you can't get it back.

**To Reproduce**
1. Load Perf Data to DAX Studio
2. Right click on the tab showing your perf data, click hide
3. Can't seem to find a way to unhide it.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fix I'm testing that will re-open the Perf Data window when you click the button again
