### ISSUE TITLE
Allow selecting Intellisense items via TAB (instead of enter)

### ISSUE THREAD

**Issue by greglow-sdu** [DaxStudio/DaxStudio#404]
Hey Darren, in many other tools (particularly SSMS), we can select an item in Intellisense by hitting TAB rather than ENTER. It'd be really good if that was supported. Can't tell you how often I hit TAB there and it just closes. Thanks !

**Comment by dgosbell** [comment]
I'm having trouble reproducing this. The TAB key should work to select an intellisense option. There is an issue with using the mouse to click on the intellisense dropdown which I just noticed tonight, but the keyboard navigation should be OK.

If I type `EV` then [Tab] it fills out to `EVALUATE` then if I type `FI` then down arrow twice and [Tab] it fills in `FIND`
I've tried with tables, columns and measures and they all appear to work, so this might be related to some sequence of actions that I don't normally do.

**Comment by greglow-sdu** [comment]
Hi Darren,

Worth noting that SSMS also allows the space bar when selecting an Intellisense choice.

Regards,

Greg

Dr Greg Low

1300SQLSQL (1300 775 775) office | +61 419201410 mobile│ +61 3 8676 4913 fax
SQL Down Under | Web: www.sqldownunder.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sqldownunder.com%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091516274&sdata=SLHeEGAMmWUY5YIwcC4oAPYr%2F9RIZdi4MNASsdzwX2I%3D&reserved=0> |http://greglow.me<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgreglow.me%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091526278&sdata=IU8tnAITCjBxWafi3A9XpO9lF3PIwZJ8ad3t36lnxvs%3D&reserved=0>

**Comment by dgosbell** [comment]
Hmm, I can't reproduce this in SSMS 18.6 with a .dax window open, it just types a space. And Identifiers in DAX can have embedded spaces, so I'm not sure how this could work. For Example if you type `Product<space>` you could want the **Product** table or you could be about to type **Product Category** or **Product Subcategory**

**Comment by greglow-sdu** [comment]
Hi Darren,

No, it’s if the intellisense list appears, and I arrow down to the one I want, in SSMS you can hit space to choose that item (or tab).

Regards,

Greg

Dr Greg Low

1300SQLSQL (1300 775 775) office | +61 419201410 mobile│ +61 3 8676 4913 fax
SQL Down Under | Web: www.sqldownunder.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sqldownunder.com%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091516274&sdata=SLHeEGAMmWUY5YIwcC4oAPYr%2F9RIZdi4MNASsdzwX2I%3D&reserved=0> |http://greglow.me<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgreglow.me%2F&data=02%7C01%7Csspahelp%40microsoft.com%7C1f0ea4d6b97e4d897f3708d666d1e890%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636809449091526278&sdata=IU8tnAITCjBxWafi3A9XpO9lF3PIwZJ8ad3t36lnxvs%3D&reserved=0>
