### ISSUE TITLE
Tabs to Spaces?

### ISSUE THREAD

**Issue by darlove** [DaxStudio/DaxStudio#406]
Hi there.

Would it be possible to have a button that would turn TAB's to n spaces, n being something one can adjust in settings? Would it be possible as well to have a button that would turn spaces AT THE BEGINNING OF A LINE into TAB's?

Thanks.
Darek

**Comment by dgosbell** [comment]
We already have a setting in the options for "Convert Tabs to Spaces" and an indentation setting to control how many spaces you want inserted. If you switch this on when you type a Tab you will get n number of spaces.

And if you want to convert tabs in an existing file you could just use the Replace function, change to the regex mode then replace `\t` with as many spaces as you want.

**Comment by dgosbell** [comment]
I'm assuming that the above answer resolved this issue
