### ISSUE TITLE
Output measures containing formatted DAX

### ISSUE THREAD

**Issue by ZedLeb** [DaxStudio/DaxStudio#407]
The ability to output measure expressions from a pbix file is fantastic - however I'm having a problem with measures where the expression is formatted.

In DaxStudio 2.11.2 I use
`select * from $SYSTEM.MDSCHEMA_MEASURES`
and have tried all versions of output available and also altering the deliminator in File|Options but I cannot get the formatted expression to be properly delimited.

In the output file I get a newline for each line of the expression.

For example in the DaxStudio results I see this:
![image](https://user-images.githubusercontent.com/8373677/90001554-db8c6000-dc91-11ea-852f-c848c1ab6657.png)

but the output is like this:

![image](https://user-images.githubusercontent.com/8373677/90002369-de3b8500-dc92-11ea-9ebe-a81ad3bb17ff.png)

Does anyone know can I output the expression as it appears in the DaxStudio results?

Many thanks in advance

**Comment by dgosbell** [comment]
When you output to a file changing the type to one of the 2 csv options should work (it did in my testing)
![image](https://user-images.githubusercontent.com/8241830/90005974-66457d00-dcdb-11ea-9bd6-a41b0daf2956.png)

**Comment by ZedLeb** [comment]
Hi dgosbell - I've tried again but it still doesn't work :( 
I've even tried the custom export and changed some settings in the Options but no joy...
I sure I used the DAX formatter prog when preparing those particular expressions.  I wonder if there's some tabs or something else going on?

**Comment by ZedLeb** [comment]
Hi dgosbell - I've tried again but it still doesn't work :(
I've even tried the custom export and changed some settings in the Options but no joy...
I sure I used the DAX formatter prog when preparing those particular expressions. I wonder if there's some tabs or something else going on?

**Comment by dgosbell** [comment]
Can you attach an example file? 

I just tried formatting a multi-line DAX expression using Daxformatter.com I can't see any unusual characters in the output and using the default UTF-8 CSV option imported fine into Excel. 

![image](https://user-images.githubusercontent.com/8241830/90013633-fccc6b00-dce8-11ea-9540-fac4afa4f6c4.png)

**Comment by ZedLeb** [comment]
Thank you so much for your time @dgosbell 
I can't send the pbix as it is enormous (one of the reasons that I want to investigate the measures!)

If I send an example of the extracted file - would that help?

I've also tried using PBI itself to create an extract of measures.  Here you can see the way the measure appears in PBI and in the highlighted line of the table.
I get exactly the same problem if I try to extract this table from PBI..

It does look like there are tab characters in the expression....so I wonder if these are measures explicitly created in PBI not via DAXformatter.

![image](https://user-images.githubusercontent.com/8373677/90014940-23b67d00-dca8-11ea-92c6-ac5029aad383.png)

**Comment by dgosbell** [comment]
oh sorry, I did not mean to send the pbix file. I was after an example of the csv output from DAX Studio which exhibits this behaviour.

**Comment by ZedLeb** [comment]
OK - I'm attaching the csv (UTF8).  My colleague and I are looking at the problem now and it really does appear to be the tabs that are causing the headache.  
Here's an example of an expression which has newlines but no tabulation and you can see in the table that it all appears on one line and exports correctly.
[SD Measures.zip](https://github.com/DaxStudio/DaxStudio/files/5062739/SD.Measures.zip)


![image](https://user-images.githubusercontent.com/8373677/90016838-edc6c800-dcaa-11ea-8ae4-a6899a0f225e.png)

**Comment by dgosbell** [comment]
I can't repllicate this issue. I unzipped your example file, double clicked on the csv file and it opened in Excel with one row per measure and the multi-line measures had embedded line breaks. Try closing all copies of Excel then double click on the csv. Sometimes Excel can remember changes you've made to the delimiter settings. 

![image](https://user-images.githubusercontent.com/8241830/90108179-3eaeed00-dd8d-11ea-9458-3d95c1be007d.png)

 Tab characters will cause issues if you use the .txt export format, but not for the csv format (unless you have told Excel to use both tab and comma as delimiters)

**Comment by ZedLeb** [comment]
@dgosbell Look at that!!  
Can I ask where you are based (UK/USA?) - are **commas** your standard deliminator for csv files?
I have to swap often between commas and semi-colons (being British but working in France for an American company!) so I thought perhaps my settings are screwing things up.  

So I asked my colleague who's settings are purely French (i.e. **semicolon** as delimiter) to open from the same zipped file and her results are the same as mine....

When she opens the file, everything is in one column (because the exported file used commas) so using TextToColums we select commas (deselecting Tab!) and get the results with the multi-line measures escaping their confines...

I've opened the file in Notepad+ to see what non-printing characters are present and the results are interesting.  For the multi-line measures there is no CR only an LF

This is the first time it occurs in the file:
![image](https://user-images.githubusercontent.com/8373677/90118582-bdd5fe00-dd58-11ea-9b48-c2f6ca08084d.png)

This is the measure you have highlighted above:
![image](https://user-images.githubusercontent.com/8373677/90119194-8d429400-dd59-11ea-9a4e-ac649551381e.png)

**Comment by ZedLeb** [comment]
Ah...Aussie! :)

**Comment by ZedLeb** [comment]
Ah ha - this is looking better.  I'm not sure if ticking the box Quote String Fields did the trick or I had an incorrect setup when I last tried. 
![image](https://user-images.githubusercontent.com/8373677/90129688-612f0f00-dd69-11ea-90c5-13cb6417d270.png)
 But my output is working now.

![image](https://user-images.githubusercontent.com/8373677/90129811-9c314280-dd69-11ea-9068-eb9f662f659b.png)

Thank you so much for your time @dgosbell 
Zx

**Comment by dgosbell** [comment]
> I've opened the file in Notepad+ to see what non-printing characters are present and the results are interesting. For the multi-line measures there is no CR only an LF

This should still be OK since the bit of text you have highlighted is inside a quoted string field. But I'm glad that the custom option worked for you. I'm not really able to test a lot of different regional settings myself so I'm glad you got this to work.
