### ISSUE TITLE
XML Formatting Request for DMVs with XML Format

### ISSUE THREAD

**Issue by dbszepesi** [DaxStudio/DaxStudio#409]
**Is your feature request related to a problem? Please describe.**
I had captured a profiler trace from DAX Studio and saved it to a SQL table.  When I did that, I lost the Event Class and Subclass - these just showed as numbers in my SQL table.  I used the DMV $SYSTEM.DISCOVER_TRACE_EVENT_CATEGORIES to dump the information but the output was unformatted XML that was really hard to use in the data field.  If I sent the output to a file, it just saved it as text format, not XML.  This meant that I had to go through the actual profiler to align Event Class and Subclass to do the lookups.  In SQL, you can just JOIN with sys.trace_Events and sys.trace_subclass_values to lookup the names but these arent the same apparently in SQL Server vs SSAS.  I connected to my Power BI Desktop using SSMS but when I ran the DMV, it again came back as unwieldy XML.  Apparently these DMVs are still using XML format instead of tabular.  I completely get that this is a pretty edge scenario but if people start using profiler more, you may see this more.  In my case, I am trying to load the profiler trace to SQL, then import it into Power BI to play with the data.

To actually see the XML that is returned, run 
select * from $SYSTEM.DISCOVER_TRACE_EVENT_CATEGORIES

**Describe the solution you'd like**
Can you create the ability to export XML output from DMVs to an XML formatted file?  For these two, this is at least the beginning of a Schema:

https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssas/b1bb43da-8a61-4ba3-8f27-6816f9bbe0a8

**Describe alternatives you've considered**
Another alternative is to catch the results coming back from the DMV and change them from XML to a tabular output in the Results pane?

**Additional context**
Once I imported the profiler trace into Power BI, I was able to map Events and SubClasses and just do a bunch of 'Replace Values'.  For example, Event Class 15 is Command Begin.  Subclass 25 is ExecuteSQL, etc.

I did dump the output from  'select * from $SYSTEM.DISCOVER_TRACE_EVENT_CATEGORIES' into a text file, loaded it into VS Code and used a formatter to at least get it to a somewhat searchable format so I could find what I needed.  I will attach that XML here.
[EventCategories.xml.txt](https://github.com/DaxStudio/DaxStudio/files/5072511/EventCategories.xml.txt)

**Comment by dgosbell** [comment]
So I don't think that schema you've linked will help much and you can already get the output formatted as an XML response using the following request in an XMLA window in SSMS. But if you do that you'll notice that the results are XML encoded fragments inside the XML response.
```
<Discover xmlns="urn:schemas-microsoft-com:xml-analysis">

	<RequestType>DISCOVER_TRACE_EVENT_CATEGORIES</RequestType>

    <Restrictions>
		<RestrictionList>
		</RestrictionList>
	</Restrictions>

    <Properties>
		<PropertyList>
   		</PropertyList>
	</Properties>

</Discover>
```

Changing the results to a tabular format is not really possible to do in a generic way as the XML is a multi-level ragged hierarchy. It would be possible to specifically extract the classes and subclasses as a table, but that would require specific coding targeting this specific DMV.

And this specific DMV is such an edge case that I can't see a broad need for it that would justify the amount of time it would take to build out a UI for something like this.

But you could do something with a scripting language like Powershell to extract a table from the XML response. I've knocked together a [small script here](https://gist.github.com/dgosbell/591ca0a62ec4ea6ed8f6cdd885ec1e7e) which outputs the class/subclass details as a table. Currently it outputs to the console, but you could easily change that to output to a file which you could then import into Power BI.

**Comment by dbszepesi** [comment]
That makes total sense, I had the feeling that it was too much of an edge scenario.  Thanks for the sample script, I will take that and run with it.
