### ISSUE TITLE
Error Unable to get version information behind corporate proxy

### ISSUE THREAD

**Issue by fhtino** [DaxStudio/DaxStudio#41]
I get the error "Unable to get version information" when I run DaxStudio behind a corporate authenticated proxy.

**Comment by dgosbell** [comment]
Do you know what sort of authentication the proxy uses? ie. does it require an explicit username/password or does it use your logged on user (NTAuthentication) Are you able to use the DAX Formatter feature (this also requires internet access so it should fail too).

Have you tried explicitly setting the proxy details in the File > Options settings?

**Comment by dgosbell** [comment]
This issue should be fixed in the 2.7.2 release
