### ISSUE TITLE
Error "refreshing model list" when connecting to Power BI

### ISSUE THREAD

**Issue by PedroSanzLl** [DaxStudio/DaxStudio#413]
When I try to connect to the database (only with some files, not with all) I receive an error and I cannot connect.
![ScreenShotDaxStudioIssue_20200825](https://user-images.githubusercontent.com/44417519/91201341-9c81f400-e700-11ea-9bf6-2f0e67ee10ae.png)
[DaxStudio-20200825.log](https://github.com/DaxStudio/DaxStudio/files/5125068/DaxStudio-20200825.log)

The error description is "Error refreshing model list: Excepción inesperada" and "Error Connecting: An error ocurred while dispatching a call to the  UI Thread"

This database has been updated using the Tabular editor (2.11.6) and contains calculation groups (but it also fails with the version without calculation groups).

I'm using DaxStudio version 2.12.2

**Comment by dgosbell** [comment]
So the error "Excepción inesperada" sounds like it's coming from the Power BI engine as I don't have any localized error messages in DAX Studio. Are you able to create a demo pbix file with dummy data which reproduces this issue and upload to this issue on Github? None of the pbix file I have (including some with calc groups) exhibit this sort of behaviour.

**Comment by PedroSanzLl** [comment]
Hello Darren, I saved the file as template and opened as pbix with no data (the message of apply/discard changes appears), I've tested this file and it has the same connection error, how can I send you the file in private?

**Comment by dgosbell** [comment]
You could email it to darren at daxstudio.org and it will come to me privately

**Comment by dgosbell** [comment]
Thanks for sending a copy of your data model. As we discussed via email this appears to have been a bug in the August 2020 release of Power BI Desktop and the updated version from Aug 24th appears to fix this issue.

**Comment by PedroSanzLl** [comment]
thanks a lot for your support
