### ISSUE TITLE
Unable to connect DataSource in DAX Studio

### ISSUE THREAD

**Issue by kumarkk20** [DaxStudio/DaxStudio#417]
Dear Team,
Kindly help me on the below errors, as I'm not able to connect any data model in the DAX Studio.

![DAX ConnectionError](https://user-images.githubusercontent.com/68598100/91519137-68305280-e90f-11ea-8d3e-af74a4ea00ed.JPG)

Thanks in advance

Many Thanks!

**Comment by dgosbell** [comment]
Thanks for logging this, but I cannot reproduce this issue at all.

What sort of connection mode is your report using?  Import mode, Direct Query or Live Connect?
(I've just double checked all 3 of these and they all work fine for me)

If it's in Direct Query or Live Connect what is the back end data source?

Can you try holding down the SHIFT key when you click on the DAX Studio button to generate a [diagnostic log](https://daxstudio.org/documentation/troubleshooting/logging-settings/) and then attach that log to this issue on github?

**Comment by kumarkk20** [comment]
Thanks for your quick response.
For me any connection mode, its not working. however in Tabular Editor it's working fine
Connection mode is import and I am using Excel file for back end data source
[DaxStudio-20200828_002.log](https://github.com/DaxStudio/DaxStudio/files/5141475/DaxStudio-20200828_002.log)
Attached log file

**Comment by dgosbell** [comment]
Do you also get this sort of error when clicking on the connect button in the DAX Studio ribbon and attempt to connect that way? What version of Power BI are you running? There was another recent issue like this #413 which was solved by installing the latest version of Power BI Desktop

**Comment by kumarkk20** [comment]
Hello Darren,
As i am using the latest Power BI Desktop version and my back end data source is excel file
![image](https://user-images.githubusercontent.com/68598100/91630346-3510c080-e9ee-11ea-9d1a-ba4e1298069c.png)

Attached pbix and source file

[Pubs Practice File.zip](https://github.com/DaxStudio/DaxStudio/files/5144844/Pubs.Practice.File.zip)

Many Thanks!

**Comment by dgosbell** [comment]
hmm, I'm not really sure what is causing this on your machine. I tried your sample file on may machine and it worked fine
![image](https://user-images.githubusercontent.com/8241830/91654205-46d78e00-eaea-11ea-8643-6ae55e254a4e.png)
 
The error appears to be coming from the Micrsoft AdomdClient libraries, but I've never seen that one before and I don't know what it means by `%1 is not a valid Win32 application`. 

```
 System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   at Microsoft.AnalysisServices.AdomdClient.XpressMethodsWrapper.SetDelegates()
   at Microsoft.AnalysisServices.AdomdClient.XpressMethodsWrapper.get_XpressWrapper()
   at Microsoft.AnalysisServices.AdomdClient.CompressedStream.InitCompress()
   at Microsoft.AnalysisServices.AdomdClient.CompressedStream.Write(Byte[] buffer, Int32 offset, Int32 size)
```

You could maybe try doing a full uninstall, re-download and re-install incase the download got corrupted somehow, but I doubt that would be the case as the digital signature would be invalidated if that were the case and windows would block the install.

**Comment by dgosbell** [comment]
OK, so I decompiled the Microsoft library and it's looking for a file called msaxpress.dll in %programfiles%/

Can you check if this file exists on your system and if so check what version you have? 

On my machine I have the following:
![image](https://user-images.githubusercontent.com/8241830/91672102-77154000-eb6f-11ea-9156-28e67455f67d.png)

If your version is older than this you could try installing the MSOLAP provider from the [Microsoft Client Libraries page](https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions) as I think this is where this dll comes from.

**Comment by dgosbell** [comment]
Oh and can I ask what operating system you are using? Apparently since Win7 is now out of support that could also be an issue here.

**Comment by kumarkk20** [comment]
Sorry for the delay response and Thank you so much for your kind support
As I have Windows 8.1 Operating system and checked msaxpress.dll file in the system 
![image](https://user-images.githubusercontent.com/68598100/91682822-67e2c200-eb70-11ea-9983-c28e65a1e581.png)

Thanks in advance.

**Comment by dgosbell** [comment]
OK, so it looks like you have a slightly newer version. I was hoping we we see something older. 

After you launch DAX Studio, can you click on the **Connect** button in the ribbon, then expand the **Advanced Options** and add `Transport Compression=None` in the **Additional Options** section. Then see if that will let you connect.

![image](https://user-images.githubusercontent.com/8241830/91683720-b99f4280-eb98-11ea-8072-2003c86f5ffa.png)

**Comment by kumarkk20** [comment]
Thanks a lot Darren
it's working fine now
![image](https://user-images.githubusercontent.com/68598100/91687445-548a2380-eb7d-11ea-97be-1fd2915b345f.png)

**Comment by dgosbell** [comment]
Glad you got this working. It should not be necessary to manually add this extra option, but at least it will get you working in the short term.
