### ISSUE TITLE
Error on Export/View Metrics - Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by DNOW-BrentPearce** [DaxStudio/DaxStudio#419]
I am a new user to DAX Studio. Most functions seem to work as described in tutorials however when I try to View or Export Metrics I get the error: Error viewing metrics. One or more errors occurred. Object reference not set to an instance of an object.

I have tried this on several production models I use and also with a new Excel model which consists of a single table with no relationships, calculated columns or measures. I can view the table and its columns. I can run several DMV queries. Only when I try to View or Export Metrics do I have this issue.

I am running O365 Excel Build 13029.20344 and DAX Studio 2.12.2

Suggestions on how to proceed?

**Comment by dgosbell** [comment]
Thanks for logging this. I'm assuming that you are connecting to a PowerPivot based model here - is that correct? I have found an issue like this which only affects PowerPivot so I'm hoping this is your issue. I have a fixed checked in which should be part of the next release.

**Comment by DNOW-BrentPearce** [comment]
Thanks for the follow-up. Yes, I only have the issue when connected to an Excel Power Pivot model. I can connect to a pbix model and view/export metrics just fine.

Brent Pearce
Mobile: 713-376-0696

**Comment by NigelBarrett** [comment]
I just downloaded DAX Studio for the first time and discovered this problem. 
Any idea when the next release is?

**Comment by dgosbell** [comment]
@NigelBarrett I'm hoping to have the next release out within a week or so.
