### ISSUE TITLE
Parameters not working with curly brackets

### ISSUE THREAD

**Issue by samaguire** [DaxStudio/DaxStudio#424]
The editor doesn't insert the parameter value(s) as expected when the statement is encapsulated within { }. This is for both running the query and merging the XML. Remove the curly brackets and the XML merge works as expected, replacing @tmp with "1". (Running the code doesn't work when removing { } - but that is expected. :-) )

```dax
evaluate
{@tmp}
<Parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:schemas-microsoft-com:xml-analysis">  <Parameter>
    <Name>tmp</Name>
    <Value xsi:type="xsd: string">1</Value>
  </Parameter>
</Parameters>
```

**Comment by dgosbell** [comment]
Thanks for logging this. As a short term work around you can insert a space before the closing curly brace. eg `{@tmp }` a proper fix for this will be included in the next release.
