### ISSUE TITLE
Only time being exported into csv when value is DateTime

### ISSUE THREAD

**Issue by josepzhang** [DaxStudio/DaxStudio#425]
Model data includes a number of columns which include Datatime data.

When running "Evaluate" on model data with output "Grid", the Datetime data is being shown correctly - see screen shot "Grid output". 

However, when "Evaluate" run and the output is to "CSV", the result data only picks up the time - which is this case is zero. See attached "Residency DAX studio" (saved as xlsx)
[REsidency DAX Studion data.xlsx](https://github.com/DaxStudio/DaxStudio/files/5172808/REsidency.DAX.Studion.data.xlsx)
. The expected behaviour is that the date is also exported into excel.

For additional context, I have attached screenshot of the summary data on the "Entry date" variable which shows that data type to be datetime. 

Unfortunately we can not provide the data to reproduce this. Thank you for your assistance.

![Grid output](https://user-images.githubusercontent.com/15990814/92201717-9ccc7d00-eec0-11ea-8a31-96b9103e455c.jpg)
![summary data on Entry date variable](https://user-images.githubusercontent.com/15990814/92201720-9e964080-eec0-11ea-9c7a-09af585d9b65.jpg)

**Comment by dgosbell** [comment]
Thanks for logging this. But I can't reproduce this issue. And I have explicit code in the csv export to force datetime fields into an Excel friendly ISO 8601 format. 

Are you able to provide copy of the original csv file instead of the xslx version as it's possible Excel did something to the file when it opened it.

**Comment by josepzhang** [comment]
Hi Darren,

Ive attached the CSV - note I've deleted the non-date columns due to the data containing personal information.

Thanks.

Joe

________________________________

**Comment by josepzhang** [comment]
Seems like github wont allow upload of csv - see link to file: https://prideliving-my.sharepoint.com/:x:/g/personal/joseph_zhang_prideliving_com_au/EUBbukJh3dlIi7xUQcNjfUoBXgI6l361ojCO1HCa4_FfWw?e=osMdwf

**Comment by dgosbell** [comment]
If you zip up the file is should let you upload it then

**Comment by josepzhang** [comment]
[REsidency DAX Studion data.zip](https://github.com/DaxStudio/DaxStudio/files/5173092/REsidency.DAX.Studion.data.zip)

Done - thanks 

Joe

**Comment by dgosbell** [comment]
> note I've deleted the non-date columns due to the data containing personal information.

Sorry I just noticed this note in your earlier reply. I really need to see the raw output from DAX Studio as my suspicion is that Excel is doing something to the file when you open it.

If you run a query like the following you can just dump out the dates from one of the columns, that way you will not need to alter the file before uploading it.

`EVALUATE VALUES( <table>[<datecolumn>] )`

**Comment by josepzhang** [comment]
Hi Darren - all sorted - we managed to extract the information from another table. Thanks for the help.
