### ISSUE TITLE
MDX Formatter

### ISSUE THREAD

**Issue by hdegroot** [DaxStudio/DaxStudio#428]
It would be great if the DAX Format button could also format MDX!

Reason: My client tool XLCubed generates MDX for our SSAS Tabular instance. To investigate performance issues, it would be helpful to see the MDX code well-formatted.  Guess folks who use Excel as the client will benefit as well.

Maybe it's possible to use the formatting logic/code from MDX Studio?

Ideal implementation: The existing DAX Formatting button process will detect whether it's dealing with MDX or DAX code, and invoke the right formatter accordingly.

Thank you!

**Comment by marcosqlbi** [comment]
I suggest you to use MDX Studio to format the MDX code.
Unfortunately, it is not reuse the MDX parser/formatter existing in MDX Studio.

**Comment by hdegroot** [comment]
Hi Marco ... that's what I'm already doing. MDX Studio is working well but, guess I'm lazy, I was hoping not having to copy-and-paste. Anyhow, thanks for considering this enhancement request.
