### ISSUE TITLE
Add-In menu not enabled

### ISSUE THREAD

**Issue by compinche** [DaxStudio/DaxStudio#43]
This is my first attempt to use DaxStudio. The add-in menu is not showing either on the Excel or Power Pivot ribbon, but not exactly sure what to look for to check the add-in is enabled.

Also, I have a failed AMO check below, but the installer did not offer to download or warned of any additional dependency.

Checking Operating System
=======================
OSCaption       = Microsoft Windows 10 Enterprise
OSVersion       = 10.0.14393
OSArchitecture  = 64-bit
VisibleMemoryGB = 11.43
FreeMemoryGB    = 1.68

Culture Name              = en-US
Culture DisplayName       = English (United States)
Culture EnglishName       = English (United States)
Culture 2-Letter ISO Name = en
Culture DecimalSeparator  = .
Culture GroupSeparator    = ,
Culture CurrencySymbol    = $
Culture ShortDatePattern  = M/d/yyyy
Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.4927
v2.0.50727\1033 -> 2.0.50727.4927
v3.0 -> 3.0.30729.4926
v3.0\Setup -> 3.0.30729.4926
v3.0\Setup\1033 -> 3.0.30729.4926
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
v3.5 -> 3.5.30729.4926
v3.5\1033 -> 3.5.30729.4926
v4\Client -> 4.6.01586
v4\Client\1033 -> 4.6.01586
v4\Full -> 4.6.01586
v4\Full\1033 -> 4.6.01586
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
**FAIL > Could not load file or assembly 'Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest** definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
Processing DaxStudio.exe.config file...
Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
Bindings Found: 9
AMO : 13.0.0.0
ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
Detected Excel Version: 16 - Excel_v16
Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
Excel Architecture: x64

DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2016 Disabled Add-ins
  PASS > No Disabled items found.

Attempting to load Excel Add-in: 
  PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.1.99, Culture=neutral, PublicKeyToken=null

Checking VSTO Configuration
Architecture: x64
  v4
    Version 10.0.60301
    Install 1
    InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
  v4M
    VSTOMFeature_UNM 1
    VSTOMFeature_CLR35 1
    VSTOMFeature_CLR40 1
  v4R
    VSTORFeature_UNM 1
    VSTORFeature_CLR35 1
    VSTORFeature_CLR40 1
    Version 10.0.50903
    Revision 00
    ProductCode {9495AEB4-AB97-39DE-8C42-806EEF75ECA7}

**Comment by compinche** [comment]
I had the Add-In menu disabled, so after enabling, I was able to run DaxStudio on my Power Pivot model. Still, I would like to know if the failed AMO check will limit functionality.

**Comment by dgosbell** [comment]
Ah yes, if the Addin if the menu gets disabled or renamed it can be tricky to launch DAX Studio. 

The failed check will not limit any functionality.  DAX Studio should bind to the highest common version of AMO and ADOMD (so v14 in your case)  But issues with the dependencies typically cause DAX Studio to crash on launch, so if you can launch the UI and connect to your model you should be good to go. If you are going to have any issues it will be todo with the Query Plan or Server Timings if this is the case feel free to open a new issue for this - worst case we can manually fix the binding configuration. 

I've been talking to Microsoft about these issues and they hope to be coming out with some new libraries in the next few months which should make these dependency issues a lot easier for us to deal with.
