### ISSUE TITLE
Unable to import Load JSON Data

### ISSUE THREAD

**Issue by msftbrian** [DaxStudio/DaxStudio#430]
I'm helping a customer troubleshoot some PBI issues.  they've captured a trace, saved as json and sent it to me.  When I select Load Perf Data and point to the JSON file, I get the following error message.
Error loading power bi performance data: Error reading JObject from json reader. Current JReader item is not an object  Start Array Path ", line 1 position 1

**Comment by msftbrian** [comment]
I didn't realize this was power bi performance analyzer exhaust.  We tried exporting it as JSON from dax studio which wouldn't load.

**Comment by dgosbell** [comment]
I'm assuming that you are talking about a Server Timings or Query Plan trace. The export of both of these was designed to be a one way operation, but there is a trick you could use to get this loaded into the user interface.

By Default if you save a query in DAX Studio while a trace is open and you name it something like `myQuery.dax` then you will find that we save an extra `myQuery.dax.serverTimings` file if you have the Server Timings open and a `myQuery.dax.queryPlans` if you have the query plan window open.

So you could just ask your customer to save the query they were running and send you the .dax file plus the .dax.serverTimings file you should just be able to open the .dax file and DAX Studio will automatically look for any trace files of the same name.

Or 

The export uses the same file format, so if you create an empty text file called `example.dax` then rename your json file to `example.dax.serverTimings`. Then go into DAX Studio and choose File > Open then open the `example.dax` file you will find that the query opens and the Server Timings pane will open with the contents of the trace.
