### ISSUE TITLE
DaxStudio Freezes on Splash Screen (Not starting)

### ISSUE THREAD

**Issue by kb2010** [DaxStudio/DaxStudio#431]
**Describe the bug**
Application freezes during initial launch (splash screen icon visible). Similar Issue to Bug #392  

Looking at task manager the process is running at 20% cpu usage so i feel like its doing something but after 5-10min nothin has happened and in the event log i do see an error. 

**To Reproduce**

Launch the application from a shortcut (or directly open the executable)
(freezes)
Close the application from task manager.

**Expected behavior**
Application loads

Screenshots
n/a

**Additional context**
Its a Work PC and it was just updated by IT to Build 17763 (October 2018). Windows 10 Enterprise. Dax studio was working fine before that. DaxStdio is not a support app by IT but we are allowed to use it. Hence why I am posting here. 

I reinstalled .net 4.7.2 by running the .net fix utility from microsoft.  It didnt help.

**Event Viewer**
Note this was from an earlier run when i waited 10min, since then i only get a application hung error since I only wait a few min before closing it forcefully. 

Application: DaxStudio.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at DaxStudio.Standalone.EntryPoint.Main()

Faulting application name: DaxStudio.exe, version: 2.12.2.344, time stamp: 0x5f288b1c
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1192, time stamp: 0x7889407f
Exception code: 0xe0434352
Fault offset: 0x0000000000039709
Faulting process id: 0x1bfc
Faulting application start time: 0x01d68de1870fc685
Faulting application path: C:\Program Files\DAX Studio\DaxStudio.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 23a1f060-c8ab-46d6-8209-14140cdf91c3
Faulting package full name: 
Faulting package-relative application ID: 

**Diagnostic Log**

2020-09-18 20:07:48.495 +01:00 [Debug] Debug Logging Enabled
2020-09-18 20:07:48.526 +01:00 [Information] ============ DaxStudio Startup =============
2020-09-18 20:07:48.742 +01:00 [Information] DAX STUDIO VERSION: "2.12.2.344"
2020-09-18 20:07:48.742 +01:00 [Information] System Info: "OSCaption" = "Microsoft Windows 10 Enterprise"
2020-09-18 20:07:48.742 +01:00 [Information] System Info: "OSRelease" = "1809"
2020-09-18 20:07:48.742 +01:00 [Information] System Info: "OSVersion" = "10.0.17763"
2020-09-18 20:07:48.742 +01:00 [Information] System Info: "OSArchitecture" = "64-bit"
2020-09-18 20:07:48.742 +01:00 [Information] System Info: "VisibleMemoryGB" = "15.88"
2020-09-18 20:07:48.742 +01:00 [Information] System Info: "FreeMemoryGB" = "8.37"
2020-09-18 20:07:48.742 +01:00 [Information] Culture Info: "Name" = "en-GB"
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "DisplayName" = "English (United Kingdom)"
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "EnglishName" = "English (United Kingdom)"
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "2-Letter ISO Name" = "en"
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "DecimalSeparator" = "."
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "GroupSeparator" = ","
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "CurrencySymbol" = "£"
2020-09-18 20:07:48.760 +01:00 [Information] Culture Info: "ShortDatePattern" = "dd/MM/yyyy"
2020-09-18 20:07:48.760 +01:00 [Information] Logging enabled due to Shift key being held down
2020-09-18 20:07:48.760 +01:00 [Information] Logging enabled by Excel Add-in
2020-09-18 20:07:48.761 +01:00 [Information] Startup Parameters Port: 0 File: "" LoggingEnabled: True
2020-09-18 20:07:48.761 +01:00 [Information] Portable Mode: False
2020-09-18 20:07:49.412 +01:00 [Debug] "AssemblyLoader" "PreJitControls" "start"
2020-09-18 20:07:50.439 +01:00 [Debug] "AssemblyLoader" "PreJitControls" "end"
2020-09-18 20:07:50.455 +01:00 [Information] "VersionCheck" "BackgroundGetGitHubVersion" "Starting Background Version Check"
2020-09-18 20:07:50.617 +01:00 [Debug] "GlobalQueryHistory" "Constructor" "Setting Query History Path" "C:\Users\2013601\AppData\Local\DaxStudio\QueryHistory"
2020-09-18 20:07:50.617 +01:00 [Debug] "QueryHistoryPaneViewModel" "ctor" "start"
2020-09-18 20:07:50.617 +01:00 [Debug] "QueryHistoryPaneViewModel" "ctor" "end"
2020-09-18 20:07:50.617 +01:00 [Debug] "GlobalQueryHistory" "LoadHistoryFilesAsync" "Start Load"
2020-09-18 20:07:50.617 +01:00 [Debug] "DaxFormatter" "PrimeConnectionAsync" "Start"
2020-09-18 20:07:50.639 +01:00 [Debug] "DocumentTabViewModel" "ActiveDocument:Set" "" {Document}
2020-09-18 20:07:51.864 +01:00 [Debug] "RibbonViewModel" "Handle:ApplicationActivatedEvent" "Start"
2020-09-18 20:07:51.864 +01:00 [Debug] "RibbonViewModel" "Handle:ApplicationActivatedEvent" "End"
2020-09-18 20:07:51.864 +01:00 [Debug] "DocumentViewModel" "OnActivate" "Query1.dax"
2020-09-18 20:07:51.880 +01:00 [Debug] "RibbonViewModel" "Handle:ActivateDocumentEvent" "Query1.dax"
2020-09-18 20:07:55.251 +01:00 [Debug] "DaxFormatter" "CallDaxFormatterAsync" Redirected to: "https://www.daxformatter.com/api/daxformatter/DaxTextFormat"
2020-09-18 20:07:55.251 +01:00 [Debug] "DaxFormatter" "PrimeConnectionAsync" "End"

**Please see the following fusion error message**

There are 5 files:
PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.HTM
System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.HTM
System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.HTM
System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.HTM
AvalonDock.Themes.VS2013, Culture=neutral.HTM

All files have very similar error message except AvalonDock.Tehmes.VS2013. Based on other bug that seems to be a known issue. But not sure about the other. 

**Example from System.Management**
*** Assembly Binder Log Entry  (18/09/2020 @ 20:07:48) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/kb/Program Files/DAX Studio/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : DaxStudio.UI, Version=2.12.2.344, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected

*** Assembly Binder Log Entry  (18/09/2020 @ 20:07:48) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/kb/Program Files/DAX Studio/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : DaxStudio.UI, Version=2.12.2.344, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected

*** Assembly Binder Log Entry  (18/09/2020 @ 20:07:48) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/kb/Program Files/DAX Studio/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : DaxStudio.UI, Version=2.12.2.344, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
WRN: No matching native image found.

*** Assembly Binder Log Entry  (18/09/2020 @ 20:07:48) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/kb/Program Files/DAX Studio/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : DaxStudio.UI, Version=2.12.2.344, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
WRN: No matching native image found.

**Example from AvalonDock.Themes.VS2013**

*** Assembly Binder Log Entry  (18/09/2020 @ 20:07:49) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = AvalonDock.Themes.VS2013, Culture=neutral
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: AvalonDock.Themes.VS2013, Culture=neutral | Domain ID: 1
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/kb/Program Files/DAX Studio/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (18/09/2020 @ 20:07:49) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = AvalonDock.Themes.VS2013, Culture=neutral
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: AvalonDock.Themes.VS2013, Culture=neutral | Domain ID: 1
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/kb/Program Files/DAX Studio/DAX Studio/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DaxStudio.exe
Calling assembly : PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\kb\Program Files\DAX Studio\DAX Studio\DaxStudio.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.DLL.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013.EXE.
LOG: Attempting download of new URL file:///C:/kb/Program Files/DAX Studio/DAX Studio/bin/AvalonDock.Themes.VS2013/AvalonDock.Themes.VS2013.EXE.
LOG: All probing URLs attempted and failed.

[DaxStudio-20200918.log](https://github.com/DaxStudio/DaxStudio/files/5247802/DaxStudio-20200918.log)
[log.zip](https://github.com/DaxStudio/DaxStudio/files/5247806/log.zip)

**Comment by dgosbell** [comment]
This actually looks more like issue #402 which appears to be a bug in the .net framework on certain hardware configurations. Installing v4.8 of the .net framework fixed this other issue, so maybe try that. If you are seeing the diagnostic logging start up it's not a fusion binding issue as that step is completed prior to the initialization of the logging.

**Comment by kb2010** [comment]
dgosbell, cant believe i didn't see that issue when i was searching. Yes its exactly the same issue as mine. Thank you so much. Installing .net 4.8 worked like a charm!!!
