### ISSUE TITLE
DAX Studio 2.12.2 - an installation bug 

### ISSUE THREAD

**Issue by MiraAbel** [DaxStudio/DaxStudio#433]
![DAX Studio issue](https://user-images.githubusercontent.com/71885906/94287548-5d88cd80-ff4e-11ea-9680-1989397c7a49.PNG)

Hello 

We tried to install DAX Studio in the business. IT Administrator installed it - no issues. However, DAX Studio when installed got "Start-In" in the computer of a person who installed (administrator) rather than a user. Please see the screen shot provided. 
We tried different ways of changing the path but IT team thinks it is the software installation issue.

Will you please help?
Thank you
Mira Abel

**Comment by dgosbell** [comment]
That means the admin chose a "Current User" option when installing. They should go to add/remove programs and uninstall, the re-install using the default "All Users" option. This will install the app in "c:\program files" where it will be available for all users not just themselves.

**Comment by dgosbell** [comment]
I'm assuming this will have resolved your problem so I'm closing this issue
