### ISSUE TITLE
Changing hardcoded hotkey settings

### ISSUE THREAD

**Issue by attilamezes** [DaxStudio/DaxStudio#436]
Hello, I am using DAX Studio with a HUN keyboard. The mostly used special character is the & sign typed as "Alt + C". This keyboard combination brings the comment "//" into the front of the line, which is nice but a pain if I need to type && :-)

I am chasing the Settings interface to change this behaviour, with no luck. Can you please help me out with this feature? Is there any way to change the hardcoded keyboard settings?

Thanks a lot in advance.

ps.: I need to note - DAX Studio improved a lot. I have not used it for 2 years, just recently to refresh my DAX. The latest releases are flowless, lovely, works as expected. Thanks a lot for your work on this. Now DAX Studio is used in my daily routine.

**Comment by dgosbell** [comment]
Thanks for logging this. I actually already have a preview feature available which will allow you to change the key bindings.

If you go to File > Options then click on the **Advanced** tab there is a **Show Key Bindings** option. This will display a new tab in the options screen where you can click on one of the current hot key bindings and type in a new one.

The only reason this is still in preview is that I am trying to figure out an automatic way of checking that someone has not bound the same key to multiple actions (nothing will break if you do this, but only one of the bindings will work).

But thanks for the kind words and for taking the time to log this issue. It really helps improve the project when people share ideas or problems they come across.

**Comment by attilamezes** [comment]
That is awesome. 
I have changed the settings, and now I have the desired & sign, just as expected.

Thank you! Works perfectly fine.
