### ISSUE TITLE
Feature View Metrics problem

### ISSUE THREAD

**Issue by nayronsilva** [DaxStudio/DaxStudio#438]
**Describe the bug**
I've tried to use the view metrics feature located in advanced foot and in a specif database returns a generic error. I could you it in others smaller database, but in that bigger database I can't do it anymore.

**To Reproduce**
1. Go to 'Advanced' foot
2. Click on 'View Metrics'
3. See error on 'Output': 'Value was either too large or too small for an Int32'

**Expected behavior**
See the database's metrics.

**Screenshots**
![image](https://user-images.githubusercontent.com/51278181/95366728-331e0500-08aa-11eb-9d91-ae867f6b7fa8.png)

**Additional context**
This feature was good with that same database in another time.

**Comment by marcosqlbi** [comment]
Please, can you try "Export Metrics" and let us know whether you get the same error or a different one?
Thanks!

**Comment by nayronsilva** [comment]
Hey @marcosqlbi ,
Unfortunately, keeps the error message.

![image](https://user-images.githubusercontent.com/51278181/95371347-77140880-08b0-11eb-8606-8c35c7482684.png)

**Comment by marcosqlbi** [comment]
Unfortunately, this means that the error is not in DAX Studio, but in the VertiPaq Analyzer library.
We have a different GitHub repository for that library: https://github.com/sql-bi/VertiPaq-Analyzer
However, without being able to reproduce the bug, it's hard to find a solution. If you know C#, you could clone the VertiPaq Analyzer repository in your environment and run the code in debugging more to find more details about the error.

@dgosbell could we provide a stack trace info in the log window in DAX Studio?

**Comment by nayronsilva** [comment]
@marcosqlbi, Thanks for your quickly replies.
I'm not good enough in C#, but I'll try to do that anyway. If you could provide it in the log window in DAX Studio as you mention to @dgosbell will be great to use it.

**Comment by dgosbell** [comment]
@nayronsilva can you go to Help > About DAX Studio and click on the open log folder link
![image](https://user-images.githubusercontent.com/8241830/95392121-ed157f80-0943-11eb-99d4-ed28a58ea8af.png)
The files have a date in the form of yyyyMMdd - can you see if there is one with the date this issue happened and upload it to this issue on GitHub (or recreate this issue and upload today's file).

It depends on where this errors from the Vertipaq library is being trapped, but there is a chance that file may have a stack trace which would allow us to fix this more easily.

**Comment by nayronsilva** [comment]
@dgosbell, 
Thanks for your response.
I attached the log archive here. 

[DaxStudio-20201007.log](https://github.com/DaxStudio/DaxStudio/files/5348238/DaxStudio-20201007.log)

**Comment by marcosqlbi** [comment]
@nayronsilva Thanks for the report - I should have fixed the bug in the library. However, it's the first time we have a relationship size larger than 2GB, it's really unusual to find such a big relationship size. When you will get a new version of DAX Studio, can you confirm there is a large relationship size somewhere?

@dgosbell You should update VertiPaq Analyzer libraries to 1.26 and the issue should be fixed this way.

**Comment by nayronsilva** [comment]
@marcosqlbi Yeah, when a new version is available I will do that.

**Comment by nayronsilva** [comment]
@dgosbell Sorry about my ignorance, but, I will need to wait a new DAX Studio version or I can use your commit #438 to fixed my problem in that current version?

**Comment by dgosbell** [comment]
Hi @nayronsilva - so you have a couple of choices.
1. This fix will be in the next release, so you could wait for that.
2. Or if you want to try this out now you could grab a preview build of the next release from [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/35741795/artifacts). It's almost ready to go - I'm mainly testing things now.
3. If you have Visual Studio you _could_ pull down the source code and build the latest commit on the develop branch, but that would be a fair bit of effort.

**Comment by nayronsilva** [comment]
@dgosbell
I followed your second suggestion item and now I can view the metrics. :)
Thank you so much for your help and congratulations for that great tool.
