### ISSUE TITLE
INNER JOINS

### ISSUE THREAD

**Issue by smittydps** [DaxStudio/DaxStudio#439]
Is it possible DAX Studio does not recognize INNER JOINS?  I followed the steps to change the analysis services tabular model according to this article:  https://www.kasperonbi.com/improve-performance-with-directquery-by-using-inner-joins/
The Power BI performance analyzer showed an improvement from 6 seconds to 3 seconds.  When the JSON file was loaded into DAX Studio the Server Timings still showed the 6 second Total time.  Up to this point most all performance analyzer timings are relatively aligned to the Server timings.

**To Reproduce**
1. Visual Studio 2019, SSAS Tabular model Edited Model.bim to add "relyOnReferentialIntegrity": true to every Relationship
2. Deployed to MS Azure 
3. Tested on out longest running visual, 17 measures in one table using performance analyzer:  Total time 5720, DAX Query 2928, Visual display 539, Other 2253.  
4. Loaded Performance Data JSON file into Dax Studio:  Total Ms column shows 3,468 for this visual
5. Double click that query and Run.  Server Timings shows 6,031 ms, the original LEFT OUTER JOIN average!
6. The SQL in DAX Studio shows LEFT OUTER JOIN on every SELECT???
7.  The dump of the DMV TMSCHEMA_Relationships  table shows RelyOnReferentialIntegrity=True for every row

**Expected behavior**
The Server Timings should be more closely aligned with the Power BI Performance Analyzer timings

**Screenshots**
Performance Analyzer
![image](https://user-images.githubusercontent.com/30245592/95385081-7f257580-08bb-11eb-8ab3-61f00d60010a.png)

DAX Studio Load Perf Data
![image](https://user-images.githubusercontent.com/30245592/95385236-ad0aba00-08bb-11eb-9a20-638fc7fd2709.png)

Server Timings
![image](https://user-images.githubusercontent.com/30245592/95385368-e4796680-08bb-11eb-911b-2c10a283b538.png)

SQL
![image](https://user-images.githubusercontent.com/30245592/95385512-1ab6e600-08bc-11eb-978c-8506f47211e4.png)

**Additional context**
We do have a few tables with RI Violations
[Tabular Model with INNER JOINS.zip](https://github.com/DaxStudio/DaxStudio/files/5343733/Tabular.Model.with.INNER.JOINS.zip)

**Comment by marcosqlbi** [comment]
The article you mention applies to DirectQuery, you are using VertiPaq loading data in-memory and the query you see is xmSQL, it is not a query to SQL Server. 
You have a large number of SE queries executed, so it's likely you need to optimize your DAX code or the data model. The difference you observe could have many explanations, but I would be worried about the number of SE queries first. You likely have a table filter or a bidirectional filter in a relationship that is affecting some of the measures of your model.
I am confident you are not seeing a bug in Visual Studio.

**Comment by dgosbell** [comment]
I agree with Marco's assessment. DAX Studio does not process any joins, this is all internal to the Microsoft tabular engine and the LEFT join you have highlighted is a Vertipaq operation, not a T-SQL one like in the article you've linked. I see no issue with the DAX Studio side of things here.
