### ISSUE TITLE
DAX STUDIO AZURE CONNECTION ISSUE

### ISSUE THREAD

**Issue by RY79** [DaxStudio/DaxStudio#44]
Hello,

I am trying to connect to AAS model from DAX studio but after entering the server name , DAX Studio is not giving me option to enter username and password for Azure connection.

My colleague is getting the option for entering the username and password for Azure connection.

It's showing me as connected but I am not able to see anything in the Metadata in DAX studio.

Please help me I needed this badly.

Thanks,
RY

**Comment by dgosbell** [comment]
Did you tick the option for ASAzure support when you installed DAX Studio? The ASAzure support requires a newer version of the Microsoft client libraries. If you did choose this option can you run the [DAX Studio Checker](http://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) and paste the output into a reply in this issue.

**Comment by dgosbell** [comment]
Closing due to a lack of response to the request for more information
