### ISSUE TITLE
Dynamic connection to Excel (standalone) fails (v2.13)

### ISSUE THREAD

**Issue by FrankFromGermany** [DaxStudio/DaxStudio#440]
Error message (translation): "We could not find 'tmpA42A.odc'. Perhaps the object has been moved, renamed or deleted?"

Static connection does work.

![image](https://user-images.githubusercontent.com/26203785/96691853-ae40ea00-1385-11eb-8336-0f3c76149343.png)

I just used "EVALUATE DimProduct" on Tabular.

Where should the odc file have been placed?

Maybe, it's related to issue # 414.

**Comment by dgosbell** [comment]
> Where should the odc file have been placed?

This could be a timing issue. The file is put into the %temp% folder, but after Excel has opened the .odc file I wait a few seconds and then I delete it. This has never failed on my machine, but maybe different Excel configurations can cause longer delays in Excel starting up. 

> Maybe, it's related to issue # 414.

No I am using a completely different mechanism of establishing the connection.

**Comment by FrankFromGermany** [comment]
It seems to be a timing issue. When I open Excel in advance the odc file will be created and it works. 😊 However, otherwise (my Excel is thick and slow) I won’t see the creation of an odc file in the temp folder at all. 

 

Von: Darren Gosbell <notifications@github.com> 
Gesendet: Mittwoch, 21. Oktober 2020 13:14
An: DaxStudio/DaxStudio <DaxStudio@noreply.github.com>
Cc: FrankFromGermany <allesvonvorn@web.de>; Author <author@noreply.github.com>
Betreff: Re: [DaxStudio/DaxStudio] Dynamic connection to Excel (standalone) fails (v2.13) (#440)

 

Where should the odc file have been placed?

This could be a timing issue. The file is put into the %temp% folder, but after Excel has opened the .odc file I wait a few seconds and then I delete it. This has never failed on my machine, but maybe different Excel configurations can cause longer delays in Excel starting up.

Maybe, it's related to issue # 414.

No I am using a completely different mechanism of establishing the connection.
