### ISSUE TITLE
No mapping for AggregateTableRewriteQuery event class

### ISSUE THREAD

**Issue by synveon** [DaxStudio/DaxStudio#446]
**Describe the bug**
Hello.  I am running DaxStudio version 2.13.1.  I am working with Power BI Aggregations and I am using DAX Studio to see if my aggregations are being hit or not.  I click on the Server Timings and run my EVALUATE statement.  The output window shows that the Query batch completed but it shows an error message immediately below it:  "No mapping for the event class AggregateTableRewriteQuery was found".  When I go to the Server Timings window, I do not see the query re-write attempt info.

**Expected behavior**
I am expecting to see this kind of information:
![image](https://user-images.githubusercontent.com/8410040/97440848-a0dbb080-18ed-11eb-8635-1e57fea2b9d1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/8410040/97440681-6540e680-18ed-11eb-9e19-ec9640ff95db.png)
![image](https://user-images.githubusercontent.com/8410040/97440759-7f7ac480-18ed-11eb-8e6e-d8fab7e12d67.png)

Thanks in advance for your assistance.

**Comment by dgosbell** [comment]
Thanks for logging this. It's an unintended site effect of some performance enhancements in the tracing engine. A fix for this will be in the next release

**Comment by synveon** [comment]
Oh ok.  Thanks for letting me know.  I'll look forward to the fix in the next release.  Great tool by the way.  Thank you.

**Comment by Vicome53** [comment]
Hello. Same problem for me today.

**Comment by dgosbell** [comment]
@Vicome53 Yes, this is a bug in the current 2.13.1 release. A fix will be coming in the next release.

**Comment by zilka193** [comment]
> @Vicome53 Yes, this is a bug in the current 2.13.1 release. A fix will be coming in the next release.

Thank you for addressing this fix! It is such a helpful feature when working on optimizing Power BI queries.
