### ISSUE TITLE
Vertipaq shows incorrect table sizes until you close/reopen Power BI Desktop

### ISSUE THREAD

**Issue by edhans** [DaxStudio/DaxStudio#448]
I have a Date table in this example with 3 fields that are unique, and about 20 fields that are not. The unique fields are Date, DateKey (YYYYMMDD format) and an Index. For the model I was working on I only needed the Date field. So I looked at the metrics 

**To Reproduce**
1. Add a date table. [You can use this one in Power Query as an example](https://www.evernote.com/shard/s1/client/snv?noteGuid=96520a8e-d8e9-4c44-ae39-56b82e23b8e5&noteKey=62a0deabb9461bbb&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs1%2Fsh%2F96520a8e-d8e9-4c44-ae39-56b82e23b8e5%2F62a0deabb9461bbb&title=Full%2BDate%2BTable%2Bin%2BPower%2BQuery%2Bfor%2BPower%2BBI%2Bor%2BPower%2BPivot%2Bin%2BExcel).
2. Load the table an look at the size. Should be south of 400KB.
3. Go back in, remove DateKey and DateID
4. Close and load. Now table will be much larger.

**Screenshots**
This is the date table before removing the 2 unneeded columns. (Ignore the annotation here - screenshot used in another example)
![image](https://user-images.githubusercontent.com/45298358/97590180-97b91500-19bb-11eb-90d7-71d923a6f85c.png)
This is the date table after removing the unneeded columns in Power Query. I then hit Close and Apply, then refreshed metadata in DAX Studio just in case, and viewed the metrics:
![image](https://user-images.githubusercontent.com/45298358/97590687-19a93e00-19bc-11eb-8e4b-022e66ce6418.png)
The table has increased in size 10X.
But if I close and reopen Power BI Desktop, It is as expected, a smaller date table.
![image](https://user-images.githubusercontent.com/45298358/97590779-35acdf80-19bc-11eb-87ec-a33693835306.png)

Is this a bug in DAX Studio, bad data passed from PBI Desktop until it is closed/reopened, or am I not understanding something about how to view this data?

**Comment by edhans** [comment]
When I clicked View Metrics is when it updated to the 5,614,060 size, so it updated, but grew much larger. The only way I could see the expected smaller size was to close and reopen the PBIX file.

**Comment by marcosqlbi** [comment]
This is by design: you see the memory allocated by the engine, during the refresh it is larger, when you close and open the PBIX file the AS engine restarts and only allocates the exact amount of memory. There is nothing we can do to show the more accurate result. After a refresh, you should always close and open the PBIX file to get accurate results.

**Comment by edhans** [comment]
Thanks! Wasn't aware of this. Appreciate the follow up on it.
