### ISSUE TITLE
Run Benchmark - connection lost

### ISSUE THREAD

**Issue by mst42a** [DaxStudio/DaxStudio#449]
**Describe the bug**

Sometime when i try to benchmark a query with more than 3 cold/warm cache give me an error.  A single run of Server Timings always return info (even if I run this several time in a row):

![image](https://user-images.githubusercontent.com/63145285/97909640-d991e480-1d48-11eb-9331-cff033467450.png)

Error Connecting to server: The server sent an unrecognizable response.
Cannot Write to a BuferedStrem while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and Write operations on this BufferedStream. Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/63145285/97908997-c7637680-1d47-11eb-8063-38c3031c7ff9.png)

**Comment by dgosbell** [comment]
Thanks for logging this. Are you able to start up DAX Studio with the [diagnostic logging enabled](https://daxstudio.org/documentation/troubleshooting/logging-settings/) by holding down the SHIFT key while you startup. Then reproduce this issue and shutdown DAX Studio and then post the log file to this issue on Github? 

Does this happen when you click away from DAX Studio then click back while a benchmark is running? I'm wondering it it is related to a new check to see if the connection is still open.

**Comment by mst42a** [comment]
Here is log with reproduced issues:
[DaxStudio-20201103.log](https://github.com/DaxStudio/DaxStudio/files/5480115/DaxStudio-20201103.log)

**Comment by dgosbell** [comment]
Thanks for the logs, they are really helpful. I think I know what is happening, but I'm struggling to trigger this issue on my dev machine so it's hard for me to be 100% sure, but I have a fix in place for the next release which should prevent the interleaved read and write operations.
