### ISSUE TITLE
Issue - Key Pad Up & Down - Non Responsive

### ISSUE THREAD

**Issue by WilliamRodriguezATT** [DaxStudio/DaxStudio#451]
Issue where after a certain number of characters is added, DAX Studio will no longer accept 'up and down' movement from the keypad. Issue in 2.13.1, 2.13, 2.12.2 >> Needed to reinstall 2.12.1 to have the keypad work again. 

**To Reproduce**
(1) Download DaxStudio 2.13.1
(2) In the query window: Press Enter > Type "abcdefj" > Enter
(3) DAX Studio will no longer let me use the up or down arrows - only left / right

**Expected behavior**
I expect to be able to navigate the code with the up and down arrows

**Screenshots**
Image of steps performed above >> No longer able to navigate up and down
![image](https://user-images.githubusercontent.com/73909031/98033514-a2bcdc80-1de3-11eb-95e1-74330b22e837.png)

**Additional context**
I tried reinstalling and installing older versions. Wasn't able to get a functioning version until 2.12.1

**Comment by dgosbell** [comment]
Thanks for logging this issue. Initially I had problems reproducing this issue until I realized that your example was not connected to a data model. It appears that the editor control we use is trying to display the intellisense window, but it must then be hiding it as there is no data to display - however it is still capturing the up/down keystrokes. 

There was a minor change recently to check if the intellisense was being shown before attempting to close the window. I've rolled back that change and it seems to now force the closing of this "hidden" window. This fix will be part of the next release.

**Comment by WilliamRodriguezATT** [comment]
Wonderful, thank you so much!
William

William Rodriguez
PowerBI, MAP Team
Mobility Marketing

AT&T
2180 Lake Blvd. NE, Atlanta, GA 30319
m  470.839.5596 | wr0630@att.com<mailto:wr0630@att.com>

**Comment by tarmacx** [comment]
I get the same from time to time. I should also mention that the end and home button are also not working when this occurs. Hoepfully the fix you checked in will also resolve this.

**Comment by dgosbell** [comment]
You should actually also find that hitting the ESC key will fix this also.
