### ISSUE TITLE
error codes

### ISSUE THREAD

**Issue by Bhadrash** [DaxStudio/DaxStudio#452]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dgosbell** [comment]
Sorry, but I don't understand this idea. Can you please explain a bit more what your idea or issue is?

**Comment by dgosbell** [comment]
Closing due to lack of information, if you can provide more information feel free to re-open this issue

**Comment by Bhadrash** [comment]
Hi Darren,
I am sorry, I am new to this DAX thing and I had a problem but got it resolved.  I will certainly get in touch with you to ask another more challenging question.
Than you very much for caring group of people asking question to you.  I like it.
Thank you,
Bhadrash Patel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
