### ISSUE TITLE
ClearCache against PBI Premium XMLA endpoint throws an error

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#456]
**Describe the bug**
When attempting to use the Clear Cache button when connected to a Power BI Premium XMLA endpoint an error is thrown

**To Reproduce**
1. Connect to a Power BI Premium workspace XMLA endpoint
2. Click on the Clear Cache button

**Expected behavior**
No error should be thrown

**Comment by marcosqlbi** [comment]
Does "Server Timings" and "Query Plan" work?

**Comment by dgosbell** [comment]
@marcosqlbi not in the current 2.13.1 release - it just times out all the time. But in the current dev branch there is a fixed checked in for this. It was actually brought to my attention this weekend by members of the product team.
