### ISSUE TITLE
Dictionary size appears to be larger than file size

### ISSUE THREAD

**Issue by tylercmsft** [DaxStudio/DaxStudio#458]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tylercmsft** [comment]
Sorry - didn't mean to submit this as-is!  I have noticed that that the Vertipaq Analyzer is displaying what appears to be erroneous dictionary size information.  I see this whether using the workbooks (tested with version 1.6 and 1.93) or viewing the summary info in Dax Studio (just upgraded to 2.13.1 – prior version was also behaving similarly).

As an example, I have a PBIX file (https://enpublica-my.sharepoint.com/:u:/p/tylerc/Eed6B_4ZfoVApPcQZf8tAocB0ieTmmYK6QgbjoxGDJtmtA?e=SgoUFJ) that is 26 MB in size – from the screenshot, one of the columns is showing a dictionary size of 41 MB.

![VertiPaq_DictionaryIssue](https://user-images.githubusercontent.com/30120831/98830815-71a26480-2400-11eb-93ab-8c48feddb27a.JPG)

**Comment by marcosqlbi** [comment]
There is nothing wrong. Check the data model size in "Summary" tab - it would be consistent with what you see.
The file size is more compressed. Only the Data structure is compressed in memory, other structures (like dictionaries and hierarchies) are not compressed, and the ZIP format of the PBIX apply a more efficient compression that what is applied to data in memory.

**Comment by tylercmsft** [comment]
Thanks Marco - that makes sense.  My suggestion would be to highlight this somewhere - e.g., in the workbook, the readme file, etc.

**Comment by dgosbell** [comment]
I've expanded the documentation for the View Metrics feature to include a note on this detail and I've also added an information icon with a tool tip to the summary pane for this. Both of these things will go live when we publish the next release.

![image](https://user-images.githubusercontent.com/8241830/107112458-e83de980-68ab-11eb-851c-9c420e82a4b2.png)
