### ISSUE TITLE
Provide more information about the failure reason behind "tracing timeout exceeded"

### ISSUE THREAD

**Issue by erssiws** [DaxStudio/DaxStudio#460]
I use the DaxStudio to debug a tabular model running in Azure Analysis Service. I run the DaxStudio on my company laptop which connect to the internet via VPN. 

It seems that none of the traces work at the moment.  I tried with "All Queries", "Query Plan", and "Server Timings". All off them fail at the right beginning with "tracing timeout exceeded" error.  I have played around with larger time-out values. But it did not help.

My company has a very strict network/system protection policy. I suspect that the issue might be caused by the unnecessary blocking in firewalls or in AAS. But I can not find any information about why DaxStudio gets "trace timeout execeeded", e.g., does the timeout happens when establishing the connection to AAS (if a new connection needs to be established in the background) or does the timeout happen when DataxStudio tries to trigger the the tracing commands over the existing connection?

At the moment, I would appreciate if someone can explain to me what happens behind the scene such that I can talk to our infra people to fix the problem. 

In the long-term, it would be great to somehow expose this information in DaxStudio. 

Thank you!
Yang

**Comment by dgosbell** [comment]
When starting a trace we open 2 additional connection to the data source. 

On the first connection we create the trace object and subscribe to it. The trace definition contains the list of events we are interested in and when we subscribe DAX Studio basically starts "listening" for those events on the server.

But depending on network latency and server load the trace sometimes does not start publishing events immediately. This is what the second additional connection is for. For a short amount of time we open this second connection and send empty batch commands to the server on a timer. As soon as the trace registers one of these events we know the trace is active and we stop the timer and close this second additional connection. But if we don't receive any events from the trace before the trace startup timeout we stop the timer, delete the trace and close both of the trace connections.

So the timeout means we are not hearing receiving any events from the server in spite of continuously sending a couple of empty batch commands every second.

What values did you try for the timeout setting? I'm not a heavy user of AAS, but I have not heard of it taking much longer than 60-70 seconds. But you could try going up 999 seconds which would cause the trace to wait for over 15 minutes for a response.

 > In the long-term, it would be great to somehow expose this information in DaxStudio.

I'm not sure what else there is to expose. There are only really two possibilities, either the server/network is slow and we did not wait long enough. Or there is an issue somewhere preventing trace events getting through (in which case it's not worth waiting any longer). But at the point where we start the timer for the timeout the trace has been created and subscribed to without error. I'm thinking of maybe adding a note in the timeout error that the timeout value can be changed in the options page.

**Comment by erssiws** [comment]
Thanks for the information!

Do you know what are the port number for the 2 connections? 

If the firewall blocks the connections, can DaxStudio detect this event? If DaxStudio indeed can detects it, does the failure to establish the connection show up as "tracing timeout exceeded" or will it be indicated with other error messages?

**Comment by dgosbell** [comment]
> Do you know what are the port number for the 2 connections?

These connections use the same port and protocol as we use to run queries. I think for AAS this is done over HTTPS so it's probably port 443, but I'm not 100% sure.

> If the firewall blocks the connections, can DaxStudio detect this event? If DaxStudio indeed can detects it, does the failure to establish the connection show up as "tracing timeout exceeded" or will it be indicated with other error messages?

If the port is completely blocked DAX Studio will not be able to connect at all and you will get an error. If the firewall lets some requests through, then starts blocking you could possibly see this cause the timeout error as that would just look to DAX Studio like the server was taking a long time to respond, but I don't know if any firewalls do that sort of thing.

**Comment by erssiws** [comment]
Additional information: I tried with "SQL Server Profiler" (version 18) to collect the traces . It works.

**Comment by erssiws** [comment]
The  "SQL Server Profiler" runs on the same laptop where I run DaxStudio.

**Comment by dgosbell** [comment]
So if Profiler works that means your firewall is probably not the issue. 

How long does Profiler sit there before it starts capturing events? 

What values did you try for the trace startup timeout in DAX Studio? 

Have you tried a large value like 300 seconds?

**Comment by dgosbell** [comment]
Hmm, I'm not sure what could be going on here. I just double checked on my AAS instance and the trace started up in 20 seconds and works fine. I have heard of instances where it's taken a minute or so to start up, but nothing this extreme. 

You are not configured as a scale out configuration are you? I'm not sure how the tracing would behave in that scenario, but it might be possible for the trace to connect to one node and the queries to go to another node.

If you start profiler capturing the CommandBegin/End and Error events and wait until it changes to a running state and then try starting a trace in DAX Studio do you see the <Create> and <Subscribe> commands and then a series of <Batch> commands firing off?

**Comment by dgosbell** [comment]
Closing due to lack of response, feel free to re-open if you have more information to add.
