### ISSUE TITLE
Show measure created date

### ISSUE THREAD

**Issue by snama2020** [DaxStudio/DaxStudio#464]
Hi There, When we query the $SYSTEM.TMSCHEMA_MEASURES DMV, we can see the measure updated date. Is there a way we can see Measure created date and time ? Having this will help in tracking the work efficiently. I am not sure whether there are other ways to do this but I typically use this view for a quick snapshot.

Thanks,
SN

**Comment by dgosbell** [comment]
Sorry, but as far as I can see there is no Created Date information captured for a measure - the modified date is the only date that Microsoft appears to be tracking at the measure level

**Comment by snama2020** [comment]
Thanks for getting back. I wish there is a field to help with that? I was wondering whether you know the best way to reach out to MS to propose this as an enhancement ? Something like the ideas.powerbi.com for power bi related stuff.

**Comment by dgosbell** [comment]
Using ideas.powerbi.com is probably as good a way as any. Or for AzureAS you could post it on https://feedback.azure.com/forums/556165-azure-analysis-services
