### ISSUE TITLE
suggestion: auto-save

### ISSUE THREAD

**Issue by matthewchilton** [DaxStudio/DaxStudio#47]
How about an auto-save feature in DAX Studio to prevent loss of work when the unfortunate little crashes occur from time to time.

Matt.

**Comment by dgosbell** [comment]
I like this idea. It would also help when you leave DAX Studio open and Windows Update forces a re-boot

**Comment by CadenPicard0603** [comment]
I like this idea as well!

**Comment by dgosbell** [comment]
Implemented in v2.8.0 - although this might be difficult to test as hopefully we have fixed the bulk of the issues that were causing hard crashes :)
