### ISSUE TITLE
Its closing all the time

### ISSUE THREAD

**Issue by gustavoleo** [DaxStudio/DaxStudio#470]
**Describe the bug**
DAX STUDIO is closing all the time after I connect to a Local Power BI or to a PPU

**To Reproduce**
All on video https://www.loom.com/share/9c08d0bc6505443696ce7d1398f2e803

**Expected behavior**
DAX STUDIO close

**Screenshots**
All on video https://www.loom.com/share/9c08d0bc6505443696ce7d1398f2e803

**Additional context**

    Version =  v2.13.1.386
    DaxStudio.exe Version =  v2.13.1.386

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSRelease       = 2009
    OSVersion       = 10.0.19042
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 31,86
    FreeMemoryGB    = 15,75

    Culture Name              = pt-BR
    Culture DisplayName       = Portuguese (Brazil)
    Culture EnglishName       = Portuguese (Brazil)
    Culture 2-Letter ISO Name = pt
    Culture DecimalSeparator  = ,
    Culture GroupSeparator    = .
    Culture CurrencySymbol    = R$
    Culture ShortDatePattern  = dd/MM/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY5 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY4  
         X: 1920 Y: 0 Width: 1920 Height: 1080
DPI X: 96 Y: 96 (Scaling: 100,0%)

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v2.0.50727\1046 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\1046 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v3.5\1046 -> 3.5.30729.4926
    v4\Client -> 4.8.04084
    v4\Client\1033 -> 4.8.04084
    v4\Client\1046 -> 4.8.04084
    v4\Full -> 4.8.04084
    v4\Full\1033 -> 4.8.04084
    v4\Full\1046 -> 4.8.04084
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528372 (4.8)
    PASS > .Net Version 4.8 is above the required minimum

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 22
    AMO : 19.10.0.0
    ADOMD : 19.10.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.13.1.386, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

Registry Settings
=======================
    CurrentDownloadVersion = 2.13.1.386
    LastVersionCheckUTC = 2020-12-02T11:25:17Z
    ShowKeyBindings = True
    ShowPreviewBenchmark = True
    ShowPreviewQueryBuilder = True
    VpaxIncludeTom = True
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>2</flags><showCmd>2</showCmd><minPosition><X>-32000</X><Y>-32000</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>1895</Left><Top>108</Top><Right>3015</Right><Bottom>828</Bottom></normalPosition></WINDOWPLACEMENT>

**Comment by dgosbell** [comment]
Thanks for logging this issue. Unfortunately I've never seen this behaviour and I cannot reproduce this based off your video. So I'm going to need some more data to try and figure out what is going wrong.

Does it just crash when resizing the View Metrics pane or is it any sort of resizing of the panes or does it not appear to be consistent?

Can you try starting up DAX Studio with the Shift key held down to enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) and then reproduce the crash and upload the log file to this issue?

**Comment by dgosbell** [comment]
Closing due to lack of response, feel free to re-open if you have more information to add.
