### ISSUE TITLE
Original data format modified in query result

### ISSUE THREAD

**Issue by RaphLob** [DaxStudio/DaxStudio#471]
Hello

I make a query in order to return a table that I want to export as a text file.
My problem is that a lot of soriginal data is being modified in the query result : decimal separator change from coma to dot, countries names with special characters are change like Brésil becomes BrÃ©sil.
Is it possible to keep the orginal format of the data in the query result?
Thank you very much.
Kind regards
Raphael

**Comment by dgosbell** [comment]
Thanks for reporting this. This looks like a similar issue to #444 - there is a link to a preview build in that issue which should fix the problem with the decimal separator. 

But I have not seen the issue with the special characters reported before and I just tried exporting Brésil and it seems to be writing out correctly. What type of file are you exporting to UTF-8 or Unicode? And how are you viewing the results?

If you are opening the csv in Excel note that Excel does not always handle UTF-8 files correctly, this is a [bug in Excel](http://www.openforis.org/support/questions/279/wrong-characters-display-when-exporting-files-to-csv-from-collect). If you want to view the output in Excel you could either use the Unicode CSV option or you could use the "Static Excel" output type to directly write to an xlsx file.

**Comment by RaphLob** [comment]
Thank you very much for your quick reply.
Please find a sample of the orginal file and a printscreen of the output.
Tell me if you need more information.
Thank you
[Source.txt](https://github.com/DaxStudio/DaxStudio/files/5642220/Source.txt)
![Results DS](https://user-images.githubusercontent.com/75472126/101155851-06773700-3628-11eb-92f7-08e0448bdf8f.JPG)

**Comment by dgosbell** [comment]
I'm a bit confused now. Your initial post said that the issue happened when exporting. Now you are showing a screenshot of the results tab.

Thanks for the example file, but I've tried importing it into Power BI a couple of different ways and I cannot reproduce this issue.
![image](https://user-images.githubusercontent.com/8241830/101168204-34439680-368f-11eb-815d-88aade7cad22.png)

Are you able to share a PBIX file which exhibits this behaviour? (you may have to zip the file before uploading it)

**Comment by RaphLob** [comment]
Hello

The problem appears on the results tab and on the export file. Can I send you my PBIX file by email as it contains some professional information?

Thank you

Raphaël

**Comment by dgosbell** [comment]
If it helps I only really need one table that exhibits this issue. I'm assuming that the data displays correctly in a Power BI table. It's strange that the results grid would behave like this as unlike the file export I don't have the option of specifying any sort of encoding, I just bind directly to the value coming from the Microsoft data provider. If you want to email me a file you can send it to info at daxstudio.org

**Comment by RaphLob** [comment]
Sorry, I didnt' notice the special characters problem apperars already in Power BI table. The decimal separator problem is now fixed by the preview version so everything is ok with Dax studio, thank you very much for your help.
