### ISSUE TITLE
Error Exporting: TOPNSKIP is not supported with the given parameter combination

### ISSUE THREAD

**Issue by scottrhodges** [DaxStudio/DaxStudio#472]
**Describe the bug**
Using v2.13.1 and receiving TOPNSKIP is not supported with the given parameter combination when trying to export a table from an import pbix model with ~60,000 rows. Export attempted to both CSV and SQL with the same result on both.

**To Reproduce**
1. Export data
2. Choose desired format
3. Click Export
4. Error appears in output window

**Expected behavior**
Data is exported as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/10208127/101184221-5fef5e00-3648-11eb-8814-f11af64ebf1e.png)
![image](https://user-images.githubusercontent.com/10208127/101184279-739ac480-3648-11eb-83b8-df666dc11383.png)

**Additional context**

**Comment by dgosbell** [comment]
Thanks for logging this. But I'm not able to reproduce this issue and I've done tests on a model with 120,000,000 rows so the model size is no issue.

All the code will be doing is running a query like the following for each of your tables

```
EVALUATE TOPNSKIP( 1000000, 0, <tablename> )
```

My only guess at the moment is that maybe one of your tables has a name which is using a reserved word that I am not quoting correctly.

Can you either try running queries like the above manually for each of you tables. Or try exporting your tables one at a time and see if this happens to all tables or just a few? And can you then let me know the name of one of the failing tables?

**Comment by scottrhodges** [comment]
Thanks, I can successfully run the command manually (see this example on AdventureWorksDW21017:

![image](https://user-images.githubusercontent.com/10208127/101239016-3e3fb680-36dc-11eb-9c4e-c81a8ef61c70.png)

But still get the error when doing the export:

![image](https://user-images.githubusercontent.com/10208127/101239024-4e579600-36dc-11eb-8c6d-76aec99b481c.png)
![image](https://user-images.githubusercontent.com/10208127/101239042-73e49f80-36dc-11eb-934b-89ead1d076f6.png)

**Comment by dgosbell** [comment]
I'm still unable to reproduce this issue and I can't think why it would report a parameter error when running the same query manually works. 

Are you able to upload the PBIX file you are using? 

Can you tell me what release of Power BI Desktop you are using?

**Comment by dgosbell** [comment]
Closing due to lack of response.

**Comment by Lamtalsi1986** [comment]
Hello, 

I had the same issue, after checking seems my tables were in DirectQuery mode, after loading the data, i had no more the issue...

**Comment by dgosbell** [comment]
Thanks @Lamtalsi1986 I might need to think about adding checks for direct query tables or partitions since TOPNSKIP is not supported against those so this error would be expected in those scenarios. Without using TOPNSKIP I would have to request all the rows in a single query and that would probably cause out-of-memory errors on tables with more than a few million rows

**Comment by iW1DOV** [comment]
HI, I am currently facing the same issue - version 3.0.11 here. 
I have a couple tables in DirectQuery, but the problem raises for EVERY table, even exporting them one by one (of course avoiding to pick the direct query ones), and even attempting to export a dummy two-columns, two-rows  table with data entered directly by hand in the model.

I am trying to convert the two DQ tables to Import and do another attempt. I will report the outcome.

**Comment by dgosbell** [comment]
The Export function was really designed to get data out of import mode models. If you have tables in DQ mode you would be better off going to the SQL tables and either using those or exporting from there.  

@iW1DOV  I cannot reproduce your issue when I avoid selecting DQ tables this works fine for me and exporting import mode tables from a composite model works without error. Can you possibly upload a .vpax file of your model (using the Export Metrics option) so I can see if I can see any other possible causes.

**Comment by iW1DOV** [comment]
HI @dgosbell 

thank you very much for your feedback. I confirm that picking a single table - namely a two-columns, two-rows table data entered directly by hand in the model, export data fails in the model with DQ tables, and finish successfully in a pure import model. 

In the screenshot below, you can see "Dim Comparabile" exported successfully in the first attempt (pure import model) and the same table export failed with TOPNSKIP error in the composite model. 
![image](https://github.com/DaxStudio/DaxStudio/assets/158599741/88b86bdc-d0ed-4219-b7df-fef2216b738a)

Here you can find atteched the .vpax file for the composite model. 
[Incassi&Retail.zip](https://github.com/DaxStudio/DaxStudio/files/14162341/Incassi.Retail.zip)
