### ISSUE TITLE
Traces -> PowerBI Premium Gen2

### ISSUE THREAD

**Issue by mst42a** [DaxStudio/DaxStudio#473]
I have testing now new preview version of PowerBI Premium Gen2, where I deploy my current Tabular Model. Now I want to use DaxStudio to measure performance, but unfortunately an error occured

![image](https://user-images.githubusercontent.com/63145285/101353485-f6638f80-3893-11eb-8c6d-9dcb8472e6b2.png)

Do you think is possible in near future to get some metrics? (Like from powerbi desktop)

I have use the connection described here:
https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#to-get-the-workspace-connection-url

![image](https://user-images.githubusercontent.com/63145285/101353972-b9e46380-3894-11eb-9531-2b27e67e6d90.png)

**Comment by marcosqlbi** [comment]
Increase the Trace Startup Timeout to 90 or 120 seconds.
![image](https://user-images.githubusercontent.com/13840816/101354567-a685c800-3895-11eb-9342-69a2608cf9e0.png)

**Comment by mst42a** [comment]
Thanks.
It actually helped me (I didn't know DaxStudio had these options).

I don't know what exactly it comes from, but it took 6 minutes to start Trace in my case (I set the timeout to 120 seconds)
!! [image] (https://user-images.githubusercontent.com/63145285/101356622-a1764800-3898-11eb-9baf-abda47e10d3e.png)
