### ISSUE TITLE
Unable to connect DAX Studio to Power Pivot

### ISSUE THREAD

**Issue by malcalaq** [DaxStudio/DaxStudio#474]
Please help with this problem, here the results of Dax Studio Checker

Version =  v2.13.1.386
    DaxStudio.exe Version =  v2.13.1.386

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSRelease       = 2004
    OSVersion       = 10.0.19041
    OSArchitecture  = 64-Bit
    VisibleMemoryGB = 8,00
    FreeMemoryGB    = 3,55

    Culture Name              = de-DE
    Culture DisplayName       = Deutsch (Deutschland)
    Culture EnglishName       = German (Germany)
    Culture 2-Letter ISO Name = de
    Culture DecimalSeparator  = ,
    Culture GroupSeparator    = .
    Culture CurrencySymbol    = €
    Culture ShortDatePattern  = dd.MM.yyyy

Checking Displays
=======================
Display: \\.\DISPLAY3 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
DPI X: 96 Y: 96 (Scaling: 100,0%)

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1031 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1031 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1031 -> 3.5.30729.5003
    v4\Client -> 4.8.04084
    v4\Client\1031 -> 4.8.04084
    v4\Client\1033 -> 4.8.04084
    v4\Full -> 4.8.04084
    v4\Full\1031 -> 4.8.04084
    v4\Full\1033 -> 4.8.04084
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528372 (4.8)
    PASS > .Net Version 4.8 is above the required minimum

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 22
    AMO : 19.10.0.0
    ADOMD : 19.10.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\PROGRA~1\MICROS~1\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.13.1.386, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      WARN > Unable to open SOFTWARE\WOW6432Node\Microsoft\VSTO Runtime Setup

FATAL ERROR:
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei DaxStudio.CheckerApp.Checker.CheckVSTO()
   bei DaxStudio.CheckerApp.Checker.CheckExcelAddin()
   bei DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by dgosbell** [comment]
The output of DaxStudio Checker is of no help here (it is only used in situations where DAX Studio fails to start). I need to know what error message you are getting when trying to connect to these sources.

**Comment by malcalaq** [comment]
Hi @dgosbell Thanks for the soon reply. Here I am not even able to connect to power pivot or power bi

![Picture1](https://user-images.githubusercontent.com/75623472/101444336-8d295e00-391f-11eb-9e48-9ceb3ad34265.png)

And in Excel I can activate the addin but I do not see DAX Studio anywhere. 
Thanks for your help

**Comment by dgosbell** [comment]
So it looks like you have no copies of Power BI Desktop open so there is nothing to connect to for that. If you open a pbix file in Power BI Desktop the **PBI / SSDT** option will enable and you will be able to choose your pbix file from the drop down (if you have more than one open)

If you have Power BI Premium you can copy the XMLA endpoint address from the Premium tab in the settings on your workspace (which has an address begining with `powerbi://` ) and then paste that address into the **Tabular Server** option.

> And in Excel I can activate the addin but I do not see DAX Studio anywhere.

It should appear in the Add-ins tab. You can only connect to Power-Pivot when launched from the Excel Addin. Excel does not support external connections to it's data model so we have to run from inside Excel.

**Comment by malcalaq** [comment]
Hi, thanks a lot. Now I can connect to my power BI but I still cannot connect to Power Pivot.  Even if I activate the Add-In, the Add-In is not visible. As you can see below, the COM Add-In field displays the following message: Not loaded. The managed Add-in Loader failed to initialize. Doyou have an Idea how I fix that?

![image](https://user-images.githubusercontent.com/75623472/101612901-72ccae80-3a0b-11eb-8a35-3af45d5b4869.png)

![image](https://user-images.githubusercontent.com/75623472/101612843-62b4cf00-3a0b-11eb-9c79-6106a40d732a.png)

Thanks again
Regards,
Maria

**Comment by dgosbell** [comment]
This is the first time I've ever seen this error message. The "Managed Ad-in Loader" is an Excel component, not a DAX Studio component. So my best guess  is that you have some problem with your Excel install. Maybe try running a repair or re-install.

**Comment by malcalaq** [comment]
ok. Thanks for your help! I will try.

**Comment by dgosbell** [comment]
Did you have any luck trying a running a repair on Excel?

**Comment by malcalaq** [comment]
yes it worked! thanks a lot

**Comment by kgas1961** [comment]
The new verion 3.0.0 and the earlier verison 2.17.3 has the same issue of not connectiing to power pivot model. I repaired office many times. Office version 2209 (Build 15619.20000) Beta channel. 
![Screenshot 2022-08-27 173528](https://user-images.githubusercontent.com/112262963/187034939-096435fb-2f6c-4acf-84cd-4fbe24059292.jpg)

**Comment by marcosqlbi** [comment]
I'm able to connect, but I see this other error (not sure if it's related - @dgosbell contact me if I should run other tests for this).
<img width="360" alt="image" src="https://user-images.githubusercontent.com/13840816/187057526-0795feb1-f295-42cc-8fa7-ac79df09e0dc.png">

**Comment by kgas1961** [comment]
> I'm able to connect, but I see this other error (not sure if it's related - @dgosbell contact me if I should run other tests for this). <img alt="image" width="360" src="https://user-images.githubusercontent.com/13840816/187057526-0795feb1-f295-42cc-8fa7-ac79df09e0dc.png">

Yes. on the first run of DAX studio 3, I got the same error and on subsequent attempt on power pivot data model the same error what I posted occurs. Power BI no issues. Thanks for your response.

**Comment by dgosbell** [comment]
Microsoft changed something in Excel v 2208. I'm in contact with one of the Excel engineers and we are trying to find the root cause so that we can fix it.

**Comment by kgas1961** [comment]
Thanks and waiting for the fix soon.

**Comment by kgas1961** [comment]
The issue still persists with the version 3.0.5, is it only isolated issue, to be confirmed by other users

**Comment by dgosbell** [comment]
@kgas1961 - as I mentioned earlier this is due to a change in Excel. I cannot fix this from the DAX Studio side. This is being tracked in issue #884 if you want to follow that. But I've been in contact with the Excel team, they have a fix in the works, but it needs to go through reviews before it can be pushed out. Once the Excel fix goes out the existing copies of DAX Studio should start working again

**Comment by kgas1961** [comment]
Thanks. Wait for the fix from Excel Team.
