### ISSUE TITLE
Error Connecting: The remote server returned an error: (407) Proxy Authentication Required.

### ISSUE THREAD

**Issue by datadu-de** [DaxStudio/DaxStudio#475]
The same thing was already fixed in TabularEditor, check here for reference:
https://github.com/otykier/TabularEditor/issues/642

This .net configuration should be added for DefaultCredentials to be used if present
```
<system.net>
    <defaultProxy useDefaultCredentials="true" />
  </system.net>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/49077745/101406953-7280c600-38da-11eb-8c54-ec7f260ad0b6.png)

**Comment by dgosbell** [comment]
Thanks for logging this. I've been able to implement the same fix as Tabular Editor so hopefully this should work without requiring config changes in the next release.

**Comment by datadu-de** [comment]
@dgosbell Thanks Darren for the fix 👍 I'll check it in the next release
