### ISSUE TITLE
Connect DAX Studio to Power BI with Azure Analysis Services to trace measure stored in Power BI report.

### ISSUE THREAD

**Issue by ThreadRider2000** [DaxStudio/DaxStudio#477]
**Is your feature request related to a problem? Please describe.**

We have an Azure Analysis Model which contains centralized measures.  However, end-users are creating measures in Power BI reports are encountering performance issues which impacts our AAS model.

**Describe the solution you'd like**

How can I use DAX studio to connect to the Power BI report and capture the measures. 

**Describe alternatives you've considered**

We tried using Power BI Performance Analyzer and tracing.  However report owners have created multiple measure dependencies which we would like to trace and document.

**Additional context**

**Comment by dgosbell** [comment]
> How can I use DAX studio to connect to the Power BI report and capture the measures.

So DAX Studio connects to data models not to reports, but you could do this in DAX Studio by connecting to your AAS model then starting an All Queries trace, then open one of the report pages with a performance issue. This should include any directly or indirectly referenced report level measures in the DEFINE clause of the query. You can then run these queries in DAX Studio to analyze the performance. However this should be the same as the queries you can capture from Power BI Performance Analyzer. But if you want to address performance issues this is what you would do.

If you want to document all the report level measures in a report regardless of whether they are used in visuals or not then you cannot do this with DAX Studio, but you could try something like [Steph Bruno's Field Finder](https://github.com/stephbruno/Power-BI-Field-Finder) or [Radacad's Power BI Helper](https://radacad.com/power-bi-helper)

**Comment by ThreadRider2000** [comment]
Hi Darren,

Thank you for the recommendations.  I really appreciate your insight.

Regards
Kelly
________________________________

**Comment by dgosbell** [comment]
OK, so I'm going to close this issue then as I think I've answered your question
