### ISSUE TITLE
XMLA for Excel $Embedded$ data source

### ISSUE THREAD

**Issue by elperfeccionista** [DaxStudio/DaxStudio#479]
Dear DaxStudio team,

first of all, thanks a lot for the great tool helping all of us in everyday work with models.

I would like to ask an advice ref. to the following topic: 

(1) there is a model created directly in Excel (importing SQL server table to Excel data model)
(2) model is very simple (contains only 2 tables), but the size of one table is rather big (>1,5 mln rows) - so update takes significant time (Excel default is to refresh the whole table)
(3) when I saw, that in DaxStudio XMLA is used to interact with Excel models - I started to think about possibility to use XMLA (ProcessAdd/MergePartitions) instruments to update model table
(4) in Excel (started from 2016) there is a built-in connection to data model (known as $Embedded$ data source)
(5) what I would like to clarify: could I use this built-in connection + classic ADO objects (Connection/Command) to execute XMLA statements against model AnalysisServices server? - and, if this is possible - are there any books/tutorials, which could help to understand difference in XMLA syntax (enveloping) for this specific case?

I understand that my question is not directly related to DaxStudio tool work - just would like to ask an advice from people with probably biggest experience in the topic. Any direction where to search for tutorials would be highly appreciated. Thx a lot in advance

**Comment by dgosbell** [comment]
Sorry, but doing anything outside of the Excel user interface that alters the model in any way usually corrupts the excel file and renders the model inaccessible. I do not believe what you are trying to do is possible. You would probably be better off trying to stream line your data loads if you can. 1.5 mln is actually not overly large for a tabular model and if you are reading from a database you should be able to refresh that many rows in a few minutes.

**Comment by elperfeccionista** [comment]
bad news... I didnt consider stream line and other 'full refresh' options cause model is often used in circumstances, when user try to update data having slow internet line + server is inside corporate internal network (so secure vpn agent slows it even more) -> process becomes not very convenient

Why I thought that maybe update (XMLA ProcessAdd) could work - is cause I tested this method for simple refresh (XMLA ProcessFull - text was like in example below) - and it worked correctly and without any issues. 
Anyway, thanks for the feedback - I'll start to search for other alternatives.. 

    textXMLA = _
                "<Batch xmlns=""https://schemas.microsoft.com/analysisservices/2003/engine"">" & _
                  "<Parallel>" & _
                    "<Process xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">" & _
                      "<Object>" & _
                        "<DatabaseID>" & sessionID & "</DatabaseID>" & _
                      "</Object>" & _
                      "<Type>ProcessFull</Type>" & _
                      "<WriteBackTableCreation>UseExisting</WriteBackTableCreation>" & _
                    "</Process>" & _
                  "</Parallel>" & _
                "</Batch>"
