### ISSUE TITLE
Discover_M_Expressions returns as blank

### ISSUE THREAD

**Issue by bniemers** [DaxStudio/DaxStudio#481]
Hello,

Whenever I am connected to a report or workspace in DAX studio, I am unable to return any result when running the Discover_M_Expressions query. I verify I am connected and other queries work but I am puzzled while this one does not.

**Comment by dgosbell** [comment]
I don't think this is a DAX Studio issue as we just send the DISCOVER_M_EXPRESSIONS query to the data source and display the results. I tested this against an Adventure Work sample model and it worked fine so this might be something to do with your datasets or something.

![image](https://user-images.githubusercontent.com/8241830/102161559-a8760980-3edb-11eb-9468-6784f0f55184.png)

If you have SQL Server Management Studio installed can you try running the same query from there and check if it shows the same results?

**Comment by bniemers** [comment]
Hi, I checked by running against SSMS and still was unable to return anything. I will check the data source and see if there are any issues there. since both SSMS and DAX Studio do not come back with anything, I will close the issue. Thanks for the help

**Comment by bniemers** [comment]
I have confirmed that there is no issue on the dataset side and when consulting with Microsoft/Mindtree they are quite confident that everything is set up correctly and point towards DAX Studio as a culprit for not seeing any result. Is there something I'm missing in between running the query and the data source?

**Comment by dgosbell** [comment]
> Microsoft/Mindtree they are quite confident that everything is set up correctly and point towards DAX Studio as a culprit for not seeing any result.

But I thought you said you ran the same query in SSMS and it also showed no results. This would point to the fact that the client tool is not the issue.

Are you able to provide an example pbix file which reproduces this issue? As you can see from my earlier screenshot this query worked fine on my sample dataset.

If you want to see the raw response to this query you could open an XMLA window in SSMS and then run the following (make sure to change the `<Catalog>` property to the name of your dataset). If you see data returned from this query, but not in SSMS and DAX Studio that could mean that there is a bug in the Microsoft ADOMDClient library.

```
<Discover xmlns="urn:schemas-microsoft-com:xml-analysis">

    <RequestType>DISCOVER_M_EXPRESSIONS</RequestType>

    <Restrictions>
        <RestrictionList>
        </RestrictionList>
    </Restrictions>

    <Properties>
        <PropertyList>
            <Catalog>Adventure Works DW 2020</Catalog>
       </PropertyList>
    </Properties>
</Discover>
```

**Comment by xlSilentHublx** [comment]
I am having a similar issue but it is only returning a subset of the mcode.

**Comment by dgosbell** [comment]
>Note, I executed the query in PowerBI and got the same results.... something is screwy.

Which points to this being a Microsoft issue. 

I don't really do any processing or filtering of the query results, specially with DMV queries. I submit the query to the tabular engine and display the results. If you are seeing the same results from 2 different client tools then it's most likely either something to do with the specifics of your model or a Microsoft bug.  

If you can provide an example pbix or model.bim file that exhibits this behaviour I'm happy to do some investigating

**Comment by Hich02** [comment]
Hello,
I have a same problem in DAXStudio and SSMS, I have three queries in power bi, but when I execute
Discover_m_expressions in a premium workspace, it's empty
do you have a solution?
Thanks,
![image](https://user-images.githubusercontent.com/77895879/105611153-ea844c00-5db3-11eb-89ba-d4eabf68f3c8.png)

![image](https://user-images.githubusercontent.com/77895879/105611352-fcb2ba00-5db4-11eb-95c3-bcf8dd1a88ef.png)

**Comment by dgosbell** [comment]
> I have a same problem in DAXStudio and SSMS,

This would confirm that this is not a DAX Studio specific issue and that it's most likely a Power BI bug. I think you will need to raise a support ticked with Microsoft and get them to investigate this.

**Comment by JoelSteph** [comment]
It is confirmed an issue, however, this DMV is meant for internal debugging use only. Therefore, you may find inconsistent results with this one. You may be able to use this DMV with old V1 .pbix/ datamodels. But for V3, I probably would suggest using TMSchema_Expressions and TMSchema_Partitions as workable alternatives

Thx,
Joel

**Comment by dgosbell** [comment]
Thanks for confirming this @JoelSteph I will probably leave this issue open with a _won't fix_ label for a while so that others can find this. We have some changes in mind that should make the View Metrics more resilient when it hits these sorts of issues that should work around this problem.

**Comment by Hich02** [comment]
I tested with the following commands  select * from $SYSTEM.TMSCHEMA_EXPRESSIONS / 
, I always have the same result as select * from $SYSTEM.DISCOVER_M_EXPRESSIONS

![image](https://user-images.githubusercontent.com/77895879/109026009-8fe65480-76bf-11eb-80a8-be83232730b9.png)

**Comment by JoelSteph** [comment]
@Hich02 : Thats correct, for a V3 data model or .pbix file, it tends to have same results as TMschema_Expressions. But Discover_m_expressions is expected to give unstable results, so its behavior will vary in the near future when compared with TMschema_Expressions.

**Comment by Hich02** [comment]
@JoelSteph:
Hello,
Thank you for your return,

If I understand correctly, currently there is no stable way to see all the requests and the M code of the dataset in premium workspace or in .pbix

I didn't understand the V3 version, what is it ?

**Comment by JoelSteph** [comment]
If you have authored your .pbix report with or later than Sep 2020 version PBI desktop it will use the "Enhanced metadata dataset format" also known as v3. 

To clarify further ,Discover_m_expressions DMV was never meant for external use and is not supported, therefore the results will be inconsistent. I believe some blog pages carried some examples of using that DMV, which is probably the source of confusion.

There are other ways of checking the M expressions suggested by Microsoft such as browsing metadata/expressions via the other DMVs, client tools. For further details on other alternatives, suggesting to raise a support case with Microsoft Power BI support as they could guide based on your specific requirement.

**Comment by xlSilentHublx** [comment]
@JoelSteph It is frustrating that something as useful as discover_m_expressions would be regulated to internal Microsoft use only.

**Comment by JoelSteph** [comment]
@xlSilentHublx : The behavior of this DMV is the same internal as well as external. To be clear, it is meant for only internal testing and the results are and will not be stable. Please refer to our page on Analysis Services DMVs supported for PBI premium, this is not part of the list.

https://docs.microsoft.com/en-us/analysis-services/instances/use-dynamic-management-views-dmvs-to-monitor-analysis-services?view=asallproducts-allversions

**Comment by dgosbell** [comment]
@xlSilentHublx  And it's not like the information is unavailable, you just have to use TMSCHEMA_PARTITIONS for a query that is a source for a partition or TMSCHEMA_EXPRESSIONS for shared expressions. Which are potentially more useful as you can then map a query to a partition/table

**Comment by bniemers** [comment]
@dgosbell Thanks for the insight on how to obtain the same information.

After opening a ticket with Microsoft they returned to me with an answer that the Discover_M_Expressions query is deprecated and no longer supported. That being said I will close the issue, thanks all
