### ISSUE TITLE
No Query Builder in v2.13.1

### ISSUE THREAD

**Issue by ericadyson** [DaxStudio/DaxStudio#482]
**Describe the bug**
There is no query builder in the ribbon.

**To Reproduce**
1. Open Dax Studio.

**Expected behavior**
Query builder should be in the ribbon. It isn't.

**Screenshots**
![dax studio ribbon](https://user-images.githubusercontent.com/24877390/102247165-454e9c00-3f08-11eb-9a88-a928bb0018fe.jpg)

**Additional context**

**Comment by marcosqlbi** [comment]
The Query Builder is a preview feature, you have to activate it in the Options.
![image](https://user-images.githubusercontent.com/13840816/102248732-cb1b1900-3f01-11eb-93da-600375b6b1f7.png)
