### ISSUE TITLE
Why am I missing Query Builder? 

### ISSUE THREAD

**Issue by alienvolm** [DaxStudio/DaxStudio#483]
Hello, 

I'm new to DAX Studio. I'm following the DAX Tools video course, but in my DAX Studio I don't see the Query Builder button: 

![image](https://user-images.githubusercontent.com/46028777/102262212-c134ee00-3ee0-11eb-835e-48bbeb755621.png)

I have downloaded version 2.13.1. 

How do I enable it? 

Thanks!

**Comment by dgosbell** [comment]
The Query Builder is a preview feature so you need to go into File > Options then in the **Advanced** tab there is a tick box to enable the Query Builder

**Comment by alienvolm** [comment]
Thank you! :-)
