### ISSUE TITLE
Error Viewing Metrics - Specified column was not found

### ISSUE THREAD

**Issue by chanu-git** [DaxStudio/DaxStudio#484]
After connecting to tabular model , navigating to Advanced tab and clicking View metrics generates attached error

![DaxStudio_VertipaqMetricError](https://user-images.githubusercontent.com/10621363/102283876-d61d7b80-3ef8-11eb-90ee-339b12afbc37.PNG)

**Comment by dgosbell** [comment]
Can you go to Help > About and then click on the **Open Log Folder** link and upload the most recent log file to this issue (or the one for the date where you took this screenshot if this did not happen today). Or if you could upload an example PBIX file that exhibits this issue that would be even better as this is not an error we've seen before

**Comment by chanu-git** [comment]
Thank you for the quick response! Here is the log file:

[DaxStudio-20201215.log](https://github.com/DaxStudio/DaxStudio/files/5699309/DaxStudio-20201215.log)

**Comment by dgosbell** [comment]
OK, so it's having trouble getting the compatibility level of the data model. What type of data source are you connecting to (SSAS, PowerBI, PowerPivot , etc)?  And can you tell me the server version number you see in the status bar next to the server name?

**Comment by chanu-git** [comment]
I am connecting to SQL Server 2014 SSAS. Server version number shows 12.0.5522.0. Current compatibility level is 1103.
.

**Comment by dgosbell** [comment]
@chanu-git we did add some extra error trapping around the code causing this issue. Are you able to check v2.16.2 and see if the issue still occurs?

**Comment by dgosbell** [comment]
closing due to lack of response
