### ISSUE TITLE
Swap Delimiters functionality, swaps more than delimiters

### ISSUE THREAD

**Issue by K3nZo87** [DaxStudio/DaxStudio#485]
**Describe the bug**
When the swap delimiters functionality is used the dots inside function names, such as "PERCENTILE.EXC", get also converted to commas as if they were the decimal delimiter.

**To Reproduce**
1. Type a function name that contains a dot ("."), such as "PERCENTILE.EXC"
2. Use the swap delimiters functionality
3. The dot (".") gets converted to a comma (",")

**Expected behavior**
The expected behavior should be to swap all delimiters that are not a function name.

**Comment by dgosbell** [comment]
Thanks for reporting this. I've just checked in a fix which will be part of the next release

**Comment by K3nZo87** [comment]
Thanks for the prompt response, and the excellent tool!!
