### ISSUE TITLE
Can not see Query Builder option in DAX Studio Version 2.13

### ISSUE THREAD

**Issue by sayaliredij** [DaxStudio/DaxStudio#490]
I am using DAX Studio 2.13. I was undergoing one training of DAX studio, where it came into my attention that Query Builder Option is missing in my ribbon. I tried to install newer version. But It did not help. Could you please help me?

**To Reproduce**
1. Install DAX Studio. using latest version link - https://github.com/DaxStudio/DaxStudio/releases/download/v2.13.1/DaxStudio_2_13_1_setup.exe
2. Open DAX Studio and See the ribbon

**Expected behavior**
I am expecting to see Query Builder option

**Screenshots**
![image](https://user-images.githubusercontent.com/76643248/103166251-85732000-4820-11eb-8d6f-36d27a28fcc7.png)

**Comment by marcosqlbi** [comment]
The "Query Builder" feature is still in preview in DAX Studio 2.13.1.
You can enable it in File / Options / Advanced / Preview Features.

**Comment by sayaliredij** [comment]
Thank you
