### ISSUE TITLE
Add tooltips to the functional metadata viewer

### ISSUE THREAD

**Issue by cvillegashak** [DaxStudio/DaxStudio#492]
**Is your feature request related to a problem? Please describe.**
No, this would just be a quality of life feature to add tooltips that are dynamic similar to when you're writing DAX within the interface that provides a highlight of what the functionality is of each DAX function.

**Describe the solution you'd like**
A simple tooltip that resembles the tooltip you receive when you're writing DAX manually over each of the functions.

**Describe alternatives you've considered**
Navigating to https://docs.microsoft.com/en-us/dax/dax-function-reference for each function and performing trial and error.

**Comment by dgosbell** [comment]
So the functions pane already has tooltips, but they currently only show the parameter details, so I assume that what you are asking for here is to add the function description to the existing tooltip. If this this correct it should be a pretty simple enhancement.

**Comment by cvillegashak** [comment]
Hi @dgosbell So sorry for not responding to all of the issues over the holiday. Thank you SO SO much for being responsive and addressing these!
