### ISSUE TITLE
Provide better error logging when users use code with table variables

### ISSUE THREAD

**Issue by cvillegashak** [DaxStudio/DaxStudio#493]
**Describe the bug**
Currently in the product you receive a generic error when using table variables indicating "The expression specified in the query is not a valid table expression. 

After scouring the internet for the cause of this because it works natively in PBI and Tabular Editor I've found this article indicating:

In Dax Studio you need to use the following to check the result of a measure:

return
ROW("Result:", COUNTROWS(tbl))

https://community.powerbi.com/t5/DAX-Commands-and-Tips/The-expression-specified-in-the-query-is-not-a-valid-table/td-p/889458

**To Reproduce**
1. Navigate to https://community.powerbi.com/t5/Desktop/How-to-detect-if-text-value-was-changed-on-previous-month/td-p/416091 and replicate the measure that Phil Seamark had created.
2. Use an Evaluate and execute the measure.
3. Reveal that you encounter a generic error.

**Expected behavior**
A more concise error that would indicate make sure to utilize a ROW function when returning the results of a table variable.

**Comment by dgosbell** [comment]
Thanks for logging this. However we  cannot actually alter that error message as it's not generated by DAX Studio, it's coming from the Microsoft Tabular engine. 

However we are working on some help text for the main editor canvas and a DAX query tutorial for our website to help those who are new to writing DAX queries.
