### ISSUE TITLE
Query builder - Filtering with query builder on datetime/date does not appear to function

### ISSUE THREAD

**Issue by cvillegashak** [DaxStudio/DaxStudio#494]
**Describe the bug**
When attempting to use the query builder to filter on date or date time for multiple fields an error appears that states unable to parse the value as a datetime or date value.

**To Reproduce**
1. Create a dataset that either uses a date or datetime (in my case I'm using a date).
2. Evaluate that the values appear correct in PBI and the values are correct when viewing them as results sets in DaxStudio.
3. Use the query builder to generate a simple query using one or two fields and the date and / or date time field in question. 
4. Add this field to the filters.
5. First try and enter a greater than value and a date and / or datetime value from the earlier result set with no quotes around it. (You get an error stating unable to parse the value '' as a DateTime value)
6. Next try and enter the greater than value with a date and / or datetime value from the earlier result set with quotes around it. You end up with the same error but this time with a valid date time appearing in the error. 

**Expected behavior**
Values to appear and no errors.

**Screenshots**
Can't post screenshot's because it violates our companies internal policies.

**Comment by dgosbell** [comment]
Thanks for logging this. This issue will be fixed in the next release. It's due to a bug when I added the between operator as a date filter operator. It's basically trying to parse the value in the second text box which is hidden unless you do a "between" filter.

**Comment by dgosbell** [comment]
This should be fixed in the 2.14 release which was just published
