### ISSUE TITLE
DAX Study query result pane need to respect the defined measure format in data model

### ISSUE THREAD

**Issue by ajit555** [DaxStudio/DaxStudio#496]
Measure is already formatted in pbix data model.

![image](https://user-images.githubusercontent.com/194380/103537795-084c4880-4ebb-11eb-8039-a7cf4ffebdfb.png)

When the DAX query is run in DAX Studio, the "Result" pane does not show the "formatted" measure output. 

It becomes very difficult to visually compare the numbers as the decimal numbers are all over the places even though the format is already present for the measure.

The query result output need to respect the predefined measure formatting in the data model.

![image](https://user-images.githubusercontent.com/194380/103537802-0da99300-4ebb-11eb-8242-97c367faaf5a.png)

**Comment by marcosqlbi** [comment]
The DAX query does not include the format string. DAX Studio tries to format the number by using the same format string of the measure. In this case, the column is named "Product Sales" and the measure name is "Sales Amount". If you rename the column to "Sales Amount" in the query, it should display the number in the correct format.

**Comment by ajit555** [comment]
Thank you, it worked.
