### ISSUE TITLE
Unexpected Results Using "Show Objects that Reference Column" (DMV $SYSTEM.DISCOVER_CALC_DEPENDENCY)

### ISSUE THREAD

**Issue by ebeery11** [DaxStudio/DaxStudio#499]
**Describe the bug**
Unexpected (ambiguous) results are returned when using the "Show Objects that Reference Column" function in the Model Metadata pane.   This behavior is observed when a model contains two columns with the same name in separate tables.  It appears that the DMV query generated does not contain criteria specifying the REFERENCED_TABLE in the WHERE clause.  Perhaps, however, this is the intended functionality in order to properly accommodate calculation dependency tracing for measures? 

**To Reproduce**
1. Model contains at least two tables (Table 1 and Table 2) which each contain an identically-named column (TestColumnA).
2. Measure uses only the column from the _second_ table. 
 `[Sum_Table2_TestColumnA] = SUM(Table2[TestColumnA])SUM(Table2[TestColumnA]`
3. From the model metadata pane, right-click on the Table1[TestColumnA] and utilize the "Show Objects that Reference Column" command.
4. One object (measure [Sum_Table2_TestColumnA]) is returned, which is unexpected because this measure actually references the column from Table2, not Table1.

**Expected behavior**
Expected behavior is that the DMV query generate would take into consideration the table name as well as the column name.  However, the query generated (below) contains no WHERE clause mentioning the [REFERENCED_TABLE].
```
SELECT 
 [OBJECT_TYPE] AS [Object Type], 
 [TABLE] AS [Object's Table], 
 [OBJECT] AS [Object], 
 [REFERENCED_TABLE] AS [Referenced Table], 
 [REFERENCED_OBJECT] AS [Referenced Object], 
 [REFERENCED_OBJECT_TYPE] AS [Referenced Object Type] 
FROM $SYSTEM.DISCOVER_CALC_DEPENDENCY 
WHERE [REFERENCED_OBJECT] = 'TestColumnA'
ORDER BY [OBJECT_TYPE]
```

Altering the query to include an additional criteria in the WHERE clause (AND [REFERENCED_TABLE] = 'Table1') yields the expected results.

```
SELECT 
 [OBJECT_TYPE] AS [Object Type], 
 [TABLE] AS [Object's Table], 
 [OBJECT] AS [Object], 
 [REFERENCED_TABLE] AS [Referenced Table], 
 [REFERENCED_OBJECT] AS [Referenced Object], 
 [REFERENCED_OBJECT_TYPE] AS [Referenced Object Type] 
FROM $SYSTEM.DISCOVER_CALC_DEPENDENCY 
WHERE [REFERENCED_OBJECT] = 'TestColumnA' AND [REFERENCED_TABLE] = 'Table1'
ORDER BY [OBJECT_TYPE]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16659917/103948624-15aa4280-5108-11eb-994f-5916a56fba0b.png)

**Additional context**

-  I thought I possibly recalled Darren calling this out in in one of his DAX Studio feature reviews (perhaps on PowerBI.tips?) but I'm not sure, and wasn't able to find anything in the videos when I looked again.
-  It crossed my mind that potentially this is the intended functionality, designed so that the same query can handle dependency tracing for measures as well as columns?  Just thinking that the formula of a measure (following best practices) wouldn't contain a reference to the Table name, and thus maybe wouldn't be returned if the query contained a [REFERENCED_TABLE] criteria in the WHERE clause?

**Comment by dgosbell** [comment]
Thanks for logging this. It was not a deliberate decision to leave out the table name. It's just more that I have mainly used this for tracking chains of measure dependencies and measure names are unique within a given model. I've just added some code to inject the [REFERENCED_TABLE] into the WHERE clause when this function is invoked against a column. This will be part of the 2.14 release which should be published some time in the next few days.

**Comment by ebeery11** [comment]
@dgosbell  thanks so much for the quick response, and for all the work you've put into this incredible tool!
