### ISSUE TITLE
Right Click ->Define Dependent Measures--> How to get full dump or entire cube

### ISSUE THREAD

**Issue by CadenPicard0603** [DaxStudio/DaxStudio#50]
Hello, 

Since SSAS no longer supports the $System.Discover_Calc_Dependency DMV for models of compatibility 1200 and up, I have been trying to find another way to get this information. DAX studio has the ability to do this so I profiled the call to the cube when I right clicked a measure and clicked "Define Dependent Measures" . I saw that you are making an XMLA call to every table to get the dependencies. However, I was unable to replicate the call to get information back. Do you guys know of a way to do this so I can get the dependencies of all measures for the cube? I will gladly take and XML result set :) 

Thank you!
Best,
Caden

**Comment by dgosbell** [comment]
So DISCOVER_CALC_DEPENDENCY is supported in 2017 for all compatibility levels, but I think it is broken in 2014 and 2016 for the 1200+ level models. In DAX Studio we use the $SYSTEM.MDSCHEMA_MEASURES DMV to get a list of all measures and their expressions for a given model. But getting the dependencies is harder, we currently do a brute force recursive string match at run time in C# but that is not entirely reliable, given that in PowerBI you can now create a measure in one table with the same name as a column in another table (before this year measure names had to be unique across the entire model)
