### ISSUE TITLE
Issue in dax studio

### ISSUE THREAD

**Issue by vanessa2509** [DaxStudio/DaxStudio#505]
Hi teams,

I have one error in Dax Studio when I want make a connection with powerBI, one idea ? 

Could not connect to : could not load file or assembly 'Microsoft AnalysisService.AdmondClient' version =11.0.0.0

**Comment by dgosbell** [comment]
What version of DAX Studio are you running? If you are not on the latest 2.13.1 can you try updating to that? 

If you are on the latest version can you hold down the SHIFT key while starting DAX Studio to enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then reproduce the error, then close DAX Studio and upload the log file to this issue on Github?

**Comment by vanessa2509** [comment]
Yes 2,36, I will try thanks !

**Comment by dgosbell** [comment]
@vanessa2509 - did updating fix this issue for you?

**Comment by vanessa2509** [comment]
Yes ! Thanks !

Vanessa Mondillon
Reporting Analyst
MCM 8th Floor - B
Hit me up on Teams!
________________________________
