### ISSUE TITLE
dax studio connect power pivot

### ISSUE THREAD

**Issue by tt0203** [DaxStudio/DaxStudio#506]
When I Using DAX studio to connect data of power pivot，
I found a URL：http://localhost:9000/xmla
This can be used as the SSAS server address to connect to power pivot.
I really want to know how DAX studio creates this URL. Can we publish the underlying construction method in detail? 
I also want to use this data connection method to create external tools for power Bi desktop.

**Comment by dgosbell** [comment]
This connection is internal for DAX Studio use only, we do not support or recommend it's use by anything else. 

>I also want to use this data connection method to create external tools for power Bi desktop.

You don't need to do this for external tools in Power BI Desktop as there is already a mechanism built in to that feature to pass the server details to an external tool

**Comment by tt0203** [comment]
Now I think of another way, COM interface can operate excel objects, so we can control power pivot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DaxStudio/DaxStudio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 晚上8:31
收件人:&nbsp;"DaxStudio/DaxStudio"<DaxStudio@noreply.github.com&gt;;
抄送:&nbsp;"黄才广"<547925332@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DaxStudio/DaxStudio] dax studio connect power pivot (#506)





 
This connection is internal for DAX Studio use only, we do not support or recommend it's use by anything else.
  
I also want to use this data connection method to create external tools for power Bi desktop.
  
You don't need to do this for external tools in Power BI Desktop as there is already a mechanism built in to that feature to pass the server details to an external tool
