### ISSUE TITLE
Unable to Luanch DAX Studio in Power BI Desktop

### ISSUE THREAD

**Issue by kumarthombre** [DaxStudio/DaxStudio#508]
Hello Team,
Please find the attached error snapshot . I'm not able to open DAX Studio in the Power BI Desktop.
Getting Below Error:- 
DAX Studio executable not found. Contact the tool author for support.

Thanks in advance.

![image](https://user-images.githubusercontent.com/74240020/104891299-c3361500-5996-11eb-9c44-10d502a40580.png)

**Comment by dgosbell** [comment]
What version of DAX Studio are you running? This used to happen in one of the old releases if you installed to a non-default path.

**Comment by kumarthombre** [comment]
Thanks Darren for your prompt response.
I am using Latest DAX Studio Version
![image](https://user-images.githubusercontent.com/74240020/104909199-86294d00-59ad-11eb-8fcf-a1b3dc91d5f0.png)

**Comment by dgosbell** [comment]
Ok, can you go to `C:\Program Files (x86)\Common Files\microsoft shared\Power BI Desktop\External Tools` in Windows Explorer. In that folder you will find a file called `daxstudio.pbitool.json` can you upload that file to this issue on Github so I can see how the installer populated it.

And can you tell me if you installed DAX Studio to the default location or did you specify a custom path?

**Comment by kumarthombre** [comment]
I have installed DAX Studio in the default location.
Attached daxstudio.pbitool.json file.




[daxstudio.pbitool.json.zip](https://github.com/DaxStudio/DaxStudio/files/5830165/daxstudio.pbitool.json.zip)

**Comment by kumarthombre** [comment]
Hello Darren
It's working now, after reinstalling along with all user privileges instead of only me user setting.

Thanks for your valuable support.
![image](https://user-images.githubusercontent.com/74240020/104924394-5dac4d80-59c3-11eb-8064-227da288321d.png)
