### ISSUE TITLE
Tooltip Statistics: Ignoring Measure tables - Nice To Have

### ISSUE THREAD

**Issue by ChthonianUK** [DaxStudio/DaxStudio#512]
**Is your feature request related to a problem? Please describe.**
This is not a problem, just an observation. I have 'Measure Tables' in my model with no actual columns, when moving the mouse over them the output window throws the "Error populating tooltip basic statistics........because it does not have any columns". 

**Describe the solution you'd like**
If possible it would be nice to have the UI ignore statistics for these tables, or even better would be to have a count of measures added to the statistic tooltip.

**Describe alternatives you've considered**
I can leave an empty column in the table and hide it, to still show the table as a measure table in the power bi window. However this throws tooltip error "Specified cast is not valid"

**Additional context**
This is purely a nice to have note :)

**Comment by dgosbell** [comment]
Thanks for logging this. I think this is a good idea. I don't have a lot of models with tables that have no columns so I don't see this issue myself, but I know that plenty of people like this pattern. It should be pretty simple to fix these warning and add a count of measures.

**Comment by ChthonianUK** [comment]
Any time Darren, you are doing amazing work. I use model tables for design measures mostly and it was just something I noticed this morning. Now if you woud like to take the measure count up a level, A tooltip/info section showing a count/list unused measures in a model would be fantastic for keeping models bloat free.

**Comment by dgosbell** [comment]
> A tooltip/info section showing a count/list unused measures in a model

We've had similar suggestions to this and that is actually harder than it seems. DAX Studio only connects to the data model we can't "see" what visuals are using what measures. And even if we did with the ability for other reports to connect to the data model on powerbi.com and the upcoming composite models over Power BI datasets we can't safely tell if a measure is being used or not.
