### ISSUE TITLE
Server Trace not working in Excel

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#514]
**Describe the bug**
Every time I try to start server trace in Excel I get the below error.

![2 14](https://user-images.githubusercontent.com/73054674/105361520-c98af200-5c1f-11eb-9ba7-856436942b9b.png)

I can confirm I have no issues with the v2.13 or v2.9. So I will stick with 2.13 for the time being.
![2 9](https://user-images.githubusercontent.com/73054674/105361534-ce4fa600-5c1f-11eb-8792-9926cc6c6b58.png)

**Comment by sminker3** [comment]
I have the same issue. I am totally new to dax studio. Tomorrow I hope I will have more insights into this issue.

**Comment by dgosbell** [comment]
This appears to be a regression in the 2.14.0 and 2.14.1 releases. I believe I've found the cause of this and am testing a fix

**Comment by sminker3** [comment]
> This appears to be a regression in the 2.14.0 and 2.14.1 releases. I believe I've found the cause of this and am testing a fix

If you need something from me that can help you, feel free to say. Also files that are showing this kind of problem...

**Comment by dgosbell** [comment]
@sminker3  thanks for the offer, but I'm able to reproduce this issue and I am now testing a fix. 

If you would like to help test you can get a preview build of the 2.14.2 release from here:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/37393978/artifacts 

But it seems to be working now for me so I'll probably push out an official update early next week.

**Comment by SharmaAntriksh** [comment]
@dgosbell Thank you!

Query Plan trace is now working if it is activated first:
![1](https://user-images.githubusercontent.com/73054674/105570663-e5ea7400-5d70-11eb-853f-4b891aaa01a7.png)

Server Timings show the below error that we usually get when All Queries option is checked and we try to use Query Plan and Server Timings option as well:
![2](https://user-images.githubusercontent.com/73054674/105570674-087c8d00-5d71-11eb-8fa0-b83db1cb7a63.png)

If Server Timings option is activated first, then I get the below error:
![3](https://user-images.githubusercontent.com/73054674/105570810-7aed6d00-5d71-11eb-9e07-51c2c0dcce2a.png)

Also before creating the original post I was trying to uninstall v2.14 and it was triggering my Antivirus and that happened couple of times as I was installing old versions and then v2.14 again and again to verify the original issue. Later it got resolved and I ignored it. But the preview version is now triggering my Antivirus, just wanted to let you know:
![4](https://user-images.githubusercontent.com/73054674/105570789-627d5280-5d71-11eb-80ce-d0ea13a72835.png)

**Comment by SharmaAntriksh** [comment]
So same thing happened with Preview version too :)
![5](https://user-images.githubusercontent.com/73054674/105571100-1c28f300-5d73-11eb-866d-b103031bf416.png)

**Comment by sminker3** [comment]
> @sminker3 thanks for the offer, but I'm able to reproduce this issue and I am now testing a fix.
> 
> If you would like to help test you can get a preview build of the 2.14.2 release from here:
> https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/37393978/artifacts
> 
> But it seems to be working now for me so I'll probably push out an official update early next week.

I tried it and now it is able to start query trace. Thank you very much. :)

**Comment by dgosbell** [comment]
@sminker3 yes, but currently it only does the Query Plan and All Queries, not Server Timings. There is a conflict with the new xmSQL feature and PowerPivot, but I've fixed that now also.

@SharmaAntriksh if you are interested also the new preview build is available below:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/37409233/artifacts

There is not much I can do about your AV scanner. All our builds are done using Appveyor. It spins up a fresh virtual machine, compiles the code, builds the installer, digitally signs it then deletes the virtual machine. It's as safe a process as I can possibly make it. I assume it's just being overly cautious since it's an exe file that it has not seen downloaded before.

**Comment by SharmaAntriksh** [comment]
@dgosbell Thank you so much for your efforts, I can confirm that both traces are working correctly in Excel! AV issue is not a big deal so we can ignore it 👍Thanks again!
