### ISSUE TITLE
Clear cache doesn't work with DAX Studio 2.7.3

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#52]
When connecting DAX Studio 2.7.3 or 2.7.2 to Power BI the Clear cache command doesn't work.
This is the command recorded in the profiler:

<Batch xmlns="http://schemas.microsoft.com/analysisservices/2003/engine">
                   <ClearCache>
                     <Object>
                       <DatabaseID/>   
                    </Object>
                   </ClearCache>
                 </Batch>

The DatabaseID should be the database ID, but because it is empty, there is an error: 
Either the user, 'DOMAIN\username, does not have read permission for the database, or the database does not exist.

The version 2.7.1 works correctly. It seems that something is broken in getting the database id.

**Comment by marcosqlbi** [comment]
The problem seems related to Clear Cache in general, it's not just Power BI - I see the same issue for Analysis Services Tabular.

**Comment by dgosbell** [comment]
Yes, the database collection was not picking up the ID property due to a minor update to fix some crash reports, this has been fixed in the 2.7.4 release
