### ISSUE TITLE
Windows cannot access 

### ISSUE THREAD

**Issue by rchungsw2** [DaxStudio/DaxStudio#524]
Whenever I tried to install the latest ver. of Dax studio, it keeps saying "Windows cannot access to the specified device, path or file." which I haven't seen before from the previous ver. of Dax studio.

I think it's something to do with the permission issue though, there's not much control I can do with current system environment.

Please fix this issue.

Thanks.

**Comment by dgosbell** [comment]
We don't set or alter any permissions. You could maybe try right clicking on the installer and choosing the run as administrator option. Although this sounds like maybe your IT department has restricted the permissions if you are getting an error on install and if this is the case you will need to work with them to fix this.

**Comment by rchungsw2** [comment]
Thank you. I'll talk to them in this regards! Thanks always for the great product.
