### ISSUE TITLE
https://github.com/daxstudio/daxstudio/discussions

### ISSUE THREAD

**Issue by 1prodm** [DaxStudio/DaxStudio#527]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
Do you have a question or a problem or was this posted by mistake?

**Comment by 1prodm** [comment]
was this posted by mistake. sorry


вт, 26 янв. 2021 г. в 00:02, Darren Gosbell <notifications@github.com>:
