### ISSUE TITLE
Output pane disappears immediately

### ISSUE THREAD

**Issue by Tormentator** [DaxStudio/DaxStudio#528]
When clicking on the "Output" button it disappears immediately which prevents me from changing the output type

![OutputError](https://user-images.githubusercontent.com/54422537/105748895-57a8f600-5f08-11eb-8da3-e08966ce60ae.gif)

1. Click on the output button
2. See error

**Expected behavior**
I would expect the menu to stay on screen for me to choose the option of the output

**Comment by dgosbell** [comment]
Hmm, I've never seen this behaviour before, but based on the fact that the Cut/Copy/Paste icons are getting enabled when the Output menu disappears it looks like something else is stealing the focus or something is generating a click event. I've seen something remotely similar when the touch screen on a laptop starts playing up, but that affects all apps, not just DAX Studio (so even when trying to open the start menu it would keep closing). Where is the cursor before you click on the output dropdown. I can't see it blinking in the main edit window?

**Comment by Tormentator** [comment]
I think I found a solution based on your observations, it seems my video card OSD is considering this some kind of video-intense application and starts to measure FPS (really weird)

By turning off video controls it seems to be more stable, I'll keep checking and close incident if it's solved by that.

Thanks!

**Comment by dgosbell** [comment]
Thanks for updating us. I can't think why that dropdown would trigger your graphics card software, but it's good to know that it appears to be something triggering this software which is "stealing" the focus and causing the dropdown to close.

**Comment by dgosbell** [comment]
Since this appears to be related to other 3rd party software I'm going to close this issue
