### ISSUE TITLE
Enable macro for excel Add-In

### ISSUE THREAD

**Issue by ratnakarsinha** [DaxStudio/DaxStudio#540]
Hi, 

Do we require to enable excel macro for installing and running Dax Studio Excel Add-In?

Can you also confirm if any elevated permission is required to run the excel Add-In? Our users are not local admin on their desktops.

Thanks,
Ratnakar.

**Comment by dgosbell** [comment]
> Do we require to enable excel macro for installing and running Dax Studio Excel Add-In?

No, the addin is compiled. It does not require macros enabled.

> Can you also confirm if any elevated permission is required to run the excel Add-In? Our users are not local admin on their desktops.

No, admin rights are not required at run time. They are only needed by the installer when doing an "All Users" install as that writes the program to "Program Files".
