### ISSUE TITLE
Link to adventure works does not work on website

### ISSUE THREAD

**Issue by FrankGoofGithub** [DaxStudio/DaxStudio#544]
https://daxstudio.org/tutorials/writing-dax-queries/

LINK TO ADVENTUREOWRKS DOES NOT WORK

**Comment by dgosbell** [comment]
Yes, I just found out that Microsoft just changed the branch name on their Github repository from master to main which broke the link. I'll need to push out an update, but in the mean time the following is the new link
[https://github.com/microsoft/powerbi-desktop-samples/raw/main/DAX/Adventure%20Works%20DW%202020.pbix](https://github.com/microsoft/powerbi-desktop-samples/raw/main/DAX/Adventure%20Works%20DW%202020.pbix)

**Comment by dgosbell** [comment]
This should be fixed now
