### ISSUE TITLE
Unable to load into EXCEL & POWER BI

### ISSUE THREAD

**Issue by suzihan2006** [DaxStudio/DaxStudio#547]
DAX Studio v2.14.0.477
Connection: not connected

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
So you are using an old version of DAX Studio, so you should start by making sure you are running the latest version. Then we are going to need much more information. Exactly what is the problem you are seeing? Is there an error message? What are the steps to reproduce the issue?

**Comment by dgosbell** [comment]
Closing due to a lack of information and no response to the request for more information
