### ISSUE TITLE
Vertipaq Analyzer fails 

### ISSUE THREAD

**Issue by farhansoomro** [DaxStudio/DaxStudio#550]
**Describe the bug**
An unexpected exception occurred

**To Reproduce**
1. Go to Vertipaq Analyzer 
2. Click on View Matrix 
An unexpected exception occurred
Report is using SAP HANA data 
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment]
> 2. Click on View Matrix
I'm not sure what matrix you are talking about - did you possibly mean "View **Metrics**"?

> 3. Scroll down to '....'
Can you explain where you are scrolling to in step 3?

> An unexpected exception occurred
Is that the only error message? Is there other error text or a message above or below this error? A screenshot of this error may help.

> Report is using SAP HANA data
Are you in import mode or Direct Query mode?

Could you gather some more information by opening DAX Studio while holding down the SHIFT key. This will enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/), then connect to your model and reproduce this issue, then close DAX Studio and attach the generated log file to this issue on github.

**Comment by dgosbell** [comment]
closing due to lack of response. Feel free to re-open this if you are able to answer the questions above
