### ISSUE TITLE
Export to SQL with AAD

### ISSUE THREAD

**Issue by macpaulos** [DaxStudio/DaxStudio#553]
**Is your feature request related to a problem? Please describe.**
This maybe due to my in experience with SQL as a general, but if I try to formulate a connection string involving Authentication=ActiveDirectoryPassword I get "Invalid value for key "authentication".
Completely understand why that is as there is no for Active Directory in the authentication section.

**Describe the solution you'd like**
Add/enable Active directory authentication when exporting to SQL  ideally as a connection string parameter

**Describe alternatives you've considered**
Add/enable Active directory authentication when exporting to SQL as a radio button option

**Additional context**
If you're tinkering with the connection string area, it would be fantastic to save connection profiles as an extra to save me copying and pasting (power shell is disabled for me)

**Comment by dgosbell** [comment]
I think AAD authentication should already work if you manually edit the connection string, but I don't think "ActiveDirectoryPassword" is a valid value for the Authentication section. If you go to [this page](https://www.connectionstrings.com/azure-sql-database/) then scroll down to the section section that has example connection strings for the **.NET Framework Data Provider for SQL Server** can you try one of those formats.

eg

```
Server=tcp:myserver.database.windows.net,1433;Authentication=Active Directory Password;Database=myDataBase;UID=myUser@myDomain;PWD=myPassword;
```

**Comment by macpaulos** [comment]
Hi Darren,

Thank you.  Indeed my connection string was incorrect. Sorry for the false post.  my string had Authentication=Active Directory Password all as one word.
Thanks for the great work and super speedy response.
Have a great Friday/weekend!!!
