### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JLOBATORAEZ** [DaxStudio/DaxStudio#555]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
27/02/2021 19:53:19		Error viewing metrics: Se han producido uno o varios errores.
	Error inesperado (archivo "xmtwdatacache.cpp", línea 2719, función "XMWindowingIterator::Init").

**Comment by dgosbell** [comment]
This is a duplicate of #459 I'm going to close this as we are tracking that problem there. There is also a possible workaround on that thread
