### ISSUE TITLE
Add option to play sound at end of query execution

### ISSUE THREAD

**Issue by mazamorac** [DaxStudio/DaxStudio#556]
**Is your feature request related to a problem? Please describe.**
When when testing long-running queries, or running batches of long-running queries, a lot of time is wasted between executions when you don't realize that the query has finished already.

**Describe the solution you'd like**
Adding an option to play a sound at the end of the query would fix this problem. A Windows default beep would work. A better option would be to provide the Windows-provided sound chooser to pick a particular system or custom sound.

**Describe alternatives you've considered**
The alternative is to stay with eyes glued to the execution window, not optimal.

**Additional context**
This is a common feature of programming IDEs, like SSIS or VS.

**Comment by dgosbell** [comment]
Thanks for this suggestion, that should not be too hard to implement. Although unfortunately I do not believe there is a windows provided sound chooser, but there is a way to hook a few of the key sounds (like Asterisk, Beep, Exclamation and one or two others) and it may not be too hard to play a selected .wav file either.

**Comment by mazamorac** [comment]
> Although unfortunately I do not believe there is a windows provided sound chooser, but there is a way to hook a few of the key sounds (like Asterisk, Beep, Exclamation and one or two others) and it may not be too hard to play a selected .wav file either.

You're right, I was thinking of an _old_ Windows SDK API. In Win10 C# you'd play system sounds with `System.Media.SystemSounds`, and `System.Media.SoundPlayer` for arbitrary WAV files or use the old PlaySound API to play event system sounds in the registry (e.g.: `PlaySound( TEXT("DeviceConnect"), NULL, SND_ALIAS|SND_ASYNC );`.

Glad you think it's easy to implement, it's a little pet peeve of mine. Thanks for the work you've put into DAX Studio!
