### ISSUE TITLE
Clear cache issue:  Query (1, 72) The syntax for '.0' is incorrect. (EVALUATE /* <<DAX Studio Internal>> */ ROW("DAX Studio Session Refresh".0))

### ISSUE THREAD

**Issue by pmsocho** [DaxStudio/DaxStudio#557]
**Describe the bug**
The reason of the behaviour described below is that I am using OTHER (a;b;c|1,23) as default separators. When i switch back to US/UK separators everything is working fine!

**To Reproduce**

1. Enable OTHER (a;b;c|1,23) as default separators
2. Use Clear Cache then run
3. The query runs but you will get such error in the Output pane:
2021-03-01 10:31:40		Query (1, 72) The syntax for '.0' is incorrect. (EVALUATE /* <<DAX Studio Internal>> */ ROW("DAX Studio Session Refresh".0)).

**Expected behavior**
The error does not appear when you just RUN the Query. You have to Clear cache and run.
The error also appears when you are clicking "Clear cache" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/79837207/109478523-a69ef980-7a79-11eb-9bf8-e5b8c5bf2f8e.png)

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fixed checked into the source and it will go out as part of the next release and this issue will close itself at that time.
