### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#565]
Just wanted to check if some of the shortcuts available in Power BI can be implemented in Dax Studio as well, for example the ability to comment/uncomment using CTRL + /

Steve from Power BI Community has put an exhaustive list so I am sharing it here for quick ideas: https://community.powerbi.com/t5/Community-Blog/Checkout-these-awesome-keyboard-shortcuts/ba-p/1706533

**Comment by dgosbell** [comment]
Closing as DAX Studio now supports customizing key bindings for comment/uncomment
