### ISSUE TITLE
Add right-click menu option in the editor to open functions in dax.guide

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#568]
Currently the links to dax.guide only display when typing a open bracket '(' 

**Describe the solution you'd like**
it would be nice if we could right click on a function and open the dax.guide page for that function

**Describe alternatives you've considered**
You can delete and re-type the '(' character to bring up the function tooltip

**Comment by erapade** [comment]
Wow, that was quick. My bad, but I realized that also a mouse over hovering option would be nice so I added an feature request for this as well: #569
