### ISSUE TITLE
No Server Timings for Power BI Premium datasets

### ISSUE THREAD

**Issue by dschingisab** [DaxStudio/DaxStudio#572]
When I try to trace "Server Timings" on a Power BI Premium dataset (Gen2 or Gen1) the result after executing the query is blank.
I'm using latest version of DAXStudio 2.14.1.

Tracings for on-prem or Azure AS models work just fine.

Is this feature not supported yet? Any plans when we can expect it to work?

Many thanks!

**Comment by dgosbell** [comment]
This is supported and it worked just now when I tested it. 

Are there any warnings or errors in the Output tab? 

Sometimes the traces take an excessively long time to start on PBI XMLA and Azure AS and you need to go into the options and extend the trace startup timeout. Mine just took 25 seconds to startup and the default timeout is 30 seconds, but I have recently heard of it taking a minute or two on occasions.

**Comment by dschingisab** [comment]
I guess it's working now. I really had to set the option "**Trace Startup Timeout (secs)**" to 90 sec in my case. Then I retrieve the Server Timings.
Thank's a lot for the quick advice!
