### ISSUE TITLE
Data truncated using Export Data Wizard

### ISSUE THREAD

**Issue by Gravanita** [DaxStudio/DaxStudio#573]
DAX Studio v2.14.1.484
Connection: PowerBIDesktop - 15.1.76.22

## Summary of Issue
Choosing not to truncate tables before inserting data has no effect in Export Data Wizard.

## Steps to Reproduce
1. Remove check mark on "Truncate tables Before inserting data"
2. Verifying that the tables have been truncated.

**Comment by dgosbell** [comment]
Duplicate of #520 - a fix has been checked in for this issue and it will go out in the next release
