### ISSUE TITLE
DAX Studio crashes when trying to edit an Existing Measure

### ISSUE THREAD

**Issue by Domaldhino** [DaxStudio/DaxStudio#576]
Hi Guys,

After connecting successfully to Excel PowerPivot Data model
1. Open Query Builder
2. Drag in existing measure
3. edit existing measure (via pencil icon)
4. DAX Studio immediately crashes

This does not happen if I create a measure from new and then edit the same measure.

Version 2.14.1.484 @ 03/23/2021 13:57:18

Exception has been thrown by the target of an invocation.
[Dax Studio Exception Error.txt](https://github.com/DaxStudio/DaxStudio/files/6186708/Dax.Studio.Exception.Error.txt)

Would appreciate any advice.

Dom

**Comment by dgosbell** [comment]
I have a fix for this already checked in which will be part of the next release. We switched a few months ago to using a newer DMV to get the measure expression if the data source reported that it supported the newer DMV. Unfortunately PowerPivot reports that it is supported, but then throws an error when we attempt to use it.

**Comment by dgosbell** [comment]
This should be fixed in v2.15 which was just released
