### ISSUE TITLE
Export to SQL only supports up to 10K rows.

### ISSUE THREAD

**Issue by bnjmnora** [DaxStudio/DaxStudio#577]
DAX Studio v2.14.1.484
Connection: PowerBIDesktop - 15.1.79.26

## Summary of Issue
Viewing of data in DAX Studio shows all of the data however when exporting to SQL only 10K rows are migrated.

## Steps to Reproduce
1. Open DAX Studio
2. Click on "Advanced" tab -> Export Data
3. Check Data on SQL

## Expected Result
1. Should show more than 63K rows of data

## Actual Result
1. Only 10K rows displayed

![image](https://user-images.githubusercontent.com/30061598/112596775-3b153580-8e47-11eb-9f84-34a336de7190.png)

**Comment by dgosbell** [comment]
I cannot reproduce this against a model in import mode and I've tested the export against one of the largest models I have exporting over 120 million rows. 

Is your model possibly in Direct Query mode? That is about the only thing I can think of which would cause that sort of TOPNSKIP error

**Comment by dgosbell** [comment]
Closing due to lack of response
