### ISSUE TITLE
Analyze in Excel doesn't work when connected to a Power BI Premium Workspace

### ISSUE THREAD

**Issue by erapade** [DaxStudio/DaxStudio#578]
**Describe the bug**
Analyze in Excel doesn't work when connected to a Power BI Premium Workspace

**To Reproduce**
1. Connect to a Power BI Premium workspace
2. In the Metadata window, select a dataset
3. Click on the Advanced tab
4. In the ribbon menu, click on "Analyze in Excel"
5. Click "Enable" at the "Microsoft Excel Security Notice"

**Expected behavior**
A Pivot table connected to the Power BI Service data model

**Screenshots**
![image](https://user-images.githubusercontent.com/17324892/112816851-1ce74980-9082-11eb-9bfd-27a19a198ee0.png)

**Additional context**
Doing the same directly from the Power BI Service works fine, i.e. clicking on the eclipse of the dataset and choose Analyze in Excel. 
As you can do the same from Power BI Service, this is also an acceptable workaround. Maybe, if it's time consuming to implement, an alternative message telling the user to use that method untill it's solve in DAX Studio would be good

**Comment by dgosbell** [comment]
Thanks for logging this, it looks like I'm passing the wrong authentication type when connected to PBI Premium (so it probably affects AzureAS also). It should not be too hard to fix.
