### ISSUE TITLE
Can't find the Layout tab in v2.15

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#579]
Previous version had the layout tab which appeared after enabling query traces but it is not showing up in the latest version:
![image](https://user-images.githubusercontent.com/73054674/112873229-fc99a800-90de-11eb-8b3d-8fe98e03d227.png)

**Comment by dgosbell** [comment]
Thanks for logging this. I updated the version of the ribbon control to fix some crashes we'd been seeing, but it looks like there was also a change in the visibility binding for contextual tabs (eg the Layout tab). I think I have a fix for this and I will look at maybe releasing a 2.15.1 update shortly

**Comment by SharmaAntriksh** [comment]
Sure, thanks a lot for your efforts!!
