### ISSUE TITLE
Parameters are always treated as text

### ISSUE THREAD

**Issue by jank-dk** [DaxStudio/DaxStudio#580]
**Describe the bug**
If a `<Parameters>` block is present, parameters are treated as text values regardless of their type attribute

**To Reproduce**
In DAX Studio, connect to any Tabular database and copy-paste this query:
```
EVALUATE
SUMMARIZECOLUMNS (
    ROLLUPADDISSUBTOTAL ( 'Date'[Calendar Year], "Date_Calendar_Year_IsSubtotal" ),
    FILTER (
        ALL ( 'Date'[Calendar Year] ),
        ( ( 'Date'[Calendar Year] = @PARAMFBA4F4C0 ) )
    ),
    "Internet Total Sales", [Internet Total Sales]
)
ORDER BY
    [Date_Calendar_Year_IsSubtotal] DESC,
    'Date'[Calendar Year]

<Parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:schemas-microsoft-com:xml-analysis">
  <Parameter>
    <Name>PARAMFBA4F4C0</Name>
    <Value xsi:type="xsd:int">2003</Value>
  </Parameter>
</Parameters>    
```

Press "Merge XML" and observe that the FILTER expression will be changed to `( ( 'Date'[Calendar Year] = "2003" ) )`

It should have been `( ( 'Date'[Calendar Year] = 2003 ) )`

If you execute it (on Adventure Works database), it will fail with "DAX comparison operations do not support comparing values of type Integer with values of type Text. Consider using the VALUE or FORMAT function to convert one of the values.". It also fails with the same error if you execute the query without pressing "Merge XML".

The code that reads the <Parameters> element should read the xsi:type attribute to determine what data type to use.

**Comment by dgosbell** [comment]
Yes it is a limitation of the current parameter handling in that it treats everything as strings. Improving the parameter handling has been one of the things on my todo list for a while. I'm going to see if I can improve both the parameter xml parsing and add a type option to the parameter dialog.
