### ISSUE TITLE
v2.15.0 All queries trace does not start when connected to Excel

### ISSUE THREAD

**Issue by 59Peter** [DaxStudio/DaxStudio#581]
DAX Studio v2.15.0.525
Connection: PowerPivot - 13.0.1700.1054

## Summary of Issue
Seems to work fine when connected to Power BI but not when connected to Excel.
All queries trace cannot start when connected to PowerPivot model (see error below).
Will revert to 2.14.2489 that was working.

## Steps to Reproduce
1.Open Excel PowerPivot file
2.Connect to DAx Studio using link in Excel Add Ins
3.Once connected to DM start Trace by clicking on "All Queries"
4.We get an "error starting trace: The Event ID=17 does not contain ID=1. To see list of event columns available, read product documentation
5.I get another error window shortly after "Dax Studio 2.15.0.525 crashed"

![DaxStudio2 15 0_AllQueriesTraceStartError](https://user-images.githubusercontent.com/78232269/113277790-64b7dc00-92e1-11eb-9666-97a1ad165ca7.jpg)
![Second error msg general tab](https://user-images.githubusercontent.com/78232269/113277818-6bdeea00-92e1-11eb-9fa0-9bbf5762348c.jpg)
![Second error msg Exceptions tab](https://user-images.githubusercontent.com/78232269/113277844-71d4cb00-92e1-11eb-9941-b336e074fa9c.jpg)

**Comment by dgosbell** [comment]
Thanks for logging this. I've had a couple of crash reports emailed in for this, but to date no one has added any details of what triggered the issue so it's been impossible to fix until now. 

I have a fixed checked in which will be included in the next release (and this issue will automatically close once that is released) and there is a preview build with the fix in it available on our build server at https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/38511329/artifacts

**Comment by 59Peter** [comment]
Hi Darren,

 

I have tried to translate the error message I got as it was partly in French as you could se in the screenshot 😊

 

Just tested v2.15.1.533 and it works fine.

 

Thanks very much

 

Pierre

**Comment by dgosbell** [comment]
@RobertMela this fix will be in the next release. You can either wait for that or you can try the pre-release build linked in my comment above
