### ISSUE TITLE
Statements are missing key-words when right-clicking over the code for the DAX-Guide

### ISSUE THREAD

**Issue by erapade** [DaxStudio/DaxStudio#584]
**Is your feature request related to a problem? Please describe.**
Thanks for implementing the right-click option. But I notised that the "Statements" are not included as DAX items, and I understand why since they where not in the list of items ealier since they doesn't start with a "(". 

**Describe the solution you'd like**
Right-clicking on e.g. EVALUATE shall also show DAX-Guide information: https://dax.guide/statements/
![image](https://user-images.githubusercontent.com/17324892/113738452-31b98200-96ff-11eb-95ec-bf558d26b3d3.png)

**Describe alternatives you've considered**
Not sure if this is a good idea when hovering over the key-words, but I leave that up to you

**Additional context**
If we also include these key-words, it will be easier for beginners to use DAX studio since they also will get help on the key-words newer of seldom used outside of DAX-studio like EVALUATE, DEFINE, etc

**Comment by dgosbell** [comment]
I've added support for most of these with the exception of ORDER BY since I'm doing simple word scanning and I don't have an easy solution for keywords with a space in them. This feature will be part of the next release and this issue will automatically close when I publish that release.
