### ISSUE TITLE
Defining calculation group items from within DAX Studio

### ISSUE THREAD

**Issue by erapade** [DaxStudio/DaxStudio#585]
**Is your feature request related to a problem? Please describe.**
I would like to be able to re-define a calculation group item from within DAX Studio

**Describe the solution you'd like**
DEFINE CALCULATION_ITEM CG_TimeIntelligence[YTD] = ...

**Describe alternatives you've considered**
Also seeing calculation items in DAX Studio and have the posibility to righ-click and choose define

**Additional context**
While developing calculation groups, it would be nice to be able to work with them using DAX Studio, but I haven't found any way to re-define them like I can do with mesures. So if we can add calculation items to the list of acceptable definition types it would be nice. I guess most people will still use the tabular editor, but as I see a trend of writing less measures and more calculation items I still would like to use DAX studio for development

**Comment by marcosqlbi** [comment]
I would love this feature, too.
Unfortunately, we should ask Microsoft - you can vote this idea: https://ideas.powerbi.com/ideas/idea/?ideaid=d08ccd21-e597-eb11-89ee-281878bdee4b

**Comment by erapade** [comment]
> I would love this feature, too.
> Unfortunately, we should ask Microsoft - you can vote this idea: https://ideas.powerbi.com/ideas/idea/?ideaid=d08ccd21-e597-eb11-89ee-281878bdee4b

Wow, 18 votes in less than 24 hours @marcosqlbi, I guess I better ask you to write ideas for me in the feature as I'm more of getting 1.8 votes in 24 months :-)

And while having you online, although a bit of topic. Calculation Groups are great. But it seems like Power BI have not managed adapt. Today I reported a bug where visual measure filters are ignored when using calculation group items as columns. But the biggest problem is that you can do a lot more customizations in e.g. bar charts using multiple measures instead of one measure and calculation items as categories. So when creating calculation groups you still end up creating explicit measures based on this calculation groups just because the visuals lack configurations required when slizing on configuration items.

What's needed now from Microsoft is that they understand this beeing an issue and does an effort in upgrading the standard visuals they provide. I know they have a lot to do, but they need to act to make sure that calculation groups will not be a disapointment. If you agree I know you and Alberto have the best channels to make a change ;-)

**Comment by marcosqlbi** [comment]
I completely agree with the goal.
Unfortunately, there is not much we can do to achieve the goal.
The three ideas with more than 2,000 votes I submitted are far from being implemented:
https://ideas.powerbi.com/ideas/idea/?ideaid=6c34e629-2807-45f4-be8b-ce6ffb2be719
https://ideas.powerbi.com/ideas/idea/?ideaid=4657bb93-bb25-48c2-9304-26bfd8def58c
https://ideas.powerbi.com/ideas/idea/?ideaid=15bd4fbe-829a-4ae2-b093-937b64cf790c

The consumption experience of calculation groups in Power BI is far from ideal. But we still struggle in having this implemented, which would be good for calculation items, too:
https://ideas.powerbi.com/ideas/idea/?ideaid=49ca8e3e-efc4-ea11-bf21-281878bd39b4

**Comment by dgosbell** [comment]
Closing this issue as it needs to be implemented in the MS tabular engine
