### ISSUE TITLE
FE timings include data transfer overhead

### ISSUE THREAD

**Issue by otykier** [DaxStudio/DaxStudio#59]
When a query that returns a significant number of bytes (typically 500+ rows) is executed in DAX Studio on a machine that connects to a remote server, the FE timings seem to include network overhead. For example, here are the timings when I execute a query on my local machine, connected to a remote server through VPN:

![image](https://user-images.githubusercontent.com/8976200/37037218-1b6b6fb6-2152-11e8-9885-2fda9ff01cc8.png)

And here are the timings when the same query is executed directly on the server:

![image](https://user-images.githubusercontent.com/8976200/37037176-0587bc18-2152-11e8-999a-b4f611956ea7.png)

Is there a way to get a more precise measurement of time spent in FE, or is the recommendation to always run queries in DAX Studio as "close" to the server as possible?

**Comment by marcosqlbi** [comment]
Unfortunately we don't have a safe metric to measure that. Ideally, when you measure performance you should minimize the materialization of the results to the client.

For example, instead of EVALUATE <table> write EVALUATE ROW ( "x", COUNTROWS ( <table> ) )
So you minimize the materialization to the client.

**Comment by dgosbell** [comment]
The complication here is that SSAS does not resolve the query first, then send the results. The results are streamed back progressively to the client, so the serialization and network communication is interwoven into the evaluation of the query making it very difficult for even Microsoft to separate the timing of these two things.

**Comment by otykier** [comment]
Thanks for the detailed answer from both of you.
