### ISSUE TITLE
Data format types should show in blue color font

### ISSUE THREAD

**Issue by m-kovalsky** [DaxStudio/DaxStudio#592]
**Describe the bug**
Data format types such as STRING, INTEGER etc. should show in blue color font. 

https://dax.guide/datatypes/

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fix checked in which will go out in the next release (at which point this issue will auto close). I've also added the data types to the code completion engine.

**Comment by m-kovalsky** [comment]
Thanks Darren!
