### ISSUE TITLE
Dark mode please

### ISSUE THREAD

**Issue by samnseir** [DaxStudio/DaxStudio#593]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please can we have dark mode/theme in the ide.

**Describe alternatives you've considered**
n/a

**Additional context**
Thank you

**Comment by samnseir** [comment]
Duplicate of #75 - thanks!

**Comment by dgosbell** [comment]
I have been slowly chipping away at this. It's just **a lot** of work to retro fit dynamic theming to an existing application.
