### ISSUE TITLE
Syntax for String Replace in DMV Queries

### ISSUE THREAD

**Issue by asocorro** [DaxStudio/DaxStudio#594]
Hi, is there a string replace function for use in DMV Queries?  I can't any documentation online.

Thanks!
Adolfo

**Comment by dgosbell** [comment]
No I do not believe that the DMV queries have support for a replace function. Microsoft actually implemented these using a language called DMX (Data Mining eXtensions for SQL) and they really only support very simple projection style queries. 

You can find the DMX language reference here https://docs.microsoft.com/en-us/sql/dmx/data-mining-extensions-dmx-reference?view=sql-server-ver15 DAX Studio does not do any processing of the DMV queries we send them back to the underlying data source so any new functionality would have to be implemented by Microsoft
