### ISSUE TITLE
Quirks in running queries against DMV

### ISSUE THREAD

**Issue by laurajludwig** [DaxStudio/DaxStudio#60]
I'm trying to streamline my org's documentation process of Power BI designs (since I can't get them to give up on documentation altogether), and I'm trying to use DAX Studio to extract some of the more tedious parts. I'm using the DMV section, and I've been successful with the following query: 
```
select TableID, ExplicitName, SourceColumn, FormatString,IsUnique,IsKey
from $SYSTEM.TMSCHEMA_COLUMNS
```
When I try to do something similar for Tables or Measures:
`select ID, Name from $SYSTEM.TMSCHEMA_TABLES`
`select ID, TableID, Name, Expression, FormatString from $SYSTEM.TMSCHEMA_MEASURES`

I get an error that says: 'The syntax for ',' is incorrect. '

It seems to me like this should be possible, given that it's some really basic SQL and it works for other tables. Am I missing something?

**Comment by dgosbell** [comment]
This behaviour is not specific to DAX Studio, you get the same syntax error running these queries from any other client tool. The DMVs actually use a query language called DMX which is almost SQL, but not quite. 

And I believe that "ID" and "Name" are reserved words in DMX, so if you quote these column names with square brackets they should work fine.

eg.

```
select [ID], [Name] from $SYSTEM.TMSCHEMA_TABLES
select [ID], TableID, [Name], Expression, FormatString from $SYSTEM.TMSCHEMA_MEASURES
```
