### ISSUE TITLE
Dax not launching on Windows 10

### ISSUE THREAD

**Issue by wuodamba** [DaxStudio/DaxStudio#601]
I have installed Dax Studio version 2.15 on windows 10 Education
It refuses to launch. The logo just keeps spinning forever. What could be the problem?

**Comment by dgosbell** [comment]
That typically indicates that there is an issue with the .net framework on your machine. Try installing .net 4.8 or if you already have that try running a repair on it.

**Comment by dgosbell** [comment]
Did repairing or re-installing the .net framework fix this issue?

**Comment by dgosbell** [comment]
Closing due to lack of response
