### ISSUE TITLE
Results of a measure using CONCATENATEX displays as right aligned text

### ISSUE THREAD

**Issue by relax528** [DaxStudio/DaxStudio#609]
Can this be left aligned for improved readability.

Using this query
DEFINE
    MEASURE 'Project Overview'[Status Determination] =
        IF (
            HASONEVALUE ( 'Project Overview'[PID] ),
            CONCATENATEX (
                'Project Overview',......

EVALUATE
SELECTCOLUMNS (
    'Project Overview',
    "ProjectTitle", 'Project Overview'[ProjectTitle],
    "Status Determination", [Status Determination]
)
The results for StatusDetermination display as right aligned

![image](https://user-images.githubusercontent.com/19497071/117182655-40e22d00-ad9c-11eb-98e9-a176ae09fd80.png)

Thanks

**Comment by dgosbell** [comment]
I'm not sure how you are getting the text to be right aligned, I tried a quick test creating a similar measure and the text is left aligned

![image](https://user-images.githubusercontent.com/8241830/117224486-69792e00-ae53-11eb-8cea-9d348461d254.png)

Are you able to create an example pbix file with dummy data that exhibits this behaviour and upload it to this issue?

It may be related to datatypes or something, but I even tried creating a numeric measure in the model (which will get right aligned) and then overriding that with a string value in the query, but the strings were still left aligned.

**Comment by dgosbell** [comment]
Closing due to lack of response and unable to reproduce. If you are able to provide more information feel free to re-open this issue
