### ISSUE TITLE
Drag DMV Issue

### ISSUE THREAD

**Issue by praghi** [DaxStudio/DaxStudio#613]
Hi All,
It was trying to drag the field from DMV but it didn't allow me. Please could you share me the step. I have added the error screen shot herewith. Appreciated for you help. Thanks 
![DAX Studio drag issue](https://user-images.githubusercontent.com/83985254/117723240-4ff42f80-b221-11eb-849f-87353a601731.jpg) 

Regards, 
Praghi

**Comment by dgosbell** [comment]
Thanks for logging this. I think some of the changes to the drag/drop code to get the Query Builder working broke the DMV and Function dragging. As a temporary work around you can double-click to insert the DMV/Function text in the current location in the editor. 

I'm testing a fix for this now which will be in the next release.
