### ISSUE TITLE
Broken link on "Writing DAX Queries" tutorial

### ISSUE THREAD

**Issue by LastThird** [DaxStudio/DaxStudio#621]
**Describe the bug**
On the [Writing DAX Queries](https://daxstudio.org/tutorials/writing-dax-queries/) tutorial page, the URL for the Adventure Works 2020 sample file is broken (looks like it was moved):

> Old: https://github.com/microsoft/powerbi-desktop-samples/raw/master/DAX/Adventure%20Works%20DW%202020.pbix
> New: https://github.com/microsoft/powerbi-desktop-samples/blob/main/DAX/Adventure%20Works%20DW%202020.pbix
> 

**To Reproduce**
1. Go to [Writing DAX Queries](https://daxstudio.org/tutorials/writing-dax-queries/) tutorial page
2. Click on "[Adventure Works 2020](https://github.com/microsoft/powerbi-desktop-samples/raw/master/DAX/Adventure%20Works%20DW%202020.pbix) sample file"
3. See GitHub error 404

**Expected behavior**
Adventure Works 2020 PBIX file downloads

**Screenshots**
> ![image](https://user-images.githubusercontent.com/7707133/118569933-e0ee6d80-b72f-11eb-97be-42ec7f58d970.png)

**Additional context**
N/A

**Comment by dgosbell** [comment]
Thanks for logging this. I've just pushed an update that should fix this link
