### ISSUE TITLE
Trying to connect with my shared dataset in Power BI Service using DAX Studio.

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#624]
Trying to connect with my shared dataset in Power BI Service using DAX Studio.
It connects successfully, but when I click on View Metrics, after a while it comes up with an error.
See attached.

Thank you

![View Metrics - error](https://user-images.githubusercontent.com/83199486/118575297-7d188300-b7c9-11eb-86ba-fe07b214e745.PNG)

_Originally posted by @ImranDJCS in https://github.com/DaxStudio/DaxStudio/discussions/623_

**Comment by ImranDJCS** [comment]
Log file attached.
[DaxStudio-20210518.log](https://github.com/DaxStudio/DaxStudio/files/6497786/DaxStudio-20210518.log)

**Comment by dgosbell** [comment]
There are a couple of things I noticed in the log. 

1. You are using the previous version of DAX Studio. I'm not sure if this will make much difference, but you could try updating to the 2.15.0 release. The new release includes updated Microsoft drivers and since the composite model feature is still in preview there may be updates in the newer version to work better with these.
2. The issue is happening when the vertipaq analyzer libraries attempt to do some distinct counts on the model to get more accurate counts. You can turn off this behaviour by turning off the highlighted setting in the Options window

![image](https://user-images.githubusercontent.com/8241830/118589322-7dbe1300-b7e3-11eb-84a6-1abf73ef31a0.png)

**Comment by dgosbell** [comment]
Did either of the above suggestions help with this issue?

**Comment by ImranDJCS** [comment]
Hi there,
Appreciate the follow-up.
It did not work, but I noticed the redeployed the dataset and refreshed successfully. Also noticed the error is intermittent regardless of dataset refresh and may not be a real error.

**Comment by dgosbell** [comment]
Ok, since this appears to be intermittent and most likely appears to be coming from the Power BI side I'm going to close this issue as I can't see any actions I can take on this. However if you get more information on this feel free to re-open this issue or raise a new one.
