### ISSUE TITLE
No Databases were found in the when connecting to localhost:54882 (PowerBIDesktop) 

### ISSUE THREAD

**Issue by avfc1982** [DaxStudio/DaxStudio#626]
**Describe the bug**
Hi,

I have had a new laptop within the last couple of months and today I needed to use DAX Studio due to a slow performing Table on Power BI.
When I try to connect to my Power BI Desktop Tabular Model but when I do I get the below message

![image](https://user-images.githubusercontent.com/47869200/118961598-622a4800-b95c-11eb-82be-27ae0c2ed284.png)

I did not have this error before?

Ay ideas what might have changed?

Thanks

**Comment by dgosbell** [comment]
Closing due to lack of response
