### ISSUE TITLE
Table names in VertiPaq

### ISSUE THREAD

**Issue by dimitriAda** [DaxStudio/DaxStudio#627]
DAX Studio v2.14.1.484
Connection: PowerBIDesktop - 15.1.83.24

## Summary of Issue
After changing the name of the table and creating a new table, identical to the old name.
It seems that the Query is confused in the Select statement.

Below you can see that the SQL statement for Step 1 and 2 is identical.
Is there a way to adjust the tables names in VertiPaq?

## Steps to Reproduce
1.
EVALUATE
  ROW(
  "Productivity_Hours", 'ΣProductivity'[Productivity Hours]
)
  Line  2
  SET DC_KIND="AUTO";
SELECT
SUM ( ' TimeWizeHours'[Hours] )
FROM ' TimeWizeHours';
  
  2.
  // DAX Query
EVALUATE
  ROW(
  "TimeWize_Hours", 'ΣTimeWize'[TimeWize Hours]
)
SET DC_KIND="AUTO";
SELECT
SUM ( ' TimeWizeHours'[Hours] )
FROM ' TimeWizeHours';

**Comment by dgosbell** [comment]
The query in the xmSQL is not confused, it's just that internally when you create a table the Tabular model  stores the original name as both the Name and the ID and when you rename a table only the name property is changed the ID stays the same and the xmSQL that the Tabular engine returns always uses the ID property.

However we do have a fix already checked in where we lookup the correct name and inject that into the xmSQL to make it easier to read and understand. This fix will be part of the next release.

**Comment by dgosbell** [comment]
v2.16 with this fix has just been released
