### ISSUE TITLE
can't install daxstudio on MacBook M1

### ISSUE THREAD

**Issue by alessandrossC** [DaxStudio/DaxStudio#632]
**Describe the bug**
can't install daxstudio on MacBook M1

**Comment by dgosbell** [comment]
That is correct, DAX Studio is a Windows application

**Comment by alessandrossC** [comment]
Sorry, Windows ARM

**Comment by alessandrossC** [comment]
![Uploading C356CCE6-C8B6-4EBD-9A46-71824B06621E.jpeg…]()

**Comment by alessandrossC** [comment]
I installed Parrales and Windows ARM 64 bit, and I have problem, I can’t install DaxStudio

**Comment by dgosbell** [comment]
DAX Studio is written as a .Net Framework application (not .net core) so it is **only** supported on x86 and x64 intel based versions of Windows. This is a Microsoft limitation, not something we can change. I believe you will also find many other programs (like Power BI Desktop) are not supported on the Windows ARM version.

**Comment by alessandrossC** [comment]
I installed power bi, I had no problems with that. Now the only problem is in the installation DAX Studio

**Comment by dgosbell** [comment]
Did you install "Power BI" or "Power BI Desktop" ? The first one is a mobile app which lets you view reports from powerbi.com on your mobile device which has both ARM and Intel builds. The second is the tool for authoring reports. I would not expect either Power BI Desktop or DAX Studio to work on the ARM platform as the libraries used by both applications are highly optimized for the intel architecture.

**Comment by alessandrossC** [comment]
I installed Power BI Desktop x64

**Comment by dgosbell** [comment]
OK, so it looks like Microsoft [recently extended](https://www.techrepublic.com/article/windows-on-arm-this-is-how-well-64-bit-emulation-is-working/) their emulator support on Windows ARM to add support for x64 apps. Although you are now running an emulator inside a virtual machine so I can't imagine the performance would be very good. 

Can you tell me what error message you are getting?

You could try running the following command from the command line in the folder where you downloaded the DAX Studio installer. If the installer is able to run it should generate a log file in c:\temp
```
DaxStudio_2_15_0_setup /log=c:\temp\daxstudio-setup.log 
```
if that works can you upload that file to this issue. I'm not sure if I will be able to do much without access to an ARM version of Windows, but it may provide some hints.

Or you could try downloading and running the portable version to see if that works.

**Comment by alessandrossC** [comment]
![Uploading 198A20D7-D451-45F2-ADBF-3C0F1666F5BF.jpeg…]()

**Comment by alessandrossC** [comment]
The portable version works and runs

**Comment by alessandrossC** [comment]
Shows an error like this "Error - This program can be installed on version of Windows designed for the following processor architectures: x86, x64"

**Comment by dgosbell** [comment]
Hmm, ok that looks like a check within the installer. It looks like there is a parameter I can add to make it bypass that check. I'll do that for the next release so the installer should then work on the x64 emulator on Windows ARM64. I've re-opened this issue and it will auto close when the next release is published

**Comment by alessandrossC** [comment]
Thank you. and when to expect the next release?

**Comment by dgosbell** [comment]
hopefully in the next few weeks. There is no firm date as I work on this in my spare time so it depends on when I'm able to finish up the current set of features I'm working on.

**Comment by alessandrossC** [comment]
Thank you! I installed on MacBook Air M1. Everything is working!

**Comment by 13317839** [comment]
:( i bought a pc for daxstudio.but i am happy for i can buy mac next time.thankyou.
