### ISSUE TITLE
Feature requests: use PBIX file name for DAX Studio window name and when exporting metrics

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#646]
1. When exporting metrics to a VPAX file, it'd be great if it were named like the PBIX file instead of the model id (hash)
2. It would also be great if the window name showed the name of the file DAX Studio connected to, like Tabular Editor does.

**Comment by dgosbell** [comment]
Thanks for logging this. It's been something I've been thinking of improving. I also want to extend this so that it flows through into the Query History since PBI Desktop seems to generate a new guid each time you open the file.
