### ISSUE TITLE
Metadata Hidden Measures still visible after ticking off checkbox in Options

### ISSUE THREAD

**Issue by fbouckae-crm** [DaxStudio/DaxStudio#647]
DAX Studio v2.15.0.525
Connection: AnalysisServices - 15.0.32.52

## Summary of Issue
in the options I ticked off the checkbox 
![image](https://user-images.githubusercontent.com/58181202/122518985-37421b00-d012-11eb-805d-e24d0fbbeded.png)

but hidden measures are still visible.
![image](https://user-images.githubusercontent.com/58181202/122519313-9d2ea280-d012-11eb-8679-9787478ad8d3.png)

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
Sorry, but I cannot reproduce this at all. When I change this setting I see a new "Metadata Refreshed" message when I switch back from the options window and the hidden objects are immediately hidden. I do re-query the database to get only the visible objects when you change this flag - is there any chance this database was being processed or something like that which may have blocked the metadata queries? Are there any warning or errors in the output pane?

If you can consistently reproduce this issue can you start up DAX Studio while holding down the SHIFT key to enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then reproduce this behaviour, the close DAX Studio and attach the generated log file to this issue on github. I'm not sure if it will tell me much if there are no errors logged in the output pane, but it may capture something that gives me a hint.

**Comment by fbouckae-crm** [comment]
Darren,

All other columns and tables are hidden, except for the hidden measures, and hidden columns from the table(s) used in the measures.
I also see separate items for the formatting string of the measures.
Nothing is blocking the metadata queries.
I’m developing the model and made several changes, and when refreshing the metadata, the changes are shown.

Filip


FilipBouckaert
SmartBI developer
+32 50 83 38 83
***@***.***

**Comment by dgosbell** [comment]
That sounds even stranger. Are you able to reproduce this issue in a demo model that you could share? 

I can't think why some hidden objects would be treated differently that others.

**Comment by fbouckae-crm** [comment]
Darren,

This runs on an on-permise server.
The model itself cannot be shared.
It contains our customers data we can use for testing, but I presume they won’t be happy if we share this data

I’ve captured my screen, perhaps you can see what exactly happens.

It starts with the option to show hidden objects (where you can see SK columns and other that are normally hidden
Also in the display folder Measures\Quantity, you can see hidden columns, and formatStings beside the visible measure columns

Then I set the option off
Then those SK columns are hidden (as expected)
But the format strings and hidden columns under Measures\Quantity remain

Filip



FilipBouckaert
SmartBI developer
+32 50 83 38 83
***@***.***

**Comment by dgosbell** [comment]
If you attached pictures to your previous email they did not come through. Unfortunately when you reply via email Github strips out any attached files. If you want to attach screenshots you need to paste them directly into a comment in this issue on the Github site. Is this possibly a calculation group not a data table?

So I don't need or want any data, a .bim file or the TMSL create script or possibly even a vpax file from the Export Metrics might have enough information. Or if you could create a small model that demonstrates this with 1-2 tables and share the .bim  file for that would be perfect.

**Comment by dgosbell** [comment]
Don't worry about a sample model - I figured it out. It's the display folders. The code that loops down through display folders is not checking that setting properly. I should be able to fix this for the next release.

**Comment by fbouckae-crm** [comment]
I was only able to install it now (was blocked by antivirus system)
the columns are hidden now, but I still see the items for FormatString which are hidden too, is this normal behaviour ?
![image](https://user-images.githubusercontent.com/58181202/122925955-a2b81f80-d367-11eb-91e2-66635651385b.png)

**Comment by dgosbell** [comment]
No this is not normal behaviour, but I cannot reproduce this. When I untick the "Show hidden Columns, Tables and Measures" option everything that is hidden including formatstring measures is no longer shown. I'll need some sort of example model which exhibits this behaviour in order to figure out what is going on here.

**Comment by fbouckae-crm** [comment]
I've reduced the model in the attached zip (BIM is not supported to be uploaded)
When deployed to Analysis services i shows the same behaviour in DAX Studio.
[Sample.zip](https://github.com/DaxStudio/DaxStudio/files/6701372/Sample.zip)

**Comment by dgosbell** [comment]
Thanks for that sample file. I can see the issue when I connect to that so I just need spend some time digging into this to find the root cause.
