### ISSUE TITLE
Unable to see Models or trace queries

### ISSUE THREAD

**Issue by Ormesome** [DaxStudio/DaxStudio#65]
DAX Studio, Version 2.7.4
PowerBI Desktop, Version: 2.56.5023.942 64-bit (March 2018)

I have downloaded a pbix file and opened it in PowerBI Desktop. The data source is a PowerBI Service and the lack of Data or Relationship tabs indicates it's a SSAS solution.

When DAX Studio connects to PowerBI Desktop it does not list any Models and cannot trace any queries.

I have referred to (https://www.sqlbi.com/articles/analyze-directquery-requests-using-dax-studio/) but I still cannot get any Models or traces.

**Comment by marcosqlbi** [comment]
You can only connect to Power BI Desktop with imported data models. If you are connecting to SSAS with a live connections, you should connect DAX Studio to SSAS.
In other words: connect DAX Studio to the service that has the data model.
