### ISSUE TITLE
Case sensitivity when passing database name using the -s and -d command line options

### ISSUE THREAD

**Issue by NickEPalmer** [DaxStudio/DaxStudio#658]
I'm running into an issue related to the case of the AS database name I'm passing when using the -s and -d command line options.

In my SSAS server I have a database named MAXPTEST

If I run the following command:

      "C:\Program Files\DAX Studio\DaxStudio.exe" -s Sunset -d ""MaxPTest""

I get the following message in the DAX Studio output window:

      The following error occurred while updating the connection: The given key was not present in the dictionary

But the following command works:

      "C:\Program Files\DAX Studio\DaxStudio.exe" -s Sunset -d ""MAXPTEST""

SSAS considers the MAXPTEST and MaxPTest databases to be the same, since I can't rename an existing SSAS database to be MaxPTest because it tells me the database name is already in use.

Is it possible to update the logic for the -d command line argument to be case-insensitive when trying to match the database?

Thanks

**Comment by dgosbell** [comment]
Thanks for logging this. I don't think I actually tested with varying cases. It should not be too hard to fix this.

**Comment by NickEPalmer** [comment]
Thanks for the quick fix on this :)
