### ISSUE TITLE
Crashing when opening projects

### ISSUE THREAD

**Issue by WillRod36** [DaxStudio/DaxStudio#66]
Version 2.7.4 

PROBLEM: application crashes when opening any other DAXStudio projects

EXAMPLE: Open DAXStudio from excel (add-in) - connect to data model - When going to 'file' > Open / Browse - when selecting the desired file to open, the application crashes... every time...

I have tried uninstalling and reinstalling to no avail.

**Comment by dgosbell** [comment]
Are you running Win7? As this sounds like this bug with a recent .Net security update http://darren.gosbell.com/archive/2018/02/06/dax-studio-recent-win7-sp1-crashes.aspx
(there are suggested workarounds to fix this in the links in the above post)

**Comment by WillRod36** [comment]
I had windows 10. Tech support was able to reset my computer (i.e., master reset where windows 10 was re-uploaded to my computer) and everything is now working as intended. 

Thanks for the help though!

**Comment by dgosbell** [comment]
Great, well I'll close this issue then as it appears to have been some strange issue on your specific environment that was fixed by the reset.
