### ISSUE TITLE
Can't open a new query tab after update of Dax Studio to v2.160.603

### ISSUE THREAD

**Issue by Dessilava** [DaxStudio/DaxStudio#660]
![image](https://user-images.githubusercontent.com/86661971/123788388-9d695080-d8e4-11eb-9776-38af9714ec12.png)

**Comment by dgosbell** [comment]
What version are you using? This issue should be fixed in the 2.16.1 release.

**Comment by Dessilava** [comment]
I was on 2.16.0 and it said that I had the latest one.  However, I saw 2.16.1 available, I installed it and as you said everything is fixed. Thanks! 
![image](https://user-images.githubusercontent.com/86661971/123794939-19b36200-d8ec-11eb-87a6-c111a5c75c1f.png)

**Comment by dgosbell** [comment]
Yes, DAX Studio currently only checks for new versions every 24 hours and 2.16.1 was released about that long ago specifically to address this issue.
