### ISSUE TITLE
Excel VertiPaq Analyzer - Summary Table Simular to DAX Studio Summary Screen

### ISSUE THREAD

**Issue by asjones987** [DaxStudio/DaxStudio#662]
It would be nice if it the same summary info that DAX Studio has were also in the Excel VertiPaq Analyzer.  Maybe some adjustments in DAX Studio that also rolled to the Excel VertiPaq Analyzer.
The summary table would include
-PBI File Name (i know that is being excluded now, but what about an option to show it? It would help with internal auditing.
-Total Size
-Number of Tables
-Number of Columns
-Last Data Refreshed (Local Time or UTC and Local)
-Analysis Date (Local Time or UTC and Local)
-Server (not as critical for the Excel version
-Count of DAX Columns (bad)
-Count of DAX Tables
-Count of DAX Measures
-Not sure this is possible, but count of automatically  generated DATE tables (if they exist).

It seems like there could be some other good summary statistics and information that could be added.

thanks

Alan

![image](https://user-images.githubusercontent.com/30843311/123859484-52523c00-d8ea-11eb-8c20-63e4100cb9be.png)

**Comment by dgosbell** [comment]
Thanks for logging this idea. So I can make changes in the DAX Studio UI and potentially to the VPAX files generated by DAX Studio, but the Excel version is published by SQLBI so @marcosqlbi would need to address any changes there

> -PBI File Name (i know that is being excluded now, but what about an option to show it? It would help with internal auditing.

All the data shown in Vertipaq Analyzer comes from running queries against the data model. And technically the file knows which data model belongs to it, but the data model is not aware of the file that loaded it. So this information is not specifically excluded, it actually does not exist. However DAX Studio is able to derive this information by scanning the running processes on the machine and looking at the associated window title so I should be able inject this in after the model scan. 

> -Last Data Refreshed (Local Time or UTC and Local)
> -Analysis Date (Local Time or UTC and Local)

The dates are always stored internally in the VPAX file as UTC time, but it should not be too hard to get this to display as local datetimes in DAX Studio and I'll probably look at adding the timezone offset information to make it clear which timezone is being used.

**Comment by marcosqlbi** [comment]
Thanks @dgosbell 
It is complex to add information to the Excel file generated by VertiPaq Analyzer if the info is not generated by scanning the model. We could add arguments to the VPAX library that the host application should complete in optional parameters.
We have a separate repository for the VertiPaq library, which is already used by different tools (DAX Studio, Tabular Editor, and others coming soon): https://github.com/sql-bi/VertiPaq-Analyzer/issues
