### ISSUE TITLE
Debug comma: comma placed at next line does not skip comment lines

### ISSUE THREAD

**Issue by zenzeinet** [DaxStudio/DaxStudio#663]
Hi, for the debug commas feature, the comma is placed at the beginning of the next line ignoring blank lines, but it does not ignore lines that are comments. For example in the following code, if you do Debug Commas, commas will appear at the beginning of the lines /*this is a comment*/ and --another comment , rather than before the next code line, defeating the purpose of Debug Commas. On the other hand, it works well with empty lines (jumps over them)

```
DEFINE
  VAR __DS0FilterTable =
    TREATAS({DATE(2021, 4, 11)}, 'Fechas_migra'[Migra_PreviousSunday])

  VAR __DS0Core =
    SUMMARIZECOLUMNS(
      'Fechas_migra'[Migra_PreviousSunday],
      __DS0FilterTable,
	  /*this is a comment*/
      "Ingresos", 'FacturaVirtual'[Ingresos],
      -- another comment
      "migraciones__clientes_", 'Migraciones'[migraciones (clientes)]

    )

EVALUATE
  __DS0Core
```

**Comment by dgosbell** [comment]
Thanks for logging this. It's a bug around the leading whitespace in front of the comment. I've added some extra unit tests around this scenario and I have a fixed checked in where it will convert from the following:

```
   Line 1,
   -- comment with leading space
   Line 2, // trailing comment
   /* leading comment */ Line 3,
   Line 4
```
to this:
```
   Line 1
   -- comment with leading space
,   Line 2 // trailing comment
,   /* leading comment */ Line 3
,   Line 4
```
So it handles leading, trailing and indented comments.

This will go out with the next update and this issue will automatically close when that is released.
