### ISSUE TITLE
VertiPaq Analyzer Metrics - Summary - Last Data Refresh

### ISSUE THREAD

**Issue by corycundy** [DaxStudio/DaxStudio#670]
When running against an Azure Analysis Service, the Last Data Refresh date on the Summary tab of the VertiPaq Analyzer results seems to be too far into the future. If you run the following two DMV queries, you get similar times in which the data is processed. These times appear to already be in UTC. I'm assuming the Last Date Refresh is calculated using something similar to these queries. 

select [Name], [RefreshedTime] from $SYSTEM.TMSCHEMA_PARTITIONS ORDER BY [RefreshedTime] DESC
SELECT * FROM $System.MDSCHEMA_CUBES ORDER BY [LAST_DATA_UPDATE] DESC

It seems as if the time from these queries is again converted to UTC, putting it further into the future. For example, in my time zone we are -5 from UTC time. I process a tabular model at 11:00 AM local time and it takes about 35 minutes. The queries correctly return 4:35 PM. The Summary tab displays 9:35 PM.

Cory Cundy

**Comment by dgosbell** [comment]
Thanks for logging this. We are currently just returning the dates directly from the following query, not against the individual partitions 
```
SELECT TOP 1 [LAST_DATA_UPDATE]
FROM $SYSTEM.MDSCHEMA_CUBES
ORDER BY [LAST_DATA_UPDATE] DESC
```

However you are correct in your assessment of the issue. The vertipaq-analyzer libraries are calling .ToUniversalTime() on a datetime which is already UTC resulting in the local timezone offset being applied twice.
 
I've created an issue against the vertipaq-analyzer libraries here https://github.com/sql-bi/VertiPaq-Analyzer/issues/16 and pushed a fix. So when @marcosqlbi  pushes a new update to the nuget packages I will pull that into DAX Studio and tag this issue so it will close when I publish the release containing this fix.

And in the next update I am converting the UTC time to the local timezone and displaying the time offset (so it was a lot easier to see this issue in my current debug build)
![image](https://user-images.githubusercontent.com/8241830/125148565-91984c80-e176-11eb-8dfb-b05e2ac7f9c1.png)

**Comment by corycundy** [comment]
Darren, that sounds perfect!

Thanks for you continued support.

Cory Cundy, MCSE: BI
Principal Architect - Data Analytics & Data Platform
P 920.593.3624 | E ***@***.******@***.***>

***@***.***D776EF.19010EC0]<https://corebts.com/>

***@***.***D776EF.19010EC0]  ***@***.***D776EF.19010EC0]
