### ISSUE TITLE
Enhancement: Add a "goto line #" function

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#68]
As a developer
I want to go to a specific line within the DAX editor window
So that I avoid needing to do repeated finds or scrolling especially when editing large query captures from PowerBI. This would implement a manual form of the go to line feature from a DAX error message

Given that I'm in a DAX editor panel
When I press [Ctrl]+[G]
Then I shall get a pop up requesting the line number

Given that I'm in the "Go to line number" pop up
When I enter a line number
And the line number is within the bounds of the lines within the current  DAX editor
Then the DAX editor shall scroll to the designated line

**Comment by dgosbell** [comment]
Thanks for this suggestion, that's a good idea and should not be too hard to implement.

**Comment by dgosbell** [comment]
Added with Ctrl-G hotkey in v2.8.0
