### ISSUE TITLE
Existing Measures

### ISSUE THREAD

**Issue by ringovski** [DaxStudio/DaxStudio#683]
**Is your feature request related to a problem? Please describe.**
Trying to use existing measures in PBIX report. Adding the evaluate command to start of code isn't enough, none the existing measures work in DAX studio.

**Describe the solution you'd like**
Be able to double click the existing measure and DAX studio imports and adds the required commands and formatting so you can just click run and see the results.

**Comment by dgosbell** [comment]
I explained why this is not working in your discussion post at #685
