### ISSUE TITLE
SSRS Parameters

### ISSUE THREAD

**Issue by ccparkhill** [DaxStudio/DaxStudio#69]
Is there any way to copy an SSRS DAX query and declare the parameters in the same way SSRS Query Designer does so that it can be run in DAX Studio without having to replace the parameters with values, e.g. declaring @City with a value of "London" instead of replacing @City in the query with "London"?

Thanks

**Comment by dgosbell** [comment]
Yes you can. This can be done by adding a parameters xml block below your query. (which reminds me that I need to add this to our features list in the documentation)

eg.

```
<Parameters>
    <Parameter>
        <Name>city</Name>
        <Value>London</Value>
    </Parameter>
</Parameters>
```

**Comment by dgosbell** [comment]
Yes, we have thought about adding something like this. I think we might have had that suggestion on the old codeplex site. I've just added a new issue #71 to track that as a feature suggestion.
