### ISSUE TITLE
CSV Custom Export Format is ignored

### ISSUE THREAD

**Issue by ivanMSC** [DaxStudio/DaxStudio#695]
**Describe the bug**
Changing "Custom Export Format" makes no difference on output CSV file.

Running 2.16.2 both installed and portable.

**Comment by dgosbell** [comment]
Thanks for reporting this, but I cannot reproduce this issue.

When I change the custom output settings as follows with ^ as the delimiter and no quoting of string fields:

![image](https://user-images.githubusercontent.com/8241830/128270927-085b3cd3-6102-4a26-bdf1-83ad01563c69.png)

When I  select the custom type when exporting:

![image](https://user-images.githubusercontent.com/8241830/128271120-d4311837-3938-4418-940d-95ae80af9804.png)


I get the output as expected:

![image](https://user-images.githubusercontent.com/8241830/128271140-5ef52ac0-05f8-45f2-a937-ec516d51a4ca.png)


Then I tested changing to tab delimited with quoted strings:

![image](https://user-images.githubusercontent.com/8241830/128271046-8c1fc613-50d1-4c1b-9c4f-b352453762ba.png)

And that produced the expected file format also:
 
![image](https://user-images.githubusercontent.com/8241830/128271076-c71e4e3c-5591-49da-a8c4-f492e2f31cb0.png)

Can you explain in more detail what specifically is not working for you?

**Comment by ivanMSC** [comment]
I am a halfwit.

**Comment by dgosbell** [comment]
> I am a halfwit.

I would not go that far. I don't think I have the options documented all that well. I might use some of the screenshots above to help improve the documentation :)
