### ISSUE TITLE
DOUBLE Data Type Missing

### ISSUE THREAD

**Issue by codepwner** [DaxStudio/DaxStudio#715]
**Describe the bug**
Syntax highlighting for DOUBLE is not working / autocomplete does not recommend DOUBLE.

**To Reproduce**
1. Run a DAX query using the DATATABLE function and include a DOUBLE column.
`EVALUATE
DATATABLE (
    "ID", INTEGER,
    "Name", STRING,
    "Age", DOUBLE,
    {
        { 1, "Bob", 35.5 }
    }
)`

**Expected behavior**
Expect syntax highlighting and autocomplete to recognize DOUBLE.

**Screenshots**
![image](https://user-images.githubusercontent.com/23459162/133508778-9542b8d0-2e99-4f6d-99db-8d72735e38ab.png)

**Additional context**
DAX Studio 2.16.2

**Comment by dgosbell** [comment]
Thanks for logging this. I've checked in a fix which will go out in the next release. This issue will automatically close once that release is published.
