### ISSUE TITLE
Formatter Mistakenly Reports Syntax Error on Valid Code

### ISSUE THREAD

**Issue by codepwner** [DaxStudio/DaxStudio#717]
DAX Studio v2.16.2.632
Connection: SSDT - 15.1.94.18

## Summary of Issue
When formatting, a syntax error is reported for the attached code.  Most times, datetime strings have not caused an issue.
![image](https://user-images.githubusercontent.com/23459162/133702882-fce4e637-08a0-4de0-bda0-8840a58793da.png)

The same code will correctly run against a SSAS server.
![image](https://user-images.githubusercontent.com/23459162/133702968-a92fddb5-5cf2-4a96-883b-ed93a2dca973.png)

## Steps to Reproduce
1. Load attached file and attempt to format the query

[Test Cases.dax.txt](https://github.com/DaxStudio/DaxStudio/files/7181545/Test.Cases.dax.txt)

**Comment by dgosbell** [comment]
Thanks for logging this. We use the daxformatter.com site to format the code. The date literal syntax is new I've raised this with that team to see when they plan to support this new syntax

**Comment by marcosqlbi** [comment]
We published a few fixes to daxformatter.com, including the date literal support in DATATABLE syntax.
It works fine now.
