### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#719]
Hey everyone,
Kindly reopening this issue ticket for DaxStudio, dated today 22/09/2021 5:37 PM EST
I'm running on a Windows 10 Home Edition 64-bit OS, and installed the application.
Sadly, not even the logo appears and the application doesn't start. I tried following what was mentioned on the [DaxStudio Checker](https://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) page to check what could the problem be,  it starts off just showing the version and DaxStudio.exe version number then it barely passes the "**Checking Operating System**" logging showing a fatal error warning.

If I could please get some help, that would be great. 
Thank you all for your help in advance, really appreciated. ^^

_Originally posted by @Ayfarag102 in https://github.com/DaxStudio/DaxStudio/issues/402#issuecomment-925352786_

**Comment by dgosbell** [comment]
> Sadly, not even the logo appears and the application doesn't start.

@Ayfarag102  I've created a new issue to track this.
If the logo is not appearing at all this is a different issue to the one where you originally posted this response.

> ...then it barely passes the "Checking Operating System" logging showing a fatal error warning.

Can you post the text of this error message?

If you do not see the logo at all it is most likely some sort of issue with the .Net framework on your machine. In the documentation on [logging settings](https://daxstudio.org/documentation/troubleshooting/logging-settings/) there is a section at the bottom on how to enable "startup logging". Can you try following those instructions, then try starting DAX Studio and then zip up and upload any log files that get generated to this issue on Github?

**Comment by Ayfarag102** [comment]
Thank You @dgosbell for opening up this issue.
This is the text of the error message, I'll get on with the logging settings you've mentioned above

> 
>     Version =  v2.15.0.525
>     DaxStudio.exe Version =  v2.15.0.525
> 
> Checking Operating System
> =======================
> 
> 
> FATAL ERROR:
> Invalid class 
>    at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
>    at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
>    at DaxStudio.CheckerApp.SystemInfo.GetOSInfo()
>    at DaxStudio.CheckerApp.SystemInfo.OutputOSInfo(RichTextBox output)
>    at DaxStudio.CheckerApp.Checker.CheckOSInfo()
>    at DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by Ayfarag102** [comment]
[NativeImage.zip](https://github.com/DaxStudio/DaxStudio/files/7214711/NativeImage.zip)
Attached is the zipped log file

**Comment by dgosbell** [comment]
Thanks for the log file. Unfortunately I've never seen anything like this before.

I did find [this similar issue](https://github.com/mgth/LittleBigMouse/issues/103#issuecomment-586357163) on another github project  which suggested that this might be caused by a corruption in the user profile.

Do you have any other users on your machine? If so do you see the same issue when logging in as a different user? If you don't it would point to a problem with your user profile.

The other github issue suggested steps like the following, but I cannot reproduce this issue so I have no way of knowing if this is safe or if it will work:

1. Uninstall DAX Studio from Control Panel
2.  Open RegEdit and go to: [HKEY_LOCAL_MACHINE]\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\
3. Under ProfileList find the profile that corresponds to your user. To do that click on the profile entry and check “ProfileImagePath” on the right side
4. After you have located your profile, add a new DWORD (32-bit) value entry name “RefCount” and set the Value to 0.(for more details you can check https://neosmart.net/wiki/corrupt-user-profile/)
5. Sign out from Windows (or restart)
6. Try installing DAX Studio and see if it works now
7. Open RegEdit again and remove the key (RefCount) you added in step 4

**Comment by dgosbell** [comment]
Someone else posted a similar issue today, with a bit more information that I think allowed me to isolate this to a corruption in their machines WMI information. I've been able to add extra error handling to deal with this situation can you check the preview build below to see if it fixes your problem also?

https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/41368710/artifacts

**Comment by dgosbell** [comment]
I believe this issue is caused by a corruption in the WMI information on the PC and there is a fix in the latest release (v2.17) which allows it to work around this problem.
