### ISSUE TITLE
Regarding blocking internet access

### ISSUE THREAD

**Issue by anique9999** [DaxStudio/DaxStudio#725]
Hi,
I used this commad `</TASKS=blockallinternetaccess>` for blocking internet access in DAX studio, but after opening the application, only version check is getting blocked. Other hyperlinks are not getting blocked and it's opening browser when clicking on it. Can you please tell me how can I block these.

Hyperlinks that are not getting blocked:-
![image](https://user-images.githubusercontent.com/90675448/134896959-ea020c1e-9cb0-47a0-9866-37ba8b971953.png)
Version Checks
![image](https://user-images.githubusercontent.com/90675448/134897120-82b6d0b4-b110-4e0d-9651-6019305b4969.png)

**Comment by dgosbell** [comment]
> but after opening the application, only version check is getting blocked.

It's not just version checks, it's also daxformatter connections and the automated bug reporting dialog. It's basically anything where DAX Studio itself makes a direct internet connection or makes an automated connection. 

Those 3 buttons open the default browser to a web URL. They only do that to an explicit user action and they don't transmit any information. If you don't want your users opening any web pages you could block them with a http proxy or some sort of firewall.

**Comment by anique9999** [comment]
Hi @dgosbell,
Apart from version checks, does this application auto-updates?

**Comment by dgosbell** [comment]
No it does not. We try to encourage people to do admin installs into "c:\program files" as it is more secure. And silent auto-updates do not work well with that sort of install as it requires admin elevation. I also know we have some people packaging DAX Studio for automated IT deployments since their users do not have admin rights at all.

**Comment by anique9999** [comment]
Thank you so much @dgosbell.
