### ISSUE TITLE
Copy with/without header option for context menu

### ISSUE THREAD

**Issue by FuegoArtificial** [DaxStudio/DaxStudio#734]
**Is your feature request related to a problem? Please describe.**
It takes time to switch between the defaults of copying data with or without headers. I need both ways a couple of times a day. Quickly choosing if headers are included during copy and paste would be brilliant.

**Describe the solution you'd like**
I could imagine having "copy" and "copy with headers" within the context menu when clicking into the selected data to quickly choose the way to copy. 
The idea is inspired by Management Studio and Azure Data Studio behavior. The feature could also be copied (without the headers ;)) from there.

**Describe alternatives you've considered**
Changing the default in the settings back and forth.

Thank you for this very helpful tool!

**Comment by dgosbell** [comment]
this is included in the 3.0.6 release
