### ISSUE TITLE
Enhancement: Pre-load Find dialog with highlighted text

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#74]
As a developer
I want to pre-load the Find dialog with any highlighted text
So that it's easier to search for a specific term without having to perform a copy/paste into the Find dialog and the environment behaves more like other IDEs (SSMS, VS)

Given that I'm in the DAX editor panel
And there is some text highlighted
When I press [CTRL]+[F]
Then I expect the Find dialog to populate with the selected text

Given that I'm in the DAX editor panel
And there is some text highlighted
When I press [CTRL]+[H]
Then I expect the Find textbox of the Replace dialog to populate with the selected text

**Comment by dgosbell** [comment]
Another good idea that should not be too hard to implement :)

**Comment by dgosbell** [comment]
This is fixed in v2.8.0
