### ISSUE TITLE
Export to Excel failed Error HRESULT: 0x80131040

### ISSUE THREAD

**Issue by nishantjainuk** [DaxStudio/DaxStudio#740]
DAX Studio v2.16.1.615
Connection: PowerBIDesktop - 15.1.92.26

## Summary of Issue
Every time I try to export a data extract either as linked or static file, I get the following error 

![image](https://user-images.githubusercontent.com/24504997/137219012-02e1ef16-6db4-4988-939b-79d7028b4c4f.png)

## Steps to Reproduce
1. Connect Dax Studio to Power BI desktop
2. Run any table query e.g. SummarizeColumn
3. Click on Home -> Output -> Static or Home -> Output -> Linked
4. Export fails with the error shown above

**Comment by nishantjainuk** [comment]
@dgosbell I think I found something. Attached is one of the log files generated by Fusion log which has the same name as the error message. The log also suggests something has failed but I couldn't understand the details. 

There are quite a few other log files generated but I think this is the one you are looking for. Let me know if you need other log files as well. If I can help in any other way, let me know

Thanks
Nishant

[System.Diagnostics.Tracing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.txt](https://github.com/DaxStudio/DaxStudio/files/7447734/System.Diagnostics.Tracing.Version.4.0.0.0.Culture.neutral.PublicKeyToken.b03f5f7f11d50a3a.txt)

**Comment by dgosbell** [comment]
Thanks for posting that log. System.Diagnostics.Tracing is a secondary dependency and that does look like an assembly loading conflict. I've made an adjustment to the build process which I think might fix this issue, but I cannot reproduce this bug so I'm not sure.

I have a preview build (with both the installer and the portable version) here
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/41368710/artifacts

can you try this and see if it fixes the issue for you?

**Comment by nishantjainuk** [comment]
Thanks @dgosbell . The new version has worked for me. I think whatever you did has fixed the issue.

**Comment by nishantjainuk** [comment]
Thanks @dgosbell  . The new version has worked for me. I think whatever you did has fixed the issue.

**Comment by dgosbell** [comment]
I thought that change I made should have fixed this. Thanks for confirming it.

**Comment by dgosbell** [comment]
I've just pushed out this fix as part of the 2.17 release
