### ISSUE TITLE
Command Line Parameter to open an VPAX file

### ISSUE THREAD

**Issue by corycundy** [DaxStudio/DaxStudio#747]
**Is your feature request related to a problem? Please describe.**
While gathering many vpax files over time, it is a handful of clicks to always get them open by going through the Import Metrics button, track down the path and open the file.

**Describe the solution you'd like**
It would be handy to have a command line parameter that opened an instance of Dax Studio with the vpax file. I would envision this working along with the other command line parameters so the vpax file (metrics) could be opened in the same window with a connection to a database. This would then open up the possibility of right clicking on a vpax file and opening it with Dax Studio as well.

**Comment by dgosbell** [comment]
This should work now in v3 and you can also do file > open and open vpax files or double click on them in Windows Explorer
