### ISSUE TITLE
Enhancement: Dark mode

### ISSUE THREAD

**Issue by Kilsgaard** [DaxStudio/DaxStudio#75]
It would be nice to be able to put DaxStudio in Darkmode.

**Comment by dgosbell** [comment]
We did look into this some time ago, but at that point one of the control libraries had issues supporting dark themes. But I think those have been resolved now so we should probably have another look at this when we get a chance.

**Comment by nuttnice187** [comment]
'Tis blinding!

**Comment by JamesDBartlett** [comment]
I would also like to see this feature. Most of the applications in my environment have dark mode enabled, so whenever I open Dax Studio, I almost have to put on sunglasses! B-)

**Comment by dgosbell** [comment]
This is on my list, it just takes hours and hours to retro fit theming to an existing app and I have a few other features in progress that I want to get finished first.

**Comment by darlove** [comment]
Hi there. First I want to thank you so much for DAX Studio. That's a brilliant job you've done. Where would we all be without it? Many, many thanks, indeed. With this post, I would like to join the crowd kindly requesting the dark mode as well. Thank you.

**Comment by dgosbell** [comment]
@darlove yeah, I know this is something that people want, but it's just slow, tedious work. I've spend hours and hours and I've made some progress, but it's still not really functional yet.

**Comment by lizou310** [comment]
Understood. Will be very excited if that's supported in the future. (I prefer dark mode for any work I do)

**Comment by danieljsc** [comment]
looking forward to have this as well 👍

**Comment by darlove** [comment]
Darren, by the way... (and I'm ashamed I did not ask this question the first time): Is there anything I could do to help you with this? I could do some work for you after my office hours...

**Comment by dgosbell** [comment]
Actually, I'm getting pretty close with this now. I think I have a solution that is now working with the various control libraries and I think I've removed most of the hard coded "light" backgrounds so that I can make them dynamic. I'm now waiting on a graphic designer who is helping re-style the UI both to freshen it up and to make it work better in light and dark modes. Hopefully sometime in the next few months I'll get the new graphic assets and at that point I'll need to do a final pass and could probably with some help. 

@darlove do you have any experience in WPF styles and theming? Or are you thinking more in terms of testing / reviewing the dark mode? (both would be helpful, I'll probably run a short private beta to get some broader feedback on the dark mode)

**Comment by darlove** [comment]
Hi Darren.

Sadly, no, I don't work with WPF and theming. But testing... why not? :)

Kind Regards
Dariusz Spiewak

**Comment by dgosbell** [comment]
No worries, like I mentioned I believe I have figured out fixes for all the big roadblocks now anyway. :)

**Comment by LuisTapiaF** [comment]
Are there any news regarding DAX Studio on dark background?
Or on custom color themes?
Anything but white backgrounds, the eye strain is too much on us who work hours in front of a monitor.
Thanks!

**Comment by dgosbell** [comment]
So the next major release will have support for both a light and dark mode, but there will be no custom color themes. I'm not exactly sure when this will land, I've been working on this as my main priority for the last 4-5 weeks and I'm maybe half way through. Although I'm also pretty much re-building a lot of the UI so it will also need a major testing pass and we are starting to get close to the Christmas holidays.

**Comment by darlove** [comment]
Hi Darren. 

Don’t try to make it perfect. Just ship iterations. It’s better to have something than nothing.  Thx

**Comment by dgosbell** [comment]
@darlove unfortunately it's not that simple. And one of the reasons I've put this off for so long is that there is no easy way to do it in small iterations. I can't simply add a dark theme. I'm actually adding *both* a dark and a light theme and then swapping all the references to theme resources in the UI to be dynamic. 

As I work through all the changes I have some things that only work properly in one of the two themes and some things that don't work in either theme. So there is existing functionality that is effectively "broken" in both themes at the moment and it would do more harm than good to release the app in this state.

**Comment by d3sc0b** [comment]
DAX Studio 3.0 has been launched today!
"...the new version also introduces multiple color themes: DAX Studio in dark mode is now just one click away!"
Download from https://daxstudio.org/

**Comment by marcosqlbi** [comment]
Good point, we can close this one!

**Comment by GKilsgaard** [comment]
So fantastic :-D
Thanks

**Comment by pdscodes** [comment]
awesome! thanks for the hard work.

**Comment by Canadug** [comment]
The dark mode looks great.  One suggestion though.  Can you put the toggle under options as well?  It took me forever to realize it was in the 'shortcut' area on the title bar.  Or at least have a comment in the Options area.  I searched for 'dark', 'theme', 'background', etc. under Options, none of which shows a match. Thanks!

**Comment by dgosbell** [comment]
@Canadug this should now be fixed in the 3.0.1 update
