### ISSUE TITLE
Edge warns DAX Studio isn't commonly downloaded

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#757]
**Describe the bug**
Edge warns DAX Studio isn't commonly downloaded

**To Reproduce**
1. Open Edge
2. Go to daxstudio.org
3. Click to download

**Expected behavior**
I expect no such warning

**Screenshots**
![image](https://user-images.githubusercontent.com/10683126/141722442-87d4ca28-08d5-48e1-a23d-10c88b97a5e0.png)

**Comment by dgosbell** [comment]
Yes, something changed in the parameters expected by AzureSignTool and the installer did not get digitally signed. I'll have a fix out shortly

**Comment by dgosbell** [comment]
Fixed in the 2.17.2 release
