### ISSUE TITLE
Make download safer

### ISSUE THREAD

**Issue by shishini** [DaxStudio/DaxStudio#758]
the DaxStudio  installer is not signed , so windows raise a warning when trying to install it
Is this is not possible can you add a sha256 checksum to verify the downloads 

![DaxStudio Capture](https://user-images.githubusercontent.com/2177439/141722592-ac7f0954-a2be-4d9e-9fec-20341965681c.PNG)

**Comment by dgosbell** [comment]
There is already a step in our automated build to sign the installer, but it failed with just a warning about some new parameter it needs. I'll get this fixed as soon as I can.

**Comment by dgosbell** [comment]
Fixed in the 2.17.2 release
