### ISSUE TITLE
daxstudio errror "input string was not in a correct format" when trying to connect to PowerBI desktop file

### ISSUE THREAD

**Issue by RadekGor** [DaxStudio/DaxStudio#760]
**Describe the bug**
I am trying to establish the connection between DaxStudio and opened PowerBI desktop model.
I am connecting using PowerBI/external tools/ Dax Studio/ button or by using "connect" option from DAX studio and choosing correct model.
Both actions fail to connect and gives me the same error: 
"input string was not in a correct format"

Above error is visible in the last DaxStudio version 2.17.2.
I switched to 2.16.2 and everything is fine - the connection works.

**Comment by teroman** [comment]
I get the same error when connecting to SSAS Tabular v15.0.32.52, also version 2.17.2 of DAX studio

**Comment by teroman** [comment]
I changed my locale from fr-FR to en-US and now it works again, hope that help repro the issue.

**Comment by jorgemlesteves** [comment]
Same error here. Nothing in the metadata area.

**Comment by jbjs5820** [comment]
> I changed my locale from fr-FR to en-US and now it works again, hope that help repro the issue.

Where you change that? In Powerbi or Dax Studio.
For me the V2.16 was working. on Ver. 2.17.2 - NOT.
Regards

**Comment by teroman** [comment]
> 
> 
> > I changed my locale from fr-FR to en-US and now it works again, hope that help repro the issue.
> 
> Where you change that? In Powerbi or Dax Studio. For me the V2.16 was working. on Ver. 2.17.2 - NOT. Regards

Just in windows Control Panel, "Change date, time or number formats"

**Comment by teroman** [comment]
#761 added PR that users the invariant locale to parse the CSDL version attribute.

**Comment by dgosbell** [comment]
I have a preview build of a 2.17.3 version which includes the PR from @teroman I'm just trying to setup a VM with a non-english locale to confirm the fix

https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/41556830/artifacts

**Comment by dgosbell** [comment]
I've tested this on a VM where I changed the regional settings to France and 2.17.2 fails with this error and the new new release works. I've just published 2.17.3 that includes this fix
