### ISSUE TITLE
Command Line Emits Exception

### ISSUE THREAD

**Issue by corycundy** [DaxStudio/DaxStudio#764]
Regardless of the parameter combination, the command line throws the following error. DaxStudio opens as expected, however, the error is displayed. This also happens without any command line parameters.

The expected behavior would be to not show the error.

![image](https://user-images.githubusercontent.com/64218283/142424969-13bb353b-f711-4558-b91f-63bf0e8a488f.png)

**Comment by dgosbell** [comment]
So I have a preview build with a fix for the error message here:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/41591562/artifacts

Note that when opening vpax files I don't currently check for any other parameters, it just opens the vpax file. I still need to add support for the server and database parameters when opening vpax files.
