### ISSUE TITLE
Query Builder: Multiple Filter Items

### ISSUE THREAD

**Issue by mihscr** [DaxStudio/DaxStudio#770]
**Is your feature request related to a problem? Please describe.**
The Query Builder does not allow filtering by more than one member/item. This becomes an issue whenever one regenerates the query code, after having manually added multiple items to a filter, which resets the filter to the item in the Query Builder filter field. 

**Describe the solution you'd like**
It would be nice to be able to add multiple items in the filter fields in Query Builder. A dropdown of available items with check boxes would be best. But, at a minimum, the ability to manually type items separated by some divider would also help.

**Describe alternatives you've considered**
So far, I have had to use a third-party text editor where I save the query text, while using the DAX Studio editor as a query drafting tool. But, whenever I update the queries, I have to pick and choose what to copy-paste from DAX Studio to the other text editor.

**Additional context**
This is the Query Builder's filtering interface:
![image](https://user-images.githubusercontent.com/47869159/144119652-34cdf0f1-eca0-4e3a-936a-c9224c292b3c.png)

This is what the Query Builder generates:
`EVALUATE`
`SUMMARIZECOLUMNS(`
`    Company[Country],`
`    KEEPFILTERS( TREATAS( {`**"US"**`}, Company[Country] ))`
`)`

This is what I end up adding manually:
`EVALUATE`
`SUMMARIZECOLUMNS(`
`    Company[Country],`
`    KEEPFILTERS( TREATAS( {`**"US", "CA", "MX"**`}, Company[Country] ))`
`)`

However, if I make changes in Query Builder and have it regenerate the query, my manual additions disappear:
`EVALUATE`
`SUMMARIZECOLUMNS(`
`    Company[Country],`
`    Company[Entity],`
`    KEEPFILTERS( TREATAS( {`**"US"**`}, Company[Country] ))`
`)`

Thank you all for your fine work and dedication!

**Comment by dgosbell** [comment]
The Query Builder already has this ability. Change the condition dropdown to **IN** then enter each value on a new line
![image](https://user-images.githubusercontent.com/8241830/144129238-05eafa2f-8558-4654-b3b0-12ad68a3b296.png)

**Comment by mihscr** [comment]
Thank you, @dgosbell! 

The "in" vs "is" confused me, but I understand the terminology now.
