### ISSUE TITLE
The given key was not present in the dictionary error while impersonating a user to Azure Analysis Service

### ISSUE THREAD

**Issue by babukumarg** [DaxStudio/DaxStudio#789]
DAX Studio v2.17.3.683
Connection: AnalysisServices - 16.0.6.24

## Summary of Issue
I'm trying to impersonate a user while connecting to Azure Analysis Service using the EffectiveUserName connection string property and I see "The given key was not present in the dictionary" error in the Output window. It also don't show the Metadata on the Left Side. All other features works fine. I tried the same feature using Excel and didn't face any issue. Not sure what is wrong. Please find attached log file and screenshot.

Thanks

[DaxStudio-20220114.log](https://github.com/DaxStudio/DaxStudio/files/7872990/DaxStudio-20220114.log)
![DaxStudioLogin](https://user-images.githubusercontent.com/7213396/149581425-d4d50214-d6b1-48d2-aed9-be42c7d269cd.jpg)
![DaxStudioScreenshot](https://user-images.githubusercontent.com/7213396/149581428-79875751-ca75-4d01-bf0a-50fd32404927.jpg)
.

**Comment by dgosbell** [comment]
I'm not able to reproduce this issue at all. I can see that the error happens when trying to load the list of tables, but I cannot see what is triggering it. Does this happen consistently for you?

**Comment by babukumarg** [comment]
It is not happening with all tabular models. Only with one tabular model.

**Comment by dgosbell** [comment]
Is there any chance of sharing a copy of the bim file for that model or do you have any idea of what might be different about this role you are testing?

**Comment by dgosbell** [comment]
closing due to lack of response
