### ISSUE TITLE
Testing OLS Security using roles connecting to a PBI dataset (PPU) shows columns secured.

### ISSUE THREAD

**Issue by jorgemlesteves** [DaxStudio/DaxStudio#791]
Connecting to a PBI dataset (PPU workspace) using a Role to simulate OLS security is not functioning well.
It's not supported or I'm doing something wrong?

Column secured: **SalesAmount**:
![image](https://user-images.githubusercontent.com/31868867/149976526-c062ddf3-4a7b-4e0e-84fa-de088ca1b00d.png)

- Simulating in Power BI Desktop is OK (column is NOT shown):

![image](https://user-images.githubusercontent.com/31868867/149975087-fde6f609-c4b6-49e3-883c-d7310b3aaf7e.png)

- Simulating in Power BI Service is OK (column is NOT shown):

![image](https://user-images.githubusercontent.com/31868867/149975514-cf5e2992-9e7e-4693-bb05-c99bd984436f.png)

- Simulating using DAX Studio connecting Power BI dataset (in a PPU workspace) is **NOT OK**  (column is shown):

![image](https://user-images.githubusercontent.com/31868867/149977190-d4a6f315-dfc7-4f7a-b638-97527e044597.png)

- Simulating using DAX Studio connecting Power BI Desktop  is OK  (column is NOT shown):

![image](https://user-images.githubusercontent.com/31868867/149977916-62f9677e-74f5-4ee3-a15d-5c49305658ab.png)

**Comment by dgosbell** [comment]
The roles are enforced on the server side so there is nothing that the different client tools need to do. The roles information bar that you see is the first part of a larger feature that I'm working on and it looks like maybe that got out of synch somehow. But I've tried everything I can think of and I cannot reproduce this behaviour. Are you able to consistenly reproduce this? If so what version of DAX Studio are you using?

**Comment by jorgemlesteves** [comment]
I will try to reproduce:

![image](https://user-images.githubusercontent.com/31868867/150776027-6b03a522-a6a4-41dd-8513-5cc379214f5f.png)

**Comment by jorgemlesteves** [comment]
Hi Darren.
In Premium capacities, like Premium, Embedded and PPU, even the one who owns the workspace is not really a server instance administrator(no one have those rights, as you can have in SSAS, AAS or in the local instance from the pbix) that is needed to impersonate Roles.
Maybe that's the reason why.

**Comment by dgosbell** [comment]
Yes, I'm pretty sure the issue here is that the Power BI XMLA endpoint does not support the Roles= parameter on the connection string. There is an alternate, undocumented API that Power BI Desktop appears to be using, I'm going to see if I can get that working and build a similar role testing interface.

**Comment by dgosbell** [comment]
So if you use the new "View As" dialog in the Advanced ribbon it should use the correct API depending on your data source and you should be able to test RLS roles on PBI Desktop or PBI Premium

**Comment by jorgemlesteves** [comment]
Solved! Thanks. 👍
