### ISSUE TITLE
Support "Ctrl +/" shortcut  for commenting

### ISSUE THREAD

**Issue by pawarbi** [DaxStudio/DaxStudio#796]
In Power BI's DAX formula editor, you can use Ctrl + / to comment or uncomment selected lines. This is very helpful for debugging and commenting/uncommenting the code on the fly. In DAX Studio, as far as I know, you have click on comment button. Is there a shortcut in DAX Studio? If not, could you please make it same as Power BI's (cntrol + /) for consistency? 

Thanks for all the great work !

**Comment by dgosbell** [comment]
So there is already a key binding to toggle comments and by default it should be Ctrl+/ 
If this is not working for you then you can go into File > Options and then under the key binding tab you can click on the key binding for "Toggle Comment" and they type the key combination you want to use. It's possible that if you are using a non-English keyboard that this key binding may be bound to a different key. On my keyboard (which is using a US keyboard layout) the / key is detected as `OemQuestionMark`
