### ISSUE TITLE
Metadata panel of the left pane too easy to close, and no way to bring back

### ISSUE THREAD

**Issue by edhans** [DaxStudio/DaxStudio#810]
**Describe the bug**
In the panel on the left, the Metadata panel has a little 'x' that is too easy to hit. I finally discovered what is causing it for me today. Clicking Output on my touchpad if I accidentally double-tap the GRID button, it is right where that "x" is, and I close the panel. The only fix is to open a new query window, copy my code, and close the old window.

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fixed checked in which will be included in the next release. This issue will auto close when I publish that release.
