### ISSUE TITLE
Define Measure not working

### ISSUE THREAD

**Issue by Tonyyadav21** [DaxStudio/DaxStudio#811]
**Describe the bug**

![image]**(https://user-images.githubusercontent.com/100932403/156752928-47eeee45-cb9c-431f-99ab-8ec2490e603e.png)

Hi Everyone, 
1) I am trying to define measure in DAX studio but I am unable to see the measure but I can see the data if I click on PREVIEW DATA  , please refer to the link for screenshot of error. 
https://user-images.githubusercontent.com/100932403/156752928-47eeee45-cb9c-431f-99ab-8ec2490e603e.png
2) I have uninstalled DAX studio 3 times and installed but even that did not help.
3) I have checked all the connections and they are fine.
4) My colleague DAX studio is working fine and we have installed on the same day and it was working fine for me till Tuesday it was working fine but it suddenly stopped working from 2 days.
  I Kindly request the team to provide me further steps so that I can able to see the measure from DEFINE MEASURE OPTION.
  
  Kind regards & Much Appreciated,
  Tony

**Comment by dgosbell** [comment]
> but I can see the data if I click on PREVIEW DATA ,

The **Preview Data** only shows columns, not measures. And **Define Measures** only works with explicit measures. This means what you have is definitely a column, not a measure.  If this is the case DAX Studio is working as expected. Although I'm not sure what that [MSC(total)] is in your screen shot and why it has not expression. It's hard to say without access to your data model. Can you upload a small example model that illustrates your issue?

**Comment by Tonyyadav21** [comment]
Hi Darren,
Thank you so much for your prompt response.

Please see below after " = " , I am unable to see the formula.

---- MODEL MEASURES BEGIN ----
MEASURE FactSale[Total Spend] = 
MEASURE FactSale[Total Spend (excl Fees) (total)] = 
MEASURE FactSale[Total Spend (excl Fees) LY (total)] = 
---- MODEL MEASURES END ----

**Comment by humanstorm** [comment]
I also encountered similar issue with Define Measure showing blank with several catalogs. It is a bit strange for me.
I used Define Measure before and it worked great back since I started using Dax in September 2021 to now.
There might be something on Power Bi side.

**Comment by humanstorm** [comment]
Curious,
If I was to run this on DAX studio `select * from $SYSTEM.MDSCHEMA_MEASURES`
Is the _Measure_Is_Visible_ column indicate whether I can see the measure or not?
![image](https://user-images.githubusercontent.com/6989467/156819906-e1156fe9-4dbd-4549-bafd-77cd940d7875.png)

**Comment by dgosbell** [comment]
> Hi Darren, Thank you so much for your prompt response.
> 
> Please see below after " = " , I am unable to see the formula.
> 
> ---- MODEL MEASURES BEGIN ---- MEASURE FactSale[Total Spend] = MEASURE FactSale[Total Spend (excl Fees) (total)] = MEASURE FactSale[Total Spend (excl Fees) LY (total)] = ---- MODEL MEASURES END ----

Sorry, but I am unable to reproduce this so I'm not sure why this is happening. 

What version of DAX Studio are you using?

What data source are you connected to (SSAS, AzureAs, Power Pivot, Power BI Desktop, Power BI XMLA endpoint)?

Are you able to upload an example .pbix or .bim file that demonstrates this issue?

**Comment by dgosbell** [comment]
> Curious, If I was to run this on DAX studio `select * from $SYSTEM.MDSCHEMA_MEASURES` Is the _Measure_Is_Visible_ column indicate whether I can see the measure expression or not? 

By default you should be able to see hidden measures, but you can change this in the options

![image](https://user-images.githubusercontent.com/8241830/156849489-778d0b08-a72e-4407-a9da-2f936fb3fc2c.png)

**Comment by humanstorm** [comment]
> By default you should be able to see hidden measures, but you can change this in the options

For me, I am using Power BI XMLA endpoint, `powerbi://api.powerbi.com/v1.0/myorg/[your workspace name]`
I am able to see both Hidden Measure & Visible Measure.
I was using version 2.17, downgraded to 2.16.2 & 2.16.1 to test. All version returns no measure.

I did try Analysis Server on SSMS with Power BI XLMA endpoint with similar SELECT on $SYSTEM.MDSCHEMA_MEASURES as 
mentioned with similar result. 
I am pretty confident that some form of restriction as in SSMS, there was metadata showing but now it won't showing anything.
Gonna try to connect to a different Power BI XMLA to test whether it is an Endpoint restriction.

**Comment by dgosbell** [comment]
OK so this could be an XMLA endpoint issue. 

What happens when you run the following query
```
select [MEASURE_NAME], [EXPRESSION]
from $system.MDSCHEMA_MEASURES
```

You should see the expression for the measure in the output

![image](https://user-images.githubusercontent.com/8241830/156863747-dde45122-7340-4082-a9cc-d60d9bb754a4.png)

Can you also test the TMSCHEMA_MEASURES DMV using the query below? We use a combination of these two DMVs, but the TMSCHEMA ones will only be available if you have admin rights on the dataset (which I think would be Member or Admin rights in the Workspace)

```
select [Name], [Expression]
from $system.TMSCHEMA_MEASURES
```

You should see output like the following (or an error if you don't have enough permissions)

![image](https://user-images.githubusercontent.com/8241830/156863787-014d512a-8462-4974-b6db-77f358ce9df2.png)

If neither of these DMVs return the DAX expression for the measure then this would be why DAX Studio is not displaying it.

**Comment by Tonyyadav21** [comment]
Hi Darren, Thanks for your response. Now ,I am able to see the Measures in DAX Studio.
The issue with my DAX studio was having admin issues. Once they have enabled its working fine.
Thanks for this community, helping everyone so promptly.

**Comment by leobfg** [comment]
@Tonyyadav21 
I think I am also having similar issues to you (TMSCHEMA_MEASURES no longer outputs local PBIX measures' DAX with an error "The CurrentCatalog XML/A property was not specified!).
But I already have Admin access to the workspaces.

How did you resolve your admin issues in DAX Studio?

**Comment by leobfg** [comment]
My issue was different in the end, as I already have admin rights to our AAS (Azure Analysis Services) model.
Our team's PBIXs have a Live connection to our AAS model, but to query TMSCHEMA_MEASURES, I had to change the Live connection to AAS in my PBIX file into a Direct Query connection to a composite/mixed model. 

Then TMSCHEMA_MEASURES was able to retrieve the DAX inside all the measures (local and external in the AAS model) 🥇

**Comment by dgosbell** [comment]
@leobfg - it sounds like what you are experiencing is the expected behaviour. DAX Studio connects to data models. When a report is in live connect mode there is no data model. Any report level measures are stored as text in the report definition and are injected into the visual query at run time.
