### ISSUE TITLE
DAX Formatter Error FIPS

### ISSUE THREAD

**Issue by charlessmithson** [DaxStudio/DaxStudio#812]
I am merely trying to use the DAX Formatter in DaxStudio and receiving the following error:
DaxFormatter.com Error: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms. 
I am on a fairly locked down laptop and have no means to change any of the system settings.

Please Help
![Capture](https://user-images.githubusercontent.com/101284946/157505507-9dd1a39d-e5b6-4182-bc97-e53869a1c625.PNG)
p

**Comment by dgosbell** [comment]
Thanks for logging this. When we call the daxformatter API we do a one way SHA256 hash of the server name and database name.   And apparently there are 2 ways of generating a SHA256 hash in C# and only one of them is FIPS compliant. I've changed to the FIPS compliant version. 

I'm not sure how hard your laptop is locked down, but there is a preview build with the fix available here if you would like to test it https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/42849403/artifacts
