### ISSUE TITLE
Run Benchmark - Default Values for Number of Executions

### ISSUE THREAD

**Issue by ruve1k** [DaxStudio/DaxStudio#813]
Request to be able to configure default values for the number and type (cold/warm) of executions.

When I typically benchmark a calculation I only need 3 cold cache executions. I'm not concerned with warm cache execution times.

**Comment by dgosbell** [comment]
Thanks for logging this idea. It would not be too hard to add this to a future release.

**Comment by dgosbell** [comment]
This has been implemented in v3

![image](https://user-images.githubusercontent.com/8241830/187346696-4b136115-7980-4526-9bc2-20c379c214ce.png)
