### ISSUE TITLE
string columns become numbers when exported as .csv

### ISSUE THREAD

**Issue by rootsmusic** [DaxStudio/DaxStudio#818]
I'm attaching the data model (export.xlsx) and its data source (election_results-169.csv).  Its data source was outputted from a Python data frame, in which the columns shown were string format.  However, Python outputted election_results-169.csv without any leading "0" characters.

The M code for export[join_col] is:
`= Table.AddColumn(#"", "join_col", each Text.Combine({[COUNTYFP10], [Precinct]}, ""), type text)`
export[COUNTYFP10] starts incrementing from the string value "001".

In Power Query, I changed format back to string and loaded into the data model.  In Dax Studio, the data model's columns are in string format.  I'm selecting to "quote all string fields" in Dax Studio's Export Data Wizard, but why aren't the column's values being quoted in the exported .csv?  (I want to read the exported .csv back into Python.)

(Discussed in https://github.com/DaxStudio/DaxStudio/discussions/817 with @dgosbell)
[election_results-169.csv](https://github.com/DaxStudio/DaxStudio/files/8293200/election_results-169.csv)
[export.xlsx](https://github.com/DaxStudio/DaxStudio/files/8293202/export.xlsx)

**Comment by dgosbell** [comment]
Again, this file exports fine for me and all the string columns are quoted when I choose that option. Are you definitely using the latest version of DAX Studio (2.17.3)?

![image](https://user-images.githubusercontent.com/8241830/158909447-1c6101b5-b7cd-4ac0-a989-057e158e7e3d.png)

**Comment by rootsmusic** [comment]
Sorry, closing.
