### ISSUE TITLE
Define Measure Error in Dax Studio v2.11 on

### ISSUE THREAD

**Issue by NKowalczyk** [DaxStudio/DaxStudio#821]
**Describe the bug**
When I right-click on a measure and press 'Define Measure,' only the measure's name appears in the text editor. It does not display the DAX code used to create the measure.

**To Reproduce**
1. Go to the left panel and right-click a measure
2. click 'define measure'
3. see error - only measure name appears, ie. DEFINE MEASURE 'DATE'[DATE] = 

**Expected behavior**
I expect that the DAX code used to create the measure would display. 

**Additional context**
When I look into the DMV and view the MDSCHEMA_MEASURES, the expression column is left blank within the expression column. I can fix this issue when I change my authorization level to our analysis cube. The cube is currently being hosted on Azure. I have also tested this issue across versions 2.11 and up. This issue persists on all versions.

**Comment by dgosbell** [comment]
This is not really a DAX Studio issue as such. Microsoft made a recent security change in the last few weeks to MDSCHEMA_MEASURES in both the Power BI Service and AzureAS to block access to the measure expressions and just return an empty string if the user does not have admin access. 

I'll probably make a change in an upcoming version to try and communicate this better to the user somehow. But there is nothing I can do from the DAX Studio side to get access to the measure expression on PowerBI or AzureAS if the user does not have admin rights.

**Comment by dgosbell** [comment]
Closing since this is not a DAX Studio bug - it's a change in the security for AAS / Power BI
