### ISSUE TITLE
Select all option in dax editor panel

### ISSUE THREAD

**Issue by nexus150** [DaxStudio/DaxStudio#822]
**Is your feature request related to a problem? Please describe.**
to be able to select all the text in the editor, in order to copy or delete, I need to shade it all either with the mouse or with shift + scroll keys, it would be ideal if when right clicking on it there was the option "select all" / and also in the key binding.

**Describe the solution you'd like**
Include "Select All" in contextual menu in dax editor and in the key bindings

**Describe alternatives you've considered**
If there are a shorcut in order to acomplish that please show in the documentation ( or in key bindings screen)

**Additional context**

**Comment by dgosbell** [comment]
So the edit control in DAX Studio has a built-in key binding of ctrl-A for doing a select all. I don't think it's one I can override so I don't have this listed in the key bindings section, but I should be able to add a "Select All" right click option to a future version
