### ISSUE TITLE
Benchmark Checkbox

### ISSUE THREAD

**Issue by colinmaitland** [DaxStudio/DaxStudio#824]
**Describe the bug**
DAX Studio 2.17.3

(a) When the checkbox option is ticked, the ability to edit Warm Cache Executions is disabled and vice versa. I am wondering if this should be the other way around?

(b) Regardless of whether the checkbox option on the Benchmark screen is ticked or not, Cold Executions and Warm Executions are both invoked after clicking Run. I definitely think this is a bug! I am wondering if the Warm Executions should only be invoked if enabled.

**To Reproduce**
TEST 1
1. Open and connect DAX Studio to a local Power BI Data Model.
2. Click 'Run Benchmark' on the Advanced tab for a DAX Query.
3. Ensure the checkbox is ticked.
4. Notice that the checkbox is ticked but Warm Cache Executions is disabled.
5. Click Run.
6. Notice that both Warn Executions and Cold Executions are invoked.

TEST 2
1. Open and connect DAX Studio to a local Power BI Data Model.
2. Click 'Run Benchmark' on the Advanced tab for a DAX Query.
3. Ensure the checkbox is NOT ticked.
4. Notice that the checkbox is NOT ticked but Warm Cache Executions is enabled This is NOT OK.
5. Click Run.
6. Notice that both Warn Executions and Cold Executions are invoked. This is OK.

**Expected behavior**
(a) When checkbox is ticked, then ability to edit Warm Executions is enabled.
(b) When checkbox is NOT ticked, then ability to edit Warm Executions is disabled.
(c) When checkbox is NOT ticked, then Warm Executions are not invoked.

Alternately, have a separate checkbox for Cold Executions versus Warm Executions so that they can be independently edited and invoked.

**Screenshots**
![image](https://user-images.githubusercontent.com/103472864/162863552-ea8c7771-b0dc-4924-ad61-6725558bfed5.png)

![image](https://user-images.githubusercontent.com/103472864/162863528-dec6d543-36e1-424f-af61-ed70e7317a17.png)

**Comment by colinmaitland** [comment]
Although I just noticed that the behaviour of the checkbox is really to do with whether editing Cold Cache Executions causes the same value to be set for Warm Cache Executions versus editing Warm Cache Executions separately. In which case the behaviour is correct. I will close this now that I have seen this.

**Comment by dgosbell** [comment]
As you've already noticed this checkbox is just meant to "link" the Warm/Cold numbers together. 

I might have a look at re-designing this screen at some point as I don't think it is as intuitive as it could be. Maybe it would be simpler to just have a check box for each which would enable or disable the cold/warm cache options.

**Comment by colinmaitland** [comment]
Hi Darren

Thanks for your review. I agree with your comment ... "Maybe it would be simpler to just have a check box for each which would enable or disable the cold/warm cache options."

DAX Studio is great product.
