### ISSUE TITLE
DAX studio inconsistently able to detect very large PowerPivot model

### ISSUE THREAD

**Issue by cwag03** [DaxStudio/DaxStudio#826]
**Describe the bug**
I have an extremely large Excel PowerPivot model, running office 365 64 bit. I have very inconsistent ability to get DAX studio to be able to detect/connect to the model. I get "Error checking if active Excel workbook has a PowerPivot model (A task was canceled.)" error message at this point more often than not when I try to get DAX studio to connect to it using the Excel add-in. I suspect it has something to do with the size of the model (the .xlsx file is 6gb+) but I don't really know. 

**To Reproduce**
The only things I suspect might be causing the issue is having a very large powerpivot model. I also suspect it could be related to settings I have changed in Excel as a result of other issues I have had with the size of this model. I have checked the "Ignore other applications that use Dynamic Data Exchange (DDE) box in excel settings because of issues I had with the file freezing. Could that be related? It doesn't seem to solve the problem if I change that setting while the model is loaded and try to open DAX Studio again.

**Expected behavior**

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/80131718/163472818-ab994cf3-6beb-49a9-8c5b-5eb4ed3a2026.png)

**Additional context**

**Comment by dgosbell** [comment]
It is highly likely that this is due to the size of your file, it's about 10 times bigger than anything else I've seen. There is an internal 30 second timeout on the check for a PowerPivot model and it's most likely this that is triggering this issue. The DDE setting in Excel should not have any impact as I'm not using DDE to talk to Excel.

Are you sure the model is loaded into memory before you try and connect DAX Studio? Can you see the status bar in Excel while you try to connect and if so does it have a message about loading the data model?

If you have a pivot table in your file can you try clicking on the dropdown for a filter? How long does it take for the dropdown to appear the first time? Is it more than 30 seconds? After the dropdown displays a list of options can you try connecting with DAX Studio and does it work then?

**Comment by cwag03** [comment]
Hi, thanks for getting back to me so quickly. I will try your suggestion,
but yes I am certain the model is loaded when I do this. Because the model
is so large, and I don't really use this file for anything other than doing
analysis with pivots or queries using DAX studio, I don't ever do anything
with the file until I know the model is loaded, which usually takes a
couple of minutes. So yes it definitely takes more than 30 seconds for this
model to load. But, as I said, I never attempt to do anything with DAX
studio without already having the model loaded into memory.

Is there any way to extend that 30 second timeout to see if that resolves
the issue?

**Comment by dgosbell** [comment]
So this was hard coded, but I've now mapped it to a setting in the options. 

![image](https://user-images.githubusercontent.com/8241830/163662674-c5254a98-ed75-4aaf-9704-b36539b3ef25.png)

Are you able to try the following preview build which has this new setting and let me know if this fixes your issue? https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/43252991/artifacts

You could maybe try bumping it up to something like 360 or 500 or something like that to see if it works with a longer timeout.

**Comment by cwag03** [comment]
Thank you, yes I will try it out Monday when back in the office.

⁣Get BlueMail for Android ​

**Comment by cwag03** [comment]
I tried to respond again via email, but not sure if it came through. I have tested several times, and the increased timeout definitely appears to have resolved my issue. I assume it is ok to keep using the preview version you sent me until a new full release is available?

**Comment by dgosbell** [comment]
>  I assume it is ok to keep using the preview version you sent me until a new full release is available?

Yes that is fine. I'm glad that seems to have fixed your issue

**Comment by cwag03** [comment]
I am pretty confident at this point that this does resolve the issue. I set
it to 120 seconds, and I have tried several times, and it is now
consistently detecting the model (and it is definitely taking longer than
30 seconds to do it). Thank you so much for the quick response on this. Do
I just keep the preview version until a new full version is released?
