### ISSUE TITLE
Records pulled is not the same with Power BI

### ISSUE THREAD

**Issue by ynsusanto** [DaxStudio/DaxStudio#832]
Hi, 

I am utilizing Dax Studio to pull some of the transformed data, but I noticed that the number of record between the Power BI and Dax Studio are not matching, it is causing discrepancies. Do you know why is this?

Thank you,
Yessie

**Comment by dgosbell** [comment]
The most likely explanation is that there is a difference in the queries. By default Power BI will apply the "Summarize By" attribute and will use this to inject implicit measure expressions into the query. DAX Studio does not do this, by default it will do a group by and relies on the query author to write any required aggregate measures.

**Comment by dgosbell** [comment]
closing due to lack of response
