### ISSUE TITLE
Error Message: "Warning: PowerPivot model not detected

### ISSUE THREAD

**Issue by jasonmhg** [DaxStudio/DaxStudio#84]
Hi,

My Version of DAX Studio cannot connect to my Power Pivot model.
Below is the log from the DAX Studio Checker:

    Version =  v2.7.4.102

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSVersion       = 10.0.15063
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 7.88
    FreeMemoryGB    = 3.41

    Culture Name              = en-CA
    Culture DisplayName       = English (Canada)
    Culture EnglishName       = English (Canada)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = yyyy/MM/dd

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v4\Client -> 4.7.02046
    v4\Client\1033 -> 4.7.02046
    v4\Full -> 4.7.02046
    v4\Full\1033 -> 4.7.02046
    v4.0\Client -> 4.0.0.0

Checking AMO
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files (x86)\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files (x86)\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 9
    AMO : 13.0.0.0
    ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\PROGRA~2\MICROS~2\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: C:\Program Files (x86)\DAX Studio\DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - file:///c:\program files (x86)\hewlett-packard\addins\hp.alm.exceladdin.vsto|vstolocal

**Comment by dgosbell** [comment]
Is this just happening on one model or with any PowerPivot model that you create?
Do you have Pivot Tables in Excel working against this model?
When you open the Manage window from the PowerPivot ribbon does it open without any errors?

**Comment by jasonmhg** [comment]
Hi dgosbell,

Thanks for helping me.

It happens for every PowerPivot model.
PowerPivot functions correctly.

Thanks,

Jason

**Comment by dgosbell** [comment]
Can you follow the instructions [here](http://daxstudio.org/documentation/troubleshooting/logging-settings/)  to enable the diagnostic logging, then try to connect to a model, then close down DAX Studio and Excel and attach the 2 log files to this issue (there should be one log file generated by the Excel addin and one generated by the UI)

**Comment by jasonmhg** [comment]
Hi Dgosbell,

I am only able to see the log file generated by the Excel addin.
Please refer to the attached.

And sorry for the delay in responding. I got assigned to another project.

Thanks.
[DaxStudio-20180820.log](https://github.com/DaxStudio/DaxStudio/files/2302917/DaxStudio-20180820.log)

**Comment by dgosbell** [comment]
@jasonmhg - sorry, but that log file is only from the user interface and it's just reporting that there is an error coming back from the Excel Add-in. You may need to check if you closed all instances of Excel before starting up with the shift key hekd down (the add-in sets it's logging options when it is first loaded which happens when the first Excel instance is launched)

**Comment by joblinomari** [comment]
I had the same problem, but thanks to @dgosbell, i opened the tab Manage on the pivot table Menu and then connect in Dax and it worked

**Comment by dgosbell** [comment]
Closing due to lack of response from original poster - feel free to re-open if you have more information to add
