### ISSUE TITLE
Error Load Perf Data from Power BI

### ISSUE THREAD

**Issue by AlexCalderaro64** [DaxStudio/DaxStudio#841]
I have a client that saved many json files from Export from Power BI Performance Analyzer. One of them loads correctly but the others no, in the output window says: Error Loading... Value cannot be null, Parameter Name: Null
![error load perf data](https://user-images.githubusercontent.com/83238100/166244813-387b4176-5327-4cf4-a421-4b9dbd625031.png)

I tried to open the json and what I could observe is that there are elements where Component is not indicated as the image bellow:
![Json Details](https://user-images.githubusercontent.com/83238100/166244860-876d12ff-1d55-4764-8873-588c9902a932.png)

Could be a empty visual?
Thank you very much,
Best regards
Alexandre

**Comment by dgosbell** [comment]
A missing component property would cause an error like this. But I don't think this is an empty visual. I tried a couple of ways to reproduce this but could not find a way to generate a file without the component property. However the component property is not critical to the loading of the data so I can add code to ignore it.

I have a fixed checked in, if you want to test a preview build you can try the one here on our build server:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/43420184/artifacts

**Comment by AlexCalderaro64** [comment]
Hi, thank you very much, I've just tested, I have no errors now!
Best regards!

**Comment by nexus150** [comment]
I had the same error today, also solved with this fix.
