### ISSUE TITLE
Export query result

### ISSUE THREAD

**Issue by laje-42** [DaxStudio/DaxStudio#844]
**Is your feature request related to a problem? Please describe.**
I'm using Dax Studio to perform Non Regression Tests. I have entered lots of tests that I run locally.

**Describe the solution you'd like**
After running the tests, I'd like to export the table containing the results to a spreadsheet for instance

**Describe alternatives you've considered**

**Additional context**
Automated tests are used based on this procedure : https://p3adaptive.com/2018/09/automated-testing-using-dax-for-power-bi/

**Comment by dgosbell** [comment]
You can already do this. If you click the Output option in the ribbon and choose to output to an Static Excel file it will send the query results to an xlsx file.

**Comment by dgosbell** [comment]
Closing this issue as the option to export to either csv or xlsx already exists
