### ISSUE TITLE
Unexpected error occurs when using Calculate to add a column to a table defined in code.

### ISSUE THREAD

**Issue by alazyworkaholic** [DaxStudio/DaxStudio#850]
DAX Studio v2.17.3.683
Connection: PowerBIDesktop - 16.0.23.21

## Summary of Issue
Unexpected error occurs when using Calculate to add a column to a table defined in code.
Here is the error:
`2022-05-10 11:06:56 PM		An unexpected error occurred (file 'xldc.hpp', line 356, function 'XLProjectEngine<class XLProjectImpl_Fusion>::ProjectImpl').`

## Steps to Reproduce
1. Open a new query in Dax Studio & connect to any blank Power BI instance.
2. Execute this code:
```
DEFINE TABLE T = DATATABLE("iKey", INTEGER, "tKey", STRING, {{1,"A"},{1,"A"},{2,"A"}})
EVALUATE
VAR A = ADDCOLUMNS(T,"C",CALCULATE(SUM('T'[iKey])))
RETURN A
```
3. Inspect output.

**Comment by dgosbell** [comment]
Unfortunately this error is coming from the Microsoft Tabular engine so there is nothing I can do to fix this from the DAX Studio side of things. The same error will occur if you run this query using some other client tool (like SSMS or Powershell). 

So I'm going to close this as there is no action I can take to fix this. If you need this fixed you will need to raise a support ticket with Microsoft.
