### ISSUE TITLE
Errors when 'Clear Cache' is followed immediately by a query

### ISSUE THREAD

**Issue by greggyb** [DaxStudio/DaxStudio#855]
**Describe the bug**

Various errors and sometimes server disconnections occur when a query is run immediately following a 'Clear Cache' action. Several sample errors included in this report.

**To Reproduce**

1. Open a new query tab
2. Connect to an SSAS server or local PBIX
3. Write or paste in any valid query (as simple as `EVALUATE 'Dim'` is sufficient)
4. Click on 'Home' > 'Clear Cache'
5. Immediately run the query by pressing F5
6. See errors in 'Output' tab

Note, the timing between clicking 'Clear Cache' and hitting F5 is critical to reproduce. My subjective reckoning of timing in the past is as loose as 2 seconds, but to reliably reproduce, I need to perform both actions nearly concurrently. The time delta should be measured in milliseconds between clicking 'Clear Cache' and pressing F5

**Expected behavior**
One of several behaviors is reasonable in this case:

1. Allow concurrent/interleaved user queries and the clear cache command
2. If it is unreasonable to interleave or have these concurrent,
    1. Block out user queries until cache clearing is complete - show a notification or popup indicating that the query cannot be run
    2. Block out user queries until cache clearing is complete - silent no-op if query is submitted during cache clearing (less desirable)
    3. Enqueue the user query to run after the cache clearing is complete

**Errors**

I am including several samples of output from the 'Output' tab below with the errors I am receiving. I am including comments in-line, preceded by '#'. Comments give context to the output line that immediately follows the comment line.

1. Error 1: 'An open request writer already exists'
```
2022-05-22 23:09:43		Establishing Connection
# This 'Query Started' is the click from 'Clear Cache'
2022-05-22 23:10:16		Query Started
2022-05-22 23:10:16		Evaluating Calculation Script for Database: 9dad7f24-ba83-43fc-b455-250f7fc1651d
# This error is from pressing F5
2022-05-22 23:10:16		An open request writer already exists.
2022-05-22 23:10:16		A connection error occurred: The connection either timed out or was lost.
Attempting to reconnect (retry: 1)
2022-05-22 23:10:16	0	Query Batch Completed with errors listed above (you may need to scroll up)
2022-05-22 23:10:16	329	Cache Cleared for Database: 9dad7f24-ba83-43fc-b455-250f7fc1651d
```
No results in the 'Results' tab. After this, the query tab lost its connection to the PBIX, and upon attempting to run the query again after the log above, the connection was re-established and the query ran successfully.

2. Error 2 'The server sent an unrecognizable response'
```
2022-05-22 23:33:03		Establishing Connection
# Clicked 'Clear Cache'
2022-05-22 23:33:06		Query Started
# Pressed F5
2022-05-22 23:33:06		The server sent an unrecognizable response.
2022-05-22 23:33:06		The server sent an unrecognizable response.
2022-05-22 23:33:06	0	Query Batch Completed with errors listed above (you may need to scroll up)
# No result in 'Results' tab
# Hit F5 again to start the query notated again
2022-05-22 23:33:37		Query Started
2022-05-22 23:33:37		Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
2022-05-22 23:33:37	0	Query Batch Completed with errors listed above (you may need to scroll up)
2022-05-22 23:33:50		Error Connecting to server: localhost:61881
```

**Comment by greggyb** [comment]
Note, original report from v2.16.2. Updated to 2.17.3 (latest download from daxstudio.org). Can reproduce. Sample from 2.17.3:

```
2022-05-23 00:27:10		Establishing Connection
2022-05-23 00:27:18		Query Started
2022-05-23 00:27:18		An open request writer already exists.
2022-05-23 00:27:18		DIME protocol error: The stream cannot be written to.
Parameter name: stream
2022-05-23 00:27:18	0	Query Batch Completed with errors listed above (you may need to scroll up)
```

**Comment by greggyb** [comment]
Another 2.17.3 error output:

```
2022-05-23 00:29:06		Establishing Connection
2022-05-23 00:29:26		Query Started
2022-05-23 00:29:26		The connection cannot be used while an XmlReader object is open.
2022-05-23 00:29:26		The server sent an unrecognizable response.
2022-05-23 00:29:26	0	Query Batch Completed with errors listed above (you may need to scroll up)
```

**Comment by dgosbell** [comment]
I've been able to reproduce this and you are correct that the issue is caused by the 2 commands interleaving. I do not think it makes sense to run them concurrently as then any cold cache timings could be inaccurate. Making the run a silent no-op is easy, but I'd like to see if I could just enqueue the query until the clear cache is complete as I think that would be the best user experience.

**Comment by greggyb** [comment]
I can come up with an argument for running a query while the cache is clearing, but it is quite an edge case. I have never had a reason to do this sort of testing, and I struggle to imagine a scenario where I recommend doing such testing for client work.

I imagine that if such testing is desired, it would be a better solution to implement outside of DAX Studio.

All this to say that I agree that interleaving the execution is not a good idea for a solution here.

**Comment by marcosqlbi** [comment]
It is all but an edge case.
Typically when you optimize a DAX query you *want* to analyze the query plan and the storage engine queries with the empty cache, otherwise, you may miss important optimization. The storage engine cache is very limited and in a real production environment, it is missed most of the time by a different report.

**Comment by greggyb** [comment]
@marcosqlbi, I do not intend to imply that clearing the cache is not helpful in optimization. I am referring specifically to the interaction of concurrent clear cache commands and user queries, i.e., the timeline of events below (and what will, in the current release of DAX Studio, sometimes yield error conditions as reported in this issue).

```
 |<--User presses 'Clear Cache'
 |    |------------------------------Server clearing cache------|
 |    |    |<--User submits query                               |
 |    |    |    |--------------------Query execution----------------------------------------|
 |    |    |    |                                               |                           |
 v    v    v    v                                               v                           v
T=0  T=1  T=2  T=3                                             T=4                         T=5
```

What we see here is that the clear cache command and the query execution are running concurrently. Between times 3 and 4, the server is doing the work of clearing cache and also the work of query execution. The errors mentioned in this issue happen somewhere in the time span between times 2 and 5 (not inclusive - the error happens after the UI interaction and before the query results are returned to the user).

The testing pattern that I believe you are suggesting is the timeline below. I have elided the user actions here to focus on the serial nature of first clearing the cache, then executing the query.

```
 |------------------------------Server clearing cache------|
                                                            |--------------------Query execution----------------------------------------|
```

Are you suggesting that the first timeline is a typical test case that DAX Studio should support, or are you referring to the second timeline?

If the first timeline is the test case you consider important, then it seems DAX Studio has never been an appropriate tool. If the latter, then fixing this issue (and my comment above) have no bearing on that.

**Comment by marcosqlbi** [comment]
I think we just have a misunderstanding.
You should only test the second timeline, and "Clear cache then Run" does exactly that.
The first timeline is useless and shouldn't happen - it's also a cause of the bug you indicated.

**Comment by dgosbell** [comment]
I agree with Marco. While the first timeline may happen in production scenarios where a query hits a "semi-warm" cache. There are too many variable for it to be a useful performance tuning scenario. What we really want is the second serial timeline which should give us a consistent "worst-case" scenario to tune against.

**Comment by greggyb** [comment]
Yep, just took a few extra comments to realize we are all agreeing.

**Comment by dgosbell** [comment]
> Yep, just took a few extra comments to realize we are all agreeing.

I figured that might have been the case :)

While technically the server _could_ handle interleaving the ClearCache and the query, as we all agree there is no real value in doing so. In this case the error is actually coming from the way I'm calling the ADOMD client libraries from multiple threads since I had not actually design for them to be called in that way.

**Comment by dgosbell** [comment]
@greggyb - I think I fixed this one, but forgot to tag the checkin to this issue. Would you mind confirming if this is still an issue or not for you?

**Comment by dgosbell** [comment]
closing due to lack of response
