### ISSUE TITLE
Option to use query buldier after closed

### ISSUE THREAD

**Issue by SebastianCamiloRodriguez** [DaxStudio/DaxStudio#860]
DAX Studio v2.17.3.683
Connection: AnalysisServices - 16.0.30.29

## Summary of Issue
Hello,

I use dax studio, and i se in the option to use again the Query Buldier after close but the option is unavalible.

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
Thanks for reporting this issue. It will be fixed in the next release. As a short term work around you can hide the query builder by clicking on the icon in the ribbon instead of using the X button.

**Comment by dgosbell** [comment]
This should be fixed in the v3 release
