### ISSUE TITLE
Does connect to Excel

### ISSUE THREAD

**Issue by crojaspdx** [DaxStudio/DaxStudio#862]
**Describe the bug:
Launch DaxStudio from Excel, it can see the model but it doesn't connect.  See attached screenshot
![Temp](https://user-images.githubusercontent.com/107213773/172924560-c1ac2028-e10f-454b-a090-f50d538112fc.jpg)
![Temp](https://user-images.githubusercontent.com/107213773/172924653-2a24523f-d37d-41ad-a212-7f4a4ad09693.jpg)

**Comment by dgosbell** [comment]
What size is your xlsx file - is this a large model? Are you seeing an error in the Output pane as was reported in issue #826 ?

**Comment by dgosbell** [comment]
Closing due to lack of response
