### ISSUE TITLE
Issue to display field list on a PBI dataset

### ISSUE THREAD

**Issue by mathindia** [DaxStudio/DaxStudio#872]
DAX Studio v2.17.3.683
Connection: AnalysisServices - 16.0.35.23

## Summary of Issue
For one of the datasets in our PowerBI premium workspace, users whose access is controlled using RLS are not able to connect properly and view the field list in DAX studio.  Sometimes an error occurs - A connection error occurred: The remote server returned an error: (400) Bad Request.  

Other datasets on the same workspace don't have this issue. If they connect to one of the other datasets and then switch to this one, the field list still doesn't populate but an existing DAX query can be run.  We did publish a new version of that dataset about 10 days back while the other datasets in the workspace were published few months back.  

What can cause such an issue?  What's more confusing is that Admins on the workspace don't have this issue and can use dax studio to view the fields and run queries on all datasets.  Any suggestions why this might happen please?

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
> Sometimes an error occurs - A connection error occurred: The remote server returned an error: (400) Bad Request.
So are you saying it does work some of the time and it only returns this error occasionally?

> What's more confusing is that Admins on the workspace don't have this issue
That is no so confusing since Admins do not get any RLS restrictions applied to them.

I have not seen this before. I'll have to see if I can setup a secondary user and test against a dataset with RLS. I've been testing this locally against SSAS and Power BI Desktop, but have not done my testing of RLS directly against the XMLA endpoint.

**Comment by mathindia** [comment]
This same dataset used to work with RLS till a few weeks back using DAX studio for all users and admins. Other datasets on the workspace also have RLS applied and it works for everyone even now.  This issue doesn't also occur for all users. There are some people facing this issue and others it does work ok. It does seem that the users who had a recent windows update applied could be the ones facing the problem. We got moved to Windows 10 Enterprise Version 20H2.  That's just my guess while trying to find a common factor.  The problem isn't intermittent - everyone facing the problem is just not able to view the field list to build queries.

**Comment by dgosbell** [comment]
Sorry, but the datasets I have with RLS work fine with DAX Studio and I do not see this issue. So this would suggest that it's something specific to your dataset. Are you able to try running Fiddler (https://www.telerik.com/download/fiddler) and turn on HTTPS decryption under Tools - Options. You should then be able to capture a network trace of the communications between DAX Studio and the Power BI Service and sometimes this can show additional information behind the generic "400" error which might tell you what the root issue is here.

**Comment by mathindia** [comment]
Hello

My apologies for the delayed update. We have been trying different things.  We weren't able to get fiddler working in our environment - some kind of proxy issues keep coming up.

We figured that when we did an update to our dataset in June, we have made some changes that don't seem compatible with version 2.17.3 for some reason (though we have been using that version for several months now).  When we tested  by removing a couple of our KPIs, it started connecting. However, doing that is not an option in our production version as they are in use.  Then we saw that it was working ok for a person who had version 2.16.2 installed.  So we uninstalled the latest version and tried that out. It has worked with some of us.  For some others, it worked the first time and then they started getting an error on trying to open DAX studio itself  'object of type 'system.componentmodel.defaultvalueattribute' cannot be converted to type 'system.int32'  I'm not sure why - maybe the uninstall wasn't done properly?  Or maybe this is a .NET framework version issue?  We are continuing our troubleshooting. But any ideas please share.

**Comment by dgosbell** [comment]
Sorry, somehow I don't think I got the notification of your reply to this issue. Are you able to test with v3.0.5 and see if this is working now? Downgrading is highly unlikely to fix issues with a Bad Request error.

**Comment by mathindia** [comment]
Hello - this issue was resolved with version 3.0 which came out when we were facing this problem. Thanks for following up on this!
