### ISSUE TITLE
i need, can copy to excel heading title in result query

### ISSUE THREAD

**Issue by sasangka2** [DaxStudio/DaxStudio#876]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dgosbell** [comment]
I'm sorry, but I do not understand what you are asking for here. Are you able to provide more information?

**Comment by dgosbell** [comment]
closing due to lack of response. Feel free to re-open if you can provide more information about this request
