### ISSUE TITLE
count name

### ISSUE THREAD

**Issue by tasleemjay** [DaxStudio/DaxStudio#880]
DAX Studio v2.17.3.683
Connection: PowerBIDesktop - 16.0.36.23

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
Can you please provide more information about this issue? As it stands I don't understand what the problem is.

**Comment by dgosbell** [comment]
Closing due to lack of response. Feel free to re-open or create a new issue if you have more information to share
