### ISSUE TITLE
That An incorrect expression here

### ISSUE THREAD

**Issue by Toughguy1226** [DaxStudio/DaxStudio#881]
**Describe the bug**

There is  An incorrect expression 

https://daxstudio.org/documentation/features/parameter-support/

EVALUTE   (EVALUTE is incorrect ,   the right one is EVALUATE)
FILTER('Product', 'Product'[Color] = @color)

**Comment by dgosbell** [comment]
Thanks for logging this. I'm working on an update to the website and I'll include a fix for this typo in that.

**Comment by dgosbell** [comment]
This should now be fixed on the new site although the link has changed slightly.
https://daxstudio.org/docs/features/parameter-support/
