### ISSUE TITLE
I can't define table in DAX studio 2.17.3

### ISSUE THREAD

**Issue by qduwg** [DaxStudio/DaxStudio#883]
I meet a strange problem.  when I want to define a Table in Dax Studio 2.17.3 ,It fails.  It prompt that The ** Table can't find.

I don't know why this happen? who can tell me ? help me!

thanks alot!

DAX lover.

**Comment by dgosbell** [comment]
This is most likely due to a syntax error in your DAX. Can you post an example query which demonstrates this issue?

**Comment by qduwg** [comment]
Thank you Mr.dgosbell，but I just copy any program about "define table“ commands to the Dax Studio to run. And no any syntax error ,but to display " ***table cant find"。 here I cant post a picture to demonstrate this issue. the code can refer to here: https://dax.guide/st/table/,  it is about how to define a table in dax studio. but I fail .Maybe I can record a screen and post your mailbox ? pls leave it to me . I post it to you.  thank you.
![tableerror](https://user-images.githubusercontent.com/68672575/183082636-0aac8ef2-5e4a-468c-9401-1c2a29fff5f2.jpg)

**Comment by marcosqlbi** [comment]
Are you using SQL Server Analysis Services?
The syntax you are using is not supported on Analysis Services 2019 or earlier versions.

**Comment by marcosqlbi** [comment]
The version of Power BI that you use is very old, too. The TABLE features has been introduced in late 2020 with composite model, probably November or December.
You can see in DAX Studio the version of the engine you are connected to:
![image](https://user-images.githubusercontent.com/13840816/183097452-b13101ef-b231-4035-8eeb-9ae7ee0c1684.png)
Unfortunately, it's not easy to convert that version into a product version by using that number - you can start from this list, but we don't have an equivalent conversion map for AS engine versions used in Power BI Desktop:
https://sqlserverbuilds.blogspot.com/

**Comment by qduwg** [comment]
I just now  run the POWERBI  2.99.862.0 64-bit (2021-11) AND  dax studio 1.17.3， I found that it runs "define table" command successfully.   I get it .

It is  the matter of POWER BI's version too low to run the defin table command .  

![tableerror2](https://user-images.githubusercontent.com/68672575/183099266-3107da3c-c38f-4b81-beea-707bb45bf030.jpg)

**Comment by qduwg** [comment]
> The version of Power BI that you use is very old, too. The TABLE features has been introduced in late 2020 with composite model, probably November or December. You can see in DAX Studio the version of the engine you are connected to: ![image]


Thank you for your answer!   MY computer is somewhat out of date . so  only the older version power bi can be runed on this WIN7 platform .  cause the older WIN7 can't surpport the newer version of POWERBI software.  So ,I can run VM to test the new feature for POWERBI.  and I get it. thank you .

**Comment by qduwg** [comment]
![tableerror3](https://user-images.githubusercontent.com/68672575/183101679-9ab8ab95-cd1d-452b-8dad-5a0932608d37.jpg)

**Comment by qduwg** [comment]
Mr Marco Russo，I am a novice for DAX all though I have stuied hard for more than half year.   I feel so much interestings in it . DAX is indeed surely one nice tool should be  worthy of  mastering it .  The most difficult to a beginner is how to understand the 
Order of Evaluation in CALCULATE Parameters[the websie is : https://dax.guide/calculate/].  I want you give me some instruction with some relative examples. Pls give me a typical case to demonstrate each step.   

Thank you very much .

Best wishs.

Yours fans, wanggang from China.

**Comment by marcosqlbi** [comment]
You can find more details in [our book](https://www.sqlbi.com/books/the-definitive-guide-to-dax-2nd-edition) or in our [Mastering DAX video course](https://www.sqlbi.com/p/mastering-dax-video-course/)!

**Comment by qduwg** [comment]
the following words is the STEP5 OF CALCULATE RULES.    My doubt is added in the Parentheses. 

CALCULATE evaluates all the explicit filter arguments in the original filter context. It applies their result to the new filter context generated after step 4. These filter arguments are applied to the new filter context once the context transition has happened so they can overwrite it, after filter removal—their filter is not   (**why here is "not"?  Is not ALL* functions to do this work? if not ALL* function do removel , who do this removel work ??????**) removed by any ALL* modifier—and after the relationship architecture has been updated.

**Comment by marcosqlbi** [comment]
It relates to "the filter arguments applied to the new filter context". In other words, the filter you write in CALCULATE are not removed by an ALL*/REMOVEFILTERS modifier in the same CALCULATE:

However, this forum is for DAX Studio :)
Please post comments on related articles on www.sqlbi.com, it would me much better - thanks!

**Comment by qduwg** [comment]
You means that the filter arguments  is the  explicit filter (the  explicit filter  is the 2nd parameter in CALCULATE) ? 

From the  fllowing text, I can't get the information that "the filter you write in CALCULATE are not removed by an ALL*/REMOVEFILTERS modifier in the same CALCULATE".  

“after filter removal ( who remove the filter? )—their filter is not removed by any ALL* modifier—and after the relationship architecture has been updated. ”

**Comment by marcosqlbi** [comment]
@qduwg please, move this discussion to the comments of a related article on www.sqlbi.com, thanks!

BTW: I don't fully understand the question, because I don't get the meaning of an "explicit" filter as opposed to an "implicit" one. But, again, this is not the right place for this conversation!

**Comment by qduwg** [comment]
From which topic on the www.sqlbi.com  can I publish my question?  pls tell me  the  web link?

**Comment by marcosqlbi** [comment]
https://www.sqlbi.com/articles/order-of-evaluation-in-calculate-parameters/

**Comment by qduwg** [comment]
I am very sorry,  from that website  I can't publish my question. NO any position can I  write my question to consult you.

**Comment by marcosqlbi** [comment]
At the bottom of the page there is a "Comments" section manage by the DISQUS service. In case you are not able to see it, check if you have a firewall that is blocking it.

**Comment by qduwg** [comment]
there is only a "comments" word at the bottom of that webpage ,but not active .it is not a hotlink. maybe it is blocked by firewall?

**Comment by marcosqlbi** [comment]
Yes, it could be a firewall blocking it. Try with a connection without the firewall.

**Comment by marcosqlbi** [comment]
I don't know - you should ask to your network administrator whether they have a firewall.

**Comment by qduwg** [comment]
I just use my pc at home.  I just stop the firewall on my PC. there is no any firewall runing. it is very strange. what can i do?

**Comment by marcosqlbi** [comment]
You should ask your provider. I don't know whether DISQUS is blocked in a few countries, in that case you might consider using a VPN.

**Comment by qduwg** [comment]
I just got suddenen lightenment  .   IN our coutry the DISQUS is surely blocked . so I can't bring my question on the form. it is a pity. 

thank you.
