### ISSUE TITLE
Tutorials link is broken

### ISSUE THREAD

**Issue by ginameronekaltra** [DaxStudio/DaxStudio#886]
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.39.21

## Steps to Reproduce
1. Open DAX Studio 3.0 with splash screens / hints enabled (such as on first load)
2. View hint for "Start typing query in this area" and click link for writing DAX queries https://daxstudio.org/tutorials/writing-dax-queries
3. Link resolves to "Page Not Found" error on daxstudio.org site

**Comment by dgosbell** [comment]
Thanks for logging this. I've rebuilt the docs site using a new framework and the links have changed. I've added a redirect on the website which should be live in a few minutes and I've update the links to the correct location for the next release.
