### ISSUE TITLE
Error Viewing Metrics - Azure AS - Compatibility 1400

### ISSUE THREAD

**Issue by ruve1k** [DaxStudio/DaxStudio#887]
When connected to an Azure AS model (compatibility level 1400) if I click View Metrics in DAX Studio 3.0.0 I get the error message below. It worked fine in 2.17.3

Error viewing metrics with ReadStatisticsFromData enabled (retry without statistics): The specified column was not found in the context at line 8, column 5.

Technical Details:
RootActivityId: ac967cee-214a-41b4-ba06-d97b34fe79bd
Date (UTC): 8/24/2022 2:16:11 PM

Error viewing metrics: The specified column was not found in the context at line 8, column 5.

Technical Details:
RootActivityId: df0f3e32-b2b3-4763-b483-bb9751f0a4be
Date (UTC): 8/24/2022 2:16:12 PM

1. Connect to an Azure AS model with compatibility level 1400 in DAX Studio 3.0.0
2. Click on View Metrics
3. See error

**Comment by marcosqlbi** [comment]
Thanks for reporting the compatibility level - it's strange you get the error on Azure AS, but I will try to reproduce it.
In the meantime, you can disable the "Read statistics from data" setting in the advanced tab of options dialog box.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/13840816/186444107-dca04e53-a10d-4e96-9cdc-ed28c4ad01e3.png">

**Comment by ruve1k** [comment]
Marco, thanks for the quick reply.  Unfortunately, changing that setting didn't help and I'm still getting the error below.
Note that in 2.17.3 "Read Statistics from Data" is turned on and it works fine. I'm not sure what might have changed in 3.0.0 for the View Metrics capability. (It seems to work on models with compatibility 1550 but many of our production data models are still compatibility 1400.)
Thanks for looking into this!

Error viewing metrics: The specified column was not found in the context at line 8, column 5.

Technical Details:
RootActivityId: dd1fbded-15ea-4cab-8249-639728ac39ad
Date (UTC): 8/24/2022 2:34:34 PM

**Comment by dgosbell** [comment]
this should now be fixed in the 3.0.1 update
