### ISSUE TITLE
Norton does not like this application

### ISSUE THREAD

**Issue by kaDargo** [DaxStudio/DaxStudio#888]
I got setup executable from https://daxstudio.org/.

I'm going to be safe and remove the application.

**Comment by marcosqlbi** [comment]
Do you have a specific error?

**Comment by kaDargo** [comment]
It kept telling me the files were unsafe.

First one it notified me about was NumberUpNumberDownlib.dll (spelling may
be incorrect) on file name.

I've uninstalled and doing a full system scan.

**Comment by marcosqlbi** [comment]
I'd say it's a false positive, probably because the file was just released and there were not many downloads. Keep us posted about new findings, there is not much we can do as the file is digitally signed and not compromised. Thanks.

**Comment by kaDargo** [comment]
I'm beginning to think that myself as I'm not noticing any strange behavior
or traffic.

Scary though.

**Comment by dgosbell** [comment]
I've run both the installer and the portable version through the Virus Total service and no other AV engines have flagged any issues (see the reports below). Unfortunately, we occasionally get false positives when releasing new versions. Most of the AV vendors have a way you can report suspected false positives to them.

**Installer**
https://www.virustotal.com/gui/url/7cddb7836f2d573ac51e61d096bab9481e1c854b51b4616892008fcdac356e3f

**Portable**
https://www.virustotal.com/gui/url/954601b8c80f39b5508a267f4c5eb18e6d5ca0e922a98ec071e1337c62f6507d?nocache=1

**Comment by kaDargo** [comment]
Thanks for the information and the reassurance.

**Comment by dgosbell** [comment]
I'm going to close this as it appears to be a Norton issue and not something we can fix from our end
