### ISSUE TITLE
DAX Studio won't connect to Power Pivot Workbook

### ISSUE THREAD

**Issue by spotpuff** [DaxStudio/DaxStudio#89]
I get the error
`Exception has been thrown by the target of an invcation.`
![image](https://user-images.githubusercontent.com/32026605/42645586-6d26d6b8-85cc-11e8-803f-c0bb4431597a.png)

I read in a previous ticket that this was related to the workbook's filename, but the filename does not contain single quotes.  I renamed the file to "test.xlsx" and DAX studio still won't connect.

I've verified that DAX studio will work with other workbooks, though, so something about this data model isn't being handled properly. It's not table names with spaces either as I tested that this works with another file.

My Excel version is:
![image](https://user-images.githubusercontent.com/32026605/42645560-57cbfa32-85cc-11e8-8927-319c7dc4cc67.png)

**Comment by dgosbell** [comment]
Yes, it is complaining about a ' character in the connection string. Does one of the folders in the path for your PowerPivot model contain one of these single quotes?

**Comment by dgosbell** [comment]
This is just a temporary issue. In the next release we are quoting the file path correctly so it will not matter if you have any of these special characters in the file path

**Comment by spotpuff** [comment]
Great! The program is awesome either way.

**Comment by dgosbell** [comment]
This should now be fixed as of the recent 2.8.0 release
