### ISSUE TITLE
DAX Studio 3 shouldn't remove old version

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#890]
The old version is already a perfected art, it is mature tool, I believe the new version shouldn't remove the old one. It is useful to also showcase someone the changes side by side.

**Comment by dgosbell** [comment]
Upgrading is optional, but all of the new development and bug fixes will be going into the current version. 

If you want to run an older version, you can use the portable release and just unzip it to a folder (or you can keep the v2 as your installed version and run v3 using the portable mode)
