### ISSUE TITLE
error at the beginning of DAX Studio 3.0 installation

### ISSUE THREAD

**Issue by marcl11** [DaxStudio/DaxStudio#893]
Tried to install DAX Studio 3.0 (like all previous versions) and immediately i get the error message Unable to execute file in the temporary directory. Setup aborted. Error 5 denied access

**Comment by dgosbell** [comment]
I cannot reproduce this. It sounds like possibly an anti-virus scanner or an IT policy blocking something. The install script has not really changed between v2.17.3 and v3.0.0

Does the v2.17.3 installer still work?

**Comment by marcl11** [comment]
The 2.17.3 installer version works

I could open the 3.0 with the portable tool

Thx for checking : yep smth in the IT of my company might be the cause (I’ll check internally)
You can close this ticket

Mit freundlichen Grüßen / Best regards / Salutations
Dr. Laurent MARC
Senior Specialist Business Controlling

Phone: +49 621 40 549 100, Mobile:  +49 1525 4912784, Email: ***@***.******@***.***>
Postal Address: Master Builders Solutions Deutschland GmbH, Glücksteinallee 43-45, 68163 Mannheim, Germany

[Ein Bild, das Zeichnung enthält.  Automatisch generierte Beschreibung]
Master Builders Solutions Deutschland GmbH, Registered Office: 83308 Trostberg, Germany
Companies' Register: Amtsgericht Traunstein, HRB 10261
Managing Directors: Thomas Gmelin, Carsten Hennicke
www.mbcc-group.com<http://www.mbcc-group.com/>

[Ein Bild, das Messer, Zeichnung enthält.  Automatisch generierte Beschreibung]

**Comment by dltmurphy** [comment]
Defender Attack Surface Reduction Rules is blocking it. I've had to create an exemption into the policy for the file path: C:\Users\*\AppData\Local\*\*\DaxStudio*.tmp

<img width="241" alt="image" src="https://user-images.githubusercontent.com/6512845/186646104-09a98799-9602-42ff-8482-c87d542195ba.png">

**Comment by marcl11** [comment]
Good morning,
I thought I had to wait for a patch, but this morning I’ve tried to install it again and it worked 😊

Thx a lot for your very prompt and efficient support , much faster than my response time 😊

Mit freundlichen Grüßen / Best regards / Salutations
Dr. Laurent MARC
Senior Specialist Business Controlling

Phone: +49 621 40 549 100, Mobile:  +49 1525 4912784, Email: ***@***.******@***.***>
Postal Address: Master Builders Solutions Deutschland GmbH, Glücksteinallee 43-45, 68163 Mannheim, Germany

[Ein Bild, das Zeichnung enthält.  Automatisch generierte Beschreibung]
Master Builders Solutions Deutschland GmbH, Registered Office: 83308 Trostberg, Germany
Companies' Register: Amtsgericht Traunstein, HRB 10261
Managing Directors: Thomas Gmelin, Carsten Hennicke
www.mbcc-group.com<http://www.mbcc-group.com/>

[Ein Bild, das Messer, Zeichnung enthält.  Automatisch generierte Beschreibung]

**Comment by marcl11** [comment]
Good morning,

Tried this morning to install the 3.0.3 version and the solved error appeared again!

I’d assume you need again to Defender Attack Surface Reduction Rules is blocking it. I've had to create an exemption into the policy for the file path: C:\Users*\AppData\Local**\DaxStudio*.tmp


***@***.***

Mit freundlichen Grüßen / Best regards / Salutations
Dr. Laurent MARC
Senior Specialist Business Controlling

Phone: +49 621 40 549 100, Mobile:  +49 1525 4912784, Email: ***@***.******@***.***>
Postal Address: Master Builders Solutions Deutschland GmbH, Glücksteinallee 43-45, 68163 Mannheim, Germany

[Ein Bild, das Zeichnung enthält.  Automatisch generierte Beschreibung]
Master Builders Solutions Deutschland GmbH, Registered Office: 83308 Trostberg, Germany
Companies' Register: Amtsgericht Traunstein, HRB 10261
Managing Directors: Thomas Gmelin, Carsten Hennicke
www.mbcc-group.com<http://www.mbcc-group.com/>

[Ein Bild, das Messer, Zeichnung enthält.  Automatisch generierte Beschreibung]

From: Laurent Marc
Sent: mardi 30 août 2022 10:44
To: DaxStudio/DaxStudio ***@***.***>; DaxStudio/DaxStudio ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [DaxStudio/DaxStudio] error at the beginning of DAX Studio 3.0 installation (Issue #893)

Good morning,
I thought I had to wait for a patch, but this morning I’ve tried to install it again and it worked 😊

Thx a lot for your very prompt and efficient support , much faster than my response time 😊

Mit freundlichen Grüßen / Best regards / Salutations
Dr. Laurent MARC
Senior Specialist Business Controlling

Phone: +49 621 40 549 100, Mobile:  +49 1525 4912784, Email: ***@***.******@***.***>
Postal Address: Master Builders Solutions Deutschland GmbH, Glücksteinallee 43-45, 68163 Mannheim, Germany

[Ein Bild, das Zeichnung enthält.  Automatisch generierte Beschreibung]
Master Builders Solutions Deutschland GmbH, Registered Office: 83308 Trostberg, Germany
Companies' Register: Amtsgericht Traunstein, HRB 10261
Managing Directors: Thomas Gmelin, Carsten Hennicke
www.mbcc-group.com<http://www.mbcc-group.com/>

[Ein Bild, das Messer, Zeichnung enthält.  Automatisch generierte Beschreibung]

**Comment by dgosbell** [comment]
Sorry, but I cannot affect the rules of third party AV program (if I could all viruses would just do this also)

**Comment by marcl11** [comment]
Danny Murphy had done last time smth on your installer of 3.0.0 so it was accepted
Maybe you could have a chat with him?

Mit freundlichen Grüßen / Best regards / Salutations
Dr. Laurent MARC
Senior Specialist Business Controlling

Phone: +49 621 40 549 100, Mobile:  +49 1525 4912784, Email: ***@***.******@***.***>
Postal Address: Master Builders Solutions Deutschland GmbH, Glücksteinallee 43-45, 68163 Mannheim, Germany

[Ein Bild, das Zeichnung enthält.  Automatisch generierte Beschreibung]
Master Builders Solutions Deutschland GmbH, Registered Office: 83308 Trostberg, Germany
Companies' Register: Amtsgericht Traunstein, HRB 10261
Managing Directors: Thomas Gmelin, Carsten Hennicke
www.mbcc-group.com<http://www.mbcc-group.com/>

[Ein Bild, das Messer, Zeichnung enthält.  Automatisch generierte Beschreibung]

**Comment by dgosbell** [comment]
no that was not me and I don't know who that person is. It would have to be someone in your company that "fixed" this
