### ISSUE TITLE
Expand measure fully qualified makes invalid code

### ISSUE THREAD

**Issue by GenisWork** [DaxStudio/DaxStudio#894]
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.39.21

## Summary of Issue
when dax studio performs expand measure option if the selected measure has nested measure fully referenced ('Table name'[measure name]) then the result of the expanding process only expand the measure itself and doesn't remove the table reference.

## Steps to Reproduce
1. Having this 2 measures 
X = SUM ( 'Table A'[Column1] )
Y = CALCULATE ( 'Table A'[X], FILTER ( 'Table A', 'Table A'[Column2] = TRUE () ) )
2. Select Y at metadata panel and click "Define and Expand Measure"
3. The resulting DEFINE is not a working measure
DEFINE 
MEASURE 'Table A'[Y] = 
CALCULATE ( 'Table A' CALCULATE ( 
SUM ( 'Table A'[Column1] ) ), FILTER ( 'Table A', 'Table A'[Column2] = TRUE () ) )

**Comment by marcosqlbi** [comment]
Thanks, it should be fixed in the next update.
