### ISSUE TITLE
Dax output uses a comma in numeric values instead of decimal

### ISSUE THREAD

**Issue by WynandCoetzee** [DaxStudio/DaxStudio#9]
Hi . 

When I execute my query in DAX studio the numeric data is returned using commas (1000 separator) instead of a decimal. If I use the Dax query in SSRS the same occurs and it causes issues with doing summaries on numerical data. 

Is there something I can do ... 

Example of my query: 
"Cubes TM", FORMAT ( [Sum of Cubes 2], "Standard" ) 
or 
"Cubes TM", [Sum of Cubes 2], 
or
"Cubes TM", FORMAT ( [Sum of Cubes 2], "General Number" ) 

Result is 0,19 instead of 0.19 

Thanks 
W

**Comment by marcosqlbi** [comment]
This does not depend on DAX Studio. You have to modify the language of your Tabular model (look at the language defined as default in your model.bim file using a text editor)

**Comment by WynandCoetzee** [comment]
Hi 

Thanks so much ! ..working. Will test in SSRS as well. 
W
