### ISSUE TITLE
Timeout value error 480 sec

### ISSUE THREAD

**Issue by ali123-algo** [DaxStudio/DaxStudio#900]
**Describe the bug**
When we use Dax Studio to retrieve a big amount of data from the cube, we see a timeout problem.
We get errors when the data size reaches roughly 12 million rows. We then reduce the number of days to obtain data that is less than 12 million.
What kind of error is this, the dax studio limit, or what else?

**Expect

**Screenshots**

![IMG_20220825_202915_654](https://user-images.githubusercontent.com/112104226/186708409-7ab45b9a-9508-4ba1-8e01-1e1c1f406d0e.jpg)

**Comment by dgosbell** [comment]
This is not an error message generated by DAX Studio so I think it must be coming from the Power BI service. 

Are you able to check the query timeout in your capacity settings?
![image](https://user-images.githubusercontent.com/8241830/186784627-4da0cd88-1bb5-4a09-9ce0-f9c9feebf3b1.png)

**Comment by dgosbell** [comment]
closing due to lack of response
