### ISSUE TITLE
DAX Query is Not Running After Pressing the RUN Button .Also Log is Showing as Establishing Connection.What to Do 

### ISSUE THREAD

**Issue by Satish0a3535** [DaxStudio/DaxStudio#903]
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.36.23

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
This appears to be the same as #904 and #905 so I'm going to close this so we can deal with your issue in #905
