### ISSUE TITLE
Run Query and Query Builder Run are not Working. Please Help 

### ISSUE THREAD

**Issue by Satish0a3535** [DaxStudio/DaxStudio#904]
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.36.23

## Summary of Issue
Run Query and Query Builder Run are not Working. Please Help 

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
This appears to be the same as #903 and #905 so I'm going to close this so we can deal with your issue in #905
