### ISSUE TITLE
Query is Not Displayed in Result in DAX Studio . Please  Help 

### ISSUE THREAD

**Issue by Satish0a3535** [DaxStudio/DaxStudio#905]
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.36.23

## Summary of Issue
Query is Not Displayed in Result in DAX Studio . Please  Help 

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
Can you post a screenshot of DAX Studio that shows your issue?

Have you been through the tutorials at https://daxstudio.org/docs/category/tutorials/ ? Do they work for you?

**Comment by Satish0a3535** [comment]
![image](https://user-images.githubusercontent.com/55406168/187016921-357b907b-c38c-4ec2-a01b-7c8d8acd32ea.png)

After Run Query the Result is Blank

**Comment by Satish0a3535** [comment]
***@***.***

**Comment by marcosqlbi** [comment]
You are running an invalid DAX query. Look at the error in the "Log" pane.

**Comment by dgosbell** [comment]
Clicking the dropdown only changes the run style between the query text and the query builder. It does not execute anything. 

If you click on the top half of the split button it will execute the selected action.

And your query is not valid you cannot do `EVALUATE` on a column, it needs to be a table expression. 

eg

```
EVALUATE
VALUES( DailyGRNReport[Buyer Name] )
```

**Comment by Satish0a3535** [comment]
Thanks Sir . Problem is Resolved.

**Comment by Satish0a3535** [comment]
Thanks Sir
