### ISSUE TITLE
Request a Digitially Signed DAX Studio.vsto 

### ISSUE THREAD

**Issue by mangocatmark** [DaxStudio/DaxStudio#91]
We are currently having an issue packaging for deployment, using the provided DaxStudio_2_7_4_setup.exe.
Due to the security restrictions in our corporate environment we require that add-ins/Plugins be digitally signed. The one provided in the installer however unfortunately is not.
Would it be possible to request and obtain a digitally signed DaxStudio.vsto file or suggest alternatives?.

**Comment by dgosbell** [comment]
Both the installer and the vsto are now signed as of the 2.8.0 release
