### ISSUE TITLE
report "PerTypeValues'1" ERROR when results export type set as static

### ISSUE THREAD

**Issue by renyusen168** [DaxStudio/DaxStudio#912]
DAX Studio v3.0.0.725
Connection: AnalysisServices - 14.0.213.1

## Steps to Reproduce
1.set results as static
2.run
3.log shows :"PerTypeValues'1"的类型初始值设定项引发异常

**Comment by dgosbell** [comment]
Thanks for reporting this. I'm going to close this particular issue as it is a duplicate of #891 and I'm tracking this bug there. I've identified the issue and it should be fixed soon.
