### ISSUE TITLE
SSAS on prem View Metrics Not Working

### ISSUE THREAD

**Issue by jaromgleed** [DaxStudio/DaxStudio#915]
When I connect to on prem SSAS I can write dax queries no problem to a tabular model. When I try to view metrics on the model I get the error: 
![image](https://user-images.githubusercontent.com/49740945/187518500-35b429aa-2461-45a1-bdba-868b88fb80aa.png)

Any idea if this is a limitation or what I need to do to resolve the issue?

**Comment by marcosqlbi** [comment]
If you have a compatibility level 1400 (or older), we already have covered this issue in #887 which is already fixed in development branch. The next release will fix it.

**Comment by jaromgleed** [comment]
Thanks @marcosqlbi
