### ISSUE TITLE
DAX Studio 3 portable version in Excel Power Pivot is not working

### ISSUE THREAD

**Issue by emirtut** [DaxStudio/DaxStudio#920]
Hi,

When connecting Excel power pivot model with DAX Studio 3, portable version, on connection, just starting, error occur as on picture enclosed / below.
So basically, no connection to data model. 
For PBI file, connections works fine.
My version of Excel on second picture below
![image](https://user-images.githubusercontent.com/69401624/188241531-26a7650d-fbf0-40af-8338-47d3817005d3.png)

![image](https://user-images.githubusercontent.com/69401624/188241628-d6d04911-6af0-40a4-b474-cdc437eeea08.png)

Thank you,
Kr
Emir

**Comment by dgosbell** [comment]
The portable version does not support the Excel add-in (see https://daxstudio.org/docs/installation/index/) as it requires the installer to register the add-in with Excel. 

But the if you still have an older v2 instance installed this error could be coming from there. There was some update to Excel recently which has broken DAX Studio. I'm in contact with one of the Microsoft Excel engineers and am tracking this issue on #884

**Comment by emirtut** [comment]
Hi @dgosbell 
I am sorry I should check documentation before raising ticket. I used to have older version of DAX Studio.
I would need admin to check details and install eventually full version.

Thank you,
Kr
Emir

**Comment by dgosbell** [comment]
OK, so I will close this issue as a duplicate then as I am tracking the problem with Excel in issue #884 - it does not matter what version of DAX Studio you use, if you are using the latest Excel you will not be able to connect until I figure out a fix for issue #884
