### ISSUE TITLE
Error querying dataset from Power BI Desktop

### ISSUE THREAD

**Issue by bwarner7578** [DaxStudio/DaxStudio#93]
Hello,

Anytime I try to query any of my datasets from Power BI Desktop, I get the following error even though I do  have access to these datasets:

Error: Either the user, 'US\bwarner', does not have permission to access the referenced mining model, 'Business Unit', or the object does not exist.

I get this error on every table in every dataset. Please help!

Thanks,
Brian

**Comment by bwarner7578** [comment]
When I try and execute a query

**Comment by dgosbell** [comment]
So are you saying that you can connect to the PBIX file that you opened in Power BI Desktop and that the metadata pane on the left populates with the list of tables in the model, but when you run a query like "Evaluate <tablename>" that you get this error?

I'm struggling to figure out what could be causing this. This is not an error message that we generate inside DAX Studio, it's something coming from the data source. But the reference to a mining model is strange, I'd only expect that if you were connecting to a multi-dimensional model in an Analysis Services instance.

**Comment by dgosbell** [comment]
Closing due to lack of response. Feel free to re-open if you have more information

**Comment by mkirubakaran** [comment]
I'm getting a similar error when trying to execute the query. I'm able to connect to the PBIX

**Comment by dgosbell** [comment]
@mkirubakaran What is the text of the query are you trying to run? That error implies that maybe your query was not understood by the Power BI engine.
