### ISSUE TITLE
Search and Replace - TAB

### ISSUE THREAD

**Issue by bluehenve** [DaxStudio/DaxStudio#931]
**Is your feature request related to a problem? Please describe.**
In search and replace, when hitting 3 x TAB, the cursor moves to replace text entry boks, but the text in this box is not selected

**Describe the solution you'd like**
In search and replace, when hitting 3 x TAB, it would be nice, if the text in the replace text entry boks was selected

Regards, Henrik

**Comment by dgosbell** [comment]
Thanks for logging this. I think this is a great idea and a fix for this will be included in the next release

**Comment by bluehenve** [comment]
Cool 👍🙂

tor. 22. sep. 2022 04.40 skrev Darren Gosbell ***@***.***>:
