### ISSUE TITLE
DAX Studio Window Invisible

### ISSUE THREAD

**Issue by tsnyd111** [DaxStudio/DaxStudio#937]
**Describe the bug**
DAX Studio's main window screen is invisible upon opening (and stays invisible). The only items that appear (temporarily) are the connection prompts. The application shows open in the taskbar. 

**Additional context**
I've tried uninstalling/reinstalling and rebooting. Nothing seems to fix it.

**Log File**
[DaxStudio-20220913.log](https://github.com/DaxStudio/DaxStudio/files/9561574/DaxStudio-20220913.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/94724978/190031557-1a0ecea4-3c4b-4205-acfe-22d90f597721.png)

**Comment by dgosbell** [comment]
This is really strange I've never seen this before. I don't have any settings or anything that will deliberately make the main window invisible. 

I know the graphics framework I'm using does support hardware acceleration so maybe it's something strange going on there. I might see if I can add a config file option to force the window to use software rendering as this is the only thing I can think of as the debug log looks perfectly normal and there are no errors or unusual sequences of events in there.

**Comment by tsnyd111** [comment]
Thanks for looking into this. Anything further I could provide from my end that could help troubleshoot?

**Comment by dgosbell** [comment]
Not at the moment. I can't see any errors in the log and the app seems to "think" it is running OK. So it's a bit of a mystery as to why it's not visible.

**Comment by tsnyd111** [comment]
@dgosbell,

Update - The issue only occurs when connected to my 27" QHD monitor from my HP Zbook laptop. However, the odd thing here is if if use my other laptop (Dell XPS) connecting to that same monitor in the exact same way, it displays. And it also displays on my native laptop's screen from my Zbook Fury. 

Any idea what could cause something like this? Seems crazy this is happening, but the problem is consistent. Always works under a certain setup, always doesn't work under the other setup.

**Comment by marcosqlbi** [comment]
Is it possible it's displayed outside of the monitor boundaries? Did you try some Windows-shortcut to see whether changing windows position works?
Windows+Shift+Up Arrow: Stretch window to the top and bottom of the screen.
Windows+Left Arrow: Maximize the window on the left side of the screen.
Windows+Right Arrow: Maximize the window on the right side of the screen.
Windows+Shift+Left or Right Arrow: Move a window from one monitor to another.

**Comment by dgosbell** [comment]
> The issue only occurs when connected to my 27" QHD monitor from my HP Zbook laptop.

So it could be that the external display uses a different graphics card. Some laptops have both integrated graphics and a dedicated graphics card and it's possible that your laptop is using a different graphics card and driver for the external monitor

**Comment by dgosbell** [comment]
In the 3.0.1 update I've added the following line in the `daxstudio.exe.config` file which will be in the root folder where you installed DAX Studio which is `c:\Program Files\DAX Studio` by default
```
<add key="ForceSoftwareRendering" value="false" />
```
can you try changing this value to true and see if that helps on your external monitor?

**Comment by tsnyd111** [comment]
Update - The application has been working the last few days without making any changes to the code. Once I open it on my local screen, it always displays on my monitors. 

To the earlier comments, I do have a dedicated graphics card and integrated graphics, which may have contributed to the issue. I'll continue monitoring, but at the moment, I'm not experiencing problems.

**Comment by dgosbell** [comment]
Closing this issue as it appears to have resolved itself
