### ISSUE TITLE
DAX Studio > Advanced > View Metrics not working

### ISSUE THREAD

**Issue by swapnil-tamboli** [DaxStudio/DaxStudio#944]
In DAX studio, when I click on Advanced > View Metrics. I get below error, please suggest:

Error viewing metrics: The specified column was not found in the context at line 8, column 5.

**Comment by dgosbell** [comment]
this is a duplicate of #926 so I'm going to close this issue as I am tracking this bug there. We have a fix for this that will be part of the next release.
