### ISSUE TITLE
do not see edit query in the query builder

### ISSUE THREAD

**Issue by Klimkiv** [DaxStudio/DaxStudio#945]
Why I do not see [edit query] and [play button] in the query builder like in tutiorial? But if I hit F5 the result is ok!
thank you!

![image](https://user-images.githubusercontent.com/57611080/190898520-31409322-d7b9-4a55-80a8-8081aeea6e76.png)

**Comment by dgosbell** [comment]
I still need to update most of the screenshots in the documentation.

The **update** button does the same thing as the old **edit query** button. It "updates" the content of the edit window.

I've removed the second play button and the main play button now has a "run query builder" mode (but it also auto-detects if just the query build or just the edit window has content and will use the appropriate one)
