### ISSUE TITLE
Unable to Connect to Power Pivot Model

### ISSUE THREAD

**Issue by jefflas** [DaxStudio/DaxStudio#948]
When attempting to connect to a power pivot model using the Dax Studio Addin I get the attached error message.
![Dax Studio Error](https://user-images.githubusercontent.com/54301556/191247491-85705773-0241-4581-9f5b-eebf03b0cbb1.jpg)

This error occurs on both my computers and with any power pivot spreadsheet.
I am using Windows 10, Excel 365 and tried Dax Studio 2.16, 2.17 & 3.?

Thaks for your help
Jeff

**Comment by marcosqlbi** [comment]
It seems an Excel issue, please follow #884 so we don't keep duplicated items open.
