### ISSUE TITLE
Data Types in DAX Studio

### ISSUE THREAD

**Issue by account2k** [DaxStudio/DaxStudio#95]
Hello,   MDSCHEMA_MEASURES has Data Types 5 and 20 in the Output.    Is there a reference to what these refer to?    Thanks in advance.

**Comment by dgosbell** [comment]
It's not particularly well documented, but this page [https://msdn.microsoft.com/en-us/library/ee301649(v=sql.105).aspx](https://msdn.microsoft.com/en-us/library/ee301649(v=sql.105).aspx) on MDSCHEMA_MEASURES says that this column uses the same values as the LEVEL_DBTYPE column here [https://msdn.microsoft.com/en-us/library/ee301892%28v=sql.105%29.aspx](https://msdn.microsoft.com/en-us/library/ee301892%28v=sql.105%29.aspx) 

so 5 and 20 would be:

- 5 – (DBTYPE_R8) Indicates a double-precision floating-point value.
- 20 – (DBTYPE_I8) Indicates an eight-byte signed integer.
