### ISSUE TITLE
Swap Delimiters Missing in Dax 3.0

### ISSUE THREAD

**Issue by Stefanoeid** [DaxStudio/DaxStudio#951]
Hello Community,

An important feature for me is the swap delimiters (, for ;) and I've found that it went missing in the new update (3.0). The "debug commas" took it's place.

I've tried to use the replace function but it didn't work for me and i've found other posts about it too claiming that it doesn't work as supposed to.

I don't know if i'm the only one that find this feature useful but i would love a way to place it back in the upper ribbon.

**Comment by dgosbell** [comment]
> I don't know if i'm the only one that find this feature useful but i would love a way to place it back in the upper ribbon.

It's really only useful for Excel PowerPivot models. All the other data sources DAX Studio supports have standardized on the "US" style delimiters. But there is a setting in the advanced options that controls whether that spot on the ribbon is used by "Swap Delimiters" or "Debug Commas" (this was turned on by default in v3.0)

![image](https://user-images.githubusercontent.com/8241830/191621136-4849cd08-a0bc-4e23-b164-4c707ca8c390.png)

> I've tried to use the replace function but it didn't work for me and i've found other posts about it too claiming that it doesn't work as supposed to.

The logic to swap delimiters correctly is more complicated than a simple search/replace. Is that what you mean when you talk about these other post? I have not seen any posts claiming that the search/replace in DAX Studio is not working correctly. Can you post some links to these?

**Comment by dgosbell** [comment]
In 3.0.6 the setting in the options will move debug commas / swap delimiters between the Home and Advanced ribbon tabs
