### ISSUE TITLE
Highlight (Select) Query does not work in 3.1.  All queries in the IDE run. 

### ISSUE THREAD

**Issue by NickCodesDotNET** [DaxStudio/DaxStudio#952]
All queries run in the DAX Studio IDE page even though I select only one. 

![image](https://user-images.githubusercontent.com/78136472/191656513-170581bc-70a9-451b-a266-69b8d289b6ae.png)

**Comment by dgosbell** [comment]
Thanks for logging this. v3.0.2 is now available with a fix for this

**Comment by NickCodesDotNET** [comment]
@dgosbell I tested on 2 machines and the issues is still present. The update to 3.2 did not fix the issue. FYI

**Comment by NickCodesDotNET** [comment]
@dgosbell Works like a charm now. Thank you
