### ISSUE TITLE
Run: Not only the selected linjes are run

### ISSUE THREAD

**Issue by bluehenve** [DaxStudio/DaxStudio#953]
When selecting some lines in Dax Studio and click Run, not only the selected linjes are run, but all the linjes in the editor
version: 3.0.1
Regards, Henrik

**Comment by dgosbell** [comment]
This is a duplicate of #952 so I'm closing this as I'm working on a fix now for the previous issue

**Comment by dgosbell** [comment]
Thanks for logging this. v3.0.2 is now available with a fix for this

**Comment by bluehenve** [comment]
Cool, thanks 🙂👍

tor. 22. sep. 2022 08.51 skrev Darren Gosbell ***@***.***>:

**Comment by NickCodesDotNET** [comment]
@dgosbell  I tested on 2 machines and the issues is still present. The update to 3.2 did not fix the issue. FYI

**Comment by dgosbell** [comment]
Yes, sorry. I had a bunch if issues with the automated build yesterday and accidentally rolled back the fix. I've just pushed out 3.0.3 with the proper fix

**Comment by bluehenve** [comment]
Thanks Darren!
Regards Henrik

tor. 22. sep. 2022 23.45 skrev Darren Gosbell ***@***.***>:
