### ISSUE TITLE
Carriage Returns

### ISSUE THREAD

**Issue by BostonTechie** [DaxStudio/DaxStudio#954]
**Describe the bug**

Within DAX studio you have the option to output the results to a CSV file by default, works great with the exception of carriage returns. 

**To Reproduce**

create an excel file that has lots of carriage returns in it ,   run it through the output to file option in DAX studio

**Expected behavior**

=SUBSTITUTE(SUBSTITUTE(   XXXX  ,UNICHAR(13),""),UNICHAR(10),"")

https://www.ablebits.com/office-addins-blog/remove-carriage-returns-excel/

**Screenshots**

original excel file all data exists in single cell...
![image](https://user-images.githubusercontent.com/85643280/191842669-bada3cc8-5646-4f4f-813f-b84defadc847.png)

**Additional context**
CSV output example below, note the one cell went to multiple lines

![image](https://user-images.githubusercontent.com/85643280/191843589-909334a4-6f09-47c0-97e5-a2d171dbce0c.png)

**Comment by dgosbell** [comment]
I think this might be something you've done in Excel. Can you check the csv file with a text editor and see if the same issue is present? I'm not seeing any differences between DAX Studio, Excel and a Text Editor, but I'm not running the file through Power Query.

![image](https://user-images.githubusercontent.com/8241830/191854581-3044fbae-0a30-4519-a59a-db12715e2f93.png)

**Comment by BostonTechie** [comment]
I think you are right dgosbell, I did run my data through power query first,  the error must be at that level

**Comment by BostonTechie** [comment]
TY!
