### ISSUE TITLE
DAX studio crashing.

### ISSUE THREAD

**Issue by anique9999** [DaxStudio/DaxStudio#957]
**Describe the bug**
Every time I'm launching the DAX studio, the application crashes suddenly. I'm seeing following errors in the event viewer:- 

```
Application: DaxStudio.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ComponentModel.ReflectPropertyDescriptor.SetValue(System.Object, System.Object)
   at DaxStudio.UI.Utils.RegistrySettingProvider.Initialize(DaxStudio.Interfaces.IGlobalOptions)
   at DaxStudio.UI.ViewModels.OptionsViewModel.Initialize()
   at DaxStudio.Standalone.EntryPoint.Main()

```

**Screenshots**
![image](https://user-images.githubusercontent.com/90675448/191939764-0cc4228b-871c-44b9-a0bb-65e9522b3e2b.png)

Can you please tell me how can I fix this issue? `Object of type 'System.ComponentModel.DefaultValueAttribute' cannot be converted to type 'System.Int32'` .

**Comment by dgosbell** [comment]
Can you run [DaxStudio.Checker](https://daxstudio.org/docs/troubleshooting/daxstudio-checker/) and post the output back here on GitHub. It sounds like some setting, maybe from an older version is not being read correctly.

After you've done that you could try opening a command prompt and navigating to the folder where you have DAX Studio and then running `daxstudio.exe -reset` this should reset all your settings back to the default and that might fix the issue.

**Comment by anique9999** [comment]
Thanks for the help. `daxstudio.exe -reset` resolved the issue.
