### ISSUE TITLE
Context menu commands not working for Define measure, Define dependent measures, Define and expand measures 

### ISSUE THREAD

**Issue by HymieHo** [DaxStudio/DaxStudio#962]
Repro:
1. Connect -> Tabular server -> enter AAS server URL. 
result: Model loads as expected.

2. Navigate to a measure, right-click and choose any of the first three options such as Define measure
result: It partially works, creating "**DEFINE MEASURE _'table'[measurename]_ =**", but no measure definition.
expected: the above + the actual measure definition.

**Comment by HymieHo** [comment]
DAX Studio v3.0.0.725
Connection: AzureAnalysisServices - 16.0.46.24

**Comment by dgosbell** [comment]
This most likely means you do not have admin access to the model. Microsoft recently increased the security settings around measure expressions so they are only available if you have read/write access to the model. If you only have read-only access then these are no longer available like they used to be. This affects both AzureAS and Power BI Premium and I'm expecting that SSAS 2022 will also have this increased level of security.

Can you confirm if this is the case in your situation?

**Comment by HymieHo** [comment]
That was exactly the issue. My credentials were accidentally deleted. Thanks for the quick response!

**Comment by dgosbell** [comment]
Closing as this is most likely due to insufficient rights on the source model
