### ISSUE TITLE
DaxStudio.exe no icon

### ISSUE THREAD

**Issue by lovelygfj** [DaxStudio/DaxStudio#963]
DAX Studio v3.0.3.762
Connection: not connected

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
I'm not sure what your issue is. Can you explain in more detail?

**Comment by jiaopengzi** [comment]
hi here
install daxstudio.exe no icon
![image](https://user-images.githubusercontent.com/52224629/192178487-d3c1a46e-deb9-48f1-9ac0-b764ef2f41ec.png)

above is the installation package, below is the desktop shortcut, no icon.

**Comment by marcosqlbi** [comment]
@dgosbell I am able to reproduce - the icon is not set on Windows starting from this build:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/44850001/artifacts

Previous builds worked well.

**Comment by dgosbell** [comment]
@lovelygfj - thanks for logging this issue. It has been fixed in the 3.0.4 release which I just published.
