### ISSUE TITLE
Installing as none admin gives registry key error

### ISSUE THREAD

**Issue by erapade** [DaxStudio/DaxStudio#967]
**Describe the bug**
When installing (using only for me), I get an error when the installer tries to register a key, see screenshot below

**To Reproduce**
1. Install the application an my Cooperate PC 
2. Choose to install only for me
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17324892/193084676-c57cb22e-1de0-4166-96ec-f3a39edb300a.png)

**Additional context**
Well this is my employers PC, so other policies than standard policies can be applied

**Comment by NickyvVr** [comment]
FYI: Also seeing this exact error in the same context
