### ISSUE TITLE
UI - Tool Window loses header after positioning causing lost access to window after nesting.

### ISSUE THREAD

**Issue by Jason-P** [DaxStudio/DaxStudio#968]
I've been trying to move the Log separate to the Results window, showing the log vertically beside the Query and Result - but doing this seems to remove the 'header' of a window, and I've found that it's possible to lose access to the results (or any tool window in the bottom half of a pane) once the window is minimised or behind another window.

Watch the [video] to make sense of the above :-)(https://drive.google.com/file/d/1epCoGFk74HB7Ro10YIL2Kl0s2cTJtU10/view?usp=sharing)

**Comment by dgosbell** [comment]
Thanks for logging this. This is happening because these windows are docking into the space used by the Edit control which does not have a window title, but I have found a way to restrict this so that other "windows" cannot dock into this space. This will be fixed in the next release.
