### ISSUE TITLE
Suggestion: Stay on Server Timings results when using log timer output

### ISSUE THREAD

**Issue by GMedlin** [DaxStudio/DaxStudio#969]
When you have server timings enabled and the results output set to the default of results table, repeated query runs leaves you on the server timings tab if you were already there. It'd be nice if this same behavior occurred when your results output is set to Log Timer. Currently, you have to click back to server timings because it takes you back to the log tab.

**Comment by dgosbell** [comment]
Thanks for logging this idea. I have the code to do this checked in and it will go out as part of the next release. Once I push out that release this issue will close itself
