### ISSUE TITLE
'Duplicate Tab' option when right clicking a query tab

### ISSUE THREAD

**Issue by samaguire** [DaxStudio/DaxStudio#973]
It would be great if I could duplicate a query tab with all the connections and built queries carried across into the new query tab. This would save time when working on creating variations of the same query; especially when using query builder 👍

![image](https://user-images.githubusercontent.com/62320770/195474919-b51faa7c-0d8d-4975-b3cd-9354b05adafc.png)

**Comment by dgosbell** [comment]
Thanks for logging this. I really like this idea and see how it could be useful.
