### ISSUE TITLE
Exporting data to Excel results in The hype initializer for 'PerTypeValues'1' threw an exception. 

### ISSUE THREAD

**Issue by relax528** [DaxStudio/DaxStudio#975]
DAX Studio v3.0.0.725
Connection: PowerBIService - 16.0.49.19

## Summary of Issue
Getting error exporting to a static Excel

## Steps to Reproduce
1. Executing EVALUATE 'Profit Center Hierarchy' with Results set to Static Excel
2. Query results shown 
![image](https://user-images.githubusercontent.com/19497071/195624921-2e576794-2e44-44fc-810c-2d277ae592b8.png)

3. Excel file has a length of 0 KB

**Comment by dgosbell** [comment]
This was fixed in the 3,0,5 update
