### ISSUE TITLE
Excel Add-in does not appear in Coms Add-In menu or load in to excel

### ISSUE THREAD

**Issue by SJGorilla** [DaxStudio/DaxStudio#978]
DAX Studio v3.0.5.767

**## Summary of Issue**
Completed a standard install for all users. No matter what i try i cannot see add in tab or see Dax Studio in the COMS add-in menu to even select it manually? Add-in tab is ticked so should appear if an add-in is loaded to excel under that default menu?

Excel Version: Microsoft® Excel® for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20070) 64-bit

**##Steps to resolve**
1. Uninstalled and reinstalled several times both as admin and not
2. Removed all non-standard COM add-ins. Only have Inquire, Power Map and Power Pivot add-ins installed.
3. Checked for any odd Excel Add-ins. Have Analysis Toolpak, Analysis Toolpak - VBA, Solver Add-in all checked. Euro Currency Tools installed but not checked.
4. Launched Excel as admin

**##DAX Studio Checker report**
    Version =  v3.0.5.767
    DaxStudio.exe Version =  v3.0.5.767

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Home
    OSRelease       = 2009
    OSVersion       = 10.0.19044
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 31.88
    FreeMemoryGB    = 23.59

    Culture Name              = en-GB
    Culture DisplayName       = English (United Kingdom)
    Culture EnglishName       = English (United Kingdom)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = £
    Culture ShortDatePattern  = dd/MM/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY2  
         X: -1920 Y: 0 Width: 1920 Height: 1080
DPI X: 96 Y: 96 (Scaling: 100.0%)

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.04084
    v4\Client\1033 -> 4.8.04084
    v4\Full -> 4.8.04084
    v4\Full\1033 -> 4.8.04084
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528372 (4.8)
    PASS > .Net Version 4.8 is above the required minimum

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 24
    AMO : 19.48.0.0
    ADOMD : 19.48.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
	HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=3.0.5.767, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4R
        VSTORFeature_UNM 1
        VSTORFeature_CLR35 1
        VSTORFeature_CLR40 1
        Version 10.0.60828
        Revision 00
        ProductCode {47C2CCDB-7A04-3797-992B-A84D3E90258F}

Registry Settings
=======================
    CurrentDownloadVersion = 3.0.5.767
    LastVersionCheckUTC = 2022-10-13T16:02:38Z
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>0</flags><showCmd>1</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>52</Left><Top>5</Top><Right>1172</Right><Bottom>725</Bottom></normalPosition></WINDOWPLACEMENT>

**Comment by SJGorilla** [comment]
Could this be the same issue as #884 ? I have Power Pivot enabled but I'm not using the same excel version/build? I will close this and wait.

**Comment by dgosbell** [comment]
No, in 884 the addin loads but cannot connect due to a bug in a recent Excel update. I have no idea why the addin would not be visible on your machine, everything in the DAX Checker output looks the same as on my machine.

**Comment by SJGorilla** [comment]
In that case will leave it open and post if I find the answer.

**Comment by SJGorilla** [comment]
FYI In addition i also have Flow and Script lab add ins from the Store active.

**Comment by SJGorilla** [comment]
Fixed It!
I'm not entirely sure what the issue was but a repair/reset using the windows 10 'Office' app worked.

1. Right click windows symbol
2. click 'Apps and Features'
3. Type 'Office' in search box
4. Select 'Office' app then click 'Advanced options'
5. Scroll down and click 'Repair' then click 'Reset'

PS After reset the previously removed Adobe 'Acrobat PDFMaker Office COM Addin' add-in appeared again along with Dax Studio Add-in. This could just be a coincidence?
