### ISSUE TITLE
Names of hidden objects hardly readable in Dark Mode

### ISSUE THREAD

**Issue by darlove** [DaxStudio/DaxStudio#979]
**Describe the bug**
Not sure if this can be classified as a bug but there doesn't seem to be a better place to describe it. The problem is that in Dark Mode the names of the hidden objects can hardly be read. The font's color is just a tad too dark.

**To Reproduce**
Open DAX Studio, switch the Dark Mode on, and see what the hidden objects' names look like in the Metadata panel.

**Expected behavior**
I just think that the font should have a more vibrant color, be more pronounced, so that it's easier to read.

**Screenshots**
<img width="182" alt="DAX Studio - hidden objects names too dark" src="https://user-images.githubusercontent.com/16683408/197724192-ee555c38-f0fd-467c-b32e-c17688ba1d83.png">

**Comment by dgosbell** [comment]
Yes, I'd classify this as a UI bug. I've updated the text color to be closer to the shade used for the icon and I've also made hidden items italic to help differentiate them.
