### ISSUE TITLE
Operations conflict in one connection

### ISSUE THREAD

**Issue by mujiannan** [DaxStudio/DaxStudio#983]
**Describe the bug**
<img width="461" alt="image" src="https://user-images.githubusercontent.com/46643837/199438523-3ffbb5a0-a1d4-485b-bb21-1d60e1ec0a7c.png">  
Error: The connection cannot be used while an XmlReader object is open.

**To Reproduce**
1. Connect to any AAS Tabular Model  
1. Run a query   
1. Sometimes see error  

**Expected behavior**  
A lock on the connection, which let the query engine to wait while not report error. Or tell user which operation is currently using the *XmlReader*.

**Comment by dgosbell** [comment]
hmm, I think this possibly happens if you start running a query while the metadata pane is still populating. Is this the case with you?

**Comment by dgosbell** [comment]
This should be fixed in the 3.0.7 release
