### ISSUE TITLE
the button “Format Query” is not available

### ISSUE THREAD

**Issue by jiaopengzi** [DaxStudio/DaxStudio#984]
hi，
the button “Format Query” is not available
this image
![image](https://user-images.githubusercontent.com/52224629/199513273-78e0c0c4-e567-44ca-b63f-374ccbe44cbb.png)

the version
![image](https://user-images.githubusercontent.com/52224629/199513578-007ae6b8-2a52-4ff0-bb6a-ae5c6545cf77.png)

**Comment by dgosbell** [comment]
That usually means that you or the person that installed DAX Studio has disabled external connections.

You can check this in File - Options 

If either of the two highlighted options below are switched on the Format Query button will be disabled

![image](https://user-images.githubusercontent.com/8241830/199600854-41974a5f-95ef-47b1-9336-38c3ef595c18.png)

**Comment by jiaopengzi** [comment]
I don't know when I unconsciously ticked this place. 
Uninstall and reinstall, leave it unchecked. 
Thank you very much for your answer.


![image](https://user-images.githubusercontent.com/52224629/199869554-c96e81bd-1a1f-4058-84dd-9ed33d5f5916.png)
