### ISSUE TITLE
DAX STUDIO is terminated when connecting to TABULAR SERVER

### ISSUE THREAD

**Issue by pietrofarias** [DaxStudio/DaxStudio#985]
**Describe the bug**
I started connecting to the workspace from version 3.0.0 and started using it again in version 3.0.5. I don't know from which version the error started to occur. DAX STUDIO terminates whenever I connect to my Workspace PU.

**To Reproduce**
1. I connect with my Workspace PU
![image](https://user-images.githubusercontent.com/24781333/199551883-e76f3655-2a4e-4f55-be16-0d660b5e118b.png)

2. My connection is successful and the Dax Studio buttons work perfectly, until...
![image](https://user-images.githubusercontent.com/24781333/199552211-0e3097ca-5c8b-4d66-b124-c354d0dd1249.png)

3. Until I started typing in the Text Editor. If I start my EVALUATE, DAX STUDIO crashes and exits.

**Expected behavior**
I cannot start writing a DAX query.

**Comment by pietrofarias** [comment]
I just noticed that my Dataset didn't update because it contains a duplicate item in a dimensional table. The problem was fixed and it returned to normal.

**Expected behavior**
I believe that the update error would not prevent the query from occurring in the already published DS. But somehow, because this error occurred in the DS update, it was harming the DAX STUDIO connection with the Workspace PU.

**Comment by pietrofarias** [comment]
I installed version v2.17.3 and it works perfectly. 3.0.0 is also having problems.

**Comment by pietrofarias** [comment]
The error continues. But in version 2.17, a screen appears that an error happened: "The window handle is invalid".
[Erro_DaxStudio.pdf](https://github.com/DaxStudio/DaxStudio/files/9924057/Erro_DaxStudio.pdf)

**Comment by dgosbell** [comment]
Does this only happen when you use the Tabular Server option or does it also happen with local Power BI Desktop connections?
Does it just happen with one dataset or does it happen with all datasets?

It sounds like possibly an issue with the intellisense window displaying, but I cannot reproduce this at my end. Can you try enabling the debug logging as described [here] (https://daxstudio.org/docs/troubleshooting/logging-settings/) and then reproduce this crash and then attach the log file to this issue on github?

Finally, if you go into File - Options then into the Editor section and turn off the "Enable Intellisense" option does that prevent the crash from happening?

**Comment by pietrofarias** [comment]
> Does this only happen when you use the Tabular Server option or does it also happen with local Power BI Desktop connections? Does it just happen with one dataset or does it happen with all datasets?
> 
> It sounds like possibly an issue with the intellisense window displaying, but I cannot reproduce this at my end. Can you try enabling the debug logging as described [here] (https://daxstudio.org/docs/troubleshooting/logging-settings/) and then reproduce this crash and then attach the log file to this issue on github?
> 
> Finally, if you go into File - Options then into the Editor section and turn off the "Enable Intellisense" option does that prevent the crash from happening?

Stay off these days and I came back yesterday. Yesterday I formatted my computer and I will test it again today and let you know if it solved. Otherwise, I will do this procedure.

**Comment by pietrofarias** [comment]
I will close the Issue. Well, it seems to me that the problem was on my computer. After I formatted, I didn't have this problem again.
