### ISSUE TITLE
Measure blue icons partially hidden

### ISSUE THREAD

**Issue by PascalUK** [DaxStudio/DaxStudio#994]
DAX Studio v3.0.5.767
Connection: PowerBIDesktop - 15.1.110.21

## Summary of Issue
When metadata left panel vertical scrollbars is visible, all measure icons are partially hidden. See Picture. 

## Steps to Reproduce
1.  Set Options>Standard>Metadata Pane>Scrollbars>Auto hide vertical scrollbars to Off.
2. Or also when Auto hide vertical scrollbars is set to On, and you hover the mouse over thje panel. 
3. 
![2022-11-17 09_42_23-DAX Studio - 3 0 5](https://user-images.githubusercontent.com/46163559/202399017-36be3cd4-9fb6-49a6-a78d-d4970584fe13.jpg)

**Comment by dgosbell** [comment]
Thanks for logging this. I should be able to adjust the measure icon position if this setting is enabled without too much hassle.
