### ISSUE TITLE
Where is 'Edit query' button in version 3.0.5 of DAX studio?

### ISSUE THREAD

**Issue by gaznez** [DaxStudio/DaxStudio#995]
Please see image below - where is the 'Edit query' button to see the DAX generated using query builder...?

![image](https://user-images.githubusercontent.com/118544579/202730452-9bac394f-dec2-4d07-9fbc-ccc10f6366f6.png)

**Comment by dgosbell** [comment]
It's been renamed to "Update" to align with the "Auto Update" toggle
