### ISSUE TITLE
Query Builder Filtering on Measure Error

### ISSUE THREAD

**Issue by bross923** [DaxStudio/DaxStudio#997]
**Describe the bug**
When using Query Builder to create a DAX query, adding a measure to the Filter pane results in a DAX query that produces an error.

**To Reproduce**
1. Connect to a Tabular dataset
2. Click on Query Builder
3. Drag a measure into the Measure/Columns pane
4. Drag the same field (or another measure) into the Filter pane
5. Run the query
6. See error

**Expected behavior**
When using query builder, I would expect that adding a measure to the Filter pane would create a query that would filter out results based on the criteria in the Filter Pane.  For example,  Building a query that retrieves calendar Date and Sales with a filter where sales > 10,000.  I would expect a query that would run and retrieve a list of sales by day where sales for the day being over $10,000

**Screenshots**
![image](https://user-images.githubusercontent.com/43995265/203137986-efd5225f-5c2d-417b-9404-a379fef6630f.png)

**Additional context**
The error produced:
The ALL function expects a table reference expression for argument '1', but a string or numeric expression was used.

**Comment by dgosbell** [comment]
Thanks for logging this. I'll need to investigate implementing a slightly different query pattern to enable measure filtering
